package es.ghatostudio.nexapdf.ui.theme

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// -----------------------------------------------------------------------------
// FICHERO GENERADO por tools/generar_colores.py. No editar a mano.
//
// Unico lugar del proyecto donde se declaran colores. Cualquier composable que
// necesite un color lo toma de MaterialTheme.colorScheme; no hay literales de
// color sueltos en el resto del codigo (lo verifica la tarea comprobarTokens).
//
// Las rampas son tonales CIELAB: el numero de tono es el L* del color, de modo
// que las parejas de roles mantienen su contraste por construccion. Verificado
// a 4.5:1 (texto) y 3:1 (bordes) por el propio generador.
// -----------------------------------------------------------------------------

internal val esquemaIndigoClaro: ColorScheme = lightColorScheme(
    primary = Color(0xFF4A5A9F),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFDFE0FF),
    onPrimaryContainer = Color(0xFF001945),
    inversePrimary = Color(0xFFBDC2FE),
    secondary = Color(0xFF5A5C77),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFDFE0FF),
    onSecondaryContainer = Color(0xFF161A30),
    tertiary = Color(0xFF7E506D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFFD8EF),
    onTertiaryContainer = Color(0xFF340B28),
    error = Color(0xFFB12938),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEDAD8),
    onErrorContainer = Color(0xFF410003),
    background = Color(0xFFF9F9FF),
    onBackground = Color(0xFF1B1B1F),
    surface = Color(0xFFF9F9FF),
    onSurface = Color(0xFF1B1B1F),
    surfaceVariant = Color(0xFFE1E1F1),
    onSurfaceVariant = Color(0xFF454652),
    surfaceTint = Color(0xFF4A5A9F),
    inverseSurface = Color(0xFF303034),
    inverseOnSurface = Color(0xFFF0F0F6),
    outline = Color(0xFF767684),
    outlineVariant = Color(0xFFC5C5D4),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF9F9FF),
    surfaceDim = Color(0xFFD9D9DF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF3F3F9),
    surfaceContainer = Color(0xFFEDEDF3),
    surfaceContainerHigh = Color(0xFFE8E8ED),
    surfaceContainerHighest = Color(0xFFE2E2E8),
)

internal val esquemaIndigoOscuro: ColorScheme = darkColorScheme(
    primary = Color(0xFFBDC2FE),
    onPrimary = Color(0xFF0A2D6B),
    primaryContainer = Color(0xFF2E4384),
    onPrimaryContainer = Color(0xFFDFE0FF),
    inversePrimary = Color(0xFF4A5A9F),
    secondary = Color(0xFFC3C4E2),
    onSecondary = Color(0xFF2C2F46),
    secondaryContainer = Color(0xFF43455E),
    onSecondaryContainer = Color(0xFFDFE0FF),
    tertiary = Color(0xFFECB7D8),
    onTertiary = Color(0xFF4C213E),
    tertiaryContainer = Color(0xFF653855),
    onTertiaryContainer = Color(0xFFFFD8EF),
    error = Color(0xFFFFB3B0),
    onError = Color(0xFF680016),
    errorContainer = Color(0xFF920023),
    onErrorContainer = Color(0xFFFEDAD8),
    background = Color(0xFF131317),
    onBackground = Color(0xFFE2E2E8),
    surface = Color(0xFF131317),
    onSurface = Color(0xFFE2E2E8),
    surfaceVariant = Color(0xFF454652),
    onSurfaceVariant = Color(0xFFC5C5D4),
    surfaceTint = Color(0xFFBDC2FE),
    inverseSurface = Color(0xFFE2E2E8),
    inverseOnSurface = Color(0xFF303034),
    outline = Color(0xFF8F909E),
    outlineVariant = Color(0xFF454652),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF39393D),
    surfaceDim = Color(0xFF131317),
    surfaceContainerLowest = Color(0xFF0E0E13),
    surfaceContainerLow = Color(0xFF1B1B1F),
    surfaceContainer = Color(0xFF1F1F23),
    surfaceContainerHigh = Color(0xFF292A2E),
    surfaceContainerHighest = Color(0xFF343439),
)

internal val esquemaBosqueClaro: ColorScheme = lightColorScheme(
    primary = Color(0xFF1A6C43),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFA4F4C3),
    onPrimaryContainer = Color(0xFF00210F),
    inversePrimary = Color(0xFF88D7A7),
    secondary = Color(0xFF486553),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFCAEAD5),
    onSecondaryContainer = Color(0xFF052012),
    tertiary = Color(0xFF006875),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF9EEFFE),
    onTertiaryContainer = Color(0xFF001F24),
    error = Color(0xFFB12938),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEDAD8),
    onErrorContainer = Color(0xFF410003),
    background = Color(0xFFF5FBF7),
    onBackground = Color(0xFF181D1A),
    surface = Color(0xFFF5FBF7),
    onSurface = Color(0xFF181D1A),
    surfaceVariant = Color(0xFFD6E6DC),
    onSurfaceVariant = Color(0xFF3D4A41),
    surfaceTint = Color(0xFF1A6C43),
    inverseSurface = Color(0xFF2D312E),
    inverseOnSurface = Color(0xFFECF2EE),
    outline = Color(0xFF6C7A71),
    outlineVariant = Color(0xFFBBCAC0),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFF5FBF7),
    surfaceDim = Color(0xFFD5DBD7),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFEFF5F1),
    surfaceContainer = Color(0xFFE9EFEB),
    surfaceContainerHigh = Color(0xFFE4EAE6),
    surfaceContainerHighest = Color(0xFFDEE4E0),
)

internal val esquemaBosqueOscuro: ColorScheme = darkColorScheme(
    primary = Color(0xFF88D7A7),
    onPrimary = Color(0xFF00391E),
    primaryContainer = Color(0xFF00522F),
    onPrimaryContainer = Color(0xFFA4F4C3),
    inversePrimary = Color(0xFF1A6C43),
    secondary = Color(0xFFAECEB9),
    onSecondary = Color(0xFF1B3626),
    secondaryContainer = Color(0xFF314D3C),
    onSecondaryContainer = Color(0xFFCAEAD5),
    tertiary = Color(0xFF81D3E1),
    onTertiary = Color(0xFF01363D),
    tertiaryContainer = Color(0xFF014F58),
    onTertiaryContainer = Color(0xFF9EEFFE),
    error = Color(0xFFFFB3B0),
    onError = Color(0xFF680016),
    errorContainer = Color(0xFF920023),
    onErrorContainer = Color(0xFFFEDAD8),
    background = Color(0xFF0F1511),
    onBackground = Color(0xFFDEE4E0),
    surface = Color(0xFF0F1511),
    onSurface = Color(0xFFDEE4E0),
    surfaceVariant = Color(0xFF3D4A41),
    onSurfaceVariant = Color(0xFFBBCAC0),
    surfaceTint = Color(0xFF88D7A7),
    inverseSurface = Color(0xFFDEE4E0),
    inverseOnSurface = Color(0xFF2D312E),
    outline = Color(0xFF86948A),
    outlineVariant = Color(0xFF3D4A41),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF363A37),
    surfaceDim = Color(0xFF0F1511),
    surfaceContainerLowest = Color(0xFF09100B),
    surfaceContainerLow = Color(0xFF181D1A),
    surfaceContainer = Color(0xFF1C211E),
    surfaceContainerHigh = Color(0xFF272B28),
    surfaceContainerHighest = Color(0xFF313633),
)

internal val esquemaOcasoClaro: ColorScheme = lightColorScheme(
    primary = Color(0xFF974722),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFDBCC),
    onPrimaryContainer = Color(0xFF311300),
    inversePrimary = Color(0xFFFFB595),
    secondary = Color(0xFF75584B),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFDBCC),
    onSecondaryContainer = Color(0xFF2D1607),
    tertiary = Color(0xFF834E66),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFFED8E8),
    onTertiaryContainer = Color(0xFF370822),
    error = Color(0xFFB12938),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFEDAD8),
    onErrorContainer = Color(0xFF410003),
    background = Color(0xFFFEF8F6),
    onBackground = Color(0xFF1F1A18),
    surface = Color(0xFFFEF8F6),
    onSurface = Color(0xFF1F1A18),
    surfaceVariant = Color(0xFFF1DFD7),
    onSurfaceVariant = Color(0xFF52443D),
    surfaceTint = Color(0xFF974722),
    inverseSurface = Color(0xFF352F2D),
    inverseOnSurface = Color(0xFFF7EFEC),
    outline = Color(0xFF84746D),
    outlineVariant = Color(0xFFD5C3BB),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFEF8F6),
    surfaceDim = Color(0xFFE0D9D6),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceContainerLow = Color(0xFFF9F2EF),
    surfaceContainer = Color(0xFFF4ECE9),
    surfaceContainerHigh = Color(0xFFEEE7E4),
    surfaceContainerHighest = Color(0xFFE8E1DE),
)

internal val esquemaOcasoOscuro: ColorScheme = darkColorScheme(
    primary = Color(0xFFFFB595),
    onPrimary = Color(0xFF581E00),
    primaryContainer = Color(0xFF7A2F0B),
    onPrimaryContainer = Color(0xFFFFDBCC),
    inversePrimary = Color(0xFF974722),
    secondary = Color(0xFFE2BFB0),
    onSecondary = Color(0xFF442A1F),
    secondaryContainer = Color(0xFF5C4034),
    onSecondaryContainer = Color(0xFFFFDBCC),
    tertiary = Color(0xFFF2B6D0),
    onTertiary = Color(0xFF502038),
    tertiaryContainer = Color(0xFF69374E),
    onTertiaryContainer = Color(0xFFFED8E8),
    error = Color(0xFFFFB3B0),
    onError = Color(0xFF680016),
    errorContainer = Color(0xFF920023),
    onErrorContainer = Color(0xFFFEDAD8),
    background = Color(0xFF18120F),
    onBackground = Color(0xFFE8E1DE),
    surface = Color(0xFF18120F),
    onSurface = Color(0xFFE8E1DE),
    surfaceVariant = Color(0xFF52443D),
    onSurfaceVariant = Color(0xFFD5C3BB),
    surfaceTint = Color(0xFFFFB595),
    inverseSurface = Color(0xFFE8E1DE),
    inverseOnSurface = Color(0xFF352F2D),
    outline = Color(0xFF9E8D86),
    outlineVariant = Color(0xFF52443D),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3E3836),
    surfaceDim = Color(0xFF18120F),
    surfaceContainerLowest = Color(0xFF140D09),
    surfaceContainerLow = Color(0xFF1F1A18),
    surfaceContainer = Color(0xFF231F1C),
    surfaceContainerHigh = Color(0xFF2E2927),
    surfaceContainerHighest = Color(0xFF393431),
)
