#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Catalogo de textos de NexaPDF en los trece idiomas.

Fuente unica de la interfaz. `generar_traducciones.py` convierte esto en los
ficheros `strings.xml` de commonMain/composeResources.

Se mantiene en un solo sitio y no en trece XML sueltos por una razon practica:
asi es imposible anadir un texto y olvidarse de traducirlo a un idioma, porque
el generador comprueba que las trece entradas existan antes de escribir nada.

Convenciones:
  - Se usa el apostrofo tipografico (U+2019), no el recto, para no depender del
    escapado del formato XML de Android.
  - Los marcadores de posicion son de estilo Java: %1$s, %1$d.
"""

IDIOMAS = ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"]

# Carpeta de recursos de cada idioma. El ingles es el respaldo y va en `values`.
CARPETAS = {
    "en": "values",
    "es": "values-es",
    "fr": "values-fr",
    "de": "values-de",
    "zh": "values-zh",
    "ja": "values-ja",
    "ru": "values-ru",
    "it": "values-it",
    "el": "values-el",
    "ar": "values-ar",
    "gl": "values-gl",
    "ca": "values-ca",
    "eu": "values-eu",
}

TEXTOS = {
    "sep_parte_n": {
        "en": "Part %1$d",
        "es": "Parte %1$d",
        "fr": "Partie %1$d",
        "de": "Teil %1$d",
        "zh": "第 %1$d 部分",
        "ja": "パート %1$d",
        "ru": "Часть %1$d",
        "it": "Parte %1$d",
        "el": "Μέρος %1$d",
        "ar": "الجزء %1$d",
        "gl": "Parte %1$d",
        "ca": "Part %1$d",
        "eu": "%1$d. zatia",
    },
    "sep_toca_paginas": {
        "en": "Tap the first page of the part and then the last one. You can also type the numbers.",
        "es": "Toca la primera página de la parte y luego la última. También puedes escribir los números.",
        "fr": "Touchez la première page de la partie puis la dernière. Vous pouvez aussi saisir les numéros.",
        "de": "Tippen Sie auf die erste Seite des Teils und dann auf die letzte. Sie können die Nummern auch eintippen.",
        "zh": "先点这一部分的首页，再点末页。也可以直接输入页码。",
        "ja": "パートの最初のページをタップし、次に最後のページをタップします。番号を入力しても構いません。",
        "ru": "Нажмите первую страницу части, затем последнюю. Номера можно и ввести вручную.",
        "it": "Tocca la prima pagina della parte e poi l’ultima. Puoi anche scrivere i numeri.",
        "el": "Πατήστε την πρώτη σελίδα του μέρους και μετά την τελευταία. Μπορείτε και να γράψετε τους αριθμούς.",
        "ar": "المس أول صفحة في الجزء ثم آخر صفحة. ويمكنك كتابة الأرقام أيضًا.",
        "gl": "Toca a primeira páxina da parte e logo a última. Tamén podes escribir os números.",
        "ca": "Toca la primera pàgina de la part i després l’última. També pots escriure els números.",
        "eu": "Ukitu zatiaren lehen orria eta gero azkena. Zenbakiak idatz ditzakezu ere.",
    },
    "sep_sin_asignar": {
        "en": "Not in any part",
        "es": "Sin parte asignada",
        "fr": "Dans aucune partie",
        "de": "Keinem Teil zugeordnet",
        "zh": "未分配到任何部分",
        "ja": "どのパートにも入っていません",
        "ru": "Не входит ни в одну часть",
        "it": "In nessuna parte",
        "el": "Σε κανένα μέρος",
        "ar": "ليست ضمن أي جزء",
        "gl": "Sen parte asignada",
        "ca": "Sense part assignada",
        "eu": "Zatirik gabe",
    },
    "sep_crear": {
        "en": "Create the files",
        "es": "Crear los ficheros",
        "fr": "Créer les fichiers",
        "de": "Dateien erstellen",
        "zh": "创建文件",
        "ja": "ファイルを作成",
        "ru": "Создать файлы",
        "it": "Crea i file",
        "el": "Δημιουργία αρχείων",
        "ar": "إنشاء الملفات",
        "gl": "Crear os ficheiros",
        "ca": "Crea els fitxers",
        "eu": "Sortu fitxategiak",
    },
    "sep_rango": {
        "en": "Pages %1$s",
        "es": "Páginas %1$s",
        "fr": "Pages %1$s",
        "de": "Seiten %1$s",
        "zh": "第 %1$s 页",
        "ja": "%1$s ページ",
        "ru": "Страницы %1$s",
        "it": "Pagine %1$s",
        "el": "Σελίδες %1$s",
        "ar": "الصفحات %1$s",
        "gl": "Páxinas %1$s",
        "ca": "Pàgines %1$s",
        "eu": "%1$s orriak",
    },
    "ayuda_visor_t": {
        "en": "Reading a PDF",
        "es": "Leer un PDF",
        "fr": "Lire un PDF",
        "de": "Ein PDF lesen",
        "zh": "阅读 PDF",
        "ja": "PDF を読む",
        "ru": "Чтение PDF",
        "it": "Leggere un PDF",
        "el": "Ανάγνωση PDF",
        "ar": "قراءة ملف PDF",
        "gl": "Ler un PDF",
        "ca": "Llegir un PDF",
        "eu": "PDF bat irakurri",
    },
    "ayuda_visor_c": {
        "en": "Open a document with Read PDF, or tap one in Recent files. The magnifier searches the whole document: matches are highlighted on the page and the arrows move between them. The list icon shows the document’s sections, if it has any, and the shield lists its digital signatures. Pinch to zoom and drag to move around.",
        "es": "Abre un documento con Leer PDF, o toca uno en Ficheros recientes. La lupa busca en todo el documento: las apariciones quedan resaltadas sobre la página y las flechas te llevan de una a otra. El icono de lista muestra las secciones del documento, si las tiene, y el escudo sus firmas digitales. Pellizca para ampliar y arrastra para moverte.",
        "fr": "Ouvrez un document avec Lire un PDF, ou touchez-en un dans Fichiers récents. La loupe cherche dans tout le document : les occurrences sont surlignées sur la page et les flèches passent de l’une à l’autre. L’icône de liste montre les sections, et le bouclier les signatures numériques. Pincez pour zoomer et faites glisser pour vous déplacer.",
        "de": "Öffnen Sie ein Dokument mit PDF lesen oder tippen Sie eins unter Zuletzt verwendet an. Die Lupe durchsucht das ganze Dokument: Treffer werden auf der Seite hervorgehoben, die Pfeile springen zwischen ihnen. Das Listensymbol zeigt die Abschnitte, das Schild die digitalen Signaturen. Zum Zoomen zwei Finger, zum Bewegen ziehen.",
        "zh": "用「阅读 PDF」打开文档，或在最近文件中点按一个。放大镜可搜索整个文档：匹配处会在页面上高亮，箭头可在它们之间跳转。列表图标显示文档章节（如果有），盾牌图标显示数字签名。双指缩放，拖动移动。",
        "ja": "「PDF を読む」で開くか、最近のファイルから選びます。虫めがねは文書全体を検索し、見つかった箇所はページ上で強調され、矢印で移動できます。リストのアイコンは目次、盾のアイコンは電子署名を表示します。ピンチで拡大、ドラッグで移動します。",
        "ru": "Откройте документ через «Читать PDF» или коснитесь его в недавних файлах. Лупа ищет по всему документу: совпадения подсвечиваются на странице, стрелки переходят между ними. Значок списка показывает разделы, щит — цифровые подписи. Щипок для масштаба, перетаскивание для перемещения.",
        "it": "Apri un documento con Leggi PDF o toccane uno tra i file recenti. La lente cerca in tutto il documento: le occorrenze vengono evidenziate sulla pagina e le frecce le scorrono. L’icona a lista mostra le sezioni, lo scudo le firme digitali. Pizzica per ingrandire e trascina per spostarti.",
        "el": "Ανοίξτε ένα έγγραφο με Ανάγνωση PDF ή πατήστε ένα στα πρόσφατα αρχεία. Ο μεγεθυντικός φακός ψάχνει σε όλο το έγγραφο: τα ευρήματα τονίζονται στη σελίδα και τα βέλη σας μετακινούν. Το εικονίδιο λίστας δείχνει τις ενότητες και η ασπίδα τις ψηφιακές υπογραφές.",
        "ar": "افتح مستندًا من «قراءة PDF» أو المس واحدًا في الملفات الأخيرة. تبحث العدسة في المستند كله: تُبرَز النتائج على الصفحة وتنقلك الأسهم بينها. أيقونة القائمة تعرض أقسام المستند، والدرع يعرض التواقيع الرقمية. اقرص للتكبير واسحب للتنقّل.",
        "gl": "Abre un documento con Ler PDF, ou toca un en Ficheiros recentes. A lupa busca en todo o documento: as aparicións quedan resaltadas na páxina e as frechas lévanche dunha a outra. A icona de lista amosa as seccións e o escudo as sinaturas dixitais.",
        "ca": "Obre un document amb Llegeix PDF, o toca’n un a Fitxers recents. La lupa cerca a tot el document: les aparicions queden ressaltades a la pàgina i les fletxes t’hi porten. La icona de llista mostra les seccions i l’escut les signatures digitals.",
        "eu": "Ireki dokumentu bat «Irakurri PDFa» aukerarekin, edo ukitu bat azken fitxategietan. Lupak dokumentu osoan bilatzen du: agerraldiak orrian nabarmentzen dira eta gezien bidez mugitzen zara. Zerrenda-ikonoak atalak erakusten ditu, eta ezkutuak sinadura digitalak.",
    },
    "ayuda_convertir_t": {
        "en": "Converting to Word, Excel or PowerPoint",
        "es": "Convertir a Word, Excel o PowerPoint",
        "fr": "Convertir en Word, Excel ou PowerPoint",
        "de": "In Word, Excel oder PowerPoint umwandeln",
        "zh": "转换为 Word、Excel 或 PowerPoint",
        "ja": "Word・Excel・PowerPoint への変換",
        "ru": "Конвертация в Word, Excel или PowerPoint",
        "it": "Convertire in Word, Excel o PowerPoint",
        "el": "Μετατροπή σε Word, Excel ή PowerPoint",
        "ar": "التحويل إلى Word أو Excel أو PowerPoint",
        "gl": "Converter a Word, Excel ou PowerPoint",
        "ca": "Convertir a Word, Excel o PowerPoint",
        "eu": "Word, Excel edo PowerPoint-era bihurtu",
    },
    "ayuda_convertir_c": {
        "en": "The Convert tool works both ways: pick a Word, Excel or PowerPoint file and it becomes a PDF; pick a PDF and you choose the format to export to. Tables in the PDF are detected and come out as real tables in Word. What you get is the content recomposed as well as possible, not the original Office file: a PDF stores letters placed on a page, not paragraphs or cells.",
        "es": "La herramienta Convertir funciona en los dos sentidos: eliges un Word, Excel o PowerPoint y sale un PDF, o eliges un PDF y decides a qué formato exportarlo. Las tablas del PDF se detectan y salen como tablas de verdad en Word. Lo que obtienes es el contenido recompuesto lo mejor posible, no el documento de Office original: un PDF guarda letras colocadas sobre una página, no párrafos ni celdas.",
        "fr": "L’outil Convertir fonctionne dans les deux sens : choisissez un Word, Excel ou PowerPoint et vous obtenez un PDF ; choisissez un PDF et vous décidez du format de sortie. Les tableaux du PDF sont détectés et deviennent de vrais tableaux dans Word. Ce que vous obtenez est le contenu recomposé au mieux, pas le fichier Office d’origine.",
        "de": "Das Werkzeug Umwandeln funktioniert in beide Richtungen: Wählen Sie eine Word-, Excel- oder PowerPoint-Datei, und es entsteht ein PDF; wählen Sie ein PDF, und Sie bestimmen das Zielformat. Tabellen im PDF werden erkannt und in Word zu echten Tabellen. Sie erhalten den bestmöglich zusammengesetzten Inhalt, nicht die ursprüngliche Office-Datei.",
        "zh": "「转换」工具双向可用：选择 Word、Excel 或 PowerPoint 会生成 PDF；选择 PDF 则由你决定导出格式。PDF 中的表格会被识别，并在 Word 中还原为真正的表格。得到的是尽力还原的内容，而非原始 Office 文件。",
        "ja": "「変換」は双方向です。Word・Excel・PowerPoint を選べば PDF になり、PDF を選べば出力形式を選べます。PDF 内の表は検出され、Word では本物の表になります。得られるのは可能な限り組み直した内容であり、元の Office ファイルそのものではありません。",
        "ru": "Инструмент «Конвертировать» работает в обе стороны: выберите Word, Excel или PowerPoint — получится PDF; выберите PDF — сами укажете формат. Таблицы в PDF распознаются и становятся настоящими таблицами в Word. Вы получаете содержимое, восстановленное как можно точнее, а не исходный файл Office.",
        "it": "Lo strumento Converti funziona in entrambe le direzioni: scegli un Word, Excel o PowerPoint e ottieni un PDF; scegli un PDF e decidi il formato di uscita. Le tabelle del PDF vengono riconosciute e diventano tabelle vere in Word. Ottieni il contenuto ricomposto al meglio, non il file Office originale.",
        "el": "Το εργαλείο Μετατροπή λειτουργεί και προς τις δύο κατευθύνσεις: επιλέγετε Word, Excel ή PowerPoint και προκύπτει PDF· επιλέγετε PDF και ορίζετε τη μορφή εξόδου. Οι πίνακες του PDF αναγνωρίζονται και γίνονται πραγματικοί πίνακες στο Word.",
        "ar": "تعمل أداة التحويل في الاتجاهين: اختر ملف Word أو Excel أو PowerPoint فينتج PDF، أو اختر ملف PDF وحدّد الصيغة. تُكتشف جداول الـ PDF وتخرج جداول حقيقية في Word. ما تحصل عليه هو المحتوى مُعاد تركيبه قدر الإمكان، لا ملف Office الأصلي.",
        "gl": "A ferramenta Converter funciona nos dous sentidos: escolles un Word, Excel ou PowerPoint e sae un PDF, ou escolles un PDF e decides a que formato exportalo. As táboas do PDF detéctanse e saen como táboas de verdade en Word.",
        "ca": "L’eina Converteix funciona en tots dos sentits: tries un Word, Excel o PowerPoint i en surt un PDF, o tries un PDF i decideixes a quin format exportar-lo. Les taules del PDF es detecten i surten com a taules de debò al Word.",
        "eu": "Bihurtu tresnak bi noranzkoetan funtzionatzen du: Word, Excel edo PowerPoint bat aukeratuz gero PDFa sortzen da; PDF bat aukeratuz gero, zuk erabakitzen duzu zein formatutara. PDFko taulak detektatu eta Word-en benetako taula bihurtzen dira.",
    },
    "vis_anterior": {
        "en": "Previous match",
        "es": "Aparición anterior",
        "fr": "Occurrence précédente",
        "de": "Vorheriger Treffer",
        "zh": "上一处匹配",
        "ja": "前の一致",
        "ru": "Предыдущее совпадение",
        "it": "Occorrenza precedente",
        "el": "Προηγούμενο αποτέλεσμα",
        "ar": "النتيجة السابقة",
        "gl": "Aparición anterior",
        "ca": "Aparició anterior",
        "eu": "Aurreko agerraldia",
    },
    "vis_siguiente": {
        "en": "Next match",
        "es": "Aparición siguiente",
        "fr": "Occurrence suivante",
        "de": "Nächster Treffer",
        "zh": "下一处匹配",
        "ja": "次の一致",
        "ru": "Следующее совпадение",
        "it": "Occorrenza successiva",
        "el": "Επόμενο αποτέλεσμα",
        "ar": "النتيجة التالية",
        "gl": "Aparición seguinte",
        "ca": "Aparició següent",
        "eu": "Hurrengo agerraldia",
    },
    "sep_titulo": {
        "en": "Split into parts",
        "es": "Dividir en partes",
        "fr": "Diviser en parties",
        "de": "In Teile aufteilen",
        "zh": "分成多个部分",
        "ja": "パートに分割",
        "ru": "Разделить на части",
        "it": "Dividi in parti",
        "el": "Διαχωρισμός σε μέρη",
        "ar": "التقسيم إلى أجزاء",
        "gl": "Dividir en partes",
        "ca": "Divideix en parts",
        "eu": "Zatitu zatitan",
    },
    "sep_desde": {
        "en": "From",
        "es": "Desde",
        "fr": "De",
        "de": "Von",
        "zh": "起始页",
        "ja": "開始",
        "ru": "С",
        "it": "Da",
        "el": "Από",
        "ar": "من",
        "gl": "Desde",
        "ca": "Des de",
        "eu": "Nondik",
    },
    "sep_hasta": {
        "en": "To",
        "es": "Hasta",
        "fr": "À",
        "de": "Bis",
        "zh": "结束页",
        "ja": "終了",
        "ru": "По",
        "it": "A",
        "el": "Έως",
        "ar": "إلى",
        "gl": "Ata",
        "ca": "Fins a",
        "eu": "Nora",
    },
    "sep_nombre_parte": {
        "en": "File name",
        "es": "Nombre del fichero",
        "fr": "Nom du fichier",
        "de": "Dateiname",
        "zh": "文件名",
        "ja": "ファイル名",
        "ru": "Имя файла",
        "it": "Nome del file",
        "el": "Όνομα αρχείου",
        "ar": "اسم الملف",
        "gl": "Nome do ficheiro",
        "ca": "Nom del fitxer",
        "eu": "Fitxategiaren izena",
    },
    "sep_anadir_parte": {
        "en": "Add a part",
        "es": "Añadir una parte",
        "fr": "Ajouter une partie",
        "de": "Teil hinzufügen",
        "zh": "添加一个部分",
        "ja": "パートを追加",
        "ru": "Добавить часть",
        "it": "Aggiungi una parte",
        "el": "Προσθήκη μέρους",
        "ar": "إضافة جزء",
        "gl": "Engadir unha parte",
        "ca": "Afegeix una part",
        "eu": "Gehitu zati bat",
    },
    "sep_quitar_parte": {
        "en": "Remove this part",
        "es": "Quitar esta parte",
        "fr": "Retirer cette partie",
        "de": "Diesen Teil entfernen",
        "zh": "移除此部分",
        "ja": "このパートを削除",
        "ru": "Убрать эту часть",
        "it": "Rimuovi questa parte",
        "el": "Αφαίρεση μέρους",
        "ar": "إزالة هذا الجزء",
        "gl": "Quitar esta parte",
        "ca": "Treu aquesta part",
        "eu": "Kendu zati hau",
    },
    "doc_separar_partes": {
        "en": "Split into parts…",
        "es": "Dividir en partes…",
        "fr": "Diviser en parties…",
        "de": "In Teile aufteilen…",
        "zh": "分成多个部分…",
        "ja": "パートに分割…",
        "ru": "Разделить на части…",
        "it": "Dividi in parti…",
        "el": "Διαχωρισμός σε μέρη…",
        "ar": "التقسيم إلى أجزاء…",
        "gl": "Dividir en partes…",
        "ca": "Divideix en parts…",
        "eu": "Zatitu zatitan…",
    },
    "rec_ordenar_por": {
        "en": "Sort by",
        "es": "Ordenar por",
        "fr": "Trier par",
        "de": "Sortieren nach",
        "zh": "排序方式",
        "ja": "並べ替え",
        "ru": "Сортировка",
        "it": "Ordina per",
        "el": "Ταξινόμηση κατά",
        "ar": "الترتيب حسب",
        "gl": "Ordenar por",
        "ca": "Ordena per",
        "eu": "Ordenatu honela",
    },
    "rec_orden_recientes": {
        "en": "Most recent",
        "es": "Más recientes",
        "fr": "Plus récents",
        "de": "Neueste zuerst",
        "zh": "最新优先",
        "ja": "新しい順",
        "ru": "Сначала новые",
        "it": "Più recenti",
        "el": "Πιο πρόσφατα",
        "ar": "الأحدث أولًا",
        "gl": "Máis recentes",
        "ca": "Més recents",
        "eu": "Berrienak lehenik",
    },
    "rec_orden_nombre": {
        "en": "Name",
        "es": "Nombre",
        "fr": "Nom",
        "de": "Name",
        "zh": "名称",
        "ja": "名前",
        "ru": "Имя",
        "it": "Nome",
        "el": "Όνομα",
        "ar": "الاسم",
        "gl": "Nome",
        "ca": "Nom",
        "eu": "Izena",
    },
    "rec_orden_tamano": {
        "en": "Size",
        "es": "Tamaño",
        "fr": "Taille",
        "de": "Größe",
        "zh": "大小",
        "ja": "サイズ",
        "ru": "Размер",
        "it": "Dimensione",
        "el": "Μέγεθος",
        "ar": "الحجم",
        "gl": "Tamaño",
        "ca": "Mida",
        "eu": "Tamaina",
    },
    "rec_vista": {
        "en": "Change view",
        "es": "Cambiar la vista",
        "fr": "Changer d’affichage",
        "de": "Ansicht wechseln",
        "zh": "切换视图",
        "ja": "表示を切り替え",
        "ru": "Сменить вид",
        "it": "Cambia vista",
        "el": "Αλλαγή προβολής",
        "ar": "تغيير طريقة العرض",
        "gl": "Cambiar a vista",
        "ca": "Canvia la vista",
        "eu": "Aldatu ikuspegia",
    },
    "comp_pregunta_titulo": {
        "en": "Share this document?",
        "es": "¿Compartir este documento?",
        "fr": "Partager ce document ?",
        "de": "Dieses Dokument teilen?",
        "zh": "要分享这个文档吗？",
        "ja": "この文書を共有しますか？",
        "ru": "Поделиться этим документом?",
        "it": "Condividere questo documento?",
        "el": "Κοινή χρήση αυτού του εγγράφου;",
        "ar": "هل تريد مشاركة هذا المستند؟",
        "gl": "Compartir este documento?",
        "ca": "Vols compartir aquest document?",
        "eu": "Dokumentu hau partekatu?",
    },
    "aj_preguntar_compartir": {
        "en": "Ask to share when a document is ready",
        "es": "Preguntar si compartir al terminar un documento",
        "fr": "Proposer de partager quand un document est prêt",
        "de": "Nach dem Erstellen fragen, ob geteilt werden soll",
        "zh": "文档完成后询问是否分享",
        "ja": "文書ができたら共有するか尋ねる",
        "ru": "Спрашивать о отправке готового документа",
        "it": "Chiedere se condividere quando un documento è pronto",
        "el": "Ερώτηση για κοινή χρήση όταν ένα έγγραφο είναι έτοιμο",
        "ar": "السؤال عن المشاركة عند إتمام مستند",
        "gl": "Preguntar se compartir ao rematar un documento",
        "ca": "Preguntar si compartir en acabar un document",
        "eu": "Galdetu partekatzeko dokumentu bat prest dagoenean",
    },
    "comun_reordenar": {
        "en": "Drag to reorder",
        "es": "Arrastra para reordenar",
        "fr": "Faites glisser pour réordonner",
        "de": "Zum Umsortieren ziehen",
        "zh": "拖动以重新排序",
        "ja": "ドラッグして並べ替え",
        "ru": "Перетащите, чтобы изменить порядок",
        "it": "Trascina per riordinare",
        "el": "Σύρετε για αναδιάταξη",
        "ar": "اسحب لإعادة الترتيب",
        "gl": "Arrastra para reordenar",
        "ca": "Arrossega per reordenar",
        "eu": "Arrastatu berrantolatzeko",
    },
    "color_personalizado": {
        "en": "Custom colour",
        "es": "Color personalizado",
        "fr": "Couleur personnalisée",
        "de": "Eigene Farbe",
        "zh": "自定义颜色",
        "ja": "自由な色",
        "ru": "Свой цвет",
        "it": "Colore personalizzato",
        "el": "Προσαρμοσμένο χρώμα",
        "ar": "لون مخصّص",
        "gl": "Cor personalizada",
        "ca": "Color personalitzat",
        "eu": "Kolore pertsonalizatua",
    },
    # --- Visor, conversor y recientes ----------------------------------------
    "comun_buscar": {
        "en": "Search",
        "es": "Buscar",
        "fr": "Rechercher",
        "de": "Suchen",
        "zh": "搜索",
        "ja": "検索",
        "ru": "Поиск",
        "it": "Cerca",
        "el": "Αναζήτηση",
        "ar": "بحث",
        "gl": "Buscar",
        "ca": "Cerca",
        "eu": "Bilatu",
    },
    "herr_visor_titulo": {
        "en": "Read PDF",
        "es": "Leer PDF",
        "fr": "Lire un PDF",
        "de": "PDF lesen",
        "zh": "阅读 PDF",
        "ja": "PDF を読む",
        "ru": "Читать PDF",
        "it": "Leggi PDF",
        "el": "Ανάγνωση PDF",
        "ar": "قراءة PDF",
        "gl": "Ler PDF",
        "ca": "Llegeix PDF",
        "eu": "Irakurri PDFa",
    },
    "herr_visor_desc": {
        "en": "Read, search and jump around the document",
        "es": "Lee, busca y muévete por el documento",
        "fr": "Lisez, cherchez et naviguez dans le document",
        "de": "Lesen, suchen und im Dokument navigieren",
        "zh": "阅读、搜索并在文档中跳转",
        "ja": "読む、探す、文書内を移動する",
        "ru": "Читайте, ищите и перемещайтесь по документу",
        "it": "Leggi, cerca e spostati nel documento",
        "el": "Διαβάστε, αναζητήστε και πλοηγηθείτε στο έγγραφο",
        "ar": "اقرأ وابحث وتنقّل في المستند",
        "gl": "Le, busca e móvete polo documento",
        "ca": "Llegeix, cerca i mou-te pel document",
        "eu": "Irakurri, bilatu eta mugitu dokumentuan",
    },
    "herr_convertir_titulo": {
        "en": "Convert",
        "es": "Convertir",
        "fr": "Convertir",
        "de": "Umwandeln",
        "zh": "转换",
        "ja": "変換",
        "ru": "Конвертировать",
        "it": "Converti",
        "el": "Μετατροπή",
        "ar": "تحويل",
        "gl": "Converter",
        "ca": "Converteix",
        "eu": "Bihurtu",
    },
    "herr_convertir_desc": {
        "en": "Word, Excel and PowerPoint to PDF, and the other way round",
        "es": "Word, Excel y PowerPoint a PDF, y al revés",
        "fr": "Word, Excel et PowerPoint vers PDF, et l’inverse",
        "de": "Word, Excel und PowerPoint zu PDF und umgekehrt",
        "zh": "Word、Excel、PowerPoint 与 PDF 互转",
        "ja": "Word・Excel・PowerPoint と PDF の相互変換",
        "ru": "Word, Excel и PowerPoint в PDF и обратно",
        "it": "Word, Excel e PowerPoint in PDF, e viceversa",
        "el": "Word, Excel και PowerPoint σε PDF, και αντίστροφα",
        "ar": "من Word و Excel و PowerPoint إلى PDF والعكس",
        "gl": "Word, Excel e PowerPoint a PDF, e ao revés",
        "ca": "Word, Excel i PowerPoint a PDF, i a l’inrevés",
        "eu": "Word, Excel eta PowerPoint PDFra, eta alderantziz",
    },
    "visor_indice": {
        "en": "Contents",
        "es": "Índice",
        "fr": "Sommaire",
        "de": "Inhalt",
        "zh": "目录",
        "ja": "目次",
        "ru": "Оглавление",
        "it": "Indice",
        "el": "Περιεχόμενα",
        "ar": "الفهرس",
        "gl": "Índice",
        "ca": "Índex",
        "eu": "Aurkibidea",
    },
    "visor_sin_indice": {
        "en": "This document has no contents list. Scanned documents usually don’t.",
        "es": "Este documento no trae índice. Los escaneados no suelen tenerlo.",
        "fr": "Ce document n’a pas de sommaire. Les documents numérisés n’en ont généralement pas.",
        "de": "Dieses Dokument hat kein Inhaltsverzeichnis. Gescannte Dokumente meist nicht.",
        "zh": "此文档没有目录。扫描件通常没有。",
        "ja": "この文書に目次はありません。スキャンした文書にはたいてい入っていません。",
        "ru": "В этом документе нет оглавления. У сканов его обычно не бывает.",
        "it": "Questo documento non ha un indice. I documenti scansionati di solito non ce l’hanno.",
        "el": "Αυτό το έγγραφο δεν έχει περιεχόμενα. Τα σαρωμένα συνήθως δεν έχουν.",
        "ar": "لا يحتوي هذا المستند على فهرس. المستندات الممسوحة ضوئيًا عادةً لا تحتوي عليه.",
        "gl": "Este documento non trae índice. Os escaneados non adoitan telo.",
        "ca": "Aquest document no porta índex. Els escanejats no acostumen a tenir-ne.",
        "eu": "Dokumentu honek ez du aurkibiderik. Eskaneatutakoek normalean ez dute.",
    },
    "visor_sin_resultados": {
        "en": "No matches",
        "es": "Sin resultados",
        "fr": "Aucun résultat",
        "de": "Keine Treffer",
        "zh": "没有结果",
        "ja": "見つかりません",
        "ru": "Ничего не найдено",
        "it": "Nessun risultato",
        "el": "Κανένα αποτέλεσμα",
        "ar": "لا نتائج",
        "gl": "Sen resultados",
        "ca": "Cap resultat",
        "eu": "Emaitzarik ez",
    },
    "visor_pagina_numero": {
        "en": "Page %1$d",
        "es": "Página %1$d",
        "fr": "Page %1$d",
        "de": "Seite %1$d",
        "zh": "第 %1$d 页",
        "ja": "%1$d ページ",
        "ru": "Страница %1$d",
        "it": "Pagina %1$d",
        "el": "Σελίδα %1$d",
        "ar": "الصفحة %1$d",
        "gl": "Páxina %1$d",
        "ca": "Pàgina %1$d",
        "eu": "%1$d. orria",
    },
    "conv_elige_destino": {
        "en": "Convert to…",
        "es": "Convertir a…",
        "fr": "Convertir en…",
        "de": "Umwandeln in…",
        "zh": "转换为…",
        "ja": "変換先…",
        "ru": "Конвертировать в…",
        "it": "Converti in…",
        "el": "Μετατροπή σε…",
        "ar": "التحويل إلى…",
        "gl": "Converter a…",
        "ca": "Converteix a…",
        "eu": "Bihurtu hona…",
    },
    # --- Tour guiado ---------------------------------------------------------
    "tour_saltar": {
        "en": "Skip",
        "es": "Saltar",
        "fr": "Passer",
        "de": "Überspringen",
        "zh": "跳过",
        "ja": "スキップ",
        "ru": "Пропустить",
        "it": "Salta",
        "el": "Παράλειψη",
        "ar": "تخطٍّ",
        "gl": "Saltar",
        "ca": "Omet",
        "eu": "Saltatu",
    },
    "tour_siguiente": {
        "en": "Next",
        "es": "Siguiente",
        "fr": "Suivant",
        "de": "Weiter",
        "zh": "下一步",
        "ja": "次へ",
        "ru": "Далее",
        "it": "Avanti",
        "el": "Επόμενο",
        "ar": "التالي",
        "gl": "Seguinte",
        "ca": "Següent",
        "eu": "Hurrengoa",
    },
    "tour_empezar": {
        "en": "Get started",
        "es": "Empezar",
        "fr": "Commencer",
        "de": "Loslegen",
        "zh": "开始使用",
        "ja": "はじめる",
        "ru": "Начать",
        "it": "Iniziamo",
        "el": "Ξεκινάμε",
        "ar": "لنبدأ",
        "gl": "Comezar",
        "ca": "Comencem",
        "eu": "Hasi",
    },
    "tour_ver_otra_vez": {
        "en": "Show the tour again",
        "es": "Ver el tour otra vez",
        "fr": "Revoir la visite guidée",
        "de": "Rundgang erneut ansehen",
        "zh": "重新查看导览",
        "ja": "ツアーをもう一度見る",
        "ru": "Показать обзор снова",
        "it": "Rivedi il tour",
        "el": "Δείτε ξανά την ξενάγηση",
        "ar": "إعادة عرض الجولة",
        "gl": "Ver o tour outra vez",
        "ca": "Torna a veure el tour",
        "eu": "Ikusi bisita berriro",
    },
    "tour_1_titulo": {
        "en": "Your PDFs never leave the phone",
        "es": "Tus PDF no salen del teléfono",
        "fr": "Vos PDF ne quittent pas le téléphone",
        "de": "Ihre PDFs verlassen das Telefon nicht",
        "zh": "您的 PDF 不会离开手机",
        "ja": "PDF は端末から出ません",
        "ru": "Ваши PDF не покидают телефон",
        "it": "I tuoi PDF non escono dal telefono",
        "el": "Τα PDF σας δεν φεύγουν από το τηλέφωνο",
        "ar": "ملفات PDF لا تغادر هاتفك",
        "gl": "Os teus PDF non saen do teléfono",
        "ca": "Els teus PDF no surten del telèfon",
        "eu": "Zure PDFak ez dira telefonotik ateratzen",
    },
    "tour_1_texto": {
        "en": "NexaPDF does not ask for internet permission, so it cannot upload anything. Everything happens on your device, with no account and no sign-up.",
        "es": "NexaPDF no pide permiso de internet, así que no puede subir nada. Todo ocurre en tu dispositivo, sin cuenta y sin registro.",
        "fr": "NexaPDF ne demande pas la permission d’accès à internet : il ne peut rien envoyer. Tout se passe sur votre appareil, sans compte ni inscription.",
        "de": "NexaPDF fordert keine Internetberechtigung an und kann daher nichts hochladen. Alles geschieht auf Ihrem Gerät, ohne Konto und ohne Anmeldung.",
        "zh": "NexaPDF 不申请联网权限，因此无法上传任何内容。一切都在您的设备上完成，无需账号和注册。",
        "ja": "NexaPDF はインターネット権限を要求しないため、何もアップロードできません。すべて端末内で完結し、アカウント登録も不要です。",
        "ru": "NexaPDF не запрашивает разрешение на доступ в интернет, поэтому ничего не может отправить. Всё происходит на вашем устройстве, без аккаунта и регистрации.",
        "it": "NexaPDF non chiede il permesso di accesso a internet, quindi non può caricare nulla. Tutto avviene sul tuo dispositivo, senza account né registrazione.",
        "el": "Το NexaPDF δεν ζητά άδεια για internet, οπότε δεν μπορεί να ανεβάσει τίποτα. Όλα γίνονται στη συσκευή σας, χωρίς λογαριασμό και χωρίς εγγραφή.",
        "ar": "لا يطلب NexaPDF إذن الإنترنت، لذا لا يمكنه رفع أي شيء. كل شيء يجري على جهازك، بلا حساب ولا تسجيل.",
        "gl": "NexaPDF non pide permiso de internet, así que non pode subir nada. Todo ocorre no teu dispositivo, sen conta e sen rexistro.",
        "ca": "NexaPDF no demana permís d’internet, així que no pot pujar res. Tot passa al teu dispositiu, sense compte ni registre.",
        "eu": "NexaPDFk ez du interneterako baimenik eskatzen, beraz ezin du ezer igo. Dena zure gailuan gertatzen da, konturik eta izen-ematerik gabe.",
    },
    "tour_2_titulo": {
        "en": "Six tools on the home screen",
        "es": "Seis herramientas en la pantalla de inicio",
        "fr": "Six outils sur l’écran d’accueil",
        "de": "Sechs Werkzeuge auf dem Startbildschirm",
        "zh": "主屏幕上的六个工具",
        "ja": "ホーム画面の 6 つの道具",
        "ru": "Шесть инструментов на главном экране",
        "it": "Sei strumenti nella schermata iniziale",
        "el": "Έξι εργαλεία στην αρχική οθόνη",
        "ar": "ست أدوات في الشاشة الرئيسية",
        "gl": "Seis ferramentas na pantalla de inicio",
        "ca": "Sis eines a la pantalla d’inici",
        "eu": "Sei tresna hasierako pantailan",
    },
    "tour_2_texto": {
        "en": "Read and search a PDF, merge, split, turn photos into documents, edit pages, sign and convert. Everything fits on one screen, and your recent files have their own tile.",
        "es": "Leer y buscar en un PDF, unir, separar, convertir fotos en documentos, editar páginas, firmar y convertir a Office. Todo cabe en una pantalla, y tus ficheros recientes tienen su propia baldosa.",
        "fr": "Lire et rechercher dans un PDF, fusionner, diviser, transformer des photos en documents, modifier des pages, signer et convertir. Tout tient sur un écran, et vos fichiers récents ont leur propre tuile.",
        "de": "Ein PDF lesen und durchsuchen, zusammenfügen, teilen, Fotos in Dokumente verwandeln, Seiten bearbeiten, unterschreiben und umwandeln. Alles passt auf einen Bildschirm, und Ihre letzten Dateien haben eine eigene Kachel.",
        "zh": "阅读和搜索 PDF、合并、拆分、把照片变成文档、编辑页面、签名和转换。全部装在一屏内，最近的文件也有自己的入口。",
        "ja": "PDF を読んで探す、結合、分割、写真から文書、ページ編集、署名、Office への変換。すべて 1 画面に収まり、最近のファイルにも専用のタイルがあります。",
        "ru": "Читать и искать в PDF, объединять, разделять, превращать фото в документы, редактировать страницы, подписывать и конвертировать. Всё помещается на одном экране, а недавние файлы имеют свою плитку.",
        "it": "Leggere e cercare in un PDF, unire, dividere, trasformare foto in documenti, modificare pagine, firmare e convertire. Tutto sta in una schermata, e i file recenti hanno la loro casella.",
        "el": "Ανάγνωση και αναζήτηση σε PDF, ένωση, διαχωρισμός, φωτογραφίες σε έγγραφα, επεξεργασία σελίδων, υπογραφή και μετατροπή. Όλα χωρούν σε μία οθόνη, και τα πρόσφατα αρχεία έχουν το δικό τους πλακίδιο.",
        "ar": "قراءة PDF والبحث فيه، والدمج، والفصل، وتحويل الصور إلى مستندات، وتحرير الصفحات، والتوقيع، والتحويل. كل ذلك في شاشة واحدة، وللملفات الأخيرة مربّعها الخاص.",
        "gl": "Ler e buscar nun PDF, unir, separar, converter fotos en documentos, editar páxinas, asinar e converter. Todo cabe nunha pantalla, e os teus ficheiros recentes teñen a súa propia baldosa.",
        "ca": "Llegir i cercar en un PDF, unir, separar, convertir fotos en documents, editar pàgines, signar i convertir. Tot cap en una pantalla, i els fitxers recents tenen la seva pròpia rajola.",
        "eu": "PDF bat irakurri eta bertan bilatu, batu, banandu, argazkiak dokumentu bihurtu, orriak editatu, sinatu eta bihurtu. Dena pantaila batean sartzen da, eta azken fitxategiek beren lauza dute.",
    },
    "tour_3_titulo": {
        "en": "Draw, write and sign on the page",
        "es": "Dibuja, escribe y firma sobre la página",
        "fr": "Dessinez, écrivez et signez sur la page",
        "de": "Zeichnen, schreiben und unterschreiben Sie auf der Seite",
        "zh": "在页面上绘制、书写和签名",
        "ja": "ページに描き、書き、署名する",
        "ru": "Рисуйте, пишите и подписывайте прямо на странице",
        "it": "Disegna, scrivi e firma sulla pagina",
        "el": "Σχεδιάστε, γράψτε και υπογράψτε πάνω στη σελίδα",
        "ar": "ارسم واكتب ووقّع على الصفحة",
        "gl": "Debuxa, escribe e asina sobre a páxina",
        "ca": "Dibuixa, escriu i signa sobre la pàgina",
        "eu": "Marraztu, idatzi eta sinatu orrian",
    },
    "tour_3_texto": {
        "en": "Draw, highlight, add shapes, text and images, and move, resize or rotate anything you add. The eraser covers with the page colour, and you can crop the page. Sign by hand or with your certificate, from a file or from the one installed on the device.",
        "es": "Dibuja, resalta, añade formas, texto e imágenes, y mueve, escala o gira cualquier cosa que añadas. La goma tapa con el color de la página, y puedes recortarla. Firma a mano o con tu certificado, desde un fichero o desde el que tengas instalado en el dispositivo.",
        "fr": "Dessinez, surlignez, ajoutez des formes, du texte et des images, puis déplacez, redimensionnez ou faites pivoter ce que vous ajoutez. La gomme recouvre avec la couleur de la page, et vous pouvez la rogner. Signez à la main ou avec votre certificat, depuis un fichier ou celui installé sur l’appareil.",
        "de": "Zeichnen, hervorheben, Formen, Text und Bilder hinzufügen und alles verschieben, skalieren oder drehen. Der Radierer überdeckt mit der Seitenfarbe, und Sie können die Seite zuschneiden. Unterschreiben Sie handschriftlich oder mit Ihrem Zertifikat, aus einer Datei oder vom Gerät.",
        "zh": "绘制、标注、添加形状、文字和图片，并可移动、缩放或旋转任何添加的内容。橡皮用页面颜色覆盖，还可以裁剪页面。可手写签名或使用证书签名，来自文件或设备中已安装的证书。",
        "ja": "描く、強調する、図形・文字・画像を追加する。追加したものは移動・拡大縮小・回転できます。消しゴムはページの色で覆い、ページのトリミングも可能。手書きでも証明書でも署名でき、証明書はファイルからでも端末からでも構いません。",
        "ru": "Рисуйте, выделяйте, добавляйте фигуры, текст и изображения, а затем перемещайте, масштабируйте или поворачивайте всё добавленное. Ластик закрывает цветом страницы, страницу можно обрезать. Подписывайте от руки или сертификатом — из файла или установленным на устройстве.",
        "it": "Disegna, evidenzia, aggiungi forme, testo e immagini, e sposta, ridimensiona o ruota tutto ciò che aggiungi. La gomma copre con il colore della pagina, che puoi anche ritagliare. Firma a mano o con il tuo certificato, da file o da quello installato sul dispositivo.",
        "el": "Σχεδιάστε, τονίστε, προσθέστε σχήματα, κείμενο και εικόνες, και μετακινήστε, αλλάξτε μέγεθος ή περιστρέψτε ό,τι προσθέτετε. Η γόμα καλύπτει με το χρώμα της σελίδας, την οποία μπορείτε και να περικόψετε. Υπογράψτε με το χέρι ή με το πιστοποιητικό σας.",
        "ar": "ارسم وظلّل وأضف الأشكال والنصوص والصور، وحرّك أو غيّر حجم أو أدر كل ما تضيفه. الممحاة تغطّي بلون الصفحة، ويمكنك اقتصاصها. وقّع بخط اليد أو بشهادتك، من ملف أو من المثبّتة على الجهاز.",
        "gl": "Debuxa, resalta, engade formas, texto e imaxes, e move, escala ou xira o que engadas. A goma tapa coa cor da páxina, e podes recortala. Asina a man ou co teu certificado, desde un ficheiro ou desde o instalado no dispositivo.",
        "ca": "Dibuixa, ressalta, afegeix formes, text i imatges, i mou, escala o gira tot el que afegeixis. La goma tapa amb el color de la pàgina, que també pots retallar. Signa a mà o amb el teu certificat, des d’un fitxer o des del que tinguis instal·lat.",
        "eu": "Marraztu, nabarmendu, gehitu formak, testua eta irudiak, eta mugitu, eskalatu edo biratu gehitzen duzun guztia. Borragomak orriaren kolorez estaltzen du, eta orria moztu dezakezu. Sinatu eskuz edo zure ziurtagiriarekin, fitxategitik edo gailuan instalatutakotik.",
    },
    "tour_4_titulo": {
        "en": "Your files, your settings",
        "es": "Tus ficheros, a tu manera",
        "fr": "Vos fichiers, à votre façon",
        "de": "Ihre Dateien, Ihre Einstellungen",
        "zh": "你的文件，按你的方式",
        "ja": "ファイルも設定も自分好みに",
        "ru": "Ваши файлы, ваши настройки",
        "it": "I tuoi file, a modo tuo",
        "el": "Τα αρχεία σας, όπως τα θέλετε",
        "ar": "ملفاتك على طريقتك",
        "gl": "Os teus ficheiros, á túa maneira",
        "ca": "Els teus fitxers, a la teva manera",
        "eu": "Zure fitxategiak, zure erara",
    },
    "tour_4_texto": {
        "en": "Results go to the NexaPDF folder in Downloads, or wherever you choose, and the original is never modified. In Settings: twelve themes, thirteen languages, when to save, and a backup of your preferences.",
        "es": "Los resultados van a la carpeta NexaPDF de Descargas, o a la que elijas, y el original no se toca nunca. En Ajustes: doce temas, trece idiomas, cuándo guardar y una copia de seguridad de tus preferencias.",
        "fr": "Les résultats vont dans le dossier NexaPDF des téléchargements, ou celui que vous choisissez, et l’original n’est jamais modifié. Dans les réglages : douze thèmes, treize langues, quand enregistrer et une sauvegarde de vos préférences.",
        "de": "Ergebnisse landen im Ordner NexaPDF unter Downloads oder in Ihrem gewählten Ordner, das Original bleibt unangetastet. In den Einstellungen: zwölf Themen, dreizehn Sprachen, wann gespeichert wird und eine Sicherung Ihrer Einstellungen.",
        "zh": "结果保存在下载中的 NexaPDF 文件夹，或您选择的文件夹，原文件绝不会被修改。设置中有十二种主题、十三种语言、保存时机和偏好备份。",
        "ja": "結果はダウンロード内の NexaPDF フォルダー、または選んだフォルダーに保存され、元のファイルは変更されません。設定にはテーマ 12 種類、言語 13 種類、保存のタイミング、設定のバックアップがあります。",
        "ru": "Результаты сохраняются в папку NexaPDF в «Загрузках» или в выбранную вами, а оригинал не изменяется. В настройках: двенадцать тем, тринадцать языков, когда сохранять и резервная копия предпочтений.",
        "it": "I risultati finiscono nella cartella NexaPDF dei download, o in quella che scegli, e l’originale non viene mai toccato. Nelle impostazioni: dodici temi, tredici lingue, quando salvare e un backup delle preferenze.",
        "el": "Τα αποτελέσματα πηγαίνουν στον φάκελο NexaPDF των λήψεων, ή σε όποιον επιλέξετε, και το πρωτότυπο δεν αλλάζει. Στις ρυθμίσεις: δώδεκα θέματα, δεκατρείς γλώσσες, πότε αποθηκεύεται και αντίγραφο των προτιμήσεων.",
        "ar": "تُحفظ النتائج في مجلد NexaPDF داخل التنزيلات، أو في المجلد الذي تختاره، والملف الأصلي لا يُمسّ. في الإعدادات: اثنا عشر سمة، وثلاث عشرة لغة، ومتى تُحفظ النتائج، ونسخة احتياطية لتفضيلاتك.",
        "gl": "Os resultados van á carpeta NexaPDF de Descargas, ou á que elixas, e o orixinal non se toca nunca. En Axustes: doce temas, trece idiomas, cando gardar e unha copia das túas preferencias.",
        "ca": "Els resultats van a la carpeta NexaPDF de Baixades, o a la que triïs, i l’original no es toca mai. A Configuració: dotze temes, tretze llengües, quan desar i una còpia de les teves preferències.",
        "eu": "Emaitzak Deskargak barruko NexaPDF karpetara doaz, edo aukeratzen duzunera, eta jatorrizkoa ez da inoiz ukitzen. Ezarpenetan: hamabi gai, hamahiru hizkuntza, noiz gorde eta zure hobespenen kopia.",
    },
    # --- Identidad -----------------------------------------------------------
    "app_nombre": dict.fromkeys(IDIOMAS, "NexaPDF"),
    "app_lema": {
        "en": "PDF tools that work offline",
        "es": "Herramientas PDF que funcionan sin conexión",
        "fr": "Des outils PDF qui fonctionnent hors ligne",
        "de": "PDF-Werkzeuge, die offline funktionieren",
        "zh": "离线可用的 PDF 工具",
        "ja": "オフラインで使える PDF ツール",
        "ru": "Инструменты PDF, работающие без интернета",
        "it": "Strumenti PDF che funzionano offline",
        "el": "Εργαλεία PDF που λειτουργούν χωρίς σύνδεση",
        "ar": "أدوات PDF تعمل دون اتصال بالإنترنت",
        "gl": "Ferramentas PDF que funcionan sen conexión",
        "ca": "Eines PDF que funcionen sense connexió",
        "eu": "Konexiorik gabe funtzionatzen duten PDF tresnak",
    },

    # --- Acciones comunes ----------------------------------------------------
    "comun_aceptar": {
        "en": "OK", "es": "Aceptar", "fr": "OK", "de": "OK", "zh": "确定",
        "ja": "OK", "ru": "ОК", "it": "OK", "el": "Εντάξει", "ar": "موافق",
        "gl": "Aceptar", "ca": "D’acord", "eu": "Ados",
    },
    "comun_cancelar": {
        "en": "Cancel", "es": "Cancelar", "fr": "Annuler", "de": "Abbrechen",
        "zh": "取消", "ja": "キャンセル", "ru": "Отмена", "it": "Annulla",
        "el": "Άκυρο", "ar": "إلغاء", "gl": "Cancelar", "ca": "Cancel·la",
        "eu": "Utzi",
    },
    "comun_guardar": {
        "en": "Save", "es": "Guardar", "fr": "Enregistrer", "de": "Speichern",
        "zh": "保存", "ja": "保存", "ru": "Сохранить", "it": "Salva",
        "el": "Αποθήκευση", "ar": "حفظ", "gl": "Gardar", "ca": "Desa",
        "eu": "Gorde",
    },
    "comun_compartir": {
        "en": "Share", "es": "Compartir", "fr": "Partager", "de": "Teilen",
        "zh": "分享", "ja": "共有", "ru": "Поделиться", "it": "Condividi",
        "el": "Κοινοποίηση", "ar": "مشاركة", "gl": "Compartir",
        "ca": "Comparteix", "eu": "Partekatu",
    },
    "comun_eliminar": {
        "en": "Delete", "es": "Eliminar", "fr": "Supprimer", "de": "Löschen",
        "zh": "删除", "ja": "削除", "ru": "Удалить", "it": "Elimina",
        "el": "Διαγραφή", "ar": "حذف", "gl": "Eliminar", "ca": "Elimina",
        "eu": "Ezabatu",
    },
    "comun_deshacer": {
        "en": "Undo", "es": "Deshacer", "fr": "Annuler", "de": "Rückgängig",
        "zh": "撤销", "ja": "元に戻す", "ru": "Отменить", "it": "Annulla",
        "el": "Αναίρεση", "ar": "تراجع", "gl": "Desfacer", "ca": "Desfés",
        "eu": "Desegin",
    },
    "comun_rehacer": {
        "en": "Redo", "es": "Rehacer", "fr": "Rétablir",
        "de": "Wiederholen", "zh": "重做", "ja": "やり直す", "ru": "Вернуть",
        "it": "Ripeti", "el": "Επανάληψη", "ar": "إعادة", "gl": "Refacer",
        "ca": "Refés", "eu": "Berregin",
    },
    "comun_cerrar": {
        "en": "Close", "es": "Cerrar", "fr": "Fermer", "de": "Schließen",
        "zh": "关闭", "ja": "閉じる", "ru": "Закрыть", "it": "Chiudi",
        "el": "Κλείσιμο", "ar": "إغلاق", "gl": "Pechar", "ca": "Tanca",
        "eu": "Itxi",
    },
    "comun_atras": {
        "en": "Back", "es": "Atrás", "fr": "Retour", "de": "Zurück",
        "zh": "返回", "ja": "戻る", "ru": "Назад", "it": "Indietro",
        "el": "Πίσω", "ar": "رجوع", "gl": "Atrás", "ca": "Enrere",
        "eu": "Atzera",
    },
    "comun_hecho": {
        "en": "Done", "es": "Hecho", "fr": "Terminé", "de": "Fertig",
        "zh": "完成", "ja": "完了", "ru": "Готово", "it": "Fatto",
        "el": "Έτοιμο", "ar": "تم", "gl": "Feito", "ca": "Fet", "eu": "Eginda",
    },
    "comun_continuar": {
        "en": "Continue", "es": "Continuar", "fr": "Continuer",
        "de": "Weiter", "zh": "继续", "ja": "続ける", "ru": "Продолжить",
        "it": "Continua", "el": "Συνέχεια", "ar": "متابعة", "gl": "Continuar",
        "ca": "Continua", "eu": "Jarraitu",
    },
    "comun_reintentar": {
        "en": "Retry", "es": "Reintentar", "fr": "Réessayer",
        "de": "Erneut versuchen", "zh": "重试", "ja": "再試行",
        "ru": "Повторить", "it": "Riprova", "el": "Επανάληψη",
        "ar": "إعادة المحاولة", "gl": "Tentar de novo", "ca": "Torna-ho a provar",
        "eu": "Saiatu berriro",
    },
    "comun_seleccionar_todo": {
        "en": "Select all", "es": "Seleccionar todo", "fr": "Tout sélectionner",
        "de": "Alle auswählen", "zh": "全选", "ja": "すべて選択",
        "ru": "Выбрать все", "it": "Seleziona tutto", "el": "Επιλογή όλων",
        "ar": "تحديد الكل", "gl": "Seleccionar todo", "ca": "Selecciona-ho tot",
        "eu": "Hautatu dena",
    },
    "comun_quitar_seleccion": {
        "en": "Clear selection", "es": "Quitar selección",
        "fr": "Effacer la sélection", "de": "Auswahl aufheben", "zh": "取消选择",
        "ja": "選択を解除", "ru": "Снять выделение", "it": "Deseleziona",
        "el": "Καθαρισμός επιλογής", "ar": "إلغاء التحديد",
        "gl": "Quitar selección", "ca": "Treu la selecció",
        "eu": "Kendu hautapena",
    },
    "comun_anadir": {
        "en": "Add", "es": "Añadir", "fr": "Ajouter", "de": "Hinzufügen",
        "zh": "添加", "ja": "追加", "ru": "Добавить", "it": "Aggiungi",
        "el": "Προσθήκη", "ar": "إضافة", "gl": "Engadir", "ca": "Afegeix",
        "eu": "Gehitu",
    },
    "comun_abrir": {
        "en": "Open", "es": "Abrir", "fr": "Ouvrir", "de": "Öffnen",
        "zh": "打开", "ja": "開く", "ru": "Открыть", "it": "Apri",
        "el": "Άνοιγμα", "ar": "فتح", "gl": "Abrir", "ca": "Obre", "eu": "Ireki",
    },
    "comun_procesando": {
        "en": "Working…", "es": "Procesando…", "fr": "Traitement…",
        "de": "Wird verarbeitet…", "zh": "处理中…", "ja": "処理中…",
        "ru": "Обработка…", "it": "Elaborazione…", "el": "Επεξεργασία…",
        "ar": "جارٍ المعالجة…", "gl": "Procesando…", "ca": "S’està processant…",
        "eu": "Prozesatzen…",
    },
    "comun_sin_titulo": {
        "en": "Untitled", "es": "Sin título", "fr": "Sans titre",
        "de": "Ohne Titel", "zh": "无标题", "ja": "無題", "ru": "Без названия",
        "it": "Senza titolo", "el": "Χωρίς τίτλο", "ar": "بدون عنوان",
        "gl": "Sen título", "ca": "Sense títol", "eu": "Izenbururik gabe",
    },

    # --- Pantalla de inicio --------------------------------------------------
    "inicio_herramientas": {
        "en": "Tools", "es": "Herramientas", "fr": "Outils", "de": "Werkzeuge",
        "zh": "工具", "ja": "ツール", "ru": "Инструменты", "it": "Strumenti",
        "el": "Εργαλεία", "ar": "الأدوات", "gl": "Ferramentas", "ca": "Eines",
        "eu": "Tresnak",
    },
    "herr_unir_titulo": {
        "en": "Merge PDFs", "es": "Unir PDF", "fr": "Fusionner des PDF",
        "de": "PDFs zusammenfügen", "zh": "合并 PDF", "ja": "PDF を結合",
        "ru": "Объединить PDF", "it": "Unisci PDF", "el": "Συγχώνευση PDF",
        "ar": "دمج ملفات PDF", "gl": "Unir PDF", "ca": "Uneix PDF",
        "eu": "Batu PDFak",
    },
    "herr_unir_desc": {
        "en": "Join several documents into one",
        "es": "Junta varios documentos en uno",
        "fr": "Réunir plusieurs documents en un seul",
        "de": "Mehrere Dokumente zu einem verbinden",
        "zh": "将多个文档合并为一个",
        "ja": "複数の文書を 1 つにまとめます",
        "ru": "Объедините несколько документов в один",
        "it": "Unisci più documenti in uno solo",
        "el": "Ενώστε πολλά έγγραφα σε ένα",
        "ar": "اجمع عدة مستندات في مستند واحد",
        "gl": "Xunta varios documentos nun só",
        "ca": "Ajunta diversos documents en un de sol",
        "eu": "Elkartu hainbat dokumentu bakarrean",
    },
    "herr_separar_titulo": {
        "en": "Split PDF", "es": "Separar PDF", "fr": "Diviser un PDF",
        "de": "PDF teilen", "zh": "拆分 PDF", "ja": "PDF を分割",
        "ru": "Разделить PDF", "it": "Dividi PDF", "el": "Διαχωρισμός PDF",
        "ar": "تقسيم ملف PDF", "gl": "Separar PDF", "ca": "Divideix PDF",
        "eu": "Zatitu PDFa",
    },
    "herr_separar_desc": {
        "en": "Extract pages or split into files",
        "es": "Extrae páginas o divide en ficheros",
        "fr": "Extraire des pages ou séparer en fichiers",
        "de": "Seiten entnehmen oder in Dateien aufteilen",
        "zh": "提取页面或拆分为多个文件",
        "ja": "ページを取り出す、またはファイルに分割します",
        "ru": "Извлеките страницы или разделите на файлы",
        "it": "Estrai pagine o dividi in file",
        "el": "Εξαγωγή σελίδων ή διαχωρισμός σε αρχεία",
        "ar": "استخرج صفحات أو قسّم إلى ملفات",
        "gl": "Extrae páxinas ou divide en ficheiros",
        "ca": "Extreu pàgines o divideix en fitxers",
        "eu": "Atera orriak edo zatitu fitxategitan",
    },
    "herr_imagen_titulo": {
        "en": "Image to PDF", "es": "Imagen a PDF", "fr": "Image en PDF",
        "de": "Bild zu PDF", "zh": "图片转 PDF", "ja": "画像を PDF に",
        "ru": "Изображение в PDF", "it": "Immagine in PDF",
        "el": "Εικόνα σε PDF", "ar": "صورة إلى PDF", "gl": "Imaxe a PDF",
        "ca": "Imatge a PDF", "eu": "Irudia PDF bihurtu",
    },
    "herr_imagen_desc": {
        "en": "Turn one photo into a document",
        "es": "Convierte una foto en un documento",
        "fr": "Transformer une photo en document",
        "de": "Ein Foto in ein Dokument verwandeln",
        "zh": "把一张照片变成文档",
        "ja": "写真 1 枚を文書にします",
        "ru": "Превратите фото в документ",
        "it": "Trasforma una foto in un documento",
        "el": "Μετατρέψτε μια φωτογραφία σε έγγραφο",
        "ar": "حوّل صورة واحدة إلى مستند",
        "gl": "Converte unha foto nun documento",
        "ca": "Converteix una foto en un document",
        "eu": "Bihurtu argazki bat dokumentu",
    },
    "herr_varias_imagenes_titulo": {
        "en": "Images to PDF", "es": "Imágenes a PDF", "fr": "Images en PDF",
        "de": "Bilder zu PDF", "zh": "多张图片转 PDF",
        "ja": "複数の画像を PDF に", "ru": "Изображения в PDF",
        "it": "Immagini in PDF", "el": "Εικόνες σε PDF",
        "ar": "صور إلى PDF", "gl": "Imaxes a PDF", "ca": "Imatges a PDF",
        "eu": "Irudiak PDF bihurtu",
    },
    "herr_varias_imagenes_desc": {
        "en": "One per page, or several together",
        "es": "Una por página, o varias juntas",
        "fr": "Une par page, ou plusieurs ensemble",
        "de": "Eins pro Seite oder mehrere zusammen",
        "zh": "每页一张，或多张排在一起",
        "ja": "1 ページに 1 枚、または複数まとめて",
        "ru": "По одному на страницу или несколько вместе",
        "it": "Una per pagina, o più insieme",
        "el": "Μία ανά σελίδα ή πολλές μαζί",
        "ar": "واحدة في كل صفحة أو عدة معًا",
        "gl": "Unha por páxina, ou varias xuntas",
        "ca": "Una per pàgina, o diverses juntes",
        "eu": "Bat orriko, edo hainbat elkarrekin",
    },
    "herr_editar_titulo": {
        "en": "Edit PDF", "es": "Editar PDF", "fr": "Modifier un PDF",
        "de": "PDF bearbeiten", "zh": "编辑 PDF", "ja": "PDF を編集",
        "ru": "Редактировать PDF", "it": "Modifica PDF",
        "el": "Επεξεργασία PDF", "ar": "تحرير PDF", "gl": "Editar PDF",
        "ca": "Edita PDF", "eu": "Editatu PDFa",
    },
    "herr_editar_desc": {
        "en": "Draw, add text, shapes and images",
        "es": "Dibuja, añade texto, formas e imágenes",
        "fr": "Dessiner, ajouter du texte, des formes et des images",
        "de": "Zeichnen, Text, Formen und Bilder hinzufügen",
        "zh": "涂画、添加文字、形状和图片",
        "ja": "手書き、文字、図形、画像を追加します",
        "ru": "Рисуйте, добавляйте текст, фигуры и изображения",
        "it": "Disegna, aggiungi testo, forme e immagini",
        "el": "Σχεδιάστε, προσθέστε κείμενο, σχήματα και εικόνες",
        "ar": "ارسم وأضف نصًا وأشكالًا وصورًا",
        "gl": "Debuxa, engade texto, formas e imaxes",
        "ca": "Dibuixa, afegeix text, formes i imatges",
        "eu": "Marraztu, gehitu testua, formak eta irudiak",
    },
    "herr_firmar_titulo": {
        "en": "Sign PDF", "es": "Firmar PDF", "fr": "Signer un PDF",
        "de": "PDF unterschreiben", "zh": "签署 PDF", "ja": "PDF に署名",
        "ru": "Подписать PDF", "it": "Firma PDF", "el": "Υπογραφή PDF",
        "ar": "توقيع PDF", "gl": "Asinar PDF", "ca": "Signa PDF",
        "eu": "Sinatu PDFa",
    },
    "herr_firmar_desc": {
        "en": "By hand or with your certificate",
        "es": "A mano o con tu certificado",
        "fr": "À la main ou avec votre certificat",
        "de": "Handschriftlich oder mit Zertifikat",
        "zh": "手写签名或使用证书",
        "ja": "手書き、または証明書で署名します",
        "ru": "От руки или сертификатом",
        "it": "A mano o con il tuo certificato",
        "el": "Με το χέρι ή με το πιστοποιητικό σας",
        "ar": "بخط اليد أو باستخدام شهادتك",
        "gl": "A man ou co teu certificado",
        "ca": "A mà o amb el teu certificat",
        "eu": "Eskuz edo zure ziurtagiriarekin",
    },
    "inicio_recientes": {
        "en": "Recent files", "es": "Ficheros recientes",
        "fr": "Fichiers récents", "de": "Zuletzt erstellt", "zh": "最近的文件",
        "ja": "最近のファイル", "ru": "Недавние файлы", "it": "File recenti",
        "el": "Πρόσφατα αρχεία", "ar": "الملفات الأخيرة",
        "gl": "Ficheiros recentes", "ca": "Fitxers recents",
        "eu": "Azken fitxategiak",
    },
    "inicio_sin_recientes": {
        "en": "Nothing here yet", "es": "Aún no hay nada aquí",
        "fr": "Rien pour l’instant", "de": "Noch nichts vorhanden",
        "zh": "这里还没有内容", "ja": "まだ何もありません", "ru": "Пока пусто",
        "it": "Ancora niente qui", "el": "Δεν υπάρχει τίποτα ακόμη",
        "ar": "لا يوجد شيء بعد", "gl": "Aínda non hai nada aquí",
        "ca": "Encara no hi ha res", "eu": "Oraindik ez dago ezer",
    },
    "inicio_sin_recientes_ayuda": {
        "en": "The documents you create will show up here.",
        "es": "Los documentos que crees aparecerán aquí.",
        "fr": "Les documents que vous créez apparaîtront ici.",
        "de": "Erstellte Dokumente erscheinen hier.",
        "zh": "你创建的文档会出现在这里。",
        "ja": "作成した文書がここに表示されます。",
        "ru": "Созданные документы появятся здесь.",
        "it": "I documenti che crei compariranno qui.",
        "el": "Τα έγγραφα που δημιουργείτε θα εμφανίζονται εδώ.",
        "ar": "ستظهر هنا المستندات التي تنشئها.",
        "gl": "Os documentos que crees aparecerán aquí.",
        "ca": "Els documents que creïs apareixeran aquí.",
        "eu": "Sortzen dituzun dokumentuak hemen agertuko dira.",
    },
}
