#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Textos del espacio de trabajo: documentos, paginas e imagenes a PDF."""

TEXTOS = {
    "doc_acciones": {
        "en": "Actions",
        "es": "Acciones",
        "fr": "Actions",
        "de": "Aktionen",
        "zh": "操作",
        "ja": "操作",
        "ru": "Действия",
        "it": "Azioni",
        "el": "Ενέργειες",
        "ar": "إجراءات",
        "gl": "Accións",
        "ca": "Accions",
        "eu": "Ekintzak",
    },
    "doc_elegir_accion": {
        "en": "Choose an action",
        "es": "Elegir acción",
        "fr": "Choisir une action",
        "de": "Aktion wählen",
        "zh": "选择操作",
        "ja": "操作を選ぶ",
        "ru": "Выбрать действие",
        "it": "Scegli un'azione",
        "el": "Επιλογή ενέργειας",
        "ar": "اختر إجراءً",
        "gl": "Elixir acción",
        "ca": "Tria una acció",
        "eu": "Aukeratu ekintza",
    },
    # --- Espacio de trabajo --------------------------------------------------
    "doc_titulo_union": {
        "en": "Order and merge", "es": "Ordenar y unir",
        "fr": "Ordonner et fusionner", "de": "Ordnen und zusammenfügen",
        "zh": "排序并合并", "ja": "並べ替えて結合", "ru": "Порядок и объединение",
        "it": "Ordina e unisci", "el": "Ταξινόμηση και συγχώνευση",
        "ar": "الترتيب والدمج", "gl": "Ordenar e unir", "ca": "Ordena i uneix",
        "eu": "Ordenatu eta batu",
    },
    "doc_titulo_paginas": {
        "en": "Pages", "es": "Páginas", "fr": "Pages", "de": "Seiten",
        "zh": "页面", "ja": "ページ", "ru": "Страницы", "it": "Pagine",
        "el": "Σελίδες", "ar": "الصفحات", "gl": "Páxinas", "ca": "Pàgines",
        "eu": "Orriak",
    },
    "doc_paso_documentos": {
        "en": "Step 1 of 2 · Order the documents",
        "es": "Paso 1 de 2 · Ordena los documentos",
        "fr": "Étape 1 sur 2 · Classez les documents",
        "de": "Schritt 1 von 2 · Dokumente ordnen",
        "zh": "第 1 步，共 2 步 · 排列文档顺序",
        "ja": "ステップ 1／2 · 文書の順番",
        "ru": "Шаг 1 из 2 · Порядок документов",
        "it": "Passo 1 di 2 · Ordina i documenti",
        "el": "Βήμα 1 από 2 · Σειρά των εγγράφων",
        "ar": "الخطوة ١ من ٢ · رتّب المستندات",
        "gl": "Paso 1 de 2 · Ordena os documentos",
        "ca": "Pas 1 de 2 · Ordena els documents",
        "eu": "1. urratsa / 2 · Ordenatu dokumentuak",
    },
    "doc_paso_paginas": {
        "en": "Step 2 of 2 · Order the pages",
        "es": "Paso 2 de 2 · Ordena las páginas",
        "fr": "Étape 2 sur 2 · Classez les pages",
        "de": "Schritt 2 von 2 · Seiten ordnen",
        "zh": "第 2 步，共 2 步 · 排列页面顺序",
        "ja": "ステップ 2／2 · ページの順番",
        "ru": "Шаг 2 из 2 · Порядок страниц",
        "it": "Passo 2 di 2 · Ordina le pagine",
        "el": "Βήμα 2 από 2 · Σειρά των σελίδων",
        "ar": "الخطوة ٢ من ٢ · رتّب الصفحات",
        "gl": "Paso 2 de 2 · Ordena as páxinas",
        "ca": "Pas 2 de 2 · Ordena les pàgines",
        "eu": "2. urratsa / 2 · Ordenatu orriak",
    },
    "doc_unir_y_seguir": {
        "en": "Merge and order pages",
        "es": "Unir y ordenar páginas",
        "fr": "Fusionner et classer les pages",
        "de": "Zusammenfügen und Seiten ordnen",
        "zh": "合并并排列页面",
        "ja": "結合してページを並べる",
        "ru": "Объединить и упорядочить страницы",
        "it": "Unisci e ordina le pagine",
        "el": "Ένωση και σειρά σελίδων",
        "ar": "ادمج ورتّب الصفحات",
        "gl": "Unir e ordenar páxinas",
        "ca": "Uneix i ordena les pàgines",
        "eu": "Batu eta ordenatu orriak",
    },
    "doc_unir_vacio": {
        "en": "Add the documents you want to join. You can pick several at once.",
        "es": "Añade los documentos que quieras juntar. Puedes elegir varios a la vez.",
        "fr": "Ajoutez les documents à réunir. Vous pouvez en choisir plusieurs à la fois.",
        "de": "Fügen Sie die Dokumente hinzu, die Sie zusammenlegen möchten. Mehrere auf einmal sind möglich.",
        "zh": "添加要合并的文档，可以一次选择多个。",
        "ja": "まとめたい文書を追加してください。まとめて選べます。",
        "ru": "Добавьте документы, которые нужно объединить. Можно выбрать сразу несколько.",
        "it": "Aggiungi i documenti da unire. Puoi sceglierne più di uno alla volta.",
        "el": "Προσθέστε τα έγγραφα που θέλετε να ενώσετε. Μπορείτε να επιλέξετε πολλά μαζί.",
        "ar": "أضف المستندات التي تريد دمجها. يمكنك اختيار عدة ملفات دفعة واحدة.",
        "gl": "Engade os documentos que queiras xuntar. Podes escoller varios á vez.",
        "ca": "Afegeix els documents que vulguis ajuntar. En pots triar més d’un alhora.",
        "eu": "Gehitu batu nahi dituzun dokumentuak. Hainbat batera aukera ditzakezu.",
    },
    "doc_unir": {
        "en": "Merge", "es": "Unir", "fr": "Fusionner", "de": "Zusammenfügen",
        "zh": "合并", "ja": "結合", "ru": "Объединить", "it": "Unisci",
        "el": "Συγχώνευση", "ar": "دمج", "gl": "Unir", "ca": "Uneix",
        "eu": "Batu",
    },
    "doc_extraer": {
        "en": "Extract", "es": "Extraer", "fr": "Extraire", "de": "Entnehmen",
        "zh": "提取", "ja": "取り出す", "ru": "Извлечь", "it": "Estrai",
        "el": "Εξαγωγή", "ar": "استخراج", "gl": "Extraer", "ca": "Extreu",
        "eu": "Atera",
    },
    "doc_separar_una_por_fichero": {
        "en": "One file per page", "es": "Un fichero por página",
        "fr": "Un fichier par page", "de": "Eine Datei pro Seite",
        "zh": "每页一个文件", "ja": "1 ページごとに 1 ファイル",
        "ru": "Один файл на страницу", "it": "Un file per pagina",
        "el": "Ένα αρχείο ανά σελίδα", "ar": "ملف لكل صفحة",
        "gl": "Un ficheiro por páxina", "ca": "Un fitxer per pàgina",
        "eu": "Fitxategi bat orriko",
    },
    "doc_girar_izquierda": {
        "en": "Rotate left", "es": "Girar a la izquierda",
        "fr": "Pivoter à gauche", "de": "Nach links drehen", "zh": "向左旋转",
        "ja": "左に回転", "ru": "Повернуть влево", "it": "Ruota a sinistra",
        "el": "Περιστροφή αριστερά", "ar": "تدوير لليسار",
        "gl": "Xirar á esquerda", "ca": "Gira a l’esquerra",
        "eu": "Biratu ezkerrera",
    },
    "doc_girar_derecha": {
        "en": "Rotate right", "es": "Girar a la derecha",
        "fr": "Pivoter à droite", "de": "Nach rechts drehen", "zh": "向右旋转",
        "ja": "右に回転", "ru": "Повернуть вправо", "it": "Ruota a destra",
        "el": "Περιστροφή δεξιά", "ar": "تدوير لليمين", "gl": "Xirar á dereita",
        "ca": "Gira a la dreta", "eu": "Biratu eskuinera",
    },
    "doc_eliminar_paginas": {
        "en": "Delete pages", "es": "Eliminar páginas",
        "fr": "Supprimer les pages", "de": "Seiten löschen", "zh": "删除页面",
        "ja": "ページを削除", "ru": "Удалить страницы", "it": "Elimina pagine",
        "el": "Διαγραφή σελίδων", "ar": "حذف الصفحات", "gl": "Eliminar páxinas",
        "ca": "Elimina pàgines", "eu": "Ezabatu orriak",
    },
    "doc_editar_pagina": {
        "en": "Edit page", "es": "Editar página", "fr": "Modifier la page",
        "de": "Seite bearbeiten", "zh": "编辑页面", "ja": "ページを編集",
        "ru": "Редактировать страницу", "it": "Modifica pagina",
        "el": "Επεξεργασία σελίδας", "ar": "تحرير الصفحة",
        "gl": "Editar páxina", "ca": "Edita la pàgina", "eu": "Editatu orria",
    },
    "doc_firmar": {
        "en": "Sign", "es": "Firmar", "fr": "Signer", "de": "Unterschreiben",
        "zh": "签署", "ja": "署名", "ru": "Подписать", "it": "Firma",
        "el": "Υπογραφή", "ar": "توقيع", "gl": "Asinar", "ca": "Signa",
        "eu": "Sinatu",
    },
    "doc_guardar_como": {
        "en": "Save as…", "es": "Guardar como…", "fr": "Enregistrer sous…",
        "de": "Speichern unter…", "zh": "另存为…", "ja": "名前を付けて保存…",
        "ru": "Сохранить как…", "it": "Salva come…",
        "el": "Αποθήκευση ως…", "ar": "حفظ باسم…", "gl": "Gardar como…",
        "ca": "Desa com a…", "eu": "Gorde honela…",
    },
    "doc_anadir_pdf": {
        "en": "Add PDF", "es": "Añadir PDF", "fr": "Ajouter un PDF",
        "de": "PDF hinzufügen", "zh": "添加 PDF", "ja": "PDF を追加",
        "ru": "Добавить PDF", "it": "Aggiungi PDF", "el": "Προσθήκη PDF",
        "ar": "إضافة PDF", "gl": "Engadir PDF", "ca": "Afegeix PDF",
        "eu": "Gehitu PDFa",
    },
    "doc_subir": {
        "en": "Move up", "es": "Subir", "fr": "Monter", "de": "Nach oben",
        "zh": "上移", "ja": "上へ", "ru": "Вверх", "it": "Sposta su",
        "el": "Μετακίνηση πάνω", "ar": "تحريك لأعلى", "gl": "Subir",
        "ca": "Puja", "eu": "Gora",
    },
    "doc_bajar": {
        "en": "Move down", "es": "Bajar", "fr": "Descendre", "de": "Nach unten",
        "zh": "下移", "ja": "下へ", "ru": "Вниз", "it": "Sposta giù",
        "el": "Μετακίνηση κάτω", "ar": "تحريك لأسفل", "gl": "Baixar",
        "ca": "Baixa", "eu": "Behera",
    },
    "doc_quitar": {
        "en": "Remove", "es": "Quitar", "fr": "Retirer", "de": "Entfernen",
        "zh": "移除", "ja": "取り除く", "ru": "Убрать", "it": "Rimuovi",
        "el": "Αφαίρεση", "ar": "إزالة", "gl": "Quitar", "ca": "Treu",
        "eu": "Kendu",
    },
    "doc_confirmar_eliminar_titulo": {
        "en": "Delete these pages?", "es": "¿Eliminar estas páginas?",
        "fr": "Supprimer ces pages ?", "de": "Diese Seiten löschen?",
        "zh": "要删除这些页面吗？", "ja": "これらのページを削除しますか？",
        "ru": "Удалить эти страницы?", "it": "Eliminare queste pagine?",
        "el": "Διαγραφή αυτών των σελίδων;", "ar": "هل تريد حذف هذه الصفحات؟",
        "gl": "Eliminar estas páxinas?", "ca": "Vols eliminar aquestes pàgines?",
        "eu": "Orri hauek ezabatu?",
    },
    "doc_confirmar_eliminar_texto": {
        "en": "They will be removed from the copy you are working on. Your original file is untouched.",
        "es": "Se quitarán de la copia con la que trabajas. Tu fichero original no se toca.",
        "fr": "Elles seront retirées de la copie en cours. Votre fichier d’origine n’est pas modifié.",
        "de": "Sie werden aus der Arbeitskopie entfernt. Ihre Originaldatei bleibt unverändert.",
        "zh": "它们会从你正在编辑的副本中移除。原始文件不会被改动。",
        "ja": "作業中のコピーから削除されます。元のファイルはそのままです。",
        "ru": "Они будут удалены из рабочей копии. Исходный файл не изменится.",
        "it": "Verranno rimosse dalla copia su cui stai lavorando. Il file originale resta intatto.",
        "el": "Θα αφαιρεθούν από το αντίγραφο εργασίας. Το πρωτότυπο αρχείο σας δεν αλλάζει.",
        "ar": "ستُزال من النسخة التي تعمل عليها. ملفك الأصلي لن يتغيّر.",
        "gl": "Quitaranse da copia coa que traballas. O teu ficheiro orixinal non se toca.",
        "ca": "S’eliminaran de la còpia amb què treballes. El fitxer original no es toca.",
        "eu": "Lanean ari zaren kopiatik kenduko dira. Zure jatorrizko fitxategia ez da ukitzen.",
    },
    "doc_aplicar_orden": {
        "en": "Apply new order", "es": "Aplicar el nuevo orden",
        "fr": "Appliquer le nouvel ordre", "de": "Neue Reihenfolge anwenden",
        "zh": "应用新顺序", "ja": "新しい順序を適用",
        "ru": "Применить новый порядок", "it": "Applica il nuovo ordine",
        "el": "Εφαρμογή νέας σειράς", "ar": "تطبيق الترتيب الجديد",
        "gl": "Aplicar a nova orde", "ca": "Aplica el nou ordre",
        "eu": "Aplikatu ordena berria",
    },
    "doc_arrastrar_ayuda": {
        "en": "Drag a page by its handle, or hold it, to change the order.",
        "es": "Arrastra una página por su asa, o mantenla pulsada, para cambiar el orden.",
        "fr": "Faites glisser une page par sa poignée, ou maintenez-la, pour changer l’ordre.",
        "de": "Ziehen Sie eine Seite am Griff oder halten Sie sie gedrückt, um die Reihenfolge zu ändern.",
        "zh": "拖动页面的手柄，或长按页面，即可调整顺序。",
        "ja": "ページのハンドルをドラッグするか長押しすると、順序を変えられます。",
        "ru": "Перетащите страницу за маркер или удерживайте её, чтобы изменить порядок.",
        "it": "Trascina una pagina dalla maniglia, o tienila premuta, per cambiare l’ordine.",
        "el": "Σύρετε μια σελίδα από τη λαβή της, ή κρατήστε την πατημένη, για να αλλάξετε τη σειρά.",
        "ar": "اسحب الصفحة من مقبضها، أو اضغط عليها مطولًا، لتغيير الترتيب.",
        "gl": "Arrastra unha páxina pola súa asa, ou mantena premida, para cambiar a orde.",
        "ca": "Arrossega una pàgina per la seva nansa, o mantén-la premuda, per canviar l’ordre.",
        "eu": "Arrastatu orria bere heldulekutik, edo eutsi sakatuta, ordena aldatzeko.",
    },
    "doc_arrastrar_documentos": {
        "en": "Drag a document by its handle, or hold it, to change the order.",
        "es": "Arrastra un documento por su asa, o mantenlo pulsado, para cambiar el orden.",
        "fr": "Faites glisser un document par sa poignée, ou maintenez-le, pour changer l’ordre.",
        "de": "Ziehen Sie ein Dokument am Griff oder halten Sie es gedrückt, um die Reihenfolge zu ändern.",
        "zh": "拖动文档的手柄，或长按文档，即可调整顺序。",
        "ja": "文書のハンドルをドラッグするか長押しすると、順序を変えられます。",
        "ru": "Перетащите документ за маркер или удерживайте его, чтобы изменить порядок.",
        "it": "Trascina un documento dalla maniglia, o tienilo premuto, per cambiare l’ordine.",
        "el": "Σύρετε ένα έγγραφο από τη λαβή του, ή κρατήστε το πατημένο, για να αλλάξετε τη σειρά.",
        "ar": "اسحب المستند من مقبضه، أو اضغط عليه مطولًا، لتغيير الترتيب.",
        "gl": "Arrastra un documento pola súa asa, ou mantéo premido, para cambiar a orde.",
        "ca": "Arrossega un document per la seva nansa, o mantén-lo premut, per canviar l’ordre.",
        "eu": "Arrastatu dokumentua bere heldulekutik, edo eutsi sakatuta, ordena aldatzeko.",
    },
    "doc_anadir_ficheros": {
        "en": "Add files", "es": "Añadir ficheros", "fr": "Ajouter des fichiers",
        "de": "Dateien hinzufügen", "zh": "添加文件", "ja": "ファイルを追加",
        "ru": "Добавить файлы", "it": "Aggiungi file", "el": "Προσθήκη αρχείων",
        "ar": "إضافة ملفات", "gl": "Engadir ficheiros", "ca": "Afegeix fitxers",
        "eu": "Gehitu fitxategiak",
    },
    "doc_convertir_titulo": {
        "en": "These files will be converted",
        "es": "Estos ficheros se convertirán",
        "fr": "Ces fichiers seront convertis",
        "de": "Diese Dateien werden umgewandelt",
        "zh": "这些文件将被转换",
        "ja": "これらのファイルは変換されます",
        "ru": "Эти файлы будут преобразованы",
        "it": "Questi file verranno convertiti",
        "el": "Αυτά τα αρχεία θα μετατραπούν",
        "ar": "سيتم تحويل هذه الملفات",
        "gl": "Estes ficheiros converteranse",
        "ca": "Aquests fitxers es convertiran",
        "eu": "Fitxategi hauek bihurtuko dira",
    },
    "doc_convertir_texto": {
        "en": "NexaPDF works with PDF, so Word, Excel, PowerPoint and image files are converted to PDF first. Text, tables and images are kept; the exact Office layout is not reproduced. When you are done you can export to any of the four formats.",
        "es": "NexaPDF trabaja con PDF, así que los ficheros de Word, Excel, PowerPoint e imagen se convierten antes a PDF. Se conserva el texto, las tablas y las imágenes; el diseño exacto de Office no se reproduce. Al terminar podrás exportar a cualquiera de los cuatro formatos.",
        "fr": "NexaPDF travaille avec le PDF : les fichiers Word, Excel, PowerPoint et images sont d’abord convertis. Le texte, les tableaux et les images sont conservés ; la mise en page exacte d’Office n’est pas reproduite. À la fin, vous pourrez exporter vers l’un des quatre formats.",
        "de": "NexaPDF arbeitet mit PDF, daher werden Word-, Excel-, PowerPoint- und Bilddateien zuerst umgewandelt. Text, Tabellen und Bilder bleiben erhalten; das exakte Office-Layout wird nicht nachgebildet. Am Ende können Sie in jedes der vier Formate exportieren.",
        "zh": "NexaPDF 以 PDF 为工作格式，因此 Word、Excel、PowerPoint 和图片会先转换为 PDF。文字、表格和图片会保留，但不会完全还原 Office 的排版。完成后可导出为这四种格式中的任意一种。",
        "ja": "NexaPDF は PDF を扱うため、Word・Excel・PowerPoint・画像はまず PDF に変換されます。文字・表・画像は保持されますが、Office のレイアウトそのままにはなりません。作業後は 4 つの形式のいずれかに書き出せます。",
        "ru": "NexaPDF работает с PDF, поэтому файлы Word, Excel, PowerPoint и изображения сначала преобразуются. Текст, таблицы и изображения сохраняются; точная вёрстка Office не воспроизводится. По окончании можно экспортировать в любой из четырёх форматов.",
        "it": "NexaPDF lavora con il PDF, quindi i file Word, Excel, PowerPoint e le immagini vengono prima convertiti. Testo, tabelle e immagini si mantengono; l’impaginazione esatta di Office non viene riprodotta. Alla fine potrai esportare in uno dei quattro formati.",
        "el": "Το NexaPDF δουλεύει με PDF, οπότε τα αρχεία Word, Excel, PowerPoint και οι εικόνες μετατρέπονται πρώτα. Το κείμενο, οι πίνακες και οι εικόνες διατηρούνται· η ακριβής διάταξη του Office δεν αναπαράγεται. Στο τέλος μπορείτε να εξαγάγετε σε οποιαδήποτε από τις τέσσερις μορφές.",
        "ar": "يعمل NexaPDF بصيغة PDF، لذا تُحوَّل ملفات Word وExcel وPowerPoint والصور إلى PDF أولًا. يُحتفظ بالنص والجداول والصور، أما تنسيق أوفيس الدقيق فلا يُعاد إنتاجه. وعند الانتهاء يمكنك التصدير إلى أي من الصيغ الأربع.",
        "gl": "NexaPDF traballa con PDF, así que os ficheiros de Word, Excel, PowerPoint e imaxe convértense antes a PDF. Consérvase o texto, as táboas e as imaxes; o deseño exacto de Office non se reproduce. Ao rematar poderás exportar a calquera dos catro formatos.",
        "ca": "NexaPDF treballa amb PDF, així que els fitxers de Word, Excel, PowerPoint i imatge es converteixen abans a PDF. Es conserva el text, les taules i les imatges; el disseny exacte d’Office no es reprodueix. En acabar podràs exportar a qualsevol dels quatre formats.",
        "eu": "NexaPDFek PDFrekin egiten du lan, beraz Word, Excel, PowerPoint eta irudi fitxategiak PDF bihurtzen dira lehenik. Testua, taulak eta irudiak gordetzen dira; Officeren diseinu zehatza ez da errepikatzen. Amaitzean lau formatuetako edozeinetara esporta dezakezu.",
    },
    "doc_convirtiendo": {
        "en": "Converting…", "es": "Convirtiendo…", "fr": "Conversion…",
        "de": "Wird umgewandelt…", "zh": "正在转换…", "ja": "変換中…",
        "ru": "Преобразование…", "it": "Conversione…", "el": "Μετατροπή…",
        "ar": "جارٍ التحويل…", "gl": "Convertendo…", "ca": "S’està convertint…",
        "eu": "Bihurtzen…",
    },
    "doc_exportar_como": {
        "en": "Export as…", "es": "Exportar como…", "fr": "Exporter sous…",
        "de": "Exportieren als…", "zh": "导出为…", "ja": "形式を選んで書き出す…",
        "ru": "Экспортировать как…", "it": "Esporta come…",
        "el": "Εξαγωγή ως…", "ar": "تصدير باسم…", "gl": "Exportar como…",
        "ca": "Exporta com a…", "eu": "Esportatu honela…",
    },
    "doc_exportar_aviso": {
        "en": "A PDF stores letters placed on a page, not paragraphs or cells: what comes out is the text and the images, laid out again as well as possible.",
        "es": "Un PDF guarda letras colocadas sobre una página, no párrafos ni celdas: lo que sale es el texto y las imágenes, recompuestos lo mejor posible.",
        "fr": "Un PDF stocke des lettres placées sur une page, pas des paragraphes ni des cellules : ce qui en ressort, c’est le texte et les images, remis en forme au mieux.",
        "de": "Ein PDF speichert Buchstaben auf einer Seite, keine Absätze oder Zellen: heraus kommen Text und Bilder, so gut wie möglich neu angeordnet.",
        "zh": "PDF 保存的是页面上的字符位置，而不是段落或单元格：导出的是文字和图片，并尽可能重新排布。",
        "ja": "PDF はページ上に置かれた文字を保存するもので、段落やセルではありません。書き出されるのは文字と画像を可能な範囲で組み直したものです。",
        "ru": "PDF хранит буквы, размещённые на странице, а не абзацы или ячейки: получается текст и изображения, скомпонованные заново по мере возможности.",
        "it": "Un PDF conserva lettere collocate su una pagina, non paragrafi né celle: quello che esce è il testo e le immagini, ricomposti al meglio.",
        "el": "Ένα PDF αποθηκεύει γράμματα τοποθετημένα σε μια σελίδα, όχι παραγράφους ή κελιά: αυτό που βγαίνει είναι το κείμενο και οι εικόνες, αναδιατεταγμένα όσο γίνεται καλύτερα.",
        "ar": "يخزّن ملف PDF حروفًا موضوعة على صفحة، لا فقرات ولا خلايا: ما يخرج هو النص والصور، مُعاد ترتيبها قدر الإمكان.",
        "gl": "Un PDF garda letras colocadas sobre unha páxina, non parágrafos nin celas: o que sae é o texto e as imaxes, recompostos o mellor posible.",
        "ca": "Un PDF desa lletres col·locades sobre una pàgina, no pas paràgrafs ni cel·les: el que en surt és el text i les imatges, recompostos al màxim possible.",
        "eu": "PDF batek orri batean jarritako letrak gordetzen ditu, ez paragrafoak ez gelaxkak: ateratzen dena testua eta irudiak dira, ahalik eta ondoen berrantolatuta.",
    },
    "doc_formato_pdf": dict.fromkeys(
        ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"], "PDF"),
    "doc_formato_docx": dict.fromkeys(
        ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"],
        "Word (.docx)"),
    "doc_formato_xlsx": dict.fromkeys(
        ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"],
        "Excel (.xlsx)"),
    "doc_formato_pptx": dict.fromkeys(
        ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"],
        "PowerPoint (.pptx)"),
    "doc_documento_cifrado": {
        "en": "This document is password protected",
        "es": "Este documento está protegido con contraseña",
        "fr": "Ce document est protégé par un mot de passe",
        "de": "Dieses Dokument ist passwortgeschützt",
        "zh": "该文档有密码保护",
        "ja": "この文書はパスワードで保護されています",
        "ru": "Документ защищён паролем",
        "it": "Questo documento è protetto da password",
        "el": "Αυτό το έγγραφο προστατεύεται με κωδικό",
        "ar": "هذا المستند محمي بكلمة مرور",
        "gl": "Este documento está protexido con contrasinal",
        "ca": "Aquest document està protegit amb contrasenya",
        "eu": "Dokumentu hau pasahitzez babestuta dago",
    },
    "doc_contrasena": {
        "en": "Password", "es": "Contraseña", "fr": "Mot de passe",
        "de": "Passwort", "zh": "密码", "ja": "パスワード", "ru": "Пароль",
        "it": "Password", "el": "Κωδικός", "ar": "كلمة المرور",
        "gl": "Contrasinal", "ca": "Contrasenya", "eu": "Pasahitza",
    },
    "doc_resultado_guardado": {
        "en": "Saved to %1$s", "es": "Guardado en %1$s",
        "fr": "Enregistré dans %1$s", "de": "Gespeichert unter %1$s",
        "zh": "已保存到 %1$s", "ja": "%1$s に保存しました",
        "ru": "Сохранено в %1$s", "it": "Salvato in %1$s",
        "el": "Αποθηκεύτηκε στο %1$s", "ar": "تم الحفظ في %1$s",
        "gl": "Gardado en %1$s", "ca": "Desat a %1$s", "eu": "%1$s-n gordeta",
    },
    "doc_ficheros_creados": {
        "en": "%1$d files created", "es": "%1$d ficheros creados",
        "fr": "%1$d fichiers créés", "de": "%1$d Dateien erstellt",
        "zh": "已创建 %1$d 个文件", "ja": "%1$d 個のファイルを作成しました",
        "ru": "Создано файлов: %1$d", "it": "%1$d file creati",
        "el": "Δημιουργήθηκαν %1$d αρχεία", "ar": "تم إنشاء %1$d ملفات",
        "gl": "%1$d ficheiros creados", "ca": "%1$d fitxers creats",
        "eu": "%1$d fitxategi sortuta",
    },

    # --- Imagenes a PDF ------------------------------------------------------
    "img_titulo": {
        "en": "Images to PDF", "es": "Imágenes a PDF", "fr": "Images en PDF",
        "de": "Bilder zu PDF", "zh": "图片转 PDF", "ja": "画像を PDF に",
        "ru": "Изображения в PDF", "it": "Immagini in PDF",
        "el": "Εικόνες σε PDF", "ar": "صور إلى PDF", "gl": "Imaxes a PDF",
        "ca": "Imatges a PDF", "eu": "Irudiak PDF bihurtu",
    },
    "img_disposicion": {
        "en": "Layout", "es": "Disposición", "fr": "Disposition",
        "de": "Anordnung", "zh": "版式", "ja": "配置", "ru": "Расположение",
        "it": "Disposizione", "el": "Διάταξη", "ar": "التخطيط",
        "gl": "Disposición", "ca": "Disposició", "eu": "Antolamendua",
    },
    "img_una_por_pagina": {
        "en": "1 per page", "es": "1 por página", "fr": "1 par page",
        "de": "1 pro Seite", "zh": "每页 1 张", "ja": "1 ページに 1 枚",
        "ru": "1 на странице", "it": "1 per pagina", "el": "1 ανά σελίδα",
        "ar": "١ في كل صفحة", "gl": "1 por páxina", "ca": "1 per pàgina",
        "eu": "1 orriko",
    },
    "img_dos_por_pagina": {
        "en": "2 per page", "es": "2 por página", "fr": "2 par page",
        "de": "2 pro Seite", "zh": "每页 2 张", "ja": "1 ページに 2 枚",
        "ru": "2 на странице", "it": "2 per pagina", "el": "2 ανά σελίδα",
        "ar": "٢ في كل صفحة", "gl": "2 por páxina", "ca": "2 per pàgina",
        "eu": "2 orriko",
    },
    "img_cuatro_por_pagina": {
        "en": "4 per page", "es": "4 por página", "fr": "4 par page",
        "de": "4 pro Seite", "zh": "每页 4 张", "ja": "1 ページに 4 枚",
        "ru": "4 на странице", "it": "4 per pagina", "el": "4 ανά σελίδα",
        "ar": "٤ في كل صفحة", "gl": "4 por páxina", "ca": "4 per pàgina",
        "eu": "4 orriko",
    },
    "img_seis_por_pagina": {
        "en": "6 per page", "es": "6 por página", "fr": "6 par page",
        "de": "6 pro Seite", "zh": "每页 6 张", "ja": "1 ページに 6 枚",
        "ru": "6 на странице", "it": "6 per pagina", "el": "6 ανά σελίδα",
        "ar": "٦ في كل صفحة", "gl": "6 por páxina", "ca": "6 per pàgina",
        "eu": "6 orriko",
    },
    "img_tamano_pagina": {
        "en": "Page size", "es": "Tamaño de página", "fr": "Format de page",
        "de": "Seitengröße", "zh": "页面尺寸", "ja": "ページサイズ",
        "ru": "Размер страницы", "it": "Formato pagina",
        "el": "Μέγεθος σελίδας", "ar": "حجم الصفحة", "gl": "Tamaño de páxina",
        "ca": "Mida de pàgina", "eu": "Orri-tamaina",
    },
    "img_ajustar_a_imagen": {
        "en": "Fit the image", "es": "Ajustar a la imagen",
        "fr": "Adapter à l’image", "de": "An Bild anpassen", "zh": "适应图片",
        "ja": "画像に合わせる", "ru": "По размеру изображения",
        "it": "Adatta all’immagine", "el": "Προσαρμογή στην εικόνα",
        "ar": "ملاءمة الصورة", "gl": "Axustar á imaxe",
        "ca": "Ajusta a la imatge", "eu": "Doitu irudira",
    },
    "img_orientacion": {
        "en": "Orientation", "es": "Orientación", "fr": "Orientation",
        "de": "Ausrichtung", "zh": "方向", "ja": "向き", "ru": "Ориентация",
        "it": "Orientamento", "el": "Προσανατολισμός", "ar": "الاتجاه",
        "gl": "Orientación", "ca": "Orientació", "eu": "Orientazioa",
    },
    "img_vertical": {
        "en": "Portrait", "es": "Vertical", "fr": "Portrait", "de": "Hochformat",
        "zh": "纵向", "ja": "縦", "ru": "Книжная", "it": "Verticale",
        "el": "Κατακόρυφος", "ar": "عمودي", "gl": "Vertical", "ca": "Vertical",
        "eu": "Bertikala",
    },
    "img_horizontal": {
        "en": "Landscape", "es": "Horizontal", "fr": "Paysage",
        "de": "Querformat", "zh": "横向", "ja": "横", "ru": "Альбомная",
        "it": "Orizzontale", "el": "Οριζόντιος", "ar": "أفقي",
        "gl": "Horizontal", "ca": "Horitzontal", "eu": "Horizontala",
    },
    "img_automatica": {
        "en": "Automatic", "es": "Automática", "fr": "Automatique",
        "de": "Automatisch", "zh": "自动", "ja": "自動",
        "ru": "Автоматически", "it": "Automatica", "el": "Αυτόματος",
        "ar": "تلقائي", "gl": "Automática", "ca": "Automàtica",
        "eu": "Automatikoa",
    },
    "img_margen": {
        "en": "Margin", "es": "Margen", "fr": "Marge", "de": "Rand",
        "zh": "页边距", "ja": "余白", "ru": "Поля", "it": "Margine",
        "el": "Περιθώριο", "ar": "الهامش", "gl": "Marxe", "ca": "Marge",
        "eu": "Marjina",
    },
    "img_espaciado": {
        "en": "Spacing", "es": "Espaciado", "fr": "Espacement",
        "de": "Abstand", "zh": "间距", "ja": "間隔", "ru": "Отступ",
        "it": "Spaziatura", "el": "Απόσταση", "ar": "التباعد",
        "gl": "Espazamento", "ca": "Espaiat", "eu": "Tartea",
    },
    "img_crear": {
        "en": "Create PDF", "es": "Crear PDF", "fr": "Créer le PDF",
        "de": "PDF erstellen", "zh": "创建 PDF", "ja": "PDF を作成",
        "ru": "Создать PDF", "it": "Crea PDF", "el": "Δημιουργία PDF",
        "ar": "إنشاء PDF", "gl": "Crear PDF", "ca": "Crea el PDF",
        "eu": "Sortu PDFa",
    },
    "img_anadir_mas": {
        "en": "Add more images", "es": "Añadir más imágenes",
        "fr": "Ajouter d’autres images", "de": "Weitere Bilder hinzufügen",
        "zh": "添加更多图片", "ja": "画像を追加", "ru": "Добавить изображения",
        "it": "Aggiungi altre immagini", "el": "Προσθήκη κι άλλων εικόνων",
        "ar": "إضافة المزيد من الصور", "gl": "Engadir máis imaxes",
        "ca": "Afegeix més imatges", "eu": "Gehitu irudi gehiago",
    },
    # Los nombres de formato de papel son normalizados y no se traducen, salvo
    # "Carta", que en Europa se conoce por su nombre local.
    "img_tamano_a4": dict.fromkeys(
        ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"], "A4"),
    "img_tamano_a5": dict.fromkeys(
        ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"], "A5"),
    "img_tamano_a3": dict.fromkeys(
        ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"], "A3"),
    "img_tamano_carta": {
        "en": "Letter", "es": "Carta", "fr": "Lettre", "de": "Letter",
        "zh": "Letter", "ja": "レター", "ru": "Letter", "it": "Letter",
        "el": "Letter", "ar": "Letter", "gl": "Carta", "ca": "Carta",
        "eu": "Letter",
    },
    "img_origen_titulo": {
        "en": "Where from?", "es": "¿De dónde?", "fr": "D’où ?",
        "de": "Woher?", "zh": "从哪里获取？", "ja": "どこから？",
        "ru": "Откуда?", "it": "Da dove?", "el": "Από πού;",
        "ar": "من أين؟", "gl": "De onde?", "ca": "D’on?", "eu": "Nondik?",
    },
    "img_desde_galeria": {
        "en": "Choose from gallery", "es": "Elegir de la galería",
        "fr": "Choisir dans la galerie", "de": "Aus der Galerie wählen",
        "zh": "从相册选择", "ja": "ギャラリーから選ぶ",
        "ru": "Выбрать из галереи", "it": "Scegli dalla galleria",
        "el": "Επιλογή από τη συλλογή", "ar": "اختيار من المعرض",
        "gl": "Escoller da galería", "ca": "Tria de la galeria",
        "eu": "Aukeratu galeriatik",
    },
    "img_desde_camara": {
        "en": "Take a photo", "es": "Hacer una foto",
        "fr": "Prendre une photo", "de": "Foto aufnehmen",
        "zh": "拍照", "ja": "写真を撮る", "ru": "Сделать фото",
        "it": "Scatta una foto", "el": "Λήψη φωτογραφίας",
        "ar": "التقاط صورة", "gl": "Facer unha foto",
        "ca": "Fes una foto", "eu": "Atera argazkia",
    },
    "img_sin_camara": {
        "en": "No camera app available on this device",
        "es": "No hay ninguna app de cámara en este dispositivo",
        "fr": "Aucune application d’appareil photo sur cet appareil",
        "de": "Auf diesem Gerät ist keine Kamera-App vorhanden",
        "zh": "此设备上没有可用的相机应用",
        "ja": "この端末で使えるカメラアプリがありません",
        "ru": "На этом устройстве нет приложения камеры",
        "it": "Nessuna app fotocamera disponibile su questo dispositivo",
        "el": "Δεν υπάρχει διαθέσιμη εφαρμογή κάμερας σε αυτή τη συσκευή",
        "ar": "لا يوجد تطبيق كاميرا متاح على هذا الجهاز",
        "gl": "Non hai ningunha app de cámara neste dispositivo",
        "ca": "No hi ha cap aplicació de càmera en aquest dispositiu",
        "eu": "Ez dago kamera-aplikaziorik gailu honetan",
    },
    "img_sin_imagenes": {
        "en": "No images selected", "es": "No hay imágenes seleccionadas",
        "fr": "Aucune image sélectionnée", "de": "Keine Bilder ausgewählt",
        "zh": "未选择图片", "ja": "画像が選択されていません",
        "ru": "Изображения не выбраны", "it": "Nessuna immagine selezionata",
        "el": "Δεν επιλέχθηκαν εικόνες", "ar": "لم يتم اختيار أي صور",
        "gl": "Non hai imaxes seleccionadas", "ca": "No hi ha imatges seleccionades",
        "eu": "Ez dago irudirik hautatuta",
    },
}
