#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Textos del editor de paginas y de la firma."""

TEXTOS = {
    # --- Herramientas del editor ---------------------------------------------
    "ed_mover": {
        "en": "Pan", "es": "Mover", "fr": "Déplacer", "de": "Verschieben",
        "zh": "移动", "ja": "移動", "ru": "Перемещение", "it": "Sposta",
        "el": "Μετακίνηση", "ar": "تحريك", "gl": "Mover", "ca": "Mou",
        "eu": "Mugitu",
    },
    "ed_dibujar": {
        "en": "Draw", "es": "Dibujar", "fr": "Dessiner", "de": "Zeichnen",
        "zh": "画笔", "ja": "手書き", "ru": "Рисовать", "it": "Disegna",
        "el": "Σχεδίαση", "ar": "رسم", "gl": "Debuxar", "ca": "Dibuixa",
        "eu": "Marraztu",
    },
    "ed_resaltar": {
        "en": "Highlight", "es": "Resaltar", "fr": "Surligner",
        "de": "Markieren", "zh": "高亮", "ja": "マーカー", "ru": "Выделить",
        "it": "Evidenzia", "el": "Επισήμανση", "ar": "تظليل", "gl": "Resaltar",
        "ca": "Ressalta", "eu": "Nabarmendu",
    },
    "ed_borrar": {
        "en": "Erase", "es": "Borrar", "fr": "Effacer", "de": "Radieren",
        "zh": "擦除", "ja": "消しゴム", "ru": "Стереть", "it": "Cancella",
        "el": "Σβήσιμο", "ar": "مسح", "gl": "Borrar", "ca": "Esborra",
        "eu": "Ezabatu",
    },
    "ed_figuras": {
        "en": "Shapes", "es": "Formas", "fr": "Formes", "de": "Formen",
        "zh": "形状", "ja": "図形", "ru": "Фигуры", "it": "Forme",
        "el": "Σχήματα", "ar": "أشكال", "gl": "Formas", "ca": "Formes",
        "eu": "Formak",
    },
    "ed_texto": {
        "en": "Text", "es": "Texto", "fr": "Texte", "de": "Text",
        "zh": "文字", "ja": "テキスト", "ru": "Текст", "it": "Testo",
        "el": "Κείμενο", "ar": "نص", "gl": "Texto", "ca": "Text",
        "eu": "Testua",
    },
    "ed_imagen": {
        "en": "Image", "es": "Imagen", "fr": "Image", "de": "Bild",
        "zh": "图片", "ja": "画像", "ru": "Изображение", "it": "Immagine",
        "el": "Εικόνα", "ar": "صورة", "gl": "Imaxe", "ca": "Imatge",
        "eu": "Irudia",
    },
    "ed_firma": {
        "en": "Signature", "es": "Firma", "fr": "Signature",
        "de": "Unterschrift", "zh": "签名", "ja": "署名", "ru": "Подпись",
        "it": "Firma", "el": "Υπογραφή", "ar": "توقيع", "gl": "Sinatura",
        "ca": "Signatura", "eu": "Sinadura",
    },
    "ed_filtro": {
        "en": "Filter", "es": "Filtro", "fr": "Filtre", "de": "Filter",
        "zh": "滤镜", "ja": "フィルター", "ru": "Фильтр", "it": "Filtro",
        "el": "Φίλτρο", "ar": "مرشّح", "gl": "Filtro", "ca": "Filtre",
        "eu": "Iragazkia",
    },
    "ed_color": {
        "en": "Colour", "es": "Color", "fr": "Couleur", "de": "Farbe",
        "zh": "颜色", "ja": "色", "ru": "Цвет", "it": "Colore",
        "el": "Χρώμα", "ar": "اللون", "gl": "Cor", "ca": "Color",
        "eu": "Kolorea",
    },
    "ed_grosor": {
        "en": "Thickness", "es": "Grosor", "fr": "Épaisseur", "de": "Stärke",
        "zh": "粗细", "ja": "太さ", "ru": "Толщина", "it": "Spessore",
        "el": "Πάχος", "ar": "السُمك", "gl": "Grosor", "ca": "Gruix",
        "eu": "Lodiera",
    },
    "ed_opacidad": {
        "en": "Opacity", "es": "Opacidad", "fr": "Opacité", "de": "Deckkraft",
        "zh": "不透明度", "ja": "不透明度", "ru": "Непрозрачность",
        "it": "Opacità", "el": "Αδιαφάνεια", "ar": "العتامة",
        "gl": "Opacidade", "ca": "Opacitat", "eu": "Opakutasuna",
    },
    "ed_rectangulo": {
        "en": "Rectangle", "es": "Rectángulo", "fr": "Rectangle",
        "de": "Rechteck", "zh": "矩形", "ja": "四角形",
        "ru": "Прямоугольник", "it": "Rettangolo", "el": "Ορθογώνιο",
        "ar": "مستطيل", "gl": "Rectángulo", "ca": "Rectangle",
        "eu": "Laukizuzena",
    },
    "ed_elipse": {
        "en": "Ellipse", "es": "Elipse", "fr": "Ellipse", "de": "Ellipse",
        "zh": "椭圆", "ja": "楕円", "ru": "Эллипс", "it": "Ellisse",
        "el": "Έλλειψη", "ar": "بيضاوي", "gl": "Elipse", "ca": "El·lipse",
        "eu": "Elipsea",
    },
    "ed_linea": {
        "en": "Line", "es": "Línea", "fr": "Ligne", "de": "Linie",
        "zh": "直线", "ja": "直線", "ru": "Линия", "it": "Linea",
        "el": "Γραμμή", "ar": "خط", "gl": "Liña", "ca": "Línia",
        "eu": "Lerroa",
    },
    "ed_flecha": {
        "en": "Arrow", "es": "Flecha", "fr": "Flèche", "de": "Pfeil",
        "zh": "箭头", "ja": "矢印", "ru": "Стрелка", "it": "Freccia",
        "el": "Βέλος", "ar": "سهم", "gl": "Frecha", "ca": "Fletxa",
        "eu": "Gezia",
    },
    "ed_relleno": {
        "en": "Fill", "es": "Relleno", "fr": "Remplissage", "de": "Füllung",
        "zh": "填充", "ja": "塗りつぶし", "ru": "Заливка", "it": "Riempimento",
        "el": "Γέμισμα", "ar": "تعبئة", "gl": "Recheo", "ca": "Emplenat",
        "eu": "Betegarria",
    },
    "ed_anadir_texto": {
        "en": "Add text", "es": "Añadir texto", "fr": "Ajouter du texte",
        "de": "Text hinzufügen", "zh": "添加文字", "ja": "文字を追加",
        "ru": "Добавить текст", "it": "Aggiungi testo",
        "el": "Προσθήκη κειμένου", "ar": "إضافة نص", "gl": "Engadir texto",
        "ca": "Afegeix text", "eu": "Gehitu testua",
    },
    "ed_editar_texto": {
        "en": "Edit text", "es": "Editar texto", "fr": "Modifier le texte",
        "de": "Text bearbeiten", "zh": "编辑文字", "ja": "文字を編集",
        "ru": "Изменить текст", "it": "Modifica testo",
        "el": "Επεξεργασία κειμένου", "ar": "تحرير النص",
        "gl": "Editar texto", "ca": "Edita el text", "eu": "Editatu testua",
    },
    "ed_negrita": {
        "en": "Bold", "es": "Negrita", "fr": "Gras", "de": "Fett",
        "zh": "加粗", "ja": "太字", "ru": "Полужирный", "it": "Grassetto",
        "el": "Έντονα", "ar": "عريض", "gl": "Grosa", "ca": "Negreta",
        "eu": "Lodia",
    },
    "ed_cursiva": {
        "en": "Italic", "es": "Cursiva", "fr": "Italique", "de": "Kursiv",
        "zh": "斜体", "ja": "斜体", "ru": "Курсив", "it": "Corsivo",
        "el": "Πλάγια", "ar": "مائل", "gl": "Cursiva", "ca": "Cursiva",
        "eu": "Etzana",
    },
    "ed_tamano_texto": {
        "en": "Text size", "es": "Tamaño del texto", "fr": "Taille du texte",
        "de": "Textgröße", "zh": "文字大小", "ja": "文字サイズ",
        "ru": "Размер текста", "it": "Dimensione testo",
        "el": "Μέγεθος κειμένου", "ar": "حجم النص", "gl": "Tamaño do texto",
        "ca": "Mida del text", "eu": "Testu-tamaina",
    },
    "ed_alineacion": {
        "en": "Alignment", "es": "Alineación", "fr": "Alignement",
        "de": "Ausrichtung", "zh": "对齐", "ja": "配置", "ru": "Выравнивание",
        "it": "Allineamento", "el": "Στοίχιση", "ar": "المحاذاة",
        "gl": "Aliñamento", "ca": "Alineació", "eu": "Lerrokatzea",
    },
    "ed_mover_ayuda": {
        "en": "Tap something you added to select it.",
        "es": "Toca algo que hayas añadido para seleccionarlo.",
        "fr": "Touchez un élément que vous avez ajouté pour le sélectionner.",
        "de": "Tippen Sie etwas Hinzugefügtes an, um es auszuwählen.",
        "zh": "点按您添加的内容即可选中。",
        "ja": "追加したものをタップすると選択できます。",
        "ru": "Коснитесь добавленного элемента, чтобы выбрать его.",
        "it": "Tocca un elemento che hai aggiunto per selezionarlo.",
        "el": "Πατήστε κάτι που προσθέσατε για να το επιλέξετε.",
        "ar": "المس عنصرًا أضفته لتحديده.",
        "gl": "Toca algo que engadiras para seleccionalo.",
        "ca": "Toca alguna cosa que hagis afegit per seleccionar-la.",
        "eu": "Ukitu gehitu duzun zerbait hautatzeko.",
    },
    "ed_mover_asas": {
        "en": "Drag to move. Bottom-right handle resizes, top-right one rotates.",
        "es": "Arrastra para moverlo. El asa de abajo escala y la de arriba gira.",
        "fr": "Faites glisser pour déplacer. La poignée du bas redimensionne, celle du haut fait pivoter.",
        "de": "Zum Verschieben ziehen. Der untere Griff skaliert, der obere dreht.",
        "zh": "拖动可移动。右下角手柄缩放，右上角手柄旋转。",
        "ja": "ドラッグで移動。右下のハンドルで拡大縮小、右上で回転します。",
        "ru": "Перетащите, чтобы переместить. Нижний маркер масштабирует, верхний поворачивает.",
        "it": "Trascina per spostare. La maniglia in basso ridimensiona, quella in alto ruota.",
        "el": "Σύρετε για μετακίνηση. Η κάτω λαβή αλλάζει μέγεθος, η πάνω περιστρέφει.",
        "ar": "اسحب للتحريك. المقبض السفلي يغيّر الحجم والعلوي يدوّر.",
        "gl": "Arrastra para movelo. A asa de abaixo escala e a de arriba xira.",
        "ca": "Arrossega per moure’l. La nansa de baix escala i la de dalt gira.",
        "eu": "Arrastatu mugitzeko. Beheko heldulekuak eskalatzen du eta goikoak biratzen.",
    },
    "ed_texto_fondo": {
        "en": "Background",
        "es": "Fondo",
        "fr": "Arrière-plan",
        "de": "Hintergrund",
        "zh": "背景",
        "ja": "背景",
        "ru": "Фон",
        "it": "Sfondo",
        "el": "Φόντο",
        "ar": "الخلفية",
        "gl": "Fondo",
        "ca": "Fons",
        "eu": "Atzeko planoa",
    },
    "ed_tocar_para_sustituir": {
        "en": "Tap a line of text to replace it",
        "es": "Toca una línea de texto para sustituirla",
        "fr": "Touchez une ligne de texte pour la remplacer",
        "de": "Tippen Sie auf eine Textzeile, um sie zu ersetzen",
        "zh": "点按一行文字即可替换",
        "ja": "文字の行をタップすると置き換えられます",
        "ru": "Коснитесь строки текста, чтобы заменить её",
        "it": "Tocca una riga di testo per sostituirla",
        "el": "Πατήστε μια γραμμή κειμένου για να την αντικαταστήσετε",
        "ar": "المس سطرًا من النص لاستبداله",
        "gl": "Toca unha liña de texto para substituíla",
        "ca": "Toca una línia de text per substituir-la",
        "eu": "Ukitu testu-lerro bat ordezteko",
    },
    "ed_sustituir_texto": {
        "en": "Replace text", "es": "Sustituir texto",
        "fr": "Remplacer le texte", "de": "Text ersetzen", "zh": "替换文字",
        "ja": "文字を置き換える", "ru": "Заменить текст",
        "it": "Sostituisci testo", "el": "Αντικατάσταση κειμένου",
        "ar": "استبدال النص", "gl": "Substituír texto",
        "ca": "Substitueix el text", "eu": "Ordeztu testua",
    },
    "ed_sustituir_aviso": {
        "en": "The original line is covered and the new text is written on top. The rest of the page is untouched.",
        "es": "La línea original se tapa y encima se escribe el texto nuevo. El resto de la página no cambia.",
        "fr": "La ligne d’origine est masquée et le nouveau texte est écrit par-dessus. Le reste de la page ne change pas.",
        "de": "Die ursprüngliche Zeile wird überdeckt und der neue Text darübergeschrieben. Der Rest der Seite bleibt unverändert.",
        "zh": "原来的一行会被遮住，新文字写在上面。页面其余部分不变。",
        "ja": "元の行を覆い、その上に新しい文字を書きます。ページの他の部分は変わりません。",
        "ru": "Исходная строка закрывается, а новый текст пишется поверх. Остальная часть страницы не меняется.",
        "it": "La riga originale viene coperta e il nuovo testo scritto sopra. Il resto della pagina non cambia.",
        "el": "Η αρχική γραμμή καλύπτεται και το νέο κείμενο γράφεται από πάνω. Η υπόλοιπη σελίδα δεν αλλάζει.",
        "ar": "يُغطّى السطر الأصلي ويُكتب النص الجديد فوقه. باقي الصفحة لا يتغيّر.",
        "gl": "A liña orixinal tápase e enriba escríbese o texto novo. O resto da páxina non cambia.",
        "ca": "La línia original es tapa i a sobre s’escriu el text nou. La resta de la pàgina no canvia.",
        "eu": "Jatorrizko lerroa estali eta gainean testu berria idazten da. Orriaren gainerakoa ez da aldatzen.",
    },
    "ed_filtro_ninguno": {
        "en": "None", "es": "Ninguno", "fr": "Aucun", "de": "Keiner",
        "zh": "无", "ja": "なし", "ru": "Нет", "it": "Nessuno",
        "el": "Κανένα", "ar": "بدون", "gl": "Ningún", "ca": "Cap",
        "eu": "Bat ere ez",
    },
    "ed_filtro_grises": {
        "en": "Greyscale", "es": "Escala de grises", "fr": "Niveaux de gris",
        "de": "Graustufen", "zh": "灰度", "ja": "グレースケール",
        "ru": "Оттенки серого", "it": "Scala di grigi",
        "el": "Κλίμακα του γκρι", "ar": "تدرّج رمادي",
        "gl": "Escala de grises", "ca": "Escala de grisos",
        "eu": "Gris-eskala",
    },
    "ed_filtro_bn": {
        "en": "Black and white", "es": "Blanco y negro",
        "fr": "Noir et blanc", "de": "Schwarzweiß", "zh": "黑白",
        "ja": "白黒", "ru": "Чёрно-белый", "it": "Bianco e nero",
        "el": "Ασπρόμαυρο", "ar": "أبيض وأسود", "gl": "Branco e negro",
        "ca": "Blanc i negre", "eu": "Zuri-beltza",
    },
    "ed_filtro_documento": {
        "en": "Clean scan", "es": "Documento nítido",
        "fr": "Document net", "de": "Klares Dokument", "zh": "文档增强",
        "ja": "くっきり書類", "ru": "Чёткий документ",
        "it": "Documento nitido", "el": "Καθαρό έγγραφο",
        "ar": "مستند واضح", "gl": "Documento nítido",
        "ca": "Document nítid", "eu": "Dokumentu garbia",
    },
    "ed_filtro_contraste": {
        "en": "High contrast", "es": "Alto contraste",
        "fr": "Contraste élevé", "de": "Hoher Kontrast", "zh": "高对比度",
        "ja": "ハイコントラスト", "ru": "Высокий контраст",
        "it": "Alto contrasto", "el": "Υψηλή αντίθεση", "ar": "تباين عالٍ",
        "gl": "Alto contraste", "ca": "Contrast alt", "eu": "Kontraste handia",
    },
    "ed_filtro_aclarar": {
        "en": "Brighten", "es": "Aclarar", "fr": "Éclaircir",
        "de": "Aufhellen", "zh": "提亮", "ja": "明るく", "ru": "Осветлить",
        "it": "Schiarisci", "el": "Φωτεινότερο", "ar": "تفتيح",
        "gl": "Aclarar", "ca": "Aclareix", "eu": "Argitu",
    },
    "ed_filtro_invertir": {
        "en": "Invert", "es": "Invertir", "fr": "Inverser",
        "de": "Umkehren", "zh": "反色", "ja": "反転", "ru": "Инвертировать",
        "it": "Inverti", "el": "Αντιστροφή", "ar": "عكس", "gl": "Inverter",
        "ca": "Inverteix", "eu": "Alderantzikatu",
    },
    "ed_intensidad": {
        "en": "Strength", "es": "Intensidad", "fr": "Intensité",
        "de": "Stärke", "zh": "强度", "ja": "強さ", "ru": "Сила",
        "it": "Intensità", "el": "Ένταση", "ar": "الشدة",
        "gl": "Intensidade", "ca": "Intensitat", "eu": "Intentsitatea",
    },
    "ed_filtro_aviso": {
        "en": "A filter turns the page into an image, so its text stops being selectable.",
        "es": "Un filtro convierte la página en una imagen, así que su texto deja de poder seleccionarse.",
        "fr": "Un filtre transforme la page en image : son texte n’est alors plus sélectionnable.",
        "de": "Ein Filter wandelt die Seite in ein Bild um, ihr Text lässt sich danach nicht mehr markieren.",
        "zh": "滤镜会把该页变成图片，页面上的文字将无法再选取。",
        "ja": "フィルターを使うとページが画像になり、文字を選択できなくなります。",
        "ru": "Фильтр превращает страницу в изображение, и её текст перестаёт выделяться.",
        "it": "Un filtro trasforma la pagina in un’immagine, quindi il testo non sarà più selezionabile.",
        "el": "Ένα φίλτρο μετατρέπει τη σελίδα σε εικόνα, οπότε το κείμενό της παύει να επιλέγεται.",
        "ar": "يحوّل المرشّح الصفحة إلى صورة، فلا يعود نصها قابلًا للتحديد.",
        "gl": "Un filtro converte a páxina nunha imaxe, así que o seu texto deixa de poder seleccionarse.",
        "ca": "Un filtre converteix la pàgina en una imatge, de manera que el text ja no es podrà seleccionar.",
        "eu": "Iragazki batek orria irudi bihurtzen du, beraz haren testua ezin izango da hautatu.",
    },
    "ed_guardar_cambios": {
        "en": "Save changes", "es": "Guardar cambios",
        "fr": "Enregistrer les modifications", "de": "Änderungen speichern",
        "zh": "保存更改", "ja": "変更を保存", "ru": "Сохранить изменения",
        "it": "Salva modifiche", "el": "Αποθήκευση αλλαγών",
        "ar": "حفظ التغييرات", "gl": "Gardar cambios", "ca": "Desa els canvis",
        "eu": "Gorde aldaketak",
    },
    "ed_descartar_titulo": {
        "en": "Discard changes?", "es": "¿Descartar los cambios?",
        "fr": "Abandonner les modifications ?", "de": "Änderungen verwerfen?",
        "zh": "要放弃更改吗？", "ja": "変更を破棄しますか？",
        "ru": "Отменить изменения?", "it": "Vuoi scartare le modifiche?",
        "el": "Απόρριψη αλλαγών;", "ar": "هل تريد تجاهل التغييرات؟",
        "gl": "Descartar os cambios?", "ca": "Vols descartar els canvis?",
        "eu": "Aldaketak baztertu?",
    },
    "ed_descartar_texto": {
        "en": "What you have drawn on this page will be lost.",
        "es": "Lo que has dibujado en esta página se perderá.",
        "fr": "Ce que vous avez dessiné sur cette page sera perdu.",
        "de": "Was Sie auf dieser Seite gezeichnet haben, geht verloren.",
        "zh": "你在这一页上画的内容会丢失。",
        "ja": "このページに描いた内容は失われます。",
        "ru": "Всё, что вы нарисовали на этой странице, будет потеряно.",
        "it": "Quello che hai disegnato su questa pagina andrà perso.",
        "el": "Ό,τι σχεδιάσατε σε αυτή τη σελίδα θα χαθεί.",
        "ar": "سيُفقد ما رسمته في هذه الصفحة.",
        "gl": "O que debuxaches nesta páxina perderase.",
        "ca": "El que has dibuixat en aquesta pàgina es perdrà.",
        "eu": "Orri honetan marraztu duzuna galduko da.",
    },
    "ed_sin_cambios": {
        "en": "Nothing to save yet", "es": "Todavía no hay nada que guardar",
        "fr": "Rien à enregistrer pour l’instant",
        "de": "Noch nichts zu speichern", "zh": "还没有需要保存的内容",
        "ja": "まだ保存するものがありません", "ru": "Пока нечего сохранять",
        "it": "Non c’è ancora nulla da salvare",
        "el": "Δεν υπάρχει τίποτα προς αποθήκευση ακόμη",
        "ar": "لا يوجد شيء لحفظه بعد", "gl": "Aínda non hai nada que gardar",
        "ca": "Encara no hi ha res per desar", "eu": "Oraindik ez dago zer gorde",
    },
    "ed_pagina_anterior": {
        "en": "Previous page",
        "es": "Página anterior",
        "fr": "Page précédente",
        "de": "Vorherige Seite",
        "zh": "上一页",
        "ja": "前のページ",
        "ru": "Предыдущая страница",
        "it": "Pagina precedente",
        "el": "Προηγούμενη σελίδα",
        "ar": "الصفحة السابقة",
        "gl": "Páxina anterior",
        "ca": "Pàgina anterior",
        "eu": "Aurreko orria",
    },
    "ed_pagina_siguiente": {
        "en": "Next page",
        "es": "Página siguiente",
        "fr": "Page suivante",
        "de": "Nächste Seite",
        "zh": "下一页",
        "ja": "次のページ",
        "ru": "Следующая страница",
        "it": "Pagina successiva",
        "el": "Επόμενη σελίδα",
        "ar": "الصفحة التالية",
        "gl": "Páxina seguinte",
        "ca": "Pàgina següent",
        "eu": "Hurrengo orria",
    },
    "ed_coloca_la_firma": {
        "en": "Draw a box where the signature should go.",
        "es": "Marca con el dedo el recuadro donde va la firma.",
        "fr": "Tracez le cadre où placer la signature.",
        "de": "Ziehen Sie den Rahmen, in den die Unterschrift soll.",
        "zh": "拖出一个方框，确定签名的位置。",
        "ja": "署名を置く枠を指でなぞってください。",
        "ru": "Обведите рамку, где будет подпись.",
        "it": "Traccia il riquadro dove va la firma.",
        "el": "Σχεδιάστε το πλαίσιο όπου θα μπει η υπογραφή.",
        "ar": "ارسم المربع الذي ستوضع فيه الشهادة.",
        "gl": "Marca co dedo o recadro onde vai a sinatura.",
        "ca": "Marca amb el dit el requadre on va la signatura.",
        "eu": "Marraztu sinadura joango den laukia.",
    },
    "ed_pagina_de": {
        "en": "%1$d of %2$d", "es": "%1$d de %2$d", "fr": "%1$d sur %2$d",
        "de": "%1$d von %2$d", "zh": "第 %1$d 页，共 %2$d 页",
        "ja": "%2$d ページ中 %1$d ページ", "ru": "%1$d из %2$d",
        "it": "%1$d di %2$d", "el": "%1$d από %2$d", "ar": "%1$d من %2$d",
        "gl": "%1$d de %2$d", "ca": "%1$d de %2$d", "eu": "%1$d / %2$d",
    },

    # --- Firma ---------------------------------------------------------------
    "firma_titulo": {
        "en": "Sign document", "es": "Firmar documento",
        "fr": "Signer le document", "de": "Dokument unterschreiben",
        "zh": "签署文档", "ja": "文書に署名", "ru": "Подписать документ",
        "it": "Firma il documento", "el": "Υπογραφή εγγράφου",
        "ar": "توقيع المستند", "gl": "Asinar documento",
        "ca": "Signa el document", "eu": "Sinatu dokumentua",
    },
    "firma_manuscrita": {
        "en": "Handwritten signature", "es": "Firma manuscrita",
        "fr": "Signature manuscrite", "de": "Handschriftliche Unterschrift",
        "zh": "手写签名", "ja": "手書き署名", "ru": "Рукописная подпись",
        "it": "Firma autografa", "el": "Χειρόγραφη υπογραφή",
        "ar": "توقيع بخط اليد", "gl": "Sinatura manuscrita",
        "ca": "Signatura manuscrita", "eu": "Eskuz idatzitako sinadura",
    },
    "firma_manuscrita_desc": {
        "en": "Draw it and place it on the page. It is a visible mark, not a certified signature.",
        "es": "Dibújala y colócala en la página. Es una marca visible, no una firma certificada.",
        "fr": "Dessinez-la et placez-la sur la page. C’est une marque visible, pas une signature certifiée.",
        "de": "Zeichnen und auf der Seite platzieren. Es ist eine sichtbare Markierung, keine zertifizierte Signatur.",
        "zh": "画好后放到页面上。这是可见的标记，不是经过认证的签名。",
        "ja": "書いてページに配置します。見た目の印であり、証明付きの署名ではありません。",
        "ru": "Нарисуйте и разместите на странице. Это видимая отметка, а не заверенная подпись.",
        "it": "Disegnala e posizionala sulla pagina. È un segno visibile, non una firma certificata.",
        "el": "Σχεδιάστε την και τοποθετήστε την στη σελίδα. Είναι ορατό σημάδι, όχι πιστοποιημένη υπογραφή.",
        "ar": "ارسمه وضعه في الصفحة. إنه علامة مرئية وليس توقيعًا مُعتمدًا.",
        "gl": "Debúxaa e colócaa na páxina. É unha marca visible, non unha sinatura certificada.",
        "ca": "Dibuixa-la i col·loca-la a la pàgina. És una marca visible, no una signatura certificada.",
        "eu": "Marraztu eta jarri orrian. Marka ikusgai bat da, ez ziurtagiridun sinadura.",
    },
    "firma_dibuja_aqui": {
        "en": "Draw your signature here", "es": "Dibuja aquí tu firma",
        "fr": "Dessinez votre signature ici",
        "de": "Zeichnen Sie hier Ihre Unterschrift", "zh": "在此处签名",
        "ja": "ここに署名してください", "ru": "Нарисуйте здесь свою подпись",
        "it": "Disegna qui la tua firma", "el": "Σχεδιάστε εδώ την υπογραφή σας",
        "ar": "ارسم توقيعك هنا", "gl": "Debuxa aquí a túa sinatura",
        "ca": "Dibuixa aquí la teva signatura", "eu": "Marraztu hemen zure sinadura",
    },
    "firma_colocar": {
        "en": "Place on the page", "es": "Colocar en la página",
        "fr": "Placer sur la page", "de": "Auf der Seite platzieren",
        "zh": "放到页面上", "ja": "ページに配置", "ru": "Разместить на странице",
        "it": "Posiziona sulla pagina", "el": "Τοποθέτηση στη σελίδα",
        "ar": "ضعه في الصفحة", "gl": "Colocar na páxina",
        "ca": "Col·loca a la pàgina", "eu": "Jarri orrian",
    },
    "firma_limpiar": {
        "en": "Clear", "es": "Limpiar", "fr": "Effacer", "de": "Löschen",
        "zh": "清除", "ja": "消す", "ru": "Очистить", "it": "Pulisci",
        "el": "Καθαρισμός", "ar": "مسح", "gl": "Limpar", "ca": "Neteja",
        "eu": "Garbitu",
    },
    "firma_guardar_firma": {
        "en": "Save this signature", "es": "Guardar esta firma",
        "fr": "Enregistrer cette signature",
        "de": "Diese Unterschrift speichern", "zh": "保存这个签名",
        "ja": "この署名を保存", "ru": "Сохранить эту подпись",
        "it": "Salva questa firma", "el": "Αποθήκευση αυτής της υπογραφής",
        "ar": "حفظ هذا التوقيع", "gl": "Gardar esta sinatura",
        "ca": "Desa aquesta signatura", "eu": "Gorde sinadura hau",
    },
    "firma_guardadas": {
        "en": "Saved signatures", "es": "Firmas guardadas",
        "fr": "Signatures enregistrées", "de": "Gespeicherte Unterschriften",
        "zh": "已保存的签名", "ja": "保存した署名",
        "ru": "Сохранённые подписи", "it": "Firme salvate",
        "el": "Αποθηκευμένες υπογραφές", "ar": "التوقيعات المحفوظة",
        "gl": "Sinaturas gardadas", "ca": "Signatures desades",
        "eu": "Gordetako sinadurak",
    },
    "firma_certificado": {
        "en": "Certificate signature", "es": "Firma con certificado",
        "fr": "Signature par certificat", "de": "Signatur mit Zertifikat",
        "zh": "证书签名", "ja": "証明書による署名",
        "ru": "Подпись сертификатом", "it": "Firma con certificato",
        "el": "Υπογραφή με πιστοποιητικό", "ar": "التوقيع بشهادة",
        "gl": "Sinatura con certificado", "ca": "Signatura amb certificat",
        "eu": "Ziurtagiriarekin sinatzea",
    },
    "firma_certificado_desc": {
        "en": "Uses your PKCS#12 certificate (.p12 or .pfx). Any reader can then verify the document has not been altered.",
        "es": "Usa tu certificado PKCS#12 (.p12 o .pfx). Cualquier lector podrá comprobar que el documento no se ha alterado.",
        "fr": "Utilise votre certificat PKCS#12 (.p12 ou .pfx). N’importe quel lecteur pourra vérifier que le document n’a pas été modifié.",
        "de": "Verwendet Ihr PKCS#12-Zertifikat (.p12 oder .pfx). Jeder Betrachter kann dann prüfen, dass das Dokument unverändert ist.",
        "zh": "使用你的 PKCS#12 证书（.p12 或 .pfx）。之后任何阅读器都能验证文档未被改动。",
        "ja": "PKCS#12 証明書（.p12 または .pfx）を使います。どの閲覧ソフトでも改ざんされていないことを確認できます。",
        "ru": "Использует ваш сертификат PKCS#12 (.p12 или .pfx). Любая программа сможет проверить, что документ не изменялся.",
        "it": "Usa il tuo certificato PKCS#12 (.p12 o .pfx). Qualsiasi lettore potrà verificare che il documento non sia stato alterato.",
        "el": "Χρησιμοποιεί το πιστοποιητικό σας PKCS#12 (.p12 ή .pfx). Κάθε πρόγραμμα ανάγνωσης θα μπορεί να επαληθεύσει ότι το έγγραφο δεν άλλαξε.",
        "ar": "يستخدم شهادتك من نوع PKCS#12 (‏.p12 أو ‎.pfx). عندها يمكن لأي قارئ التحقق من أن المستند لم يُعدَّل.",
        "gl": "Usa o teu certificado PKCS#12 (.p12 ou .pfx). Calquera lector poderá comprobar que o documento non se alterou.",
        "ca": "Fa servir el teu certificat PKCS#12 (.p12 o .pfx). Qualsevol lector podrà comprovar que el document no s’ha alterat.",
        "eu": "Zure PKCS#12 ziurtagiria erabiltzen du (.p12 edo .pfx). Edozein irakurgailuk egiaztatu ahal izango du dokumentua ez dela aldatu.",
    },
    "firma_origen": {
        "en": "Where is your certificate?",
        "es": "¿Dónde tienes el certificado?",
        "fr": "Où se trouve votre certificat ?",
        "de": "Wo liegt Ihr Zertifikat?",
        "zh": "证书在哪里？",
        "ja": "証明書の場所",
        "ru": "Где ваш сертификат?",
        "it": "Dove si trova il certificato?",
        "el": "Πού είναι το πιστοποιητικό σας;",
        "ar": "أين شهادتك؟",
        "gl": "Onde tes o certificado?",
        "ca": "On tens el certificat?",
        "eu": "Non duzu ziurtagiria?",
    },
    "firma_desde_almacen": {
        "en": "Installed on this device",
        "es": "Instalado en el dispositivo",
        "fr": "Installé sur cet appareil",
        "de": "Auf diesem Gerät installiert",
        "zh": "已安装在本机",
        "ja": "この端末にある証明書",
        "ru": "Установлен на устройстве",
        "it": "Installato sul dispositivo",
        "el": "Εγκατεστημένο στη συσκευή",
        "ar": "مثبّتة على الجهاز",
        "gl": "Instalado no dispositivo",
        "ca": "Instal·lat al dispositiu",
        "eu": "Gailuan instalatuta",
    },
    "firma_desde_almacen_desc": {
        "en": "Certificates you added in Android settings. The private key never leaves the system store.",
        "es": "Los certificados que instalaste en los ajustes de Android. La clave privada no sale nunca del almacén del sistema.",
        "fr": "Les certificats ajoutés dans les paramètres d’Android. La clé privée ne quitte jamais le magasin du système.",
        "de": "Zertifikate, die Sie in den Android-Einstellungen hinzugefügt haben. Der private Schlüssel verlässt den Systemspeicher nie.",
        "zh": "您在 Android 设置中安装的证书。私钥始终不会离开系统存储区。",
        "ja": "Android の設定で追加した証明書です。秘密鍵がシステムの保管庫から出ることはありません。",
        "ru": "Сертификаты, добавленные в настройках Android. Закрытый ключ никогда не покидает системное хранилище.",
        "it": "I certificati installati nelle impostazioni di Android. La chiave privata non esce mai dall’archivio di sistema.",
        "el": "Τα πιστοποιητικά που εγκαταστήσατε στις ρυθμίσεις του Android. Το ιδιωτικό κλειδί δεν βγαίνει ποτέ από το σύστημα.",
        "ar": "الشهادات التي ثبّتها في إعدادات أندرويد. المفتاح الخاص لا يغادر مخزن النظام أبدًا.",
        "gl": "Os certificados que instalaches nos axustes de Android. A chave privada non sae nunca do almacén do sistema.",
        "ca": "Els certificats que vas instal·lar als ajustos d’Android. La clau privada no surt mai del magatzem del sistema.",
        "eu": "Android-en ezarpenetan instalatu zenituen ziurtagiriak. Gako pribatua ez da inoiz sistemaren biltegitik ateratzen.",
    },
    "firma_desde_fichero": {
        "en": "From a file (.p12 or .pfx)",
        "es": "Desde un fichero (.p12 o .pfx)",
        "fr": "Depuis un fichier (.p12 ou .pfx)",
        "de": "Aus einer Datei (.p12 oder .pfx)",
        "zh": "从文件选择（.p12 或 .pfx）",
        "ja": "ファイルから（.p12 または .pfx）",
        "ru": "Из файла (.p12 или .pfx)",
        "it": "Da un file (.p12 o .pfx)",
        "el": "Από αρχείο (.p12 ή .pfx)",
        "ar": "من ملف (‏.p12 أو ‎.pfx)",
        "gl": "Desde un ficheiro (.p12 ou .pfx)",
        "ca": "Des d’un fitxer (.p12 o .pfx)",
        "eu": "Fitxategi batetik (.p12 edo .pfx)",
    },
    "firma_desde_fichero_desc": {
        "en": "A certificate file saved on the phone. You will be asked for its password.",
        "es": "Un fichero de certificado guardado en el teléfono. Te pedirá su contraseña.",
        "fr": "Un fichier de certificat enregistré sur le téléphone. Son mot de passe vous sera demandé.",
        "de": "Eine auf dem Telefon gespeicherte Zertifikatsdatei. Das Passwort wird abgefragt.",
        "zh": "保存在手机上的证书文件。稍后会请您输入密码。",
        "ja": "スマートフォンに保存した証明書ファイルです。パスワードの入力を求められます。",
        "ru": "Файл сертификата на телефоне. Потребуется его пароль.",
        "it": "Un file di certificato salvato sul telefono. Ti verrà chiesta la password.",
        "el": "Ένα αρχείο πιστοποιητικού στο τηλέφωνο. Θα σας ζητηθεί ο κωδικός του.",
        "ar": "ملف شهادة محفوظ في الهاتف. سيُطلب منك إدخال كلمة مروره.",
        "gl": "Un ficheiro de certificado gardado no teléfono. Pedirache o seu contrasinal.",
        "ca": "Un fitxer de certificat desat al telèfon. Te’n demanarà la contrasenya.",
        "eu": "Telefonoan gordetako ziurtagiri-fitxategi bat. Bere pasahitza eskatuko dizu.",
    },
    "firma_certificado_activo": {
        "en": "Certificate: %1$s",
        "es": "Certificado: %1$s",
        "fr": "Certificat : %1$s",
        "de": "Zertifikat: %1$s",
        "zh": "证书：%1$s",
        "ja": "証明書：%1$s",
        "ru": "Сертификат: %1$s",
        "it": "Certificato: %1$s",
        "el": "Πιστοποιητικό: %1$s",
        "ar": "الشهادة: %1$s",
        "gl": "Certificado: %1$s",
        "ca": "Certificat: %1$s",
        "eu": "Ziurtagiria: %1$s",
    },
    "firma_vista_previa": {
        "en": "First page of the document",
        "es": "Primera página del documento",
        "fr": "Première page du document",
        "de": "Erste Seite des Dokuments",
        "zh": "文档的第一页",
        "ja": "文書の 1 ページ目",
        "ru": "Первая страница документа",
        "it": "Prima pagina del documento",
        "el": "Πρώτη σελίδα του εγγράφου",
        "ar": "الصفحة الأولى من المستند",
        "gl": "Primeira páxina do documento",
        "ca": "Primera pàgina del document",
        "eu": "Dokumentuaren lehen orria",
    },
    "firma_elegir_certificado": {
        "en": "Choose certificate", "es": "Elegir certificado",
        "fr": "Choisir un certificat", "de": "Zertifikat wählen",
        "zh": "选择证书", "ja": "証明書を選ぶ", "ru": "Выбрать сертификат",
        "it": "Scegli certificato", "el": "Επιλογή πιστοποιητικού",
        "ar": "اختيار شهادة", "gl": "Escoller certificado",
        "ca": "Tria el certificat", "eu": "Aukeratu ziurtagiria",
    },
    "firma_motivo": {
        "en": "Reason (optional)", "es": "Motivo (opcional)",
        "fr": "Motif (facultatif)", "de": "Grund (optional)",
        "zh": "原因（可选）", "ja": "理由（任意）",
        "ru": "Причина (необязательно)", "it": "Motivo (facoltativo)",
        "el": "Λόγος (προαιρετικά)", "ar": "السبب (اختياري)",
        "gl": "Motivo (opcional)", "ca": "Motiu (opcional)",
        "eu": "Arrazoia (aukerakoa)",
    },
    "firma_lugar": {
        "en": "Place (optional)", "es": "Lugar (opcional)",
        "fr": "Lieu (facultatif)", "de": "Ort (optional)",
        "zh": "地点（可选）", "ja": "場所（任意）",
        "ru": "Место (необязательно)", "it": "Luogo (facoltativo)",
        "el": "Τόπος (προαιρετικά)", "ar": "المكان (اختياري)",
        "gl": "Lugar (opcional)", "ca": "Lloc (opcional)",
        "eu": "Lekua (aukerakoa)",
    },
    "firma_nombre_visible": {
        "en": "Name shown", "es": "Nombre visible", "fr": "Nom affiché",
        "de": "Angezeigter Name", "zh": "显示的姓名", "ja": "表示する名前",
        "ru": "Отображаемое имя", "it": "Nome visibile",
        "el": "Εμφανιζόμενο όνομα", "ar": "الاسم الظاهر",
        "gl": "Nome visible", "ca": "Nom visible", "eu": "Izen ikusgaia",
    },
    "firma_firmar_ahora": {
        "en": "Sign now", "es": "Firmar ahora", "fr": "Signer maintenant",
        "de": "Jetzt unterschreiben", "zh": "立即签署", "ja": "署名する",
        "ru": "Подписать", "it": "Firma ora", "el": "Υπογραφή τώρα",
        "ar": "وقّع الآن", "gl": "Asinar agora", "ca": "Signa ara",
        "eu": "Sinatu orain",
    },
    "firma_existentes": {
        "en": "Signatures in this document",
        "es": "Firmas de este documento",
        "fr": "Signatures de ce document",
        "de": "Signaturen in diesem Dokument", "zh": "本文档中的签名",
        "ja": "この文書の署名", "ru": "Подписи в этом документе",
        "it": "Firme in questo documento", "el": "Υπογραφές σε αυτό το έγγραφο",
        "ar": "التوقيعات في هذا المستند", "gl": "Sinaturas deste documento",
        "ca": "Signatures d’aquest document", "eu": "Dokumentu honetako sinadurak",
    },
    "firma_sin_existentes": {
        "en": "This document is not signed yet",
        "es": "Este documento aún no está firmado",
        "fr": "Ce document n’est pas encore signé",
        "de": "Dieses Dokument ist noch nicht signiert",
        "zh": "该文档尚未签署", "ja": "この文書はまだ署名されていません",
        "ru": "Документ ещё не подписан",
        "it": "Questo documento non è ancora firmato",
        "el": "Αυτό το έγγραφο δεν έχει υπογραφεί ακόμη",
        "ar": "لم يُوقَّع هذا المستند بعد",
        "gl": "Este documento aínda non está asinado",
        "ca": "Aquest document encara no està signat",
        "eu": "Dokumentu hau ez dago oraindik sinatuta",
    },
    "firma_cubre_todo": {
        "en": "Covers the whole document",
        "es": "Cubre todo el documento",
        "fr": "Couvre tout le document",
        "de": "Umfasst das gesamte Dokument", "zh": "覆盖整个文档",
        "ja": "文書全体を保護しています", "ru": "Охватывает весь документ",
        "it": "Copre tutto il documento", "el": "Καλύπτει όλο το έγγραφο",
        "ar": "يغطي المستند بالكامل", "gl": "Cobre todo o documento",
        "ca": "Cobreix tot el document", "eu": "Dokumentu osoa hartzen du",
    },
    "firma_hecha": {
        "en": "Document signed", "es": "Documento firmado",
        "fr": "Document signé", "de": "Dokument signiert",
        "zh": "文档已签署", "ja": "文書に署名しました",
        "ru": "Документ подписан", "it": "Documento firmato",
        "el": "Το έγγραφο υπογράφηκε", "ar": "تم توقيع المستند",
        "gl": "Documento asinado", "ca": "Document signat",
        "eu": "Dokumentua sinatuta",
    },
    "firma_aviso_legal": {
        "en": "NexaPDF applies the signature on your device and never sends your certificate anywhere. Whether the signature is legally valid depends on who issued the certificate.",
        "es": "NexaPDF aplica la firma en tu dispositivo y nunca envía tu certificado a ningún sitio. Que la firma tenga validez legal depende de quién emitió el certificado.",
        "fr": "NexaPDF applique la signature sur votre appareil et n’envoie jamais votre certificat nulle part. La validité juridique de la signature dépend de l’émetteur du certificat.",
        "de": "NexaPDF signiert auf Ihrem Gerät und sendet Ihr Zertifikat niemals irgendwohin. Ob die Signatur rechtsgültig ist, hängt vom Aussteller des Zertifikats ab.",
        "zh": "NexaPDF 在你的设备上完成签名，绝不会把证书发送到任何地方。签名是否具有法律效力，取决于证书的颁发机构。",
        "ja": "NexaPDF は端末内で署名し、証明書をどこにも送信しません。署名に法的効力があるかどうかは証明書の発行元によります。",
        "ru": "NexaPDF подписывает на вашем устройстве и никуда не отправляет сертификат. Юридическая сила подписи зависит от того, кто выдал сертификат.",
        "it": "NexaPDF applica la firma sul tuo dispositivo e non invia mai il certificato da nessuna parte. La validità legale dipende da chi ha emesso il certificato.",
        "el": "Το NexaPDF υπογράφει στη συσκευή σας και δεν στέλνει ποτέ το πιστοποιητικό σας πουθενά. Η νομική ισχύς εξαρτάται από τον εκδότη του πιστοποιητικού.",
        "ar": "يوقّع NexaPDF داخل جهازك ولا يرسل شهادتك إلى أي مكان. أما الصلاحية القانونية للتوقيع فتعتمد على الجهة التي أصدرت الشهادة.",
        "gl": "NexaPDF aplica a sinatura no teu dispositivo e nunca envía o teu certificado a ningún sitio. Que a sinatura teña validez legal depende de quen emitiu o certificado.",
        "ca": "NexaPDF aplica la signatura al teu dispositiu i mai envia el teu certificat enlloc. Que la signatura tingui validesa legal depèn de qui va emetre el certificat.",
        "eu": "NexaPDFek zure gailuan sinatzen du eta ez du zure ziurtagiria inora bidaltzen. Sinadurak balio juridikoa duen ala ez, ziurtagiria nork eman duen araberakoa da.",
    },
}
