#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Textos de Ajustes, copias de seguridad, ayuda, acerca de, donacion y errores."""

TEXTOS = {
    # --- Ajustes -------------------------------------------------------------
    "aj_titulo": {
        "en": "Settings", "es": "Ajustes", "fr": "Réglages",
        "de": "Einstellungen", "zh": "设置", "ja": "設定", "ru": "Настройки",
        "it": "Impostazioni", "el": "Ρυθμίσεις", "ar": "الإعدادات",
        "gl": "Axustes", "ca": "Configuració", "eu": "Ezarpenak",
    },
    "aj_tema": {
        "en": "Theme", "es": "Tema", "fr": "Thème", "de": "Design",
        "zh": "主题", "ja": "テーマ", "ru": "Тема", "it": "Tema",
        "el": "Θέμα", "ar": "السمة", "gl": "Tema", "ca": "Tema",
        "eu": "Gaia",
    },
    "aj_tema_grafito_claro": {
        "en": "Graphite light",
        "es": "Grafito claro",
        "fr": "Graphite clair",
        "de": "Graphit hell",
        "zh": "石墨 浅色",
        "ja": "グラファイト ライト",
        "ru": "Графит светлая",
        "it": "Grafite chiaro",
        "el": "Γραφίτης ανοιχτό",
        "ar": "غرافيت فاتح",
        "gl": "Grafito claro",
        "ca": "Grafit clar",
        "eu": "Grafitoa argia",
    },
    "aj_tema_grafito_oscuro": {
        "en": "Graphite dark",
        "es": "Grafito oscuro",
        "fr": "Graphite sombre",
        "de": "Graphit dunkel",
        "zh": "石墨 深色",
        "ja": "グラファイト ダーク",
        "ru": "Графит тёмная",
        "it": "Grafite scuro",
        "el": "Γραφίτης σκούρο",
        "ar": "غرافيت داكن",
        "gl": "Grafito escuro",
        "ca": "Grafit fosc",
        "eu": "Grafitoa iluna",
    },
    "aj_tema_vino_claro": {
        "en": "Wine light",
        "es": "Vino claro",
        "fr": "Vin clair",
        "de": "Wein hell",
        "zh": "酒红 浅色",
        "ja": "ワイン ライト",
        "ru": "Вино светлая",
        "it": "Vino chiaro",
        "el": "Κρασί ανοιχτό",
        "ar": "نبيذي فاتح",
        "gl": "Viño claro",
        "ca": "Vi clar",
        "eu": "Ardoa argia",
    },
    "aj_tema_vino_oscuro": {
        "en": "Wine dark",
        "es": "Vino oscuro",
        "fr": "Vin sombre",
        "de": "Wein dunkel",
        "zh": "酒红 深色",
        "ja": "ワイン ダーク",
        "ru": "Вино тёмная",
        "it": "Vino scuro",
        "el": "Κρασί σκούρο",
        "ar": "نبيذي داكن",
        "gl": "Viño escuro",
        "ca": "Vi fosc",
        "eu": "Ardoa iluna",
    },
    "aj_tema_oceano_claro": {
        "en": "Ocean light",
        "es": "Océano claro",
        "fr": "Océan clair",
        "de": "Ozean hell",
        "zh": "海洋 浅色",
        "ja": "オーシャン ライト",
        "ru": "Океан светлая",
        "it": "Oceano chiaro",
        "el": "Ωκεανός ανοιχτό",
        "ar": "محيط فاتح",
        "gl": "Océano claro",
        "ca": "Oceà clar",
        "eu": "Ozeanoa argia",
    },
    "aj_tema_oceano_oscuro": {
        "en": "Ocean dark",
        "es": "Océano oscuro",
        "fr": "Océan sombre",
        "de": "Ozean dunkel",
        "zh": "海洋 深色",
        "ja": "オーシャン ダーク",
        "ru": "Океан тёмная",
        "it": "Oceano scuro",
        "el": "Ωκεανός σκούρο",
        "ar": "محيط داكن",
        "gl": "Océano escuro",
        "ca": "Oceà fosc",
        "eu": "Ozeanoa iluna",
    },
    "aj_tema_indigo_claro": {
        "en": "Indigo light", "es": "Índigo claro", "fr": "Indigo clair",
        "de": "Indigo hell", "zh": "靛蓝浅色", "ja": "インディゴ（ライト）",
        "ru": "Индиго, светлая", "it": "Indaco chiaro", "el": "Λουλακί ανοιχτό",
        "ar": "نيلي فاتح", "gl": "Índigo claro", "ca": "Indi clar",
        "eu": "Indigo argia",
    },
    "aj_tema_indigo_oscuro": {
        "en": "Indigo dark", "es": "Índigo oscuro", "fr": "Indigo sombre",
        "de": "Indigo dunkel", "zh": "靛蓝深色", "ja": "インディゴ（ダーク）",
        "ru": "Индиго, тёмная", "it": "Indaco scuro", "el": "Λουλακί σκούρο",
        "ar": "نيلي داكن", "gl": "Índigo escuro", "ca": "Indi fosc",
        "eu": "Indigo iluna",
    },
    "aj_tema_bosque_claro": {
        "en": "Forest light", "es": "Bosque claro", "fr": "Forêt claire",
        "de": "Wald hell", "zh": "森林浅色", "ja": "フォレスト（ライト）",
        "ru": "Лес, светлая", "it": "Foresta chiara", "el": "Δάσος ανοιχτό",
        "ar": "غابة فاتحة", "gl": "Bosque claro", "ca": "Bosc clar",
        "eu": "Baso argia",
    },
    "aj_tema_bosque_oscuro": {
        "en": "Forest dark", "es": "Bosque oscuro", "fr": "Forêt sombre",
        "de": "Wald dunkel", "zh": "森林深色", "ja": "フォレスト（ダーク）",
        "ru": "Лес, тёмная", "it": "Foresta scura", "el": "Δάσος σκούρο",
        "ar": "غابة داكنة", "gl": "Bosque escuro", "ca": "Bosc fosc",
        "eu": "Baso iluna",
    },
    "aj_tema_ocaso_claro": {
        "en": "Sunset light", "es": "Ocaso claro", "fr": "Crépuscule clair",
        "de": "Sonnenuntergang hell", "zh": "日落浅色", "ja": "サンセット（ライト）",
        "ru": "Закат, светлая", "it": "Tramonto chiaro",
        "el": "Ηλιοβασίλεμα ανοιχτό", "ar": "غروب فاتح", "gl": "Ocaso claro",
        "ca": "Capvespre clar", "eu": "Ilunabar argia",
    },
    "aj_tema_ocaso_oscuro": {
        "en": "Sunset dark", "es": "Ocaso oscuro", "fr": "Crépuscule sombre",
        "de": "Sonnenuntergang dunkel", "zh": "日落深色", "ja": "サンセット（ダーク）",
        "ru": "Закат, тёмная", "it": "Tramonto scuro",
        "el": "Ηλιοβασίλεμα σκούρο", "ar": "غروب داكن", "gl": "Ocaso escuro",
        "ca": "Capvespre fosc", "eu": "Ilunabar iluna",
    },
    "aj_tema_sistema_desc": {
        "en": "Uses the light or dark version of the palette you last chose, following the phone.",
        "es": "Usa la versión clara u oscura de la paleta que hayas elegido, siguiendo al teléfono.",
        "fr": "Utilise la version claire ou sombre de la palette choisie, en suivant le téléphone.",
        "de": "Verwendet die helle oder dunkle Fassung der zuletzt gewählten Palette, je nach Telefon.",
        "zh": "跟随手机，使用你所选配色的浅色或深色版本。",
        "ja": "端末に合わせて、選んだ配色のライト版かダーク版を使います。",
        "ru": "Использует светлый или тёмный вариант выбранной палитры, следуя настройке телефона.",
        "it": "Usa la versione chiara o scura della tavolozza scelta, seguendo il telefono.",
        "el": "Χρησιμοποιεί την ανοιχτή ή σκούρα εκδοχή της παλέτας που επιλέξατε, ακολουθώντας το τηλέφωνο.",
        "ar": "يستخدم النسخة الفاتحة أو الداكنة من اللوحة التي اخترتها، تبعًا للهاتف.",
        "gl": "Usa a versión clara ou escura da paleta que elixiches, seguindo o teléfono.",
        "ca": "Fa servir la versió clara o fosca de la paleta que has triat, seguint el telèfon.",
        "eu": "Aukeratu duzun paletaren bertsio argia edo iluna erabiltzen du, telefonoari jarraituz.",
    },
    "aj_apariencia": {
        "en": "Appearance", "es": "Apariencia", "fr": "Apparence",
        "de": "Darstellung", "zh": "外观", "ja": "外観", "ru": "Вид",
        "it": "Aspetto", "el": "Εμφάνιση", "ar": "المظهر", "gl": "Aparencia",
        "ca": "Aparença", "eu": "Itxura",
    },
    "aj_modo": {
        "en": "Mode", "es": "Modo", "fr": "Mode", "de": "Modus",
        "zh": "模式", "ja": "モード", "ru": "Режим", "it": "Modalità",
        "el": "Λειτουργία", "ar": "الوضع", "gl": "Modo", "ca": "Mode",
        "eu": "Modua",
    },
    "aj_modo_claro": {
        "en": "Light", "es": "Claro", "fr": "Clair", "de": "Hell",
        "zh": "浅色", "ja": "ライト", "ru": "Светлый", "it": "Chiaro",
        "el": "Φωτεινό", "ar": "فاتح", "gl": "Claro", "ca": "Clar",
        "eu": "Argia",
    },
    "aj_modo_oscuro": {
        "en": "Dark", "es": "Oscuro", "fr": "Sombre", "de": "Dunkel",
        "zh": "深色", "ja": "ダーク", "ru": "Тёмный", "it": "Scuro",
        "el": "Σκοτεινό", "ar": "داكن", "gl": "Escuro", "ca": "Fosc",
        "eu": "Iluna",
    },
    "aj_modo_sistema": {
        "en": "Follow the system", "es": "Seguir al sistema",
        "fr": "Suivre le système", "de": "Systemeinstellung folgen",
        "zh": "跟随系统", "ja": "システムに合わせる",
        "ru": "Как в системе", "it": "Segui il sistema",
        "el": "Όπως το σύστημα", "ar": "حسب النظام", "gl": "Seguir o sistema",
        "ca": "Segueix el sistema", "eu": "Jarraitu sistemari",
    },
    "aj_paleta": {
        "en": "Palette", "es": "Paleta", "fr": "Palette", "de": "Farbpalette",
        "zh": "配色", "ja": "配色", "ru": "Палитра", "it": "Tavolozza",
        "el": "Παλέτα", "ar": "لوحة الألوان", "gl": "Paleta", "ca": "Paleta",
        "eu": "Paleta",
    },
    "aj_paleta_indigo": {
        "en": "Indigo", "es": "Índigo", "fr": "Indigo", "de": "Indigo",
        "zh": "靛蓝", "ja": "インディゴ", "ru": "Индиго", "it": "Indaco",
        "el": "Λουλακί", "ar": "نيلي", "gl": "Índigo", "ca": "Indi",
        "eu": "Indigoa",
    },
    "aj_paleta_bosque": {
        "en": "Forest", "es": "Bosque", "fr": "Forêt", "de": "Wald",
        "zh": "森林", "ja": "フォレスト", "ru": "Лес", "it": "Foresta",
        "el": "Δάσος", "ar": "غابة", "gl": "Bosque", "ca": "Bosc",
        "eu": "Basoa",
    },
    "aj_paleta_ocaso": {
        "en": "Sunset", "es": "Ocaso", "fr": "Crépuscule",
        "de": "Sonnenuntergang", "zh": "日落", "ja": "サンセット",
        "ru": "Закат", "it": "Tramonto", "el": "Ηλιοβασίλεμα", "ar": "غروب",
        "gl": "Ocaso", "ca": "Capvespre", "eu": "Ilunabarra",
    },
    "aj_idioma": {
        "en": "Language", "es": "Idioma", "fr": "Langue", "de": "Sprache",
        "zh": "语言", "ja": "言語", "ru": "Язык", "it": "Lingua",
        "el": "Γλώσσα", "ar": "اللغة", "gl": "Idioma", "ca": "Idioma",
        "eu": "Hizkuntza",
    },
    "aj_idioma_detalle_sistema": {
        "en": "Follows the phone. Changes only if you change the phone’s language.",
        "es": "Sigue al teléfono. Solo cambia si cambias el idioma del teléfono.",
        "fr": "Suit le téléphone. Ne change que si vous changez la langue du téléphone.",
        "de": "Folgt dem Telefon. Ändert sich nur, wenn Sie die Sprache des Telefons ändern.",
        "zh": "跟随手机设置，仅在您更改手机语言时才变化。",
        "ja": "端末に合わせます。端末の言語を変えたときだけ切り替わります。",
        "ru": "Следует за телефоном. Меняется, только если сменить язык телефона.",
        "it": "Segue il telefono. Cambia solo se cambi la lingua del telefono.",
        "el": "Ακολουθεί το τηλέφωνο. Αλλάζει μόνο αν αλλάξετε τη γλώσσα του τηλεφώνου.",
        "ar": "يتبع الهاتف. لا يتغيّر إلا إذا غيّرت لغة الهاتف.",
        "gl": "Segue o teléfono. Só cambia se cambias o idioma do teléfono.",
        "ca": "Segueix el telèfon. Només canvia si canvies l’idioma del telèfon.",
        "eu": "Telefonoari jarraitzen dio. Telefonoaren hizkuntza aldatzean bakarrik aldatzen da.",
    },
    "aj_idioma_detalle_fijo": {
        "en": "The app stays in this language, whatever the phone uses.",
        "es": "La aplicación se queda en este idioma, use el que use el teléfono.",
        "fr": "L’application reste dans cette langue, quelle que soit celle du téléphone.",
        "de": "Die App bleibt in dieser Sprache, unabhängig vom Telefon.",
        "zh": "无论手机使用哪种语言，应用都保持此语言。",
        "ja": "端末の言語にかかわらず、アプリはこの言語のままです。",
        "ru": "Приложение остаётся на этом языке независимо от языка телефона.",
        "it": "L’app resta in questa lingua, qualunque sia quella del telefono.",
        "el": "Η εφαρμογή μένει σε αυτή τη γλώσσα, ανεξάρτητα από το τηλέφωνο.",
        "ar": "يبقى التطبيق بهذه اللغة مهما كانت لغة الهاتف.",
        "gl": "A aplicación queda neste idioma, use o que use o teléfono.",
        "ca": "L’aplicació es queda en aquesta llengua, sigui quina sigui la del telèfon.",
        "eu": "Aplikazioa hizkuntza honetan geratzen da, telefonoak edozein erabilita ere.",
    },
    "aj_idioma_sistema": {
        "en": "System language", "es": "Idioma del sistema",
        "fr": "Langue du système", "de": "Systemsprache", "zh": "系统语言",
        "ja": "システムの言語", "ru": "Язык системы",
        "it": "Lingua di sistema", "el": "Γλώσσα συστήματος",
        "ar": "لغة النظام", "gl": "Idioma do sistema",
        "ca": "Idioma del sistema", "eu": "Sistemaren hizkuntza",
    },
    "aj_calidad": {
        "en": "Preview quality", "es": "Calidad de la vista previa",
        "fr": "Qualité de l’aperçu", "de": "Qualität der Vorschau",
        "zh": "预览质量", "ja": "プレビューの画質",
        "ru": "Качество предпросмотра", "it": "Qualità dell’anteprima",
        "el": "Ποιότητα προεπισκόπησης", "ar": "جودة المعاينة",
        "gl": "Calidade da vista previa", "ca": "Qualitat de la previsualització",
        "eu": "Aurrebistaren kalitatea",
    },
    "aj_calidad_desc": {
        "en": "Only affects what you see on screen. Saved files always keep their full quality.",
        "es": "Solo afecta a lo que ves en pantalla. Los ficheros guardados conservan siempre toda su calidad.",
        "fr": "N’affecte que l’affichage. Les fichiers enregistrés conservent toujours leur pleine qualité.",
        "de": "Betrifft nur die Bildschirmanzeige. Gespeicherte Dateien behalten stets ihre volle Qualität.",
        "zh": "只影响屏幕显示。保存的文件始终保持原有质量。",
        "ja": "画面表示だけに影響します。保存されるファイルは常に元の品質のままです。",
        "ru": "Влияет только на изображение на экране. Сохранённые файлы всегда сохраняют полное качество.",
        "it": "Riguarda solo ciò che vedi sullo schermo. I file salvati mantengono sempre la piena qualità.",
        "el": "Επηρεάζει μόνο όσα βλέπετε στην οθόνη. Τα αποθηκευμένα αρχεία διατηρούν πάντα την πλήρη ποιότητά τους.",
        "ar": "يؤثر فقط على ما تراه على الشاشة. أما الملفات المحفوظة فتحتفظ دائمًا بجودتها الكاملة.",
        "gl": "Só afecta ao que ves na pantalla. Os ficheiros gardados conservan sempre toda a súa calidade.",
        "ca": "Només afecta el que veus a la pantalla. Els fitxers desats conserven sempre tota la qualitat.",
        "eu": "Pantailan ikusten duzuna baino ez du aldatzen. Gordetako fitxategiek kalitate osoa gordetzen dute beti.",
    },
    "aj_calidad_rapida": {
        "en": "Fast", "es": "Rápida", "fr": "Rapide", "de": "Schnell",
        "zh": "快速", "ja": "速い", "ru": "Быстро", "it": "Rapida",
        "el": "Γρήγορη", "ar": "سريعة", "gl": "Rápida", "ca": "Ràpida",
        "eu": "Azkarra",
    },
    "aj_calidad_equilibrada": {
        "en": "Balanced", "es": "Equilibrada", "fr": "Équilibrée",
        "de": "Ausgewogen", "zh": "均衡", "ja": "標準",
        "ru": "Сбалансированно", "it": "Equilibrata", "el": "Ισορροπημένη",
        "ar": "متوازنة", "gl": "Equilibrada", "ca": "Equilibrada",
        "eu": "Orekatua",
    },
    "aj_calidad_nitida": {
        "en": "Sharp", "es": "Nítida", "fr": "Nette", "de": "Scharf",
        "zh": "清晰", "ja": "高精細", "ru": "Чётко", "it": "Nitida",
        "el": "Ευκρινής", "ar": "حادة", "gl": "Nítida", "ca": "Nítida",
        "eu": "Zorrotza",
    },
    "aj_cuando_guardar": {
        "en": "When to save the results",
        "es": "Cuándo guardar los resultados",
        "fr": "Quand enregistrer les résultats",
        "de": "Wann Ergebnisse gespeichert werden",
        "zh": "何时保存结果",
        "ja": "結果を保存するタイミング",
        "ru": "Когда сохранять результаты",
        "it": "Quando salvare i risultati",
        "el": "Πότε αποθηκεύονται τα αποτελέσματα",
        "ar": "متى تُحفظ النتائج",
        "gl": "Cando gardar os resultados",
        "ca": "Quan desar els resultats",
        "eu": "Noiz gorde emaitzak",
    },
    "aj_guardar_paso_a_paso": {
        "en": "Step by step",
        "es": "Paso a paso",
        "fr": "Étape par étape",
        "de": "Schritt für Schritt",
        "zh": "逐步保存",
        "ja": "工程ごと",
        "ru": "На каждом шаге",
        "it": "Passo per passo",
        "el": "Σε κάθε βήμα",
        "ar": "خطوة بخطوة",
        "gl": "Paso a paso",
        "ca": "Pas a pas",
        "eu": "Urratsez urrats",
    },
    "aj_guardar_al_final": {
        "en": "Only at the end",
        "es": "Sólo al final",
        "fr": "Seulement à la fin",
        "de": "Nur am Ende",
        "zh": "仅在最后",
        "ja": "最後だけ",
        "ru": "Только в конце",
        "it": "Solo alla fine",
        "el": "Μόνο στο τέλος",
        "ar": "في النهاية فقط",
        "gl": "Só ao final",
        "ca": "Només al final",
        "eu": "Amaieran bakarrik",
    },
    "aj_carpeta_destino": {
        "en": "Folder: %1$s",
        "es": "Carpeta: %1$s",
        "fr": "Dossier : %1$s",
        "de": "Ordner: %1$s",
        "zh": "文件夹：%1$s",
        "ja": "フォルダー：%1$s",
        "ru": "Папка: %1$s",
        "it": "Cartella: %1$s",
        "el": "Φάκελος: %1$s",
        "ar": "المجلد: %1$s",
        "gl": "Cartafol: %1$s",
        "ca": "Carpeta: %1$s",
        "eu": "Karpeta: %1$s",
    },
    "aj_carpeta_predeterminada": {
        "en": "Downloads/NexaPDF",
        "es": "Descargas/NexaPDF",
        "fr": "Téléchargements/NexaPDF",
        "de": "Downloads/NexaPDF",
        "zh": "下载/NexaPDF",
        "ja": "ダウンロード/NexaPDF",
        "ru": "Загрузки/NexaPDF",
        "it": "Download/NexaPDF",
        "el": "Λήψεις/NexaPDF",
        "ar": "التنزيلات/NexaPDF",
        "gl": "Descargas/NexaPDF",
        "ca": "Baixades/NexaPDF",
        "eu": "Deskargak/NexaPDF",
    },
    "aj_elegir_carpeta": {
        "en": "Choose folder",
        "es": "Elegir carpeta",
        "fr": "Choisir un dossier",
        "de": "Ordner wählen",
        "zh": "选择文件夹",
        "ja": "フォルダーを選ぶ",
        "ru": "Выбрать папку",
        "it": "Scegli cartella",
        "el": "Επιλογή φακέλου",
        "ar": "اختيار مجلد",
        "gl": "Escoller cartafol",
        "ca": "Tria una carpeta",
        "eu": "Aukeratu karpeta",
    },
    "aj_datos": {
        "en": "Your data", "es": "Tus datos", "fr": "Vos données",
        "de": "Ihre Daten", "zh": "你的数据", "ja": "あなたのデータ",
        "ru": "Ваши данные", "it": "I tuoi dati", "el": "Τα δεδομένα σας",
        "ar": "بياناتك", "gl": "Os teus datos", "ca": "Les teves dades",
        "eu": "Zure datuak",
    },
    "aj_exportar": {
        "en": "Export settings", "es": "Exportar ajustes",
        "fr": "Exporter les réglages", "de": "Einstellungen exportieren",
        "zh": "导出设置", "ja": "設定を書き出す",
        "ru": "Экспорт настроек", "it": "Esporta impostazioni",
        "el": "Εξαγωγή ρυθμίσεων", "ar": "تصدير الإعدادات",
        "gl": "Exportar axustes", "ca": "Exporta la configuració",
        "eu": "Esportatu ezarpenak",
    },
    "aj_exportar_desc": {
        "en": "Saves a %1$s file with your preferences and signatures. Your documents are not included: they already live on your device.",
        "es": "Guarda un fichero %1$s con tus preferencias y tus firmas. Tus documentos no van dentro: ya están en tu dispositivo.",
        "fr": "Enregistre un fichier %1$s avec vos préférences et vos signatures. Vos documents n’y figurent pas : ils sont déjà sur votre appareil.",
        "de": "Speichert eine %1$s-Datei mit Ihren Einstellungen und Unterschriften. Ihre Dokumente sind nicht enthalten: sie liegen bereits auf Ihrem Gerät.",
        "zh": "保存一个 %1$s 文件，内含你的偏好设置和签名。不包含你的文档，因为它们已经在你的设备上。",
        "ja": "設定と署名を含む %1$s ファイルを保存します。文書は含まれません。すでに端末にあるからです。",
        "ru": "Сохраняет файл %1$s с вашими настройками и подписями. Документы в него не входят: они уже на устройстве.",
        "it": "Salva un file %1$s con le tue preferenze e le tue firme. I documenti non sono inclusi: sono già sul tuo dispositivo.",
        "el": "Αποθηκεύει ένα αρχείο %1$s με τις προτιμήσεις και τις υπογραφές σας. Τα έγγραφά σας δεν περιλαμβάνονται: βρίσκονται ήδη στη συσκευή σας.",
        "ar": "يحفظ ملف %1$s يتضمن تفضيلاتك وتوقيعاتك. مستنداتك غير مضمّنة، فهي موجودة أصلًا على جهازك.",
        "gl": "Garda un ficheiro %1$s coas túas preferencias e as túas sinaturas. Os teus documentos non van dentro: xa están no teu dispositivo.",
        "ca": "Desa un fitxer %1$s amb les teves preferències i signatures. Els teus documents no hi són: ja són al teu dispositiu.",
        "eu": "%1$s fitxategi bat gordetzen du zure hobespenekin eta sinadurekin. Zure dokumentuak ez doaz barruan: dagoeneko zure gailuan daude.",
    },
    "aj_importar": {
        "en": "Import settings", "es": "Importar ajustes",
        "fr": "Importer des réglages", "de": "Einstellungen importieren",
        "zh": "导入设置", "ja": "設定を読み込む",
        "ru": "Импорт настроек", "it": "Importa impostazioni",
        "el": "Εισαγωγή ρυθμίσεων", "ar": "استيراد الإعدادات",
        "gl": "Importar axustes", "ca": "Importa la configuració",
        "eu": "Inportatu ezarpenak",
    },
    "aj_importar_desc": {
        "en": "Restores a %1$s file you exported before.",
        "es": "Restaura un fichero %1$s que exportaste antes.",
        "fr": "Restaure un fichier %1$s exporté auparavant.",
        "de": "Stellt eine zuvor exportierte %1$s-Datei wieder her.",
        "zh": "恢复你之前导出的 %1$s 文件。",
        "ja": "以前に書き出した %1$s ファイルを復元します。",
        "ru": "Восстанавливает ранее экспортированный файл %1$s.",
        "it": "Ripristina un file %1$s che hai esportato prima.",
        "el": "Επαναφέρει ένα αρχείο %1$s που εξάγατε νωρίτερα.",
        "ar": "يستعيد ملف %1$s سبق أن صدّرته.",
        "gl": "Restaura un ficheiro %1$s que exportaches antes.",
        "ca": "Restaura un fitxer %1$s que has exportat abans.",
        "eu": "Lehenago esportatu duzun %1$s fitxategi bat leheneratzen du.",
    },
    "aj_confirmar_destructivas": {
        "en": "Ask before deleting", "es": "Preguntar antes de borrar",
        "fr": "Demander avant de supprimer", "de": "Vor dem Löschen fragen",
        "zh": "删除前询问", "ja": "削除する前に確認する",
        "ru": "Спрашивать перед удалением", "it": "Chiedi prima di eliminare",
        "el": "Ερώτηση πριν τη διαγραφή", "ar": "السؤال قبل الحذف",
        "gl": "Preguntar antes de borrar", "ca": "Pregunta abans d’esborrar",
        "eu": "Galdetu ezabatu aurretik",
    },
    "aj_guardar_descargas": {
        "en": "Also save to Downloads",
        "es": "Guardar también en Descargas",
        "fr": "Enregistrer aussi dans Téléchargements",
        "de": "Auch in Downloads speichern", "zh": "同时保存到“下载”",
        "ja": "ダウンロードにも保存する",
        "ru": "Сохранять также в «Загрузки»",
        "it": "Salva anche in Download", "el": "Αποθήκευση και στις Λήψεις",
        "ar": "الحفظ أيضًا في مجلد التنزيلات",
        "gl": "Gardar tamén en Descargas", "ca": "Desa també a Baixades",
        "eu": "Gorde Deskargak karpetan ere",
    },
    "aj_guardar_descargas_desc": {
        "en": "Every document you create is copied to Downloads/NexaPDF so other apps can find it.",
        "es": "Cada documento que crees se copia a Descargas/NexaPDF para que otras apps puedan encontrarlo.",
        "fr": "Chaque document créé est copié dans Téléchargements/NexaPDF pour que d’autres applis le trouvent.",
        "de": "Jedes erstellte Dokument wird nach Downloads/NexaPDF kopiert, damit andere Apps es finden.",
        "zh": "你创建的每个文档都会复制到“下载/NexaPDF”，方便其他应用找到。",
        "ja": "作成した文書は「ダウンロード/NexaPDF」にコピーされ、他のアプリからも開けます。",
        "ru": "Каждый созданный документ копируется в «Загрузки/NexaPDF», чтобы другие приложения его находили.",
        "it": "Ogni documento creato viene copiato in Download/NexaPDF così altre app possono trovarlo.",
        "el": "Κάθε έγγραφο που δημιουργείτε αντιγράφεται στο Λήψεις/NexaPDF ώστε να το βρίσκουν άλλες εφαρμογές.",
        "ar": "يُنسخ كل مستند تنشئه إلى مجلد التنزيلات/NexaPDF لتتمكن التطبيقات الأخرى من العثور عليه.",
        "gl": "Cada documento que crees cópiase a Descargas/NexaPDF para que outras apps poidan atopalo.",
        "ca": "Cada document que creïs es copia a Baixades/NexaPDF perquè altres aplicacions el puguin trobar.",
        "eu": "Sortzen duzun dokumentu bakoitza Deskargak/NexaPDF karpetara kopiatzen da, beste aplikazioek aurki dezaten.",
    },
    "aj_nombre_firmas": {
        "en": "Name for signatures", "es": "Nombre para las firmas",
        "fr": "Nom pour les signatures", "de": "Name für Unterschriften",
        "zh": "签名使用的姓名", "ja": "署名に使う名前",
        "ru": "Имя для подписей", "it": "Nome per le firme",
        "el": "Όνομα για τις υπογραφές", "ar": "الاسم المستخدم في التوقيعات",
        "gl": "Nome para as sinaturas", "ca": "Nom per a les signatures",
        "eu": "Sinaduretarako izena",
    },
    "aj_apoyo": {
        "en": "Support", "es": "Apoyo", "fr": "Soutien",
        "de": "Unterstützung", "zh": "支持", "ja": "応援", "ru": "Поддержка",
        "it": "Sostegno", "el": "Υποστήριξη", "ar": "الدعم", "gl": "Apoio",
        "ca": "Suport", "eu": "Laguntza",
    },
    "aj_apoyar_desarrollo": {
        "en": "Support the development", "es": "Apoyar el desarrollo",
        "fr": "Soutenir le développement", "de": "Die Entwicklung unterstützen",
        "zh": "支持开发", "ja": "開発を応援する",
        "ru": "Поддержать разработку", "it": "Sostieni lo sviluppo",
        "el": "Στηρίξτε την ανάπτυξη", "ar": "ادعم التطوير",
        "gl": "Apoiar o desenvolvemento", "ca": "Dona suport al desenvolupament",
        "eu": "Lagundu garapena",
    },
    "aj_compartir_app": {
        "en": "Share NexaPDF", "es": "Compartir NexaPDF",
        "fr": "Partager NexaPDF", "de": "NexaPDF teilen",
        "zh": "分享 NexaPDF", "ja": "NexaPDF を共有",
        "ru": "Поделиться NexaPDF", "it": "Condividi NexaPDF",
        "el": "Κοινοποίηση του NexaPDF", "ar": "مشاركة NexaPDF",
        "gl": "Compartir NexaPDF", "ca": "Comparteix NexaPDF",
        "eu": "Partekatu NexaPDF",
    },
    "aj_compartir_texto": {
        "en": "NexaPDF: merge, split, edit and sign PDFs on your phone, offline and free. %1$s",
        "es": "NexaPDF: une, separa, edita y firma PDF en el móvil, sin conexión y gratis. %1$s",
        "fr": "NexaPDF : fusionnez, divisez, modifiez et signez des PDF sur votre téléphone, hors ligne et gratuitement. %1$s",
        "de": "NexaPDF: PDFs am Handy zusammenfügen, teilen, bearbeiten und signieren – offline und kostenlos. %1$s",
        "zh": "NexaPDF：在手机上合并、拆分、编辑和签署 PDF，离线且免费。%1$s",
        "ja": "NexaPDF：スマホで PDF を結合・分割・編集・署名。オフラインで無料です。%1$s",
        "ru": "NexaPDF: объединяйте, разделяйте, редактируйте и подписывайте PDF на телефоне — офлайн и бесплатно. %1$s",
        "it": "NexaPDF: unisci, dividi, modifica e firma PDF sul telefono, offline e gratis. %1$s",
        "el": "NexaPDF: ενώστε, χωρίστε, επεξεργαστείτε και υπογράψτε PDF στο κινητό, χωρίς σύνδεση και δωρεάν. %1$s",
        "ar": "‏NexaPDF: ادمج وقسّم وحرّر ووقّع ملفات PDF على هاتفك، دون اتصال ومجانًا. %1$s",
        "gl": "NexaPDF: une, separa, edita e asina PDF no móbil, sen conexión e de balde. %1$s",
        "ca": "NexaPDF: uneix, divideix, edita i signa PDF al mòbil, sense connexió i gratis. %1$s",
        "eu": "NexaPDF: batu, zatitu, editatu eta sinatu PDFak mugikorrean, konexiorik gabe eta doan. %1$s",
    },
    "aj_ayuda": {
        "en": "Help", "es": "Ayuda", "fr": "Aide", "de": "Hilfe",
        "zh": "帮助", "ja": "ヘルプ", "ru": "Справка", "it": "Aiuto",
        "el": "Βοήθεια", "ar": "المساعدة", "gl": "Axuda", "ca": "Ajuda",
        "eu": "Laguntza",
    },
    "aj_acerca_de": {
        "en": "About", "es": "Acerca de", "fr": "À propos", "de": "Über",
        "zh": "关于", "ja": "このアプリについて", "ru": "О приложении",
        "it": "Informazioni", "el": "Σχετικά", "ar": "حول التطبيق",
        "gl": "Acerca de", "ca": "Quant a", "eu": "Honi buruz",
    },

    # --- Copias de seguridad -------------------------------------------------
    "copia_exportada": {
        "en": "Settings exported", "es": "Ajustes exportados",
        "fr": "Réglages exportés", "de": "Einstellungen exportiert",
        "zh": "设置已导出", "ja": "設定を書き出しました",
        "ru": "Настройки экспортированы", "it": "Impostazioni esportate",
        "el": "Οι ρυθμίσεις εξήχθησαν", "ar": "تم تصدير الإعدادات",
        "gl": "Axustes exportados", "ca": "Configuració exportada",
        "eu": "Ezarpenak esportatuta",
    },
    "copia_importar_titulo": {
        "en": "Replace your settings?", "es": "¿Reemplazar tus ajustes?",
        "fr": "Remplacer vos réglages ?", "de": "Einstellungen ersetzen?",
        "zh": "要替换你的设置吗？", "ja": "設定を置き換えますか？",
        "ru": "Заменить ваши настройки?", "it": "Sostituire le impostazioni?",
        "el": "Αντικατάσταση των ρυθμίσεών σας;",
        "ar": "هل تريد استبدال إعداداتك؟", "gl": "Substituír os teus axustes?",
        "ca": "Vols substituir la teva configuració?",
        "eu": "Zure ezarpenak ordeztu?",
    },
    "copia_importar_texto": {
        "en": "The file replaces your current preferences and signatures. A backup of what you have now is saved first, so nothing is lost if you change your mind.",
        "es": "El fichero reemplaza tus preferencias y firmas actuales. Antes se guarda una copia de lo que tienes ahora, así que no se pierde nada si te arrepientes.",
        "fr": "Le fichier remplace vos préférences et signatures actuelles. Une copie de l’état actuel est enregistrée au préalable : rien n’est perdu si vous changez d’avis.",
        "de": "Die Datei ersetzt Ihre aktuellen Einstellungen und Unterschriften. Vorher wird eine Sicherung des jetzigen Standes angelegt, es geht also nichts verloren.",
        "zh": "该文件会替换你当前的偏好设置和签名。系统会先备份现在的内容，所以即使反悔也不会丢失。",
        "ja": "このファイルは現在の設定と署名を置き換えます。先に今の状態のバックアップを保存するので、気が変わっても失われません。",
        "ru": "Файл заменит текущие настройки и подписи. Сначала сохраняется резервная копия нынешнего состояния, поэтому ничего не потеряется.",
        "it": "Il file sostituisce le preferenze e le firme attuali. Prima viene salvata una copia di quello che hai ora, quindi non si perde nulla se cambi idea.",
        "el": "Το αρχείο αντικαθιστά τις τρέχουσες προτιμήσεις και υπογραφές σας. Πρώτα αποθηκεύεται αντίγραφο της τωρινής κατάστασης, ώστε να μη χαθεί τίποτα.",
        "ar": "سيستبدل الملف تفضيلاتك وتوقيعاتك الحالية. تُحفظ أولًا نسخة احتياطية من وضعك الحالي، فلا يضيع شيء إن غيّرت رأيك.",
        "gl": "O ficheiro substitúe as túas preferencias e sinaturas actuais. Antes gárdase unha copia do que tes agora, así que non se perde nada se te arrepintes.",
        "ca": "El fitxer substitueix les teves preferències i signatures actuals. Abans es desa una còpia del que tens ara, així que no es perd res si canvies d’opinió.",
        "eu": "Fitxategiak zure oraingo hobespenak eta sinadurak ordezten ditu. Aurretik oraingoaren kopia bat gordetzen da, beraz ez da ezer galtzen.",
    },
    "copia_importada": {
        "en": "Settings restored", "es": "Ajustes restaurados",
        "fr": "Réglages restaurés", "de": "Einstellungen wiederhergestellt",
        "zh": "设置已恢复", "ja": "設定を復元しました",
        "ru": "Настройки восстановлены", "it": "Impostazioni ripristinate",
        "el": "Οι ρυθμίσεις επανήλθαν", "ar": "تمت استعادة الإعدادات",
        "gl": "Axustes restaurados", "ca": "Configuració restaurada",
        "eu": "Ezarpenak leheneratuta",
    },
    "copia_error_formato": {
        "en": "That file is not a NexaPDF backup",
        "es": "Ese fichero no es una copia de NexaPDF",
        "fr": "Ce fichier n’est pas une sauvegarde NexaPDF",
        "de": "Diese Datei ist keine NexaPDF-Sicherung",
        "zh": "该文件不是 NexaPDF 备份",
        "ja": "そのファイルは NexaPDF のバックアップではありません",
        "ru": "Этот файл не является резервной копией NexaPDF",
        "it": "Quel file non è un backup di NexaPDF",
        "el": "Αυτό το αρχείο δεν είναι αντίγραφο του NexaPDF",
        "ar": "هذا الملف ليس نسخة احتياطية من NexaPDF",
        "gl": "Ese ficheiro non é unha copia de NexaPDF",
        "ca": "Aquest fitxer no és una còpia de NexaPDF",
        "eu": "Fitxategi hori ez da NexaPDF kopia bat",
    },
    "copia_error_version": {
        "en": "That backup was made with a newer version of NexaPDF",
        "es": "Esa copia se hizo con una versión más nueva de NexaPDF",
        "fr": "Cette sauvegarde a été créée avec une version plus récente de NexaPDF",
        "de": "Diese Sicherung stammt aus einer neueren NexaPDF-Version",
        "zh": "该备份是用更新版本的 NexaPDF 创建的",
        "ja": "そのバックアップは新しいバージョンの NexaPDF で作成されています",
        "ru": "Эта копия создана более новой версией NexaPDF",
        "it": "Quel backup è stato creato con una versione più recente di NexaPDF",
        "el": "Αυτό το αντίγραφο δημιουργήθηκε με νεότερη έκδοση του NexaPDF",
        "ar": "أُنشئت هذه النسخة بإصدار أحدث من NexaPDF",
        "gl": "Esa copia fíxose cunha versión máis nova de NexaPDF",
        "ca": "Aquesta còpia es va fer amb una versió més nova de NexaPDF",
        "eu": "Kopia hori NexaPDFen bertsio berriago batekin egin zen",
    },
    "copia_error_incompleta": {
        "en": "That backup is incomplete or damaged",
        "es": "Esa copia está incompleta o dañada",
        "fr": "Cette sauvegarde est incomplète ou endommagée",
        "de": "Diese Sicherung ist unvollständig oder beschädigt",
        "zh": "该备份不完整或已损坏",
        "ja": "そのバックアップは不完全か壊れています",
        "ru": "Эта копия неполная или повреждена",
        "it": "Quel backup è incompleto o danneggiato",
        "el": "Αυτό το αντίγραφο είναι ελλιπές ή κατεστραμμένο",
        "ar": "هذه النسخة ناقصة أو تالفة",
        "gl": "Esa copia está incompleta ou danada",
        "ca": "Aquesta còpia està incompleta o malmesa",
        "eu": "Kopia hori osatugabea edo hondatuta dago",
    },

    # --- Errores -------------------------------------------------------------
    "error_contrasena": {
        "en": "Wrong password", "es": "Contraseña incorrecta",
        "fr": "Mot de passe incorrect", "de": "Falsches Passwort",
        "zh": "密码不正确", "ja": "パスワードが違います", "ru": "Неверный пароль",
        "it": "Password errata", "el": "Λανθασμένος κωδικός",
        "ar": "كلمة المرور غير صحيحة", "gl": "Contrasinal incorrecto",
        "ca": "Contrasenya incorrecta", "eu": "Pasahitz okerra",
    },
    "error_fichero_invalido": {
        "en": "This file cannot be opened. It may not be a PDF, or it may be damaged.",
        "es": "Este fichero no se puede abrir. Puede que no sea un PDF, o que esté dañado.",
        "fr": "Ce fichier ne peut pas être ouvert. Ce n’est peut-être pas un PDF, ou il est endommagé.",
        "de": "Diese Datei lässt sich nicht öffnen. Vielleicht ist es kein PDF oder sie ist beschädigt.",
        "zh": "无法打开该文件。它可能不是 PDF，或者已损坏。",
        "ja": "このファイルは開けません。PDF ではないか、壊れている可能性があります。",
        "ru": "Не удалось открыть файл. Возможно, это не PDF или он повреждён.",
        "it": "Questo file non si può aprire. Forse non è un PDF, oppure è danneggiato.",
        "el": "Αυτό το αρχείο δεν ανοίγει. Ίσως δεν είναι PDF ή είναι κατεστραμμένο.",
        "ar": "تعذّر فتح هذا الملف. قد لا يكون PDF أو قد يكون تالفًا.",
        "gl": "Este ficheiro non se pode abrir. Pode que non sexa un PDF, ou que estea danado.",
        "ca": "Aquest fitxer no es pot obrir. Potser no és un PDF, o està malmès.",
        "eu": "Fitxategi hau ezin da ireki. Agian ez da PDF bat, edo hondatuta dago.",
    },
    "error_sin_memoria": {
        "en": "The document is too large for the memory available. Try splitting it into parts first.",
        "es": "El documento es demasiado grande para la memoria disponible. Prueba a separarlo en partes antes.",
        "fr": "Le document est trop volumineux pour la mémoire disponible. Essayez de le diviser d’abord.",
        "de": "Das Dokument ist zu groß für den verfügbaren Speicher. Teilen Sie es zuerst auf.",
        "zh": "文档太大，超出可用内存。可以先把它拆成几部分。",
        "ja": "文書が大きすぎて空きメモリに収まりません。先に分割してみてください。",
        "ru": "Документ слишком велик для доступной памяти. Попробуйте сначала разделить его.",
        "it": "Il documento è troppo grande per la memoria disponibile. Prova prima a dividerlo in parti.",
        "el": "Το έγγραφο είναι πολύ μεγάλο για τη διαθέσιμη μνήμη. Δοκιμάστε πρώτα να το χωρίσετε.",
        "ar": "المستند أكبر من الذاكرة المتاحة. جرّب تقسيمه إلى أجزاء أولًا.",
        "gl": "O documento é grande de máis para a memoria dispoñible. Proba a separalo en partes antes.",
        "ca": "El document és massa gran per a la memòria disponible. Prova de dividir-lo abans.",
        "eu": "Dokumentua handiegia da eskuragarri dagoen memoriarako. Saiatu lehenik zatitzen.",
    },
    "error_escritura": {
        "en": "The result could not be saved. Check that there is free space.",
        "es": "No se ha podido guardar el resultado. Comprueba que queda espacio libre.",
        "fr": "Le résultat n’a pas pu être enregistré. Vérifiez qu’il reste de l’espace libre.",
        "de": "Das Ergebnis konnte nicht gespeichert werden. Prüfen Sie den freien Speicherplatz.",
        "zh": "无法保存结果。请检查是否还有可用空间。",
        "ja": "結果を保存できませんでした。空き容量を確認してください。",
        "ru": "Не удалось сохранить результат. Проверьте, есть ли свободное место.",
        "it": "Non è stato possibile salvare il risultato. Controlla che ci sia spazio libero.",
        "el": "Δεν ήταν δυνατή η αποθήκευση. Ελέγξτε αν υπάρχει ελεύθερος χώρος.",
        "ar": "تعذّر حفظ النتيجة. تأكد من توفر مساحة خالية.",
        "gl": "Non se puido gardar o resultado. Comproba que queda espazo libre.",
        "ca": "No s’ha pogut desar el resultat. Comprova que queda espai lliure.",
        "eu": "Ezin izan da emaitza gorde. Egiaztatu leku librea dagoela.",
    },
    "error_certificado": {
        "en": "The certificate could not be opened. Check the password and that the file is a .p12 or .pfx.",
        "es": "No se ha podido abrir el certificado. Revisa la contraseña y que el fichero sea .p12 o .pfx.",
        "fr": "Le certificat n’a pas pu être ouvert. Vérifiez le mot de passe et que le fichier est un .p12 ou .pfx.",
        "de": "Das Zertifikat konnte nicht geöffnet werden. Prüfen Sie Passwort und Dateityp (.p12 oder .pfx).",
        "zh": "无法打开证书。请检查密码，并确认文件是 .p12 或 .pfx。",
        "ja": "証明書を開けませんでした。パスワードと、ファイルが .p12 か .pfx かを確認してください。",
        "ru": "Не удалось открыть сертификат. Проверьте пароль и что файл имеет формат .p12 или .pfx.",
        "it": "Non è stato possibile aprire il certificato. Controlla la password e che il file sia .p12 o .pfx.",
        "el": "Δεν ήταν δυνατό το άνοιγμα του πιστοποιητικού. Ελέγξτε τον κωδικό και ότι το αρχείο είναι .p12 ή .pfx.",
        "ar": "تعذّر فتح الشهادة. تحقّق من كلمة المرور ومن أن الملف بصيغة ‎.p12 أو ‎.pfx.",
        "gl": "Non se puido abrir o certificado. Revisa o contrasinal e que o ficheiro sexa .p12 ou .pfx.",
        "ca": "No s’ha pogut obrir el certificat. Revisa la contrasenya i que el fitxer sigui .p12 o .pfx.",
        "eu": "Ezin izan da ziurtagiria ireki. Egiaztatu pasahitza eta fitxategia .p12 edo .pfx dela.",
    },
    "error_desconocido": {
        "en": "Something went wrong", "es": "Algo ha salido mal",
        "fr": "Un problème est survenu", "de": "Etwas ist schiefgelaufen",
        "zh": "出了点问题", "ja": "問題が発生しました",
        "ru": "Что-то пошло не так", "it": "Qualcosa è andato storto",
        "el": "Κάτι πήγε στραβά", "ar": "حدث خطأ ما",
        "gl": "Algo saíu mal", "ca": "Alguna cosa ha anat malament",
        "eu": "Zerbait gaizki joan da",
    },
    "error_nada_seleccionado": {
        "en": "Select at least one page first",
        "es": "Selecciona al menos una página",
        "fr": "Sélectionnez au moins une page",
        "de": "Wählen Sie zuerst mindestens eine Seite",
        "zh": "请先至少选择一页", "ja": "まずページを 1 つ以上選んでください",
        "ru": "Сначала выберите хотя бы одну страницу",
        "it": "Seleziona almeno una pagina", "el": "Επιλέξτε τουλάχιστον μία σελίδα",
        "ar": "اختر صفحة واحدة على الأقل",
        "gl": "Selecciona polo menos unha páxina",
        "ca": "Selecciona almenys una pàgina",
        "eu": "Hautatu gutxienez orri bat",
    },
    "error_faltan_documentos": {
        "en": "Add at least two documents to merge",
        "es": "Añade al menos dos documentos para unir",
        "fr": "Ajoutez au moins deux documents à fusionner",
        "de": "Fügen Sie mindestens zwei Dokumente zum Zusammenfügen hinzu",
        "zh": "请至少添加两个要合并的文档",
        "ja": "結合するには文書を 2 つ以上追加してください",
        "ru": "Добавьте минимум два документа для объединения",
        "it": "Aggiungi almeno due documenti da unire",
        "el": "Προσθέστε τουλάχιστον δύο έγγραφα για συγχώνευση",
        "ar": "أضف مستندين على الأقل للدمج",
        "gl": "Engade polo menos dous documentos para unir",
        "ca": "Afegeix almenys dos documents per unir",
        "eu": "Gehitu gutxienez bi dokumentu batzeko",
    },
}
