#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Catalogo de textos de NexaPDF en los trece idiomas.

Fuente unica de la interfaz. `generar_traducciones.py` convierte esto en los
ficheros `strings.xml` de commonMain/composeResources.

Se mantiene en un solo sitio y no en trece XML sueltos por una razon practica:
asi es imposible anadir un texto y olvidarse de traducirlo a un idioma, porque
el generador comprueba que las trece entradas existan antes de escribir nada.

Convenciones:
  - Se usa el apostrofo tipografico (U+2019), no el recto, para no depender del
    escapado del formato XML de Android.
  - Los marcadores de posicion son de estilo Java: %1$s, %1$d.
"""

IDIOMAS = ["en", "es", "fr", "de", "zh", "ja", "ru", "it", "el", "ar", "gl", "ca", "eu"]

# Carpeta de recursos de cada idioma. El ingles es el respaldo y va en `values`.
CARPETAS = {
    "en": "values",
    "es": "values-es",
    "fr": "values-fr",
    "de": "values-de",
    "zh": "values-zh",
    "ja": "values-ja",
    "ru": "values-ru",
    "it": "values-it",
    "el": "values-el",
    "ar": "values-ar",
    "gl": "values-gl",
    "ca": "values-ca",
    "eu": "values-eu",
}

TEXTOS = {
    "tour_z_baldosas_t": {
        "en": "Everything it does, at a glance",
        "es": "Todo lo que hace, de un vistazo",
        "fr": "Tout ce qu’elle fait, d’un coup d’œil",
        "de": "Alles auf einen Blick",
        "zh": "所有功能，一眼看全",
        "ja": "できることが一目で",
        "ru": "Всё, что умеет, — сразу видно",
        "it": "Tutto quello che fa, a colpo d’occhio",
        "el": "Όλα όσα κάνει, με μια ματιά",
        "ar": "كل ما تفعله في لمحة",
        "gl": "Todo o que fai, dun vistazo",
        "ca": "Tot el que fa, d’un cop d’ull",
        "eu": "Egiten duen guztia, begirada batean",
    },
    "tour_z_baldosas_c": {
        "en": "Eight tools on one screen. Nothing hidden in menus.",
        "es": "Ocho herramientas en una pantalla. Nada escondido en menús.",
        "fr": "Huit outils sur un écran. Rien de caché dans des menus.",
        "de": "Acht Werkzeuge auf einem Bildschirm. Nichts in Menüs versteckt.",
        "zh": "八个工具，一屏放下，没有藏在菜单里的功能。",
        "ja": "8 つの道具が 1 画面に。メニューの奥に隠れているものはありません。",
        "ru": "Восемь инструментов на одном экране. Ничего не спрятано в меню.",
        "it": "Otto strumenti in una schermata. Niente nascosto nei menu.",
        "el": "Οκτώ εργαλεία σε μία οθόνη. Τίποτα κρυμμένο σε μενού.",
        "ar": "ثماني أدوات في شاشة واحدة. لا شيء مخبّأ في القوائم.",
        "gl": "Oito ferramentas nunha pantalla. Nada agochado en menús.",
        "ca": "Vuit eines en una pantalla. Res amagat en menús.",
        "eu": "Zortzi tresna pantaila bakarrean. Ezer ez menuetan ezkutatuta.",
    },
    "tour_z_leer_t": {
        "en": "Start by reading",
        "es": "Empieza por leer",
        "fr": "Commencez par lire",
        "de": "Fang mit Lesen an",
        "zh": "先从阅读开始",
        "ja": "まずは読むところから",
        "ru": "Начните с чтения",
        "it": "Inizia leggendo",
        "el": "Ξεκινήστε διαβάζοντας",
        "ar": "ابدأ بالقراءة",
        "gl": "Empeza por ler",
        "ca": "Comença llegint",
        "eu": "Hasi irakurtzen",
    },
    "tour_z_leer_c": {
        "en": "Search inside the document, jump to any page and see its sections and signatures.",
        "es": "Busca dentro del documento, salta a la página que quieras y mira sus secciones y firmas.",
        "fr": "Cherchez dans le document, allez à la page voulue et voyez ses sections et signatures.",
        "de": "Im Dokument suchen, zu jeder Seite springen und Abschnitte und Signaturen sehen.",
        "zh": "在文档内搜索、跳到任意页面，并查看其章节和签名。",
        "ja": "文書内を検索し、好きなページへ移動し、目次と署名を確認できます。",
        "ru": "Ищите внутри документа, переходите к любой странице и смотрите разделы и подписи.",
        "it": "Cerca dentro il documento, salta alla pagina che vuoi e guarda sezioni e firme.",
        "el": "Αναζητήστε μέσα στο έγγραφο, πηγαίνετε σε όποια σελίδα θέλετε και δείτε ενότητες και υπογραφές.",
        "ar": "ابحث داخل المستند، وانتقل إلى أي صفحة، واطّلع على أقسامه وتوقيعاته.",
        "gl": "Busca dentro do documento, salta á páxina que queiras e mira as súas seccións e sinaturas.",
        "ca": "Cerca dins el document, salta a la pàgina que vulguis i mira’n les seccions i signatures.",
        "eu": "Bilatu dokumentuaren barruan, jauzi nahi duzun orrira eta ikusi atalak eta sinadurak.",
    },
    "tour_z_editar_t": {
        "en": "Write on the page",
        "es": "Escribe sobre la página",
        "fr": "Écrivez sur la page",
        "de": "Auf der Seite schreiben",
        "zh": "在页面上书写",
        "ja": "ページに書き込む",
        "ru": "Пишите на странице",
        "it": "Scrivi sulla pagina",
        "el": "Γράψτε πάνω στη σελίδα",
        "ar": "اكتب على الصفحة",
        "gl": "Escribe sobre a páxina",
        "ca": "Escriu sobre la pàgina",
        "eu": "Idatzi orrian",
    },
    "tour_z_editar_c": {
        "en": "Draw, add text, shapes and images, and move, resize or rotate anything you added.",
        "es": "Dibuja, añade texto, formas e imágenes, y mueve, escala o gira lo que hayas añadido.",
        "fr": "Dessinez, ajoutez du texte, des formes et des images, et déplacez ou faites pivoter ce que vous ajoutez.",
        "de": "Zeichnen, Text, Formen und Bilder hinzufügen und alles verschieben, skalieren oder drehen.",
        "zh": "绘制、添加文字、形状和图片，并可移动、缩放或旋转你添加的内容。",
        "ja": "描く、文字・図形・画像を足す。足したものは移動・拡大縮小・回転できます。",
        "ru": "Рисуйте, добавляйте текст, фигуры и изображения, а добавленное двигайте и вращайте.",
        "it": "Disegna, aggiungi testo, forme e immagini, e sposta, ridimensiona o ruota ciò che aggiungi.",
        "el": "Σχεδιάστε, προσθέστε κείμενο, σχήματα και εικόνες, και μετακινήστε ή περιστρέψτε ό,τι προσθέτετε.",
        "ar": "ارسم وأضف النصوص والأشكال والصور، وحرّك أو أدر ما تضيفه.",
        "gl": "Debuxa, engade texto, formas e imaxes, e move, escala ou xira o que engadas.",
        "ca": "Dibuixa, afegeix text, formes i imatges, i mou, escala o gira el que afegeixis.",
        "eu": "Marraztu, gehitu testua, formak eta irudiak, eta mugitu edo biratu gehitutakoa.",
    },
    "tour_z_recientes_t": {
        "en": "What you have made",
        "es": "Lo que has hecho",
        "fr": "Ce que vous avez fait",
        "de": "Was du erstellt hast",
        "zh": "你做过的文件",
        "ja": "作ったファイル",
        "ru": "То, что вы сделали",
        "it": "Quello che hai fatto",
        "el": "Όσα έχετε φτιάξει",
        "ar": "ما أنشأته",
        "gl": "O que fixeches",
        "ca": "El que has fet",
        "eu": "Egin duzuna",
    },
    "tour_z_recientes_c": {
        "en": "Every document you create lands here. Hold one to rename or delete it.",
        "es": "Todo lo que creas acaba aquí. Mantén pulsado uno para renombrarlo o borrarlo.",
        "fr": "Tout ce que vous créez arrive ici. Maintenez pour renommer ou supprimer.",
        "de": "Alles, was Sie erstellen, landet hier. Gedrückt halten zum Umbenennen oder Löschen.",
        "zh": "你创建的文件都会到这里。长按可重命名或删除。",
        "ja": "作ったものはすべてここに集まります。長押しで名前の変更や削除ができます。",
        "ru": "Всё созданное попадает сюда. Удерживайте, чтобы переименовать или удалить.",
        "it": "Tutto ciò che crei finisce qui. Tieni premuto per rinominare o eliminare.",
        "el": "Ό,τι δημιουργείτε καταλήγει εδώ. Κρατήστε πατημένο για μετονομασία ή διαγραφή.",
        "ar": "كل ما تنشئه ينتهي هنا. اضغط مطولًا لإعادة التسمية أو الحذف.",
        "gl": "Todo o que crees acaba aquí. Mantén premido un para renomealo ou borralo.",
        "ca": "Tot el que creïs acaba aquí. Mantén premut per reanomenar-lo o esborrar-lo.",
        "eu": "Sortzen duzun guztia hona dator. Eutsi sakatuta berrizendatzeko edo ezabatzeko.",
    },
    "tour_z_ajustes_t": {
        "en": "Make it yours",
        "es": "Ajústala a tu gusto",
        "fr": "À votre convenance",
        "de": "Nach deinem Geschmack",
        "zh": "按你的习惯来",
        "ja": "自分好みに",
        "ru": "Настройте под себя",
        "it": "Regolala come vuoi",
        "el": "Ρυθμίστε την όπως θέλετε",
        "ar": "اضبطها على ذوقك",
        "gl": "Axústaa ao teu gusto",
        "ca": "Ajusta-la al teu gust",
        "eu": "Egokitu zure gustura",
    },
    "tour_z_ajustes_c": {
        "en": "Themes, languages, how you read, where files go and what happens when one is ready.",
        "es": "Temas, idiomas, cómo se lee, dónde van los ficheros y qué pasa cuando uno está listo.",
        "fr": "Thèmes, langues, mode de lecture, dossier de destination et ce qui se passe à la fin.",
        "de": "Themen, Sprachen, Leseweise, Zielordner und was passiert, wenn etwas fertig ist.",
        "zh": "主题、语言、阅读方式、文件保存位置，以及文件完成后的行为。",
        "ja": "テーマ、言語、読み方、保存先、そしてできあがったときの動き。",
        "ru": "Темы, языки, способ чтения, папка для файлов и что делать, когда файл готов.",
        "it": "Temi, lingue, come si legge, dove vanno i file e cosa succede quando uno è pronto.",
        "el": "Θέματα, γλώσσες, τρόπος ανάγνωσης, πού πάνε τα αρχεία και τι γίνεται όταν ένα είναι έτοιμο.",
        "ar": "السمات واللغات وطريقة القراءة ووجهة الملفات وما يحدث عند اكتمال أحدها.",
        "gl": "Temas, idiomas, como se le, onde van os ficheiros e que pasa cando un está listo.",
        "ca": "Temes, llengües, com es llegeix, on van els fitxers i què passa quan un és a punt.",
        "eu": "Gaiak, hizkuntzak, nola irakurri, fitxategiak nora doazen eta bat prest dagoenean zer gertatzen den.",
    },
    "doc_separar_todo_pregunta": {
        "en": "This creates %1$d files, one per page. Go ahead?",
        "es": "Se van a crear %1$d ficheros, uno por página. ¿Seguimos?",
        "fr": "Cela va créer %1$d fichiers, un par page. On continue ?",
        "de": "Das erzeugt %1$d Dateien, eine pro Seite. Weiter?",
        "zh": "这会生成 %1$d 个文件，每页一个。要继续吗？",
        "ja": "1 ページにつき 1 つ、%1$d 個のファイルができます。続けますか。",
        "ru": "Будет создано %1$d файлов, по одному на страницу. Продолжить?",
        "it": "Si creeranno %1$d file, uno per pagina. Procediamo?",
        "el": "Θα δημιουργηθούν %1$d αρχεία, ένα ανά σελίδα. Συνεχίζουμε;",
        "ar": "سيُنشأ %1$d ملفًا، واحد لكل صفحة. هل نتابع؟",
        "gl": "Vanse crear %1$d ficheiros, un por páxina. Seguimos?",
        "ca": "Es crearan %1$d fitxers, un per pàgina. Continuem?",
        "eu": "%1$d fitxategi sortuko dira, orriko bat. Jarraitu?",
    },
    "ed_texto_tamano": {
        "en": "Size",
        "es": "Tamaño",
        "fr": "Taille",
        "de": "Größe",
        "zh": "字号",
        "ja": "文字の大きさ",
        "ru": "Размер",
        "it": "Dimensione",
        "el": "Μέγεθος",
        "ar": "الحجم",
        "gl": "Tamaño",
        "ca": "Mida",
        "eu": "Tamaina",
    },
    "ed_texto_escribe": {
        "en": "What it says",
        "es": "Lo que pone",
        "fr": "Le texte",
        "de": "Der Text",
        "zh": "文字内容",
        "ja": "入れる文字",
        "ru": "Текст",
        "it": "Il testo",
        "el": "Το κείμενο",
        "ar": "النص",
        "gl": "O que pon",
        "ca": "El text",
        "eu": "Testua",
    },
    "rec_renombrar": {
        "en": "Rename",
        "es": "Renombrar",
        "fr": "Renommer",
        "de": "Umbenennen",
        "zh": "重命名",
        "ja": "名前を変更",
        "ru": "Переименовать",
        "it": "Rinomina",
        "el": "Μετονομασία",
        "ar": "إعادة تسمية",
        "gl": "Renomear",
        "ca": "Canvia el nom",
        "eu": "Berrizendatu",
    },
    "rec_borrar": {
        "en": "Delete file",
        "es": "Borrar el fichero",
        "fr": "Supprimer le fichier",
        "de": "Datei löschen",
        "zh": "删除文件",
        "ja": "ファイルを削除",
        "ru": "Удалить файл",
        "it": "Elimina il file",
        "el": "Διαγραφή αρχείου",
        "ar": "حذف الملف",
        "gl": "Borrar o ficheiro",
        "ca": "Esborra el fitxer",
        "eu": "Ezabatu fitxategia",
    },
    "rec_borrar_pregunta": {
        "en": "Delete %1$s? It cannot be undone.",
        "es": "¿Borrar %1$s? No se puede deshacer.",
        "fr": "Supprimer %1$s ? C’est irréversible.",
        "de": "%1$s löschen? Das lässt sich nicht rückgängig machen.",
        "zh": "删除 %1$s？此操作无法撤销。",
        "ja": "%1$s を削除しますか？元には戻せません。",
        "ru": "Удалить %1$s? Отменить будет нельзя.",
        "it": "Eliminare %1$s? Non si può annullare.",
        "el": "Διαγραφή του %1$s; Δεν αναιρείται.",
        "ar": "حذف %1$s؟ لا يمكن التراجع.",
        "gl": "Borrar %1$s? Non se pode desfacer.",
        "ca": "Esborrar %1$s? No es pot desfer.",
        "eu": "%1$s ezabatu? Ezin da desegin.",
    },
    "rec_nombre_nuevo": {
        "en": "New name",
        "es": "Nombre nuevo",
        "fr": "Nouveau nom",
        "de": "Neuer Name",
        "zh": "新名称",
        "ja": "新しい名前",
        "ru": "Новое имя",
        "it": "Nuovo nome",
        "el": "Νέο όνομα",
        "ar": "الاسم الجديد",
        "gl": "Nome novo",
        "ca": "Nom nou",
        "eu": "Izen berria",
    },
    "rec_opciones": {
        "en": "File options",
        "es": "Opciones del fichero",
        "fr": "Options du fichier",
        "de": "Dateioptionen",
        "zh": "文件选项",
        "ja": "ファイルの操作",
        "ru": "Действия с файлом",
        "it": "Opzioni del file",
        "el": "Επιλογές αρχείου",
        "ar": "خيارات الملف",
        "gl": "Opcións do ficheiro",
        "ca": "Opcions del fitxer",
        "eu": "Fitxategiaren aukerak",
    },
    "rec_borrado": {
        "en": "File deleted",
        "es": "Fichero borrado",
        "fr": "Fichier supprimé",
        "de": "Datei gelöscht",
        "zh": "文件已删除",
        "ja": "ファイルを削除しました",
        "ru": "Файл удалён",
        "it": "File eliminato",
        "el": "Το αρχείο διαγράφηκε",
        "ar": "حُذف الملف",
        "gl": "Ficheiro borrado",
        "ca": "Fitxer esborrat",
        "eu": "Fitxategia ezabatuta",
    },
    "rec_renombrado": {
        "en": "File renamed",
        "es": "Fichero renombrado",
        "fr": "Fichier renommé",
        "de": "Datei umbenannt",
        "zh": "文件已重命名",
        "ja": "名前を変更しました",
        "ru": "Файл переименован",
        "it": "File rinominato",
        "el": "Το αρχείο μετονομάστηκε",
        "ar": "أُعيدت تسمية الملف",
        "gl": "Ficheiro renomeado",
        "ca": "Fitxer reanomenat",
        "eu": "Fitxategia berrizendatuta",
    },
    "aj_al_terminar": {
        "en": "When a document is ready",
        "es": "Al terminar un documento",
        "fr": "Quand un document est prêt",
        "de": "Wenn ein Dokument fertig ist",
        "zh": "文档完成后",
        "ja": "文書ができたとき",
        "ru": "Когда документ готов",
        "it": "Quando un documento è pronto",
        "el": "Όταν ένα έγγραφο είναι έτοιμο",
        "ar": "عند اكتمال المستند",
        "gl": "Ao rematar un documento",
        "ca": "En acabar un document",
        "eu": "Dokumentu bat amaitzean",
    },
    "aj_al_terminar_abrir": {
        "en": "Open it",
        "es": "Abrirlo",
        "fr": "L’ouvrir",
        "de": "Öffnen",
        "zh": "打开",
        "ja": "開く",
        "ru": "Открыть",
        "it": "Aprilo",
        "el": "Άνοιγμα",
        "ar": "افتحه",
        "gl": "Abrilo",
        "ca": "Obre’l",
        "eu": "Ireki",
    },
    "aj_al_terminar_preguntar": {
        "en": "Ask",
        "es": "Preguntar",
        "fr": "Demander",
        "de": "Fragen",
        "zh": "询问",
        "ja": "確認する",
        "ru": "Спросить",
        "it": "Chiedi",
        "el": "Ερώτηση",
        "ar": "اسأل",
        "gl": "Preguntar",
        "ca": "Pregunta",
        "eu": "Galdetu",
    },
    "aj_al_terminar_no": {
        "en": "Leave it",
        "es": "No abrirlo",
        "fr": "Ne pas l’ouvrir",
        "de": "Nicht öffnen",
        "zh": "不打开",
        "ja": "開かない",
        "ru": "Не открывать",
        "it": "Non aprirlo",
        "el": "Χωρίς άνοιγμα",
        "ar": "لا تفتحه",
        "gl": "Non abrilo",
        "ca": "No l’obris",
        "eu": "Ez ireki",
    },
    "aj_al_terminar_desc": {
        "en": "Each task on its own. It goes to your folder either way.",
        "es": "Cada tarea a su aire. En cualquier caso va a tu carpeta.",
        "fr": "Chaque tâche à sa façon. Dans tous les cas, il va dans votre dossier.",
        "de": "Jede Aufgabe für sich. In den gewählten Ordner kommt es ohnehin.",
        "zh": "每种任务各自设定。无论如何都会保存到你的文件夹。",
        "ja": "作業ごとに設定できます。いずれも選んだフォルダーに保存されます。",
        "ru": "Каждая задача по-своему. В вашу папку он попадёт в любом случае.",
        "it": "Ogni operazione a modo suo. In ogni caso finisce nella tua cartella.",
        "el": "Κάθε εργασία ξεχωριστά. Σε κάθε περίπτωση πάει στον φάκελό σας.",
        "ar": "كل مهمة على حدة. وفي كل الأحوال يُحفظ في مجلدك.",
        "gl": "Cada tarefa ao seu. En calquera caso vai á túa carpeta.",
        "ca": "Cada tasca a la seva. En qualsevol cas va a la teva carpeta.",
        "eu": "Zeregin bakoitza bere aldetik. Nolanahi ere, zure karpetara doa.",
    },
    "res_abrir_titulo": {
        "en": "Document ready",
        "es": "Documento listo",
        "fr": "Document prêt",
        "de": "Dokument fertig",
        "zh": "文档已完成",
        "ja": "文書ができました",
        "ru": "Документ готов",
        "it": "Documento pronto",
        "el": "Το έγγραφο είναι έτοιμο",
        "ar": "المستند جاهز",
        "gl": "Documento listo",
        "ca": "Document a punt",
        "eu": "Dokumentua prest",
    },
    "res_abrir": {
        "en": "Open",
        "es": "Abrir",
        "fr": "Ouvrir",
        "de": "Öffnen",
        "zh": "打开",
        "ja": "開く",
        "ru": "Открыть",
        "it": "Apri",
        "el": "Άνοιγμα",
        "ar": "فتح",
        "gl": "Abrir",
        "ca": "Obre",
        "eu": "Ireki",
    },
    "res_ahora_no": {
        "en": "Not now",
        "es": "Ahora no",
        "fr": "Pas maintenant",
        "de": "Jetzt nicht",
        "zh": "暂不",
        "ja": "今はしない",
        "ru": "Не сейчас",
        "it": "Non ora",
        "el": "Όχι τώρα",
        "ar": "ليس الآن",
        "gl": "Agora non",
        "ca": "Ara no",
        "eu": "Orain ez",
    },
    "firma_paso_manuscrita": {
        "en": "Step 1 of 2 · Handwritten signature",
        "es": "Paso 1 de 2 · Firma manuscrita",
        "fr": "Étape 1 sur 2 · Signature manuscrite",
        "de": "Schritt 1 von 2 · Handschriftliche Unterschrift",
        "zh": "第 1 步，共 2 步 · 手写签名",
        "ja": "ステップ 1 / 2 · 手書きの署名",
        "ru": "Шаг 1 из 2 · Подпись от руки",
        "it": "Passo 1 di 2 · Firma autografa",
        "el": "Βήμα 1 από 2 · Χειρόγραφη υπογραφή",
        "ar": "الخطوة 1 من 2 · التوقيع بخط اليد",
        "gl": "Paso 1 de 2 · Sinatura manuscrita",
        "ca": "Pas 1 de 2 · Signatura manuscrita",
        "eu": "1. urratsa 2tik · Eskuzko sinadura",
    },
    "firma_paso_certificado": {
        "en": "Step 2 of 2 · Digital signature",
        "es": "Paso 2 de 2 · Firma digital",
        "fr": "Étape 2 sur 2 · Signature numérique",
        "de": "Schritt 2 von 2 · Digitale Signatur",
        "zh": "第 2 步，共 2 步 · 数字签名",
        "ja": "ステップ 2 / 2 · 電子署名",
        "ru": "Шаг 2 из 2 · Цифровая подпись",
        "it": "Passo 2 di 2 · Firma digitale",
        "el": "Βήμα 2 από 2 · Ψηφιακή υπογραφή",
        "ar": "الخطوة 2 من 2 · التوقيع الرقمي",
        "gl": "Paso 2 de 2 · Sinatura dixital",
        "ca": "Pas 2 de 2 · Signatura digital",
        "eu": "2. urratsa 2tik · Sinadura digitala",
    },
    "firma_saltar_manuscrita": {
        "en": "Skip, go to the digital signature",
        "es": "Saltar e ir a la firma digital",
        "fr": "Passer et aller à la signature numérique",
        "de": "Überspringen und zur digitalen Signatur",
        "zh": "跳过，直接进行数字签名",
        "ja": "スキップして電子署名へ",
        "ru": "Пропустить и перейти к цифровой подписи",
        "it": "Salta e vai alla firma digitale",
        "el": "Παράλειψη, μετάβαση στην ψηφιακή υπογραφή",
        "ar": "تخطَّ وانتقل إلى التوقيع الرقمي",
        "gl": "Saltar e ir á sinatura dixital",
        "ca": "Omet i ves a la signatura digital",
        "eu": "Saltatu eta joan sinadura digitalera",
    },
    "firma_volver_manuscrita": {
        "en": "Back to the handwritten signature",
        "es": "Volver a la firma manuscrita",
        "fr": "Retour à la signature manuscrite",
        "de": "Zurück zur handschriftlichen Unterschrift",
        "zh": "返回手写签名",
        "ja": "手書きの署名に戻る",
        "ru": "Назад к подписи от руки",
        "it": "Torna alla firma autografa",
        "el": "Πίσω στη χειρόγραφη υπογραφή",
        "ar": "العودة إلى التوقيع بخط اليد",
        "gl": "Volver á sinatura manuscrita",
        "ca": "Torna a la signatura manuscrita",
        "eu": "Itzuli eskuzko sinadurara",
    },
    "firma_manuscrita_hecha": {
        "en": "The handwritten signature is already on the document. Now the digital one, if you want it.",
        "es": "La firma manuscrita ya está en el documento. Ahora la digital, si la quieres.",
        "fr": "La signature manuscrite est déjà sur le document. Passons au numérique, si vous le souhaitez.",
        "de": "Die handschriftliche Unterschrift steht schon im Dokument. Jetzt die digitale, wenn Sie möchten.",
        "zh": "手写签名已加入文档。如果需要，接下来是数字签名。",
        "ja": "手書きの署名は文書に入りました。必要なら次は電子署名です。",
        "ru": "Подпись от руки уже в документе. Теперь цифровая, если она нужна.",
        "it": "La firma autografa è già nel documento. Ora quella digitale, se la vuoi.",
        "el": "Η χειρόγραφη υπογραφή είναι ήδη στο έγγραφο. Τώρα η ψηφιακή, αν τη θέλετε.",
        "ar": "التوقيع بخط اليد موجود في المستند بالفعل. والآن التوقيع الرقمي، إن أردته.",
        "gl": "A sinatura manuscrita xa está no documento. Agora a dixital, se a queres.",
        "ca": "La signatura manuscrita ja és al document. Ara la digital, si la vols.",
        "eu": "Eskuzko sinadura dokumentuan dago jada. Orain digitala, nahi baduzu.",
    },
    "vis_de_total": {
        "en": "of %1$d",
        "es": "de %1$d",
        "fr": "sur %1$d",
        "de": "von %1$d",
        "zh": "/ %1$d",
        "ja": "/ %1$d",
        "ru": "из %1$d",
        "it": "di %1$d",
        "el": "από %1$d",
        "ar": "من %1$d",
        "gl": "de %1$d",
        "ca": "de %1$d",
        "eu": "/ %1$d",
    },
    "aj_lectura": {
        "en": "How you read",
        "es": "Cómo se lee",
        "fr": "Mode de lecture",
        "de": "Leseweise",
        "zh": "阅读方式",
        "ja": "読み方",
        "ru": "Как читать",
        "it": "Come si legge",
        "el": "Τρόπος ανάγνωσης",
        "ar": "طريقة القراءة",
        "gl": "Como se le",
        "ca": "Com es llegeix",
        "eu": "Nola irakurri",
    },
    "aj_lectura_lateral": {
        "en": "Page by page",
        "es": "Página a página",
        "fr": "Page par page",
        "de": "Seite für Seite",
        "zh": "逐页翻阅",
        "ja": "1 ページずつ",
        "ru": "По страницам",
        "it": "Pagina per pagina",
        "el": "Σελίδα προς σελίδα",
        "ar": "صفحة بصفحة",
        "gl": "Páxina a páxina",
        "ca": "Pàgina a pàgina",
        "eu": "Orriz orri",
    },
    "aj_lectura_vertical": {
        "en": "Continuous scroll",
        "es": "Desplazamiento continuo",
        "fr": "Défilement continu",
        "de": "Fortlaufend scrollen",
        "zh": "连续滚动",
        "ja": "連続スクロール",
        "ru": "Непрерывная прокрутка",
        "it": "Scorrimento continuo",
        "el": "Συνεχής κύλιση",
        "ar": "تمرير متواصل",
        "gl": "Desprazamento continuo",
        "ca": "Desplaçament continu",
        "eu": "Etengabeko korritzea",
    },
    "aj_lectura_desc": {
        "en": "How you move from one page to the next.",
        "es": "Cómo se pasa de una página a la siguiente.",
        "fr": "Comment on passe d’une page à la suivante.",
        "de": "Wie man von Seite zu Seite wechselt.",
        "zh": "如何从一页翻到下一页。",
        "ja": "ページからページへの移り方。",
        "ru": "Как переходить со страницы на страницу.",
        "it": "Come si passa da una pagina all’altra.",
        "el": "Πώς περνάτε από τη μία σελίδα στην άλλη.",
        "ar": "كيف تنتقل من صفحة إلى أخرى.",
        "gl": "Como se pasa dunha páxina á seguinte.",
        "ca": "Com es passa d’una pàgina a la següent.",
        "eu": "Nola pasatzen den orri batetik hurrengora.",
    },
    "vis_ir_a_pagina": {
        "en": "Go to page",
        "es": "Ir a la página",
        "fr": "Aller à la page",
        "de": "Gehe zu Seite",
        "zh": "跳转到页面",
        "ja": "ページへ移動",
        "ru": "Перейти к странице",
        "it": "Vai alla pagina",
        "el": "Μετάβαση σε σελίδα",
        "ar": "الانتقال إلى صفحة",
        "gl": "Ir á páxina",
        "ca": "Ves a la pàgina",
        "eu": "Joan orrira",
    },
    "vis_numero_pagina": {
        "en": "Page number",
        "es": "Número de página",
        "fr": "Numéro de page",
        "de": "Seitenzahl",
        "zh": "页码",
        "ja": "ページ番号",
        "ru": "Номер страницы",
        "it": "Numero di pagina",
        "el": "Αριθμός σελίδας",
        "ar": "رقم الصفحة",
        "gl": "Número de páxina",
        "ca": "Número de pàgina",
        "eu": "Orri-zenbakia",
    },
    "vis_ir": {
        "en": "Go",
        "es": "Ir",
        "fr": "Aller",
        "de": "Los",
        "zh": "前往",
        "ja": "移動",
        "ru": "Перейти",
        "it": "Vai",
        "el": "Μετάβαση",
        "ar": "انتقال",
        "gl": "Ir",
        "ca": "Ves-hi",
        "eu": "Joan",
    },
    "aj_resumen_separar": {
        "en": "Show a summary before splitting",
        "es": "Enseñar un resumen antes de dividir",
        "fr": "Afficher un résumé avant de diviser",
        "de": "Vor dem Teilen eine Übersicht zeigen",
        "zh": "拆分前显示摘要",
        "ja": "分割する前に内容を確認する",
        "ru": "Показывать сводку перед разделением",
        "it": "Mostra un riepilogo prima di dividere",
        "el": "Εμφάνιση σύνοψης πριν τον διαχωρισμό",
        "ar": "عرض ملخّص قبل التقسيم",
        "gl": "Amosar un resumo antes de dividir",
        "ca": "Mostra un resum abans de dividir",
        "eu": "Erakutsi laburpena banandu aurretik",
    },
    "aj_resumen_separar_desc": {
        "en": "Dividing is what creates the most files at once, and the hardest to undo.",
        "es": "Dividir es lo que más ficheros crea de una vez, y lo que más cuesta deshacer.",
        "fr": "Diviser est ce qui crée le plus de fichiers d’un coup, et le plus difficile à défaire.",
        "de": "Beim Teilen entstehen die meisten Dateien auf einmal, und es lässt sich am schwersten rückgängig machen.",
        "zh": "拆分一次生成的文件最多，也最难撤销。",
        "ja": "分割は一度に最も多くのファイルを作り、やり直しが一番大変な操作です。",
        "ru": "Разделение создаёт больше всего файлов за раз, и его труднее всего отменить.",
        "it": "Dividere è ciò che crea più file in una volta, e ciò che costa di più annullare.",
        "el": "Ο διαχωρισμός δημιουργεί τα περισσότερα αρχεία μαζί, και είναι το πιο δύσκολο να αναιρεθεί.",
        "ar": "التقسيم هو ما يُنشئ أكبر عدد من الملفات دفعة واحدة، وأصعبها تراجعًا.",
        "gl": "Dividir é o que máis ficheiros crea dunha vez, e o que máis custa desfacer.",
        "ca": "Dividir és el que més fitxers crea de cop, i el que més costa desfer.",
        "eu": "Banantzea da aldi berean fitxategi gehien sortzen dituena, eta desegiten zailena.",
    },
    "sep_modo_rango": {
        "en": "Range",
        "es": "Rango",
        "fr": "Plage",
        "de": "Bereich",
        "zh": "连续范围",
        "ja": "範囲",
        "ru": "Диапазон",
        "it": "Intervallo",
        "el": "Εύρος",
        "ar": "نطاق",
        "gl": "Rango",
        "ca": "Interval",
        "eu": "Barrutia",
    },
    "sep_modo_sueltas": {
        "en": "Loose pages",
        "es": "Páginas sueltas",
        "fr": "Pages isolées",
        "de": "Einzelne Seiten",
        "zh": "单独页面",
        "ja": "個別のページ",
        "ru": "Отдельные страницы",
        "it": "Pagine sciolte",
        "el": "Μεμονωμένες σελίδες",
        "ar": "صفحات متفرّقة",
        "gl": "Páxinas soltas",
        "ca": "Pàgines soltes",
        "eu": "Orri solteak",
    },
    "sep_toca_sueltas": {
        "en": "Tap each page you want to keep. They do not have to be next to each other.",
        "es": "Toca cada página que quieras quedarte. No hace falta que estén seguidas.",
        "fr": "Touchez chaque page que vous voulez garder. Elles n’ont pas besoin de se suivre.",
        "de": "Tippen Sie jede Seite an, die Sie behalten wollen. Sie müssen nicht aufeinanderfolgen.",
        "zh": "点选每一页你想保留的页面，不必连续。",
        "ja": "残したいページを 1 枚ずつタップします。連続していなくても構いません。",
        "ru": "Нажмите каждую страницу, которую хотите оставить. Подряд идти они не обязаны.",
        "it": "Tocca ogni pagina che vuoi tenere. Non devono essere consecutive.",
        "el": "Πατήστε κάθε σελίδα που θέλετε να κρατήσετε. Δεν χρειάζεται να είναι συνεχόμενες.",
        "ar": "المس كل صفحة تريد الاحتفاظ بها. ولا يلزم أن تكون متتالية.",
        "gl": "Toca cada páxina que queiras gardar. Non fai falta que estean seguidas.",
        "ca": "Toca cada pàgina que vulguis conservar. No cal que siguin seguides.",
        "eu": "Ukitu gorde nahi duzun orri bakoitza. Ez dute jarraian egon behar.",
    },
    "sep_resumen_titulo": {
        "en": "This is what will be created",
        "es": "Esto es lo que se va a crear",
        "fr": "Voici ce qui va être créé",
        "de": "Das wird erstellt",
        "zh": "将要创建的内容",
        "ja": "作成されるファイル",
        "ru": "Вот что будет создано",
        "it": "Ecco cosa verrà creato",
        "el": "Αυτά θα δημιουργηθούν",
        "ar": "هذا ما سيُنشأ",
        "gl": "Isto é o que se vai crear",
        "ca": "Això és el que es crearà",
        "eu": "Hau da sortuko dena",
    },
    "sep_resumen_vacia": {
        "en": "No pages chosen",
        "es": "Sin páginas elegidas",
        "fr": "Aucune page choisie",
        "de": "Keine Seiten ausgewählt",
        "zh": "未选择页面",
        "ja": "ページが選ばれていません",
        "ru": "Страницы не выбраны",
        "it": "Nessuna pagina scelta",
        "el": "Δεν επιλέχθηκαν σελίδες",
        "ar": "لم تُختَر أي صفحة",
        "gl": "Sen páxinas elixidas",
        "ca": "Sense pàgines triades",
        "eu": "Ez da orririk aukeratu",
    },
    "sep_ninguna": {
        "en": "Clear",
        "es": "Quitar todas",
        "fr": "Tout enlever",
        "de": "Alle abwählen",
        "zh": "全部取消",
        "ja": "すべて解除",
        "ru": "Снять все",
        "it": "Togli tutte",
        "el": "Καθαρισμός",
        "ar": "إزالة الكل",
        "gl": "Quitar todas",
        "ca": "Treu-les totes",
        "eu": "Kendu guztiak",
    },
    "sep_parte_n": {
        "en": "Part %1$d",
        "es": "Parte %1$d",
        "fr": "Partie %1$d",
        "de": "Teil %1$d",
        "zh": "第 %1$d 部分",
        "ja": "パート %1$d",
        "ru": "Часть %1$d",
        "it": "Parte %1$d",
        "el": "Μέρος %1$d",
        "ar": "الجزء %1$d",
        "gl": "Parte %1$d",
        "ca": "Part %1$d",
        "eu": "%1$d. zatia",
    },
    "sep_toca_paginas": {
        "en": "Tap the first page of the part and then the last one. You can also type the numbers.",
        "es": "Toca la primera página de la parte y luego la última. También puedes escribir los números.",
        "fr": "Touchez la première page de la partie puis la dernière. Vous pouvez aussi saisir les numéros.",
        "de": "Tippen Sie auf die erste Seite des Teils und dann auf die letzte. Sie können die Nummern auch eintippen.",
        "zh": "先点这一部分的首页，再点末页。也可以直接输入页码。",
        "ja": "パートの最初のページをタップし、次に最後のページをタップします。番号を入力しても構いません。",
        "ru": "Нажмите первую страницу части, затем последнюю. Номера можно и ввести вручную.",
        "it": "Tocca la prima pagina della parte e poi l’ultima. Puoi anche scrivere i numeri.",
        "el": "Πατήστε την πρώτη σελίδα του μέρους και μετά την τελευταία. Μπορείτε και να γράψετε τους αριθμούς.",
        "ar": "المس أول صفحة في الجزء ثم آخر صفحة. ويمكنك كتابة الأرقام أيضًا.",
        "gl": "Toca a primeira páxina da parte e logo a última. Tamén podes escribir os números.",
        "ca": "Toca la primera pàgina de la part i després l’última. També pots escriure els números.",
        "eu": "Ukitu zatiaren lehen orria eta gero azkena. Zenbakiak idatz ditzakezu ere.",
    },
    "sep_sin_asignar": {
        "en": "Not in any part",
        "es": "Sin parte asignada",
        "fr": "Dans aucune partie",
        "de": "Keinem Teil zugeordnet",
        "zh": "未分配到任何部分",
        "ja": "どのパートにも入っていません",
        "ru": "Не входит ни в одну часть",
        "it": "In nessuna parte",
        "el": "Σε κανένα μέρος",
        "ar": "ليست ضمن أي جزء",
        "gl": "Sen parte asignada",
        "ca": "Sense part assignada",
        "eu": "Zatirik gabe",
    },
    "sep_crear": {
        "en": "Create the files",
        "es": "Crear los ficheros",
        "fr": "Créer les fichiers",
        "de": "Dateien erstellen",
        "zh": "创建文件",
        "ja": "ファイルを作成",
        "ru": "Создать файлы",
        "it": "Crea i file",
        "el": "Δημιουργία αρχείων",
        "ar": "إنشاء الملفات",
        "gl": "Crear os ficheiros",
        "ca": "Crea els fitxers",
        "eu": "Sortu fitxategiak",
    },
    "sep_rango": {
        "en": "Pages %1$s",
        "es": "Páginas %1$s",
        "fr": "Pages %1$s",
        "de": "Seiten %1$s",
        "zh": "第 %1$s 页",
        "ja": "%1$s ページ",
        "ru": "Страницы %1$s",
        "it": "Pagine %1$s",
        "el": "Σελίδες %1$s",
        "ar": "الصفحات %1$s",
        "gl": "Páxinas %1$s",
        "ca": "Pàgines %1$s",
        "eu": "%1$s orriak",
    },
    "ayuda_visor_t": {
        "en": "Reading a PDF",
        "es": "Leer un PDF",
        "fr": "Lire un PDF",
        "de": "Ein PDF lesen",
        "zh": "阅读 PDF",
        "ja": "PDF を読む",
        "ru": "Чтение PDF",
        "it": "Leggere un PDF",
        "el": "Ανάγνωση PDF",
        "ar": "قراءة ملف PDF",
        "gl": "Ler un PDF",
        "ca": "Llegir un PDF",
        "eu": "PDF bat irakurri",
    },
    "ayuda_visor_c": {
        "en": "Open a document with Read PDF, or tap one in Recent files. The magnifier searches the whole document: matches are highlighted on the page and the arrows move between them. The list icon shows the document’s sections, if it has any, and the shield lists its digital signatures. Pinch to zoom and drag to move around.",
        "es": "Abre un documento con Leer PDF, o toca uno en Ficheros recientes. La lupa busca en todo el documento: las apariciones quedan resaltadas sobre la página y las flechas te llevan de una a otra. El icono de lista muestra las secciones del documento, si las tiene, y el escudo sus firmas digitales. Pellizca para ampliar y arrastra para moverte.",
        "fr": "Ouvrez un document avec Lire un PDF, ou touchez-en un dans Fichiers récents. La loupe cherche dans tout le document : les occurrences sont surlignées sur la page et les flèches passent de l’une à l’autre. L’icône de liste montre les sections, et le bouclier les signatures numériques. Pincez pour zoomer et faites glisser pour vous déplacer.",
        "de": "Öffnen Sie ein Dokument mit PDF lesen oder tippen Sie eins unter Zuletzt verwendet an. Die Lupe durchsucht das ganze Dokument: Treffer werden auf der Seite hervorgehoben, die Pfeile springen zwischen ihnen. Das Listensymbol zeigt die Abschnitte, das Schild die digitalen Signaturen. Zum Zoomen zwei Finger, zum Bewegen ziehen.",
        "zh": "用「阅读 PDF」打开文档，或在最近文件中点按一个。放大镜可搜索整个文档：匹配处会在页面上高亮，箭头可在它们之间跳转。列表图标显示文档章节（如果有），盾牌图标显示数字签名。双指缩放，拖动移动。",
        "ja": "「PDF を読む」で開くか、最近のファイルから選びます。虫めがねは文書全体を検索し、見つかった箇所はページ上で強調され、矢印で移動できます。リストのアイコンは目次、盾のアイコンは電子署名を表示します。ピンチで拡大、ドラッグで移動します。",
        "ru": "Откройте документ через «Читать PDF» или коснитесь его в недавних файлах. Лупа ищет по всему документу: совпадения подсвечиваются на странице, стрелки переходят между ними. Значок списка показывает разделы, щит — цифровые подписи. Щипок для масштаба, перетаскивание для перемещения.",
        "it": "Apri un documento con Leggi PDF o toccane uno tra i file recenti. La lente cerca in tutto il documento: le occorrenze vengono evidenziate sulla pagina e le frecce le scorrono. L’icona a lista mostra le sezioni, lo scudo le firme digitali. Pizzica per ingrandire e trascina per spostarti.",
        "el": "Ανοίξτε ένα έγγραφο με Ανάγνωση PDF ή πατήστε ένα στα πρόσφατα αρχεία. Ο μεγεθυντικός φακός ψάχνει σε όλο το έγγραφο: τα ευρήματα τονίζονται στη σελίδα και τα βέλη σας μετακινούν. Το εικονίδιο λίστας δείχνει τις ενότητες και η ασπίδα τις ψηφιακές υπογραφές.",
        "ar": "افتح مستندًا من «قراءة PDF» أو المس واحدًا في الملفات الأخيرة. تبحث العدسة في المستند كله: تُبرَز النتائج على الصفحة وتنقلك الأسهم بينها. أيقونة القائمة تعرض أقسام المستند، والدرع يعرض التواقيع الرقمية. اقرص للتكبير واسحب للتنقّل.",
        "gl": "Abre un documento con Ler PDF, ou toca un en Ficheiros recentes. A lupa busca en todo o documento: as aparicións quedan resaltadas na páxina e as frechas lévanche dunha a outra. A icona de lista amosa as seccións e o escudo as sinaturas dixitais.",
        "ca": "Obre un document amb Llegeix PDF, o toca’n un a Fitxers recents. La lupa cerca a tot el document: les aparicions queden ressaltades a la pàgina i les fletxes t’hi porten. La icona de llista mostra les seccions i l’escut les signatures digitals.",
        "eu": "Ireki dokumentu bat «Irakurri PDFa» aukerarekin, edo ukitu bat azken fitxategietan. Lupak dokumentu osoan bilatzen du: agerraldiak orrian nabarmentzen dira eta gezien bidez mugitzen zara. Zerrenda-ikonoak atalak erakusten ditu, eta ezkutuak sinadura digitalak.",
    },
    "ayuda_convertir_t": {
        "en": "Converting to Word, Excel or PowerPoint",
        "es": "Convertir a Word, Excel o PowerPoint",
        "fr": "Convertir en Word, Excel ou PowerPoint",
        "de": "In Word, Excel oder PowerPoint umwandeln",
        "zh": "转换为 Word、Excel 或 PowerPoint",
        "ja": "Word・Excel・PowerPoint への変換",
        "ru": "Конвертация в Word, Excel или PowerPoint",
        "it": "Convertire in Word, Excel o PowerPoint",
        "el": "Μετατροπή σε Word, Excel ή PowerPoint",
        "ar": "التحويل إلى Word أو Excel أو PowerPoint",
        "gl": "Converter a Word, Excel ou PowerPoint",
        "ca": "Convertir a Word, Excel o PowerPoint",
        "eu": "Word, Excel edo PowerPoint-era bihurtu",
    },
    "ayuda_convertir_c": {
        "en": "The Convert tool works both ways: pick a Word, Excel or PowerPoint file and it becomes a PDF; pick a PDF and you choose the format to export to. Tables in the PDF are detected and come out as real tables in Word. What you get is the content recomposed as well as possible, not the original Office file: a PDF stores letters placed on a page, not paragraphs or cells.",
        "es": "La herramienta Convertir funciona en los dos sentidos: eliges un Word, Excel o PowerPoint y sale un PDF, o eliges un PDF y decides a qué formato exportarlo. Las tablas del PDF se detectan y salen como tablas de verdad en Word. Lo que obtienes es el contenido recompuesto lo mejor posible, no el documento de Office original: un PDF guarda letras colocadas sobre una página, no párrafos ni celdas.",
        "fr": "L’outil Convertir fonctionne dans les deux sens : choisissez un Word, Excel ou PowerPoint et vous obtenez un PDF ; choisissez un PDF et vous décidez du format de sortie. Les tableaux du PDF sont détectés et deviennent de vrais tableaux dans Word. Ce que vous obtenez est le contenu recomposé au mieux, pas le fichier Office d’origine.",
        "de": "Das Werkzeug Umwandeln funktioniert in beide Richtungen: Wählen Sie eine Word-, Excel- oder PowerPoint-Datei, und es entsteht ein PDF; wählen Sie ein PDF, und Sie bestimmen das Zielformat. Tabellen im PDF werden erkannt und in Word zu echten Tabellen. Sie erhalten den bestmöglich zusammengesetzten Inhalt, nicht die ursprüngliche Office-Datei.",
        "zh": "「转换」工具双向可用：选择 Word、Excel 或 PowerPoint 会生成 PDF；选择 PDF 则由你决定导出格式。PDF 中的表格会被识别，并在 Word 中还原为真正的表格。得到的是尽力还原的内容，而非原始 Office 文件。",
        "ja": "「変換」は双方向です。Word・Excel・PowerPoint を選べば PDF になり、PDF を選べば出力形式を選べます。PDF 内の表は検出され、Word では本物の表になります。得られるのは可能な限り組み直した内容であり、元の Office ファイルそのものではありません。",
        "ru": "Инструмент «Конвертировать» работает в обе стороны: выберите Word, Excel или PowerPoint — получится PDF; выберите PDF — сами укажете формат. Таблицы в PDF распознаются и становятся настоящими таблицами в Word. Вы получаете содержимое, восстановленное как можно точнее, а не исходный файл Office.",
        "it": "Lo strumento Converti funziona in entrambe le direzioni: scegli un Word, Excel o PowerPoint e ottieni un PDF; scegli un PDF e decidi il formato di uscita. Le tabelle del PDF vengono riconosciute e diventano tabelle vere in Word. Ottieni il contenuto ricomposto al meglio, non il file Office originale.",
        "el": "Το εργαλείο Μετατροπή λειτουργεί και προς τις δύο κατευθύνσεις: επιλέγετε Word, Excel ή PowerPoint και προκύπτει PDF· επιλέγετε PDF και ορίζετε τη μορφή εξόδου. Οι πίνακες του PDF αναγνωρίζονται και γίνονται πραγματικοί πίνακες στο Word.",
        "ar": "تعمل أداة التحويل في الاتجاهين: اختر ملف Word أو Excel أو PowerPoint فينتج PDF، أو اختر ملف PDF وحدّد الصيغة. تُكتشف جداول الـ PDF وتخرج جداول حقيقية في Word. ما تحصل عليه هو المحتوى مُعاد تركيبه قدر الإمكان، لا ملف Office الأصلي.",
        "gl": "A ferramenta Converter funciona nos dous sentidos: escolles un Word, Excel ou PowerPoint e sae un PDF, ou escolles un PDF e decides a que formato exportalo. As táboas do PDF detéctanse e saen como táboas de verdade en Word.",
        "ca": "L’eina Converteix funciona en tots dos sentits: tries un Word, Excel o PowerPoint i en surt un PDF, o tries un PDF i decideixes a quin format exportar-lo. Les taules del PDF es detecten i surten com a taules de debò al Word.",
        "eu": "Bihurtu tresnak bi noranzkoetan funtzionatzen du: Word, Excel edo PowerPoint bat aukeratuz gero PDFa sortzen da; PDF bat aukeratuz gero, zuk erabakitzen duzu zein formatutara. PDFko taulak detektatu eta Word-en benetako taula bihurtzen dira.",
    },
    "vis_anterior": {
        "en": "Previous match",
        "es": "Aparición anterior",
        "fr": "Occurrence précédente",
        "de": "Vorheriger Treffer",
        "zh": "上一处匹配",
        "ja": "前の一致",
        "ru": "Предыдущее совпадение",
        "it": "Occorrenza precedente",
        "el": "Προηγούμενο αποτέλεσμα",
        "ar": "النتيجة السابقة",
        "gl": "Aparición anterior",
        "ca": "Aparició anterior",
        "eu": "Aurreko agerraldia",
    },
    "vis_siguiente": {
        "en": "Next match",
        "es": "Aparición siguiente",
        "fr": "Occurrence suivante",
        "de": "Nächster Treffer",
        "zh": "下一处匹配",
        "ja": "次の一致",
        "ru": "Следующее совпадение",
        "it": "Occorrenza successiva",
        "el": "Επόμενο αποτέλεσμα",
        "ar": "النتيجة التالية",
        "gl": "Aparición seguinte",
        "ca": "Aparició següent",
        "eu": "Hurrengo agerraldia",
    },
    "sep_titulo": {
        "en": "Split into parts",
        "es": "Dividir en partes",
        "fr": "Diviser en parties",
        "de": "In Teile aufteilen",
        "zh": "分成多个部分",
        "ja": "パートに分割",
        "ru": "Разделить на части",
        "it": "Dividi in parti",
        "el": "Διαχωρισμός σε μέρη",
        "ar": "التقسيم إلى أجزاء",
        "gl": "Dividir en partes",
        "ca": "Divideix en parts",
        "eu": "Zatitu zatitan",
    },
    "sep_desde": {
        "en": "From",
        "es": "Desde",
        "fr": "De",
        "de": "Von",
        "zh": "起始页",
        "ja": "開始",
        "ru": "С",
        "it": "Da",
        "el": "Από",
        "ar": "من",
        "gl": "Desde",
        "ca": "Des de",
        "eu": "Nondik",
    },
    "sep_hasta": {
        "en": "To",
        "es": "Hasta",
        "fr": "À",
        "de": "Bis",
        "zh": "结束页",
        "ja": "終了",
        "ru": "По",
        "it": "A",
        "el": "Έως",
        "ar": "إلى",
        "gl": "Ata",
        "ca": "Fins a",
        "eu": "Nora",
    },
    "sep_nombre_parte": {
        "en": "File name",
        "es": "Nombre del fichero",
        "fr": "Nom du fichier",
        "de": "Dateiname",
        "zh": "文件名",
        "ja": "ファイル名",
        "ru": "Имя файла",
        "it": "Nome del file",
        "el": "Όνομα αρχείου",
        "ar": "اسم الملف",
        "gl": "Nome do ficheiro",
        "ca": "Nom del fitxer",
        "eu": "Fitxategiaren izena",
    },
    "sep_anadir_parte": {
        "en": "Add a part",
        "es": "Añadir una parte",
        "fr": "Ajouter une partie",
        "de": "Teil hinzufügen",
        "zh": "添加一个部分",
        "ja": "パートを追加",
        "ru": "Добавить часть",
        "it": "Aggiungi una parte",
        "el": "Προσθήκη μέρους",
        "ar": "إضافة جزء",
        "gl": "Engadir unha parte",
        "ca": "Afegeix una part",
        "eu": "Gehitu zati bat",
    },
    "sep_quitar_parte": {
        "en": "Remove this part",
        "es": "Quitar esta parte",
        "fr": "Retirer cette partie",
        "de": "Diesen Teil entfernen",
        "zh": "移除此部分",
        "ja": "このパートを削除",
        "ru": "Убрать эту часть",
        "it": "Rimuovi questa parte",
        "el": "Αφαίρεση μέρους",
        "ar": "إزالة هذا الجزء",
        "gl": "Quitar esta parte",
        "ca": "Treu aquesta part",
        "eu": "Kendu zati hau",
    },
    "doc_separar_partes": {
        "en": "Split into parts…",
        "es": "Dividir en partes…",
        "fr": "Diviser en parties…",
        "de": "In Teile aufteilen…",
        "zh": "分成多个部分…",
        "ja": "パートに分割…",
        "ru": "Разделить на части…",
        "it": "Dividi in parti…",
        "el": "Διαχωρισμός σε μέρη…",
        "ar": "التقسيم إلى أجزاء…",
        "gl": "Dividir en partes…",
        "ca": "Divideix en parts…",
        "eu": "Zatitu zatitan…",
    },
    "rec_ordenar_por": {
        "en": "Sort by",
        "es": "Ordenar por",
        "fr": "Trier par",
        "de": "Sortieren nach",
        "zh": "排序方式",
        "ja": "並べ替え",
        "ru": "Сортировка",
        "it": "Ordina per",
        "el": "Ταξινόμηση κατά",
        "ar": "الترتيب حسب",
        "gl": "Ordenar por",
        "ca": "Ordena per",
        "eu": "Ordenatu honela",
    },
    "rec_orden_recientes": {
        "en": "Most recent",
        "es": "Más recientes",
        "fr": "Plus récents",
        "de": "Neueste zuerst",
        "zh": "最新优先",
        "ja": "新しい順",
        "ru": "Сначала новые",
        "it": "Più recenti",
        "el": "Πιο πρόσφατα",
        "ar": "الأحدث أولًا",
        "gl": "Máis recentes",
        "ca": "Més recents",
        "eu": "Berrienak lehenik",
    },
    "rec_orden_nombre": {
        "en": "Name",
        "es": "Nombre",
        "fr": "Nom",
        "de": "Name",
        "zh": "名称",
        "ja": "名前",
        "ru": "Имя",
        "it": "Nome",
        "el": "Όνομα",
        "ar": "الاسم",
        "gl": "Nome",
        "ca": "Nom",
        "eu": "Izena",
    },
    "rec_orden_tamano": {
        "en": "Size",
        "es": "Tamaño",
        "fr": "Taille",
        "de": "Größe",
        "zh": "大小",
        "ja": "サイズ",
        "ru": "Размер",
        "it": "Dimensione",
        "el": "Μέγεθος",
        "ar": "الحجم",
        "gl": "Tamaño",
        "ca": "Mida",
        "eu": "Tamaina",
    },
    "rec_vista": {
        "en": "Change view",
        "es": "Cambiar la vista",
        "fr": "Changer d’affichage",
        "de": "Ansicht wechseln",
        "zh": "切换视图",
        "ja": "表示を切り替え",
        "ru": "Сменить вид",
        "it": "Cambia vista",
        "el": "Αλλαγή προβολής",
        "ar": "تغيير طريقة العرض",
        "gl": "Cambiar a vista",
        "ca": "Canvia la vista",
        "eu": "Aldatu ikuspegia",
    },
    "comp_pregunta_titulo": {
        "en": "Share this document?",
        "es": "¿Compartir este documento?",
        "fr": "Partager ce document ?",
        "de": "Dieses Dokument teilen?",
        "zh": "要分享这个文档吗？",
        "ja": "この文書を共有しますか？",
        "ru": "Поделиться этим документом?",
        "it": "Condividere questo documento?",
        "el": "Κοινή χρήση αυτού του εγγράφου;",
        "ar": "هل تريد مشاركة هذا المستند؟",
        "gl": "Compartir este documento?",
        "ca": "Vols compartir aquest document?",
        "eu": "Dokumentu hau partekatu?",
    },
    "aj_preguntar_compartir": {
        "en": "Ask to share when a document is ready",
        "es": "Preguntar si compartir al terminar un documento",
        "fr": "Proposer de partager quand un document est prêt",
        "de": "Nach dem Erstellen fragen, ob geteilt werden soll",
        "zh": "文档完成后询问是否分享",
        "ja": "文書ができたら共有するか尋ねる",
        "ru": "Спрашивать о отправке готового документа",
        "it": "Chiedere se condividere quando un documento è pronto",
        "el": "Ερώτηση για κοινή χρήση όταν ένα έγγραφο είναι έτοιμο",
        "ar": "السؤال عن المشاركة عند إتمام مستند",
        "gl": "Preguntar se compartir ao rematar un documento",
        "ca": "Preguntar si compartir en acabar un document",
        "eu": "Galdetu partekatzeko dokumentu bat prest dagoenean",
    },
    "comun_reordenar": {
        "en": "Drag to reorder",
        "es": "Arrastra para reordenar",
        "fr": "Faites glisser pour réordonner",
        "de": "Zum Umsortieren ziehen",
        "zh": "拖动以重新排序",
        "ja": "ドラッグして並べ替え",
        "ru": "Перетащите, чтобы изменить порядок",
        "it": "Trascina per riordinare",
        "el": "Σύρετε για αναδιάταξη",
        "ar": "اسحب لإعادة الترتيب",
        "gl": "Arrastra para reordenar",
        "ca": "Arrossega per reordenar",
        "eu": "Arrastatu berrantolatzeko",
    },
    "color_personalizado": {
        "en": "Custom colour",
        "es": "Color personalizado",
        "fr": "Couleur personnalisée",
        "de": "Eigene Farbe",
        "zh": "自定义颜色",
        "ja": "自由な色",
        "ru": "Свой цвет",
        "it": "Colore personalizzato",
        "el": "Προσαρμοσμένο χρώμα",
        "ar": "لون مخصّص",
        "gl": "Cor personalizada",
        "ca": "Color personalitzat",
        "eu": "Kolore pertsonalizatua",
    },
    # --- Visor, conversor y recientes ----------------------------------------
    "comun_buscar": {
        "en": "Search",
        "es": "Buscar",
        "fr": "Rechercher",
        "de": "Suchen",
        "zh": "搜索",
        "ja": "検索",
        "ru": "Поиск",
        "it": "Cerca",
        "el": "Αναζήτηση",
        "ar": "بحث",
        "gl": "Buscar",
        "ca": "Cerca",
        "eu": "Bilatu",
    },
    "herr_visor_titulo": {
        "en": "Read PDF",
        "es": "Leer PDF",
        "fr": "Lire un PDF",
        "de": "PDF lesen",
        "zh": "阅读 PDF",
        "ja": "PDF を読む",
        "ru": "Читать PDF",
        "it": "Leggi PDF",
        "el": "Ανάγνωση PDF",
        "ar": "قراءة PDF",
        "gl": "Ler PDF",
        "ca": "Llegeix PDF",
        "eu": "Irakurri PDFa",
    },
    "herr_visor_desc": {
        "en": "Read, search and jump around the document",
        "es": "Lee, busca y muévete por el documento",
        "fr": "Lisez, cherchez et naviguez dans le document",
        "de": "Lesen, suchen und im Dokument navigieren",
        "zh": "阅读、搜索并在文档中跳转",
        "ja": "読む、探す、文書内を移動する",
        "ru": "Читайте, ищите и перемещайтесь по документу",
        "it": "Leggi, cerca e spostati nel documento",
        "el": "Διαβάστε, αναζητήστε και πλοηγηθείτε στο έγγραφο",
        "ar": "اقرأ وابحث وتنقّل في المستند",
        "gl": "Le, busca e móvete polo documento",
        "ca": "Llegeix, cerca i mou-te pel document",
        "eu": "Irakurri, bilatu eta mugitu dokumentuan",
    },
    "herr_convertir_titulo": {
        "en": "Convert",
        "es": "Convertir",
        "fr": "Convertir",
        "de": "Umwandeln",
        "zh": "转换",
        "ja": "変換",
        "ru": "Конвертировать",
        "it": "Converti",
        "el": "Μετατροπή",
        "ar": "تحويل",
        "gl": "Converter",
        "ca": "Converteix",
        "eu": "Bihurtu",
    },
    "herr_convertir_desc": {
        "en": "Word, Excel and PowerPoint to PDF, and the other way round",
        "es": "Word, Excel y PowerPoint a PDF, y al revés",
        "fr": "Word, Excel et PowerPoint vers PDF, et l’inverse",
        "de": "Word, Excel und PowerPoint zu PDF und umgekehrt",
        "zh": "Word、Excel、PowerPoint 与 PDF 互转",
        "ja": "Word・Excel・PowerPoint と PDF の相互変換",
        "ru": "Word, Excel и PowerPoint в PDF и обратно",
        "it": "Word, Excel e PowerPoint in PDF, e viceversa",
        "el": "Word, Excel και PowerPoint σε PDF, και αντίστροφα",
        "ar": "من Word و Excel و PowerPoint إلى PDF والعكس",
        "gl": "Word, Excel e PowerPoint a PDF, e ao revés",
        "ca": "Word, Excel i PowerPoint a PDF, i a l’inrevés",
        "eu": "Word, Excel eta PowerPoint PDFra, eta alderantziz",
    },
    "visor_indice": {
        "en": "Contents",
        "es": "Índice",
        "fr": "Sommaire",
        "de": "Inhalt",
        "zh": "目录",
        "ja": "目次",
        "ru": "Оглавление",
        "it": "Indice",
        "el": "Περιεχόμενα",
        "ar": "الفهرس",
        "gl": "Índice",
        "ca": "Índex",
        "eu": "Aurkibidea",
    },
    "visor_sin_indice": {
        "en": "This document has no contents list. Scanned documents usually don’t.",
        "es": "Este documento no trae índice. Los escaneados no suelen tenerlo.",
        "fr": "Ce document n’a pas de sommaire. Les documents numérisés n’en ont généralement pas.",
        "de": "Dieses Dokument hat kein Inhaltsverzeichnis. Gescannte Dokumente meist nicht.",
        "zh": "此文档没有目录。扫描件通常没有。",
        "ja": "この文書に目次はありません。スキャンした文書にはたいてい入っていません。",
        "ru": "В этом документе нет оглавления. У сканов его обычно не бывает.",
        "it": "Questo documento non ha un indice. I documenti scansionati di solito non ce l’hanno.",
        "el": "Αυτό το έγγραφο δεν έχει περιεχόμενα. Τα σαρωμένα συνήθως δεν έχουν.",
        "ar": "لا يحتوي هذا المستند على فهرس. المستندات الممسوحة ضوئيًا عادةً لا تحتوي عليه.",
        "gl": "Este documento non trae índice. Os escaneados non adoitan telo.",
        "ca": "Aquest document no porta índex. Els escanejats no acostumen a tenir-ne.",
        "eu": "Dokumentu honek ez du aurkibiderik. Eskaneatutakoek normalean ez dute.",
    },
    "visor_sin_resultados": {
        "en": "No matches",
        "es": "Sin resultados",
        "fr": "Aucun résultat",
        "de": "Keine Treffer",
        "zh": "没有结果",
        "ja": "見つかりません",
        "ru": "Ничего не найдено",
        "it": "Nessun risultato",
        "el": "Κανένα αποτέλεσμα",
        "ar": "لا نتائج",
        "gl": "Sen resultados",
        "ca": "Cap resultat",
        "eu": "Emaitzarik ez",
    },
    "visor_pagina_numero": {
        "en": "Page %1$d",
        "es": "Página %1$d",
        "fr": "Page %1$d",
        "de": "Seite %1$d",
        "zh": "第 %1$d 页",
        "ja": "%1$d ページ",
        "ru": "Страница %1$d",
        "it": "Pagina %1$d",
        "el": "Σελίδα %1$d",
        "ar": "الصفحة %1$d",
        "gl": "Páxina %1$d",
        "ca": "Pàgina %1$d",
        "eu": "%1$d. orria",
    },
    "conv_elige_destino": {
        "en": "Convert to…",
        "es": "Convertir a…",
        "fr": "Convertir en…",
        "de": "Umwandeln in…",
        "zh": "转换为…",
        "ja": "変換先…",
        "ru": "Конвертировать в…",
        "it": "Converti in…",
        "el": "Μετατροπή σε…",
        "ar": "التحويل إلى…",
        "gl": "Converter a…",
        "ca": "Converteix a…",
        "eu": "Bihurtu hona…",
    },
    # --- Tour guiado ---------------------------------------------------------
    "tour_saltar": {
        "en": "Skip",
        "es": "Saltar",
        "fr": "Passer",
        "de": "Überspringen",
        "zh": "跳过",
        "ja": "スキップ",
        "ru": "Пропустить",
        "it": "Salta",
        "el": "Παράλειψη",
        "ar": "تخطٍّ",
        "gl": "Saltar",
        "ca": "Omet",
        "eu": "Saltatu",
    },
    "tour_siguiente": {
        "en": "Next",
        "es": "Siguiente",
        "fr": "Suivant",
        "de": "Weiter",
        "zh": "下一步",
        "ja": "次へ",
        "ru": "Далее",
        "it": "Avanti",
        "el": "Επόμενο",
        "ar": "التالي",
        "gl": "Seguinte",
        "ca": "Següent",
        "eu": "Hurrengoa",
    },
    "tour_empezar": {
        "en": "Get started",
        "es": "Empezar",
        "fr": "Commencer",
        "de": "Loslegen",
        "zh": "开始使用",
        "ja": "はじめる",
        "ru": "Начать",
        "it": "Iniziamo",
        "el": "Ξεκινάμε",
        "ar": "لنبدأ",
        "gl": "Comezar",
        "ca": "Comencem",
        "eu": "Hasi",
    },
    "tour_ver_otra_vez": {
        "en": "Show the tour again",
        "es": "Ver el tour otra vez",
        "fr": "Revoir la visite guidée",
        "de": "Rundgang erneut ansehen",
        "zh": "重新查看导览",
        "ja": "ツアーをもう一度見る",
        "ru": "Показать обзор снова",
        "it": "Rivedi il tour",
        "el": "Δείτε ξανά την ξενάγηση",
        "ar": "إعادة عرض الجولة",
        "gl": "Ver o tour outra vez",
        "ca": "Torna a veure el tour",
        "eu": "Ikusi bisita berriro",
    },
    # --- Identidad -----------------------------------------------------------
    "app_nombre": dict.fromkeys(IDIOMAS, "NexaPDF"),
    "app_lema": {
        "en": "PDF tools that work offline",
        "es": "Herramientas PDF que funcionan sin conexión",
        "fr": "Des outils PDF qui fonctionnent hors ligne",
        "de": "PDF-Werkzeuge, die offline funktionieren",
        "zh": "离线可用的 PDF 工具",
        "ja": "オフラインで使える PDF ツール",
        "ru": "Инструменты PDF, работающие без интернета",
        "it": "Strumenti PDF che funzionano offline",
        "el": "Εργαλεία PDF που λειτουργούν χωρίς σύνδεση",
        "ar": "أدوات PDF تعمل دون اتصال بالإنترنت",
        "gl": "Ferramentas PDF que funcionan sen conexión",
        "ca": "Eines PDF que funcionen sense connexió",
        "eu": "Konexiorik gabe funtzionatzen duten PDF tresnak",
    },

    # --- Acciones comunes ----------------------------------------------------
    "comun_aceptar": {
        "en": "OK", "es": "Aceptar", "fr": "OK", "de": "OK", "zh": "确定",
        "ja": "OK", "ru": "ОК", "it": "OK", "el": "Εντάξει", "ar": "موافق",
        "gl": "Aceptar", "ca": "D’acord", "eu": "Ados",
    },
    "comun_cancelar": {
        "en": "Cancel", "es": "Cancelar", "fr": "Annuler", "de": "Abbrechen",
        "zh": "取消", "ja": "キャンセル", "ru": "Отмена", "it": "Annulla",
        "el": "Άκυρο", "ar": "إلغاء", "gl": "Cancelar", "ca": "Cancel·la",
        "eu": "Utzi",
    },
    "comun_guardar": {
        "en": "Save", "es": "Guardar", "fr": "Enregistrer", "de": "Speichern",
        "zh": "保存", "ja": "保存", "ru": "Сохранить", "it": "Salva",
        "el": "Αποθήκευση", "ar": "حفظ", "gl": "Gardar", "ca": "Desa",
        "eu": "Gorde",
    },
    "comun_compartir": {
        "en": "Share", "es": "Compartir", "fr": "Partager", "de": "Teilen",
        "zh": "分享", "ja": "共有", "ru": "Поделиться", "it": "Condividi",
        "el": "Κοινοποίηση", "ar": "مشاركة", "gl": "Compartir",
        "ca": "Comparteix", "eu": "Partekatu",
    },
    "comun_eliminar": {
        "en": "Delete", "es": "Eliminar", "fr": "Supprimer", "de": "Löschen",
        "zh": "删除", "ja": "削除", "ru": "Удалить", "it": "Elimina",
        "el": "Διαγραφή", "ar": "حذف", "gl": "Eliminar", "ca": "Elimina",
        "eu": "Ezabatu",
    },
    "comun_deshacer": {
        "en": "Undo", "es": "Deshacer", "fr": "Annuler", "de": "Rückgängig",
        "zh": "撤销", "ja": "元に戻す", "ru": "Отменить", "it": "Annulla",
        "el": "Αναίρεση", "ar": "تراجع", "gl": "Desfacer", "ca": "Desfés",
        "eu": "Desegin",
    },
    "comun_rehacer": {
        "en": "Redo", "es": "Rehacer", "fr": "Rétablir",
        "de": "Wiederholen", "zh": "重做", "ja": "やり直す", "ru": "Вернуть",
        "it": "Ripeti", "el": "Επανάληψη", "ar": "إعادة", "gl": "Refacer",
        "ca": "Refés", "eu": "Berregin",
    },
    "comun_cerrar": {
        "en": "Close", "es": "Cerrar", "fr": "Fermer", "de": "Schließen",
        "zh": "关闭", "ja": "閉じる", "ru": "Закрыть", "it": "Chiudi",
        "el": "Κλείσιμο", "ar": "إغلاق", "gl": "Pechar", "ca": "Tanca",
        "eu": "Itxi",
    },
    "comun_atras": {
        "en": "Back", "es": "Atrás", "fr": "Retour", "de": "Zurück",
        "zh": "返回", "ja": "戻る", "ru": "Назад", "it": "Indietro",
        "el": "Πίσω", "ar": "رجوع", "gl": "Atrás", "ca": "Enrere",
        "eu": "Atzera",
    },
    "comun_hecho": {
        "en": "Done", "es": "Hecho", "fr": "Terminé", "de": "Fertig",
        "zh": "完成", "ja": "完了", "ru": "Готово", "it": "Fatto",
        "el": "Έτοιμο", "ar": "تم", "gl": "Feito", "ca": "Fet", "eu": "Eginda",
    },
    "comun_continuar": {
        "en": "Continue", "es": "Continuar", "fr": "Continuer",
        "de": "Weiter", "zh": "继续", "ja": "続ける", "ru": "Продолжить",
        "it": "Continua", "el": "Συνέχεια", "ar": "متابعة", "gl": "Continuar",
        "ca": "Continua", "eu": "Jarraitu",
    },
    "comun_reintentar": {
        "en": "Retry", "es": "Reintentar", "fr": "Réessayer",
        "de": "Erneut versuchen", "zh": "重试", "ja": "再試行",
        "ru": "Повторить", "it": "Riprova", "el": "Επανάληψη",
        "ar": "إعادة المحاولة", "gl": "Tentar de novo", "ca": "Torna-ho a provar",
        "eu": "Saiatu berriro",
    },
    "comun_seleccionar_todo": {
        "en": "Select all", "es": "Seleccionar todo", "fr": "Tout sélectionner",
        "de": "Alle auswählen", "zh": "全选", "ja": "すべて選択",
        "ru": "Выбрать все", "it": "Seleziona tutto", "el": "Επιλογή όλων",
        "ar": "تحديد الكل", "gl": "Seleccionar todo", "ca": "Selecciona-ho tot",
        "eu": "Hautatu dena",
    },
    "comun_quitar_seleccion": {
        "en": "Clear selection", "es": "Quitar selección",
        "fr": "Effacer la sélection", "de": "Auswahl aufheben", "zh": "取消选择",
        "ja": "選択を解除", "ru": "Снять выделение", "it": "Deseleziona",
        "el": "Καθαρισμός επιλογής", "ar": "إلغاء التحديد",
        "gl": "Quitar selección", "ca": "Treu la selecció",
        "eu": "Kendu hautapena",
    },
    "comun_anadir": {
        "en": "Add", "es": "Añadir", "fr": "Ajouter", "de": "Hinzufügen",
        "zh": "添加", "ja": "追加", "ru": "Добавить", "it": "Aggiungi",
        "el": "Προσθήκη", "ar": "إضافة", "gl": "Engadir", "ca": "Afegeix",
        "eu": "Gehitu",
    },
    "comun_abrir": {
        "en": "Open", "es": "Abrir", "fr": "Ouvrir", "de": "Öffnen",
        "zh": "打开", "ja": "開く", "ru": "Открыть", "it": "Apri",
        "el": "Άνοιγμα", "ar": "فتح", "gl": "Abrir", "ca": "Obre", "eu": "Ireki",
    },
    "comun_procesando": {
        "en": "Working…", "es": "Procesando…", "fr": "Traitement…",
        "de": "Wird verarbeitet…", "zh": "处理中…", "ja": "処理中…",
        "ru": "Обработка…", "it": "Elaborazione…", "el": "Επεξεργασία…",
        "ar": "جارٍ المعالجة…", "gl": "Procesando…", "ca": "S’està processant…",
        "eu": "Prozesatzen…",
    },
    "comun_sin_titulo": {
        "en": "Untitled", "es": "Sin título", "fr": "Sans titre",
        "de": "Ohne Titel", "zh": "无标题", "ja": "無題", "ru": "Без названия",
        "it": "Senza titolo", "el": "Χωρίς τίτλο", "ar": "بدون عنوان",
        "gl": "Sen título", "ca": "Sense títol", "eu": "Izenbururik gabe",
    },

    # --- Pantalla de inicio --------------------------------------------------
    "inicio_herramientas": {
        "en": "Tools", "es": "Herramientas", "fr": "Outils", "de": "Werkzeuge",
        "zh": "工具", "ja": "ツール", "ru": "Инструменты", "it": "Strumenti",
        "el": "Εργαλεία", "ar": "الأدوات", "gl": "Ferramentas", "ca": "Eines",
        "eu": "Tresnak",
    },
    "herr_unir_titulo": {
        "en": "Merge PDFs", "es": "Unir PDF", "fr": "Fusionner des PDF",
        "de": "PDFs zusammenfügen", "zh": "合并 PDF", "ja": "PDF を結合",
        "ru": "Объединить PDF", "it": "Unisci PDF", "el": "Συγχώνευση PDF",
        "ar": "دمج ملفات PDF", "gl": "Unir PDF", "ca": "Uneix PDF",
        "eu": "Batu PDFak",
    },
    "herr_unir_desc": {
        "en": "Join several documents into one",
        "es": "Junta varios documentos en uno",
        "fr": "Réunir plusieurs documents en un seul",
        "de": "Mehrere Dokumente zu einem verbinden",
        "zh": "将多个文档合并为一个",
        "ja": "複数の文書を 1 つにまとめます",
        "ru": "Объедините несколько документов в один",
        "it": "Unisci più documenti in uno solo",
        "el": "Ενώστε πολλά έγγραφα σε ένα",
        "ar": "اجمع عدة مستندات في مستند واحد",
        "gl": "Xunta varios documentos nun só",
        "ca": "Ajunta diversos documents en un de sol",
        "eu": "Elkartu hainbat dokumentu bakarrean",
    },
    "herr_separar_titulo": {
        "en": "Split PDF", "es": "Separar PDF", "fr": "Diviser un PDF",
        "de": "PDF teilen", "zh": "拆分 PDF", "ja": "PDF を分割",
        "ru": "Разделить PDF", "it": "Dividi PDF", "el": "Διαχωρισμός PDF",
        "ar": "تقسيم ملف PDF", "gl": "Separar PDF", "ca": "Divideix PDF",
        "eu": "Zatitu PDFa",
    },
    "herr_separar_desc": {
        "en": "Extract pages or split into files",
        "es": "Extrae páginas o divide en ficheros",
        "fr": "Extraire des pages ou séparer en fichiers",
        "de": "Seiten entnehmen oder in Dateien aufteilen",
        "zh": "提取页面或拆分为多个文件",
        "ja": "ページを取り出す、またはファイルに分割します",
        "ru": "Извлеките страницы или разделите на файлы",
        "it": "Estrai pagine o dividi in file",
        "el": "Εξαγωγή σελίδων ή διαχωρισμός σε αρχεία",
        "ar": "استخرج صفحات أو قسّم إلى ملفات",
        "gl": "Extrae páxinas ou divide en ficheiros",
        "ca": "Extreu pàgines o divideix en fitxers",
        "eu": "Atera orriak edo zatitu fitxategitan",
    },
    "herr_imagen_titulo": {
        "en": "Image to PDF", "es": "Imagen a PDF", "fr": "Image en PDF",
        "de": "Bild zu PDF", "zh": "图片转 PDF", "ja": "画像を PDF に",
        "ru": "Изображение в PDF", "it": "Immagine in PDF",
        "el": "Εικόνα σε PDF", "ar": "صورة إلى PDF", "gl": "Imaxe a PDF",
        "ca": "Imatge a PDF", "eu": "Irudia PDF bihurtu",
    },
    "herr_imagen_desc": {
        "en": "Turn one photo into a document",
        "es": "Convierte una foto en un documento",
        "fr": "Transformer une photo en document",
        "de": "Ein Foto in ein Dokument verwandeln",
        "zh": "把一张照片变成文档",
        "ja": "写真 1 枚を文書にします",
        "ru": "Превратите фото в документ",
        "it": "Trasforma una foto in un documento",
        "el": "Μετατρέψτε μια φωτογραφία σε έγγραφο",
        "ar": "حوّل صورة واحدة إلى مستند",
        "gl": "Converte unha foto nun documento",
        "ca": "Converteix una foto en un document",
        "eu": "Bihurtu argazki bat dokumentu",
    },
    "herr_varias_imagenes_titulo": {
        "en": "Images to PDF", "es": "Imágenes a PDF", "fr": "Images en PDF",
        "de": "Bilder zu PDF", "zh": "多张图片转 PDF",
        "ja": "複数の画像を PDF に", "ru": "Изображения в PDF",
        "it": "Immagini in PDF", "el": "Εικόνες σε PDF",
        "ar": "صور إلى PDF", "gl": "Imaxes a PDF", "ca": "Imatges a PDF",
        "eu": "Irudiak PDF bihurtu",
    },
    "herr_varias_imagenes_desc": {
        "en": "One per page, or several together",
        "es": "Una por página, o varias juntas",
        "fr": "Une par page, ou plusieurs ensemble",
        "de": "Eins pro Seite oder mehrere zusammen",
        "zh": "每页一张，或多张排在一起",
        "ja": "1 ページに 1 枚、または複数まとめて",
        "ru": "По одному на страницу или несколько вместе",
        "it": "Una per pagina, o più insieme",
        "el": "Μία ανά σελίδα ή πολλές μαζί",
        "ar": "واحدة في كل صفحة أو عدة معًا",
        "gl": "Unha por páxina, ou varias xuntas",
        "ca": "Una per pàgina, o diverses juntes",
        "eu": "Bat orriko, edo hainbat elkarrekin",
    },
    "herr_editar_titulo": {
        "en": "Edit PDF", "es": "Editar PDF", "fr": "Modifier un PDF",
        "de": "PDF bearbeiten", "zh": "编辑 PDF", "ja": "PDF を編集",
        "ru": "Редактировать PDF", "it": "Modifica PDF",
        "el": "Επεξεργασία PDF", "ar": "تحرير PDF", "gl": "Editar PDF",
        "ca": "Edita PDF", "eu": "Editatu PDFa",
    },
    "herr_editar_desc": {
        "en": "Draw, add text, shapes and images",
        "es": "Dibuja, añade texto, formas e imágenes",
        "fr": "Dessiner, ajouter du texte, des formes et des images",
        "de": "Zeichnen, Text, Formen und Bilder hinzufügen",
        "zh": "涂画、添加文字、形状和图片",
        "ja": "手書き、文字、図形、画像を追加します",
        "ru": "Рисуйте, добавляйте текст, фигуры и изображения",
        "it": "Disegna, aggiungi testo, forme e immagini",
        "el": "Σχεδιάστε, προσθέστε κείμενο, σχήματα και εικόνες",
        "ar": "ارسم وأضف نصًا وأشكالًا وصورًا",
        "gl": "Debuxa, engade texto, formas e imaxes",
        "ca": "Dibuixa, afegeix text, formes i imatges",
        "eu": "Marraztu, gehitu testua, formak eta irudiak",
    },
    "herr_firmar_titulo": {
        "en": "Sign PDF", "es": "Firmar PDF", "fr": "Signer un PDF",
        "de": "PDF unterschreiben", "zh": "签署 PDF", "ja": "PDF に署名",
        "ru": "Подписать PDF", "it": "Firma PDF", "el": "Υπογραφή PDF",
        "ar": "توقيع PDF", "gl": "Asinar PDF", "ca": "Signa PDF",
        "eu": "Sinatu PDFa",
    },
    "herr_firmar_desc": {
        "en": "By hand or with your certificate",
        "es": "A mano o con tu certificado",
        "fr": "À la main ou avec votre certificat",
        "de": "Handschriftlich oder mit Zertifikat",
        "zh": "手写签名或使用证书",
        "ja": "手書き、または証明書で署名します",
        "ru": "От руки или сертификатом",
        "it": "A mano o con il tuo certificato",
        "el": "Με το χέρι ή με το πιστοποιητικό σας",
        "ar": "بخط اليد أو باستخدام شهادتك",
        "gl": "A man ou co teu certificado",
        "ca": "A mà o amb el teu certificat",
        "eu": "Eskuz edo zure ziurtagiriarekin",
    },
    "inicio_recientes": {
        "en": "Recent files", "es": "Ficheros recientes",
        "fr": "Fichiers récents", "de": "Zuletzt erstellt", "zh": "最近的文件",
        "ja": "最近のファイル", "ru": "Недавние файлы", "it": "File recenti",
        "el": "Πρόσφατα αρχεία", "ar": "الملفات الأخيرة",
        "gl": "Ficheiros recentes", "ca": "Fitxers recents",
        "eu": "Azken fitxategiak",
    },
    "inicio_sin_recientes": {
        "en": "Nothing here yet", "es": "Aún no hay nada aquí",
        "fr": "Rien pour l’instant", "de": "Noch nichts vorhanden",
        "zh": "这里还没有内容", "ja": "まだ何もありません", "ru": "Пока пусто",
        "it": "Ancora niente qui", "el": "Δεν υπάρχει τίποτα ακόμη",
        "ar": "لا يوجد شيء بعد", "gl": "Aínda non hai nada aquí",
        "ca": "Encara no hi ha res", "eu": "Oraindik ez dago ezer",
    },
    "inicio_sin_recientes_ayuda": {
        "en": "The documents you create will show up here.",
        "es": "Los documentos que crees aparecerán aquí.",
        "fr": "Les documents que vous créez apparaîtront ici.",
        "de": "Erstellte Dokumente erscheinen hier.",
        "zh": "你创建的文档会出现在这里。",
        "ja": "作成した文書がここに表示されます。",
        "ru": "Созданные документы появятся здесь.",
        "it": "I documenti che crei compariranno qui.",
        "el": "Τα έγγραφα που δημιουργείτε θα εμφανίζονται εδώ.",
        "ar": "ستظهر هنا المستندات التي تنشئها.",
        "gl": "Os documentos que crees aparecerán aquí.",
        "ca": "Els documents que creïs apareixeran aquí.",
        "eu": "Sortzen dituzun dokumentuak hemen agertuko dira.",
    },
}
