#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Textos de Ayuda, Acerca de, donacion, accesibilidad y plurales."""

TEXTOS = {
    # --- Ayuda ---------------------------------------------------------------
    "ayuda_titulo": {
        "en": "Help", "es": "Ayuda", "fr": "Aide", "de": "Hilfe",
        "zh": "帮助", "ja": "ヘルプ", "ru": "Справка", "it": "Aiuto",
        "el": "Βοήθεια", "ar": "المساعدة", "gl": "Axuda", "ca": "Ajuda",
        "eu": "Laguntza",
    },
    "ayuda_que_es_t": {
        "en": "What is NexaPDF?", "es": "¿Qué es NexaPDF?",
        "fr": "Qu’est-ce que NexaPDF ?", "de": "Was ist NexaPDF?",
        "zh": "NexaPDF 是什么？", "ja": "NexaPDF とは？",
        "ru": "Что такое NexaPDF?", "it": "Che cos’è NexaPDF?",
        "el": "Τι είναι το NexaPDF;", "ar": "ما هو NexaPDF؟",
        "gl": "Que é NexaPDF?", "ca": "Què és NexaPDF?",
        "eu": "Zer da NexaPDF?",
    },
    "ayuda_que_es_c": {
        "en": "A toolbox for PDFs that runs entirely on your phone. Merge, split, turn photos into documents, draw and write on pages, and sign. No account, no internet, no ads.",
        "es": "Una caja de herramientas para PDF que funciona entera en tu móvil. Unir, separar, convertir fotos en documentos, dibujar y escribir sobre las páginas, y firmar. Sin cuenta, sin internet y sin anuncios.",
        "fr": "Une boîte à outils PDF qui fonctionne entièrement sur votre téléphone. Fusionner, diviser, transformer des photos en documents, dessiner et écrire sur les pages, et signer. Sans compte, sans internet, sans publicité.",
        "de": "Ein PDF-Werkzeugkasten, der vollständig auf Ihrem Handy läuft. Zusammenfügen, teilen, Fotos in Dokumente verwandeln, auf Seiten zeichnen und schreiben, unterschreiben. Ohne Konto, ohne Internet, ohne Werbung.",
        "zh": "一套完全在手机上运行的 PDF 工具。合并、拆分、把照片变成文档、在页面上涂画和书写、签署。无需账号、无需联网、没有广告。",
        "ja": "すべて端末内で動く PDF の道具箱です。結合、分割、写真を文書に変換、ページへの手書きや文字入力、署名ができます。アカウント不要、インターネット不要、広告なし。",
        "ru": "Набор инструментов для PDF, работающий целиком на телефоне. Объединение, разделение, превращение фото в документы, рисование и надписи на страницах, подпись. Без аккаунта, без интернета, без рекламы.",
        "it": "Una cassetta degli attrezzi per PDF che gira interamente sul telefono. Unire, dividere, trasformare foto in documenti, disegnare e scrivere sulle pagine, firmare. Senza account, senza internet, senza pubblicità.",
        "el": "Μια εργαλειοθήκη για PDF που τρέχει εξ ολοκλήρου στο κινητό σας. Συγχώνευση, διαχωρισμός, μετατροπή φωτογραφιών σε έγγραφα, σχεδίαση και γραφή στις σελίδες, υπογραφή. Χωρίς λογαριασμό, χωρίς διαδίκτυο, χωρίς διαφημίσεις.",
        "ar": "صندوق أدوات لملفات PDF يعمل بالكامل على هاتفك. الدمج والتقسيم وتحويل الصور إلى مستندات والرسم والكتابة على الصفحات والتوقيع. بلا حساب ولا إنترنت ولا إعلانات.",
        "gl": "Unha caixa de ferramentas para PDF que funciona enteira no teu móbil. Unir, separar, converter fotos en documentos, debuxar e escribir sobre as páxinas, e asinar. Sen conta, sen internet e sen anuncios.",
        "ca": "Una caixa d’eines per a PDF que funciona sencera al teu mòbil. Unir, dividir, convertir fotos en documents, dibuixar i escriure sobre les pàgines, i signar. Sense compte, sense internet i sense anuncis.",
        "eu": "PDFetarako tresna-kutxa bat, osorik zure mugikorrean dabilena. Batu, zatitu, argazkiak dokumentu bihurtu, orrialdeetan marraztu eta idatzi, eta sinatu. Konturik gabe, internetik gabe eta iragarkirik gabe.",
    },
    "ayuda_privacidad_t": {
        "en": "Where do my documents go?", "es": "¿A dónde van mis documentos?",
        "fr": "Où vont mes documents ?", "de": "Wohin gehen meine Dokumente?",
        "zh": "我的文档会去哪里？", "ja": "文書はどこへ行きますか？",
        "ru": "Куда попадают мои документы?", "it": "Dove finiscono i miei documenti?",
        "el": "Πού πηγαίνουν τα έγγραφά μου;", "ar": "إلى أين تذهب مستنداتي؟",
        "gl": "A onde van os meus documentos?", "ca": "On van els meus documents?",
        "eu": "Nora doaz nire dokumentuak?",
    },
    "ayuda_privacidad_c": {
        "en": "Nowhere. NexaPDF has no internet permission at all, so it cannot send anything even by mistake. Everything happens inside your device, and the results are saved to Downloads/NexaPDF.",
        "es": "A ningún sitio. NexaPDF no tiene ni permiso de internet, así que no puede enviar nada ni por error. Todo ocurre dentro de tu dispositivo, y los resultados se guardan en Descargas/NexaPDF.",
        "fr": "Nulle part. NexaPDF n’a même pas la permission d’accès à internet, il ne peut donc rien envoyer, même par erreur. Tout se passe sur votre appareil et les résultats sont enregistrés dans Téléchargements/NexaPDF.",
        "de": "Nirgendwohin. NexaPDF hat nicht einmal die Internetberechtigung und kann daher nichts versenden, auch nicht versehentlich. Alles geschieht auf Ihrem Gerät, die Ergebnisse landen in Downloads/NexaPDF.",
        "zh": "哪儿也不去。NexaPDF 连联网权限都没有，因此即使出错也无法发送任何内容。一切都在你的设备内完成，结果保存在“下载/NexaPDF”。",
        "ja": "どこにも行きません。NexaPDF はインターネット権限すら持たないため、誤ってでも送信できません。すべて端末内で処理され、結果は「ダウンロード/NexaPDF」に保存されます。",
        "ru": "Никуда. У NexaPDF нет даже разрешения на доступ в интернет, поэтому он не может ничего отправить даже по ошибке. Всё происходит на устройстве, а результаты сохраняются в «Загрузки/NexaPDF».",
        "it": "Da nessuna parte. NexaPDF non ha nemmeno il permesso di accedere a internet, quindi non può inviare nulla nemmeno per sbaglio. Tutto avviene sul tuo dispositivo e i risultati vanno in Download/NexaPDF.",
        "el": "Πουθενά. Το NexaPDF δεν έχει καν άδεια πρόσβασης στο διαδίκτυο, οπότε δεν μπορεί να στείλει τίποτα ούτε κατά λάθος. Όλα γίνονται στη συσκευή σας και τα αποτελέσματα αποθηκεύονται στο Λήψεις/NexaPDF.",
        "ar": "إلى لا مكان. لا يملك NexaPDF حتى إذن الوصول إلى الإنترنت، فلا يستطيع إرسال أي شيء ولو بالخطأ. كل شيء يجري داخل جهازك، وتُحفظ النتائج في التنزيلات/NexaPDF.",
        "gl": "A ningún sitio. NexaPDF non ten nin permiso de internet, así que non pode enviar nada nin por erro. Todo ocorre dentro do teu dispositivo, e os resultados gárdanse en Descargas/NexaPDF.",
        "ca": "Enlloc. NexaPDF no té ni permís d’internet, així que no pot enviar res ni per error. Tot passa dins del teu dispositiu i els resultats es desen a Baixades/NexaPDF.",
        "eu": "Inora ez. NexaPDFek ez du interneteko baimenik ere, beraz ezin du ezer bidali, ezta akatsez ere. Dena zure gailuaren barruan gertatzen da, eta emaitzak Deskargak/NexaPDF karpetan gordetzen dira.",
    },
    "ayuda_editar_t": {
        "en": "Can I change the text of a PDF?",
        "es": "¿Puedo cambiar el texto de un PDF?",
        "fr": "Puis-je modifier le texte d’un PDF ?",
        "de": "Kann ich den Text eines PDFs ändern?",
        "zh": "我可以修改 PDF 里的文字吗？",
        "ja": "PDF の文字を変更できますか？",
        "ru": "Можно ли изменить текст PDF?",
        "it": "Posso cambiare il testo di un PDF?",
        "el": "Μπορώ να αλλάξω το κείμενο ενός PDF;",
        "ar": "هل يمكنني تغيير نص ملف PDF؟",
        "gl": "Podo cambiar o texto dun PDF?",
        "ca": "Puc canviar el text d’un PDF?",
        "eu": "PDF baten testua alda dezaket?",
    },
    "ayuda_editar_c": {
        "en": "Yes, line by line. Pick the text tool and tap a line: NexaPDF covers the old line and writes yours in its place, as real selectable text. It does not reflow the rest of the paragraph, because a PDF stores fixed positions rather than a flowing document.",
        "es": "Sí, línea a línea. Elige la herramienta de texto y toca una línea: NexaPDF tapa la antigua y escribe la tuya en su lugar, como texto real y seleccionable. No recoloca el resto del párrafo, porque un PDF guarda posiciones fijas y no un documento que fluya.",
        "fr": "Oui, ligne par ligne. Choisissez l’outil texte et touchez une ligne : NexaPDF masque l’ancienne et écrit la vôtre à la place, en vrai texte sélectionnable. Le reste du paragraphe n’est pas réagencé, car un PDF enregistre des positions fixes et non un document qui s’écoule.",
        "de": "Ja, Zeile für Zeile. Wählen Sie das Textwerkzeug und tippen Sie auf eine Zeile: NexaPDF deckt die alte ab und schreibt Ihre an ihre Stelle, als echten markierbaren Text. Der Rest des Absatzes wird nicht neu umbrochen, denn ein PDF speichert feste Positionen statt eines fließenden Dokuments.",
        "zh": "可以，逐行修改。选择文字工具并点按某一行：NexaPDF 会遮住原来那行，并在原位写上你的文字，是可选取的真实文字。它不会重排段落其余部分，因为 PDF 保存的是固定位置，而不是可回流的文档。",
        "ja": "はい、行単位で можно。テキストツールを選んで行をタップすると、NexaPDF が元の行を覆い、その位置にあなたの文字を選択可能な本物のテキストとして書きます。段落全体の再配置は行いません。PDF は流し込みではなく固定位置を保存する形式だからです。",
        "ru": "Да, построчно. Выберите инструмент текста и коснитесь строки: NexaPDF закроет старую и напишет вашу на её месте настоящим выделяемым текстом. Остальной абзац не перекомпоновывается, потому что PDF хранит фиксированные позиции, а не текущий текст.",
        "it": "Sì, riga per riga. Scegli lo strumento testo e tocca una riga: NexaPDF copre quella vecchia e scrive la tua al suo posto, come testo reale e selezionabile. Non ricompone il resto del paragrafo, perché un PDF salva posizioni fisse e non un documento che scorre.",
        "el": "Ναι, γραμμή προς γραμμή. Επιλέξτε το εργαλείο κειμένου και πατήστε μια γραμμή: το NexaPDF καλύπτει την παλιά και γράφει τη δική σας στη θέση της, ως πραγματικό κείμενο που επιλέγεται. Δεν αναδιατάσσει την υπόλοιπη παράγραφο, γιατί ένα PDF αποθηκεύει σταθερές θέσεις και όχι κείμενο που ρέει.",
        "ar": "نعم، سطرًا بسطر. اختر أداة النص والمس سطرًا: يغطي NexaPDF السطر القديم ويكتب نصك مكانه كنص حقيقي قابل للتحديد. لا يعيد ترتيب بقية الفقرة، لأن ملف PDF يخزّن مواضع ثابتة لا نصًا متدفقًا.",
        "gl": "Si, liña a liña. Escolle a ferramenta de texto e toca unha liña: NexaPDF tapa a antiga e escribe a túa no seu lugar, como texto real e seleccionable. Non recoloca o resto do parágrafo, porque un PDF garda posicións fixas e non un documento que flúa.",
        "ca": "Sí, línia a línia. Tria l’eina de text i toca una línia: NexaPDF tapa l’antiga i escriu la teva al seu lloc, com a text real i seleccionable. No recol·loca la resta del paràgraf, perquè un PDF desa posicions fixes i no un document que flueixi.",
        "eu": "Bai, lerroz lerro. Aukeratu testu-tresna eta ukitu lerro bat: NexaPDFek zaharra estali eta zurea idazten du haren lekuan, hautagarria den benetako testu gisa. Ez du gainerako paragrafoa berrantolatzen, PDF batek kokapen finkoak gordetzen baititu, ez testu jarraitua.",
    },
    "ayuda_firmar_t": {
        "en": "Which signature should I use?", "es": "¿Qué firma debo usar?",
        "fr": "Quelle signature utiliser ?", "de": "Welche Signatur soll ich nutzen?",
        "zh": "我该用哪种签名？", "ja": "どちらの署名を使えばいい？",
        "ru": "Какую подпись использовать?", "it": "Quale firma devo usare?",
        "el": "Ποια υπογραφή να χρησιμοποιήσω;", "ar": "أي توقيع ينبغي أن أستخدم؟",
        "gl": "Que sinatura debo usar?", "ca": "Quina signatura he de fer servir?",
        "eu": "Zein sinadura erabili behar dut?",
    },
    "ayuda_firmar_c": {
        "en": "The handwritten one is a drawing on the page: fine for a delivery note or an internal form. The certificate one uses your .p12 or .pfx file and lets any reader verify that the document has not changed since you signed it: that is the one for anything official.",
        "es": "La manuscrita es un dibujo sobre la página: vale para un albarán o un formulario interno. La de certificado usa tu fichero .p12 o .pfx y permite que cualquier lector compruebe que el documento no ha cambiado desde que lo firmaste: esa es la que sirve para lo oficial.",
        "fr": "La manuscrite est un dessin sur la page : suffisante pour un bon de livraison ou un formulaire interne. Celle par certificat utilise votre fichier .p12 ou .pfx et permet à tout lecteur de vérifier que le document n’a pas changé depuis la signature : c’est celle qui convient pour l’officiel.",
        "de": "Die handschriftliche ist eine Zeichnung auf der Seite: gut für einen Lieferschein oder ein internes Formular. Die mit Zertifikat nutzt Ihre .p12- oder .pfx-Datei und lässt jeden prüfen, dass sich das Dokument seit der Unterschrift nicht geändert hat: die ist für Offizielles.",
        "zh": "手写签名只是画在页面上的图形，适合送货单或内部表单。证书签名使用你的 .p12 或 .pfx 文件，让任何阅读者都能验证文档自签署后未被更改，正式场合应使用它。",
        "ja": "手書きはページ上の絵にすぎず、納品書や社内書類には十分です。証明書による署名は .p12 や .pfx を使い、署名後に文書が変更されていないことを誰でも検証できます。公式な用途にはこちらを使ってください。",
        "ru": "Рукописная — это рисунок на странице: подойдёт для накладной или внутренней формы. Подпись сертификатом использует ваш файл .p12 или .pfx и позволяет любому убедиться, что документ не менялся после подписания: она нужна для официальных случаев.",
        "it": "Quella autografa è un disegno sulla pagina: va bene per una bolla o un modulo interno. Quella con certificato usa il tuo file .p12 o .pfx e permette a chiunque di verificare che il documento non sia cambiato dopo la firma: è quella per le cose ufficiali.",
        "el": "Η χειρόγραφη είναι ένα σχέδιο πάνω στη σελίδα: αρκεί για ένα δελτίο αποστολής ή μια εσωτερική φόρμα. Η υπογραφή με πιστοποιητικό χρησιμοποιεί το αρχείο .p12 ή .pfx και επιτρέπει σε οποιονδήποτε να επαληθεύσει ότι το έγγραφο δεν άλλαξε: αυτή χρειάζεται για τα επίσημα.",
        "ar": "التوقيع بخط اليد مجرد رسم على الصفحة، ويكفي لإذن تسليم أو نموذج داخلي. أما التوقيع بالشهادة فيستخدم ملف ‎.p12 أو ‎.pfx ويتيح لأي قارئ التحقق من أن المستند لم يتغيّر بعد توقيعه، وهو المناسب للأمور الرسمية.",
        "gl": "A manuscrita é un debuxo sobre a páxina: vale para un albará ou un formulario interno. A de certificado usa o teu ficheiro .p12 ou .pfx e permite que calquera lector comprobe que o documento non cambiou desde que o asinaches: esa é a que serve para o oficial.",
        "ca": "La manuscrita és un dibuix sobre la pàgina: serveix per a un albarà o un formulari intern. La de certificat fa servir el teu fitxer .p12 o .pfx i permet que qualsevol lector comprovi que el document no ha canviat des que el vas signar: aquesta és la que serveix per a l’oficial.",
        "eu": "Eskuz idatzitakoa orriaren gaineko marrazki bat da: nahikoa albaran baterako edo barne-inprimaki baterako. Ziurtagiriarekikoak zure .p12 edo .pfx fitxategia erabiltzen du eta edonork egiaztatu dezake dokumentua ez dela aldatu sinatu zenuenetik: hori da ofizialerako balio duena.",
    },
    "ayuda_donde_t": {
        "en": "Where are the files I create?",
        "es": "¿Dónde están los ficheros que creo?",
        "fr": "Où sont les fichiers que je crée ?",
        "de": "Wo sind die erstellten Dateien?",
        "zh": "我创建的文件在哪里？", "ja": "作成したファイルはどこ？",
        "ru": "Где созданные файлы?", "it": "Dove sono i file che creo?",
        "el": "Πού βρίσκονται τα αρχεία που δημιουργώ;",
        "ar": "أين الملفات التي أنشئها؟",
        "gl": "Onde están os ficheiros que creo?",
        "ca": "On són els fitxers que creo?",
        "eu": "Non daude sortzen ditudan fitxategiak?",
    },
    "ayuda_donde_c": {
        "en": "In the Downloads/NexaPDF folder of your phone, where any file manager or app can open them. From the app you can also share them or save a copy wherever you like.",
        "es": "En la carpeta Descargas/NexaPDF de tu móvil, donde cualquier gestor de archivos o app puede abrirlos. Desde la app también puedes compartirlos o guardar una copia donde quieras.",
        "fr": "Dans le dossier Téléchargements/NexaPDF de votre téléphone, où tout gestionnaire de fichiers peut les ouvrir. Depuis l’appli, vous pouvez aussi les partager ou en enregistrer une copie où vous voulez.",
        "de": "Im Ordner Downloads/NexaPDF Ihres Handys, wo jede Datei-App sie öffnen kann. In der App können Sie sie auch teilen oder eine Kopie beliebig speichern.",
        "zh": "在手机的“下载/NexaPDF”文件夹里，任何文件管理器或应用都能打开。在应用内你也可以分享它们，或另存到任意位置。",
        "ja": "端末の「ダウンロード/NexaPDF」フォルダにあり、どのファイル管理アプリからでも開けます。アプリ内から共有したり、好きな場所にコピーを保存したりもできます。",
        "ru": "В папке «Загрузки/NexaPDF» вашего телефона — их откроет любой файловый менеджер. Из приложения их также можно отправить или сохранить копию куда угодно.",
        "it": "Nella cartella Download/NexaPDF del telefono, dove qualsiasi gestore di file può aprirli. Dall’app puoi anche condividerli o salvarne una copia dove preferisci.",
        "el": "Στον φάκελο Λήψεις/NexaPDF του κινητού σας, όπου μπορεί να τα ανοίξει οποιαδήποτε εφαρμογή αρχείων. Από την εφαρμογή μπορείτε επίσης να τα μοιραστείτε ή να αποθηκεύσετε αντίγραφο όπου θέλετε.",
        "ar": "في مجلد التنزيلات/NexaPDF على هاتفك، حيث يمكن لأي مدير ملفات فتحها. ومن داخل التطبيق يمكنك أيضًا مشاركتها أو حفظ نسخة حيث تشاء.",
        "gl": "Na carpeta Descargas/NexaPDF do teu móbil, onde calquera xestor de ficheiros pode abrilos. Desde a app tamén podes compartilos ou gardar unha copia onde queiras.",
        "ca": "A la carpeta Baixades/NexaPDF del teu mòbil, on qualsevol gestor de fitxers els pot obrir. Des de l’aplicació també els pots compartir o desar-ne una còpia on vulguis.",
        "eu": "Zure mugikorreko Deskargak/NexaPDF karpetan, edozein fitxategi-kudeatzailek ireki ditzake. Aplikaziotik ere parteka ditzakezu edo kopia bat nahi duzun lekuan gorde.",
    },
    "ayuda_problemas_t": {
        "en": "Something is not working", "es": "Algo no funciona",
        "fr": "Quelque chose ne marche pas", "de": "Etwas funktioniert nicht",
        "zh": "有些功能不正常", "ja": "うまく動かないとき",
        "ru": "Что-то не работает", "it": "Qualcosa non funziona",
        "el": "Κάτι δεν λειτουργεί", "ar": "هناك شيء لا يعمل",
        "gl": "Algo non funciona", "ca": "Alguna cosa no funciona",
        "eu": "Zerbaitek ez du funtzionatzen",
    },
    "ayuda_problemas_c": {
        "en": "If a document will not open, it may be damaged or protected: try opening it in another reader first. If the app runs out of memory with a very large file, split it into parts and work on them one at a time. For anything else, write to %1$s and say what you were doing.",
        "es": "Si un documento no abre, puede estar dañado o protegido: prueba a abrirlo antes en otro lector. Si la app se queda sin memoria con un fichero muy grande, sepáralo en partes y trabájalas de una en una. Para cualquier otra cosa, escribe a %1$s contando qué estabas haciendo.",
        "fr": "Si un document ne s’ouvre pas, il est peut-être endommagé ou protégé : essayez d’abord un autre lecteur. Si l’appli manque de mémoire sur un très gros fichier, divisez-le et traitez les parties une par une. Pour le reste, écrivez à %1$s en indiquant ce que vous faisiez.",
        "de": "Lässt sich ein Dokument nicht öffnen, ist es vielleicht beschädigt oder geschützt: probieren Sie es zuerst in einem anderen Betrachter. Geht der App bei sehr großen Dateien der Speicher aus, teilen Sie sie auf und bearbeiten Sie die Teile einzeln. Für alles andere schreiben Sie an %1$s und schildern Sie, was Sie gerade taten.",
        "zh": "如果文档打不开，可能已损坏或受保护：先试试用别的阅读器打开。如果处理超大文件时内存不足，请先拆分再逐个处理。其他问题请写信到 %1$s，并说明你当时在做什么。",
        "ja": "文書が開かない場合は、壊れているか保護されている可能性があります。まず別のビューアで試してください。とても大きなファイルでメモリが足りなくなるときは、分割して 1 つずつ処理してください。それ以外は %1$s まで、何をしていたか添えてご連絡ください。",
        "ru": "Если документ не открывается, он может быть повреждён или защищён: попробуйте сначала другой просмотрщик. Если приложению не хватает памяти на очень большом файле, разделите его и работайте с частями по очереди. По остальным вопросам напишите на %1$s и опишите, что вы делали.",
        "it": "Se un documento non si apre, potrebbe essere danneggiato o protetto: prova prima con un altro lettore. Se l’app esaurisce la memoria con un file molto grande, dividilo e lavora una parte alla volta. Per tutto il resto, scrivi a %1$s raccontando cosa stavi facendo.",
        "el": "Αν ένα έγγραφο δεν ανοίγει, ίσως είναι κατεστραμμένο ή προστατευμένο: δοκιμάστε πρώτα σε άλλο πρόγραμμα. Αν τελειώσει η μνήμη με πολύ μεγάλο αρχείο, χωρίστε το και δουλέψτε ένα κομμάτι τη φορά. Για οτιδήποτε άλλο, γράψτε στο %1$s περιγράφοντας τι κάνατε.",
        "ar": "إذا تعذّر فتح مستند، فقد يكون تالفًا أو محميًا: جرّب فتحه أولًا في قارئ آخر. وإذا نفدت ذاكرة التطبيق مع ملف ضخم، فقسّمه واعمل على أجزائه واحدًا تلو الآخر. ولأي أمر آخر، راسل %1$s موضّحًا ما كنت تفعله.",
        "gl": "Se un documento non abre, pode estar danado ou protexido: proba a abrilo antes noutro lector. Se a app queda sen memoria cun ficheiro moi grande, sepárao en partes e trabállaas dunha en unha. Para calquera outra cousa, escribe a %1$s contando que estabas a facer.",
        "ca": "Si un document no s’obre, pot estar malmès o protegit: prova d’obrir-lo abans en un altre lector. Si l’aplicació es queda sense memòria amb un fitxer molt gran, divideix-lo i treballa’n les parts d’una en una. Per a qualsevol altra cosa, escriu a %1$s explicant què estaves fent.",
        "eu": "Dokumentu bat irekitzen ez bada, hondatuta edo babestuta egon liteke: saiatu lehenik beste irakurgailu batean. Aplikazioari memoria amaitzen bazaio fitxategi oso handi batekin, zatitu eta banaka landu. Beste ezertarako, idatzi %1$s helbidera zer egiten ari zinen azalduz.",
    },

    # --- Acerca de -----------------------------------------------------------
    "acerca_titulo": {
        "en": "About NexaPDF", "es": "Acerca de NexaPDF",
        "fr": "À propos de NexaPDF", "de": "Über NexaPDF",
        "zh": "关于 NexaPDF", "ja": "NexaPDF について", "ru": "О NexaPDF",
        "it": "Informazioni su NexaPDF", "el": "Σχετικά με το NexaPDF",
        "ar": "حول NexaPDF", "gl": "Acerca de NexaPDF",
        "ca": "Quant a NexaPDF", "eu": "NexaPDFi buruz",
    },
    "acerca_version": {
        "en": "Version", "es": "Versión", "fr": "Version", "de": "Version",
        "zh": "版本", "ja": "バージョン", "ru": "Версия", "it": "Versione",
        "el": "Έκδοση", "ar": "الإصدار", "gl": "Versión", "ca": "Versió",
        "eu": "Bertsioa",
    },
    "acerca_compilacion": {
        "en": "Build", "es": "Compilación", "fr": "Build", "de": "Build",
        "zh": "构建号", "ja": "ビルド", "ru": "Сборка", "it": "Build",
        "el": "Έκδοση κατασκευής", "ar": "رقم البناء", "gl": "Compilación",
        "ca": "Compilació", "eu": "Konpilazioa",
    },
    "acerca_fecha": {
        "en": "Build date", "es": "Fecha de compilación",
        "fr": "Date de compilation", "de": "Build-Datum", "zh": "构建日期",
        "ja": "ビルド日", "ru": "Дата сборки", "it": "Data di build",
        "el": "Ημερομηνία κατασκευής", "ar": "تاريخ البناء",
        "gl": "Data de compilación", "ca": "Data de compilació",
        "eu": "Konpilazio-data",
    },
    "acerca_commit": {
        "en": "Commit", "es": "Commit", "fr": "Commit", "de": "Commit",
        "zh": "提交", "ja": "コミット", "ru": "Коммит", "it": "Commit",
        "el": "Commit", "ar": "الالتزام", "gl": "Commit", "ca": "Commit",
        "eu": "Commit",
    },
    "acerca_plataforma": {
        "en": "Platform", "es": "Plataforma", "fr": "Plateforme",
        "de": "Plattform", "zh": "平台", "ja": "プラットフォーム",
        "ru": "Платформа", "it": "Piattaforma", "el": "Πλατφόρμα",
        "ar": "المنصة", "gl": "Plataforma", "ca": "Plataforma",
        "eu": "Plataforma",
    },
    "acerca_licencia": {
        "en": "Licence", "es": "Licencia", "fr": "Licence", "de": "Lizenz",
        "zh": "许可证", "ja": "ライセンス", "ru": "Лицензия", "it": "Licenza",
        "el": "Άδεια", "ar": "الترخيص", "gl": "Licenza", "ca": "Llicència",
        "eu": "Lizentzia",
    },
    "acerca_licencias_terceros": {
        "en": "Third-party licences", "es": "Licencias de terceros",
        "fr": "Licences tierces", "de": "Lizenzen Dritter",
        "zh": "第三方许可证", "ja": "サードパーティのライセンス",
        "ru": "Лицензии третьих сторон", "it": "Licenze di terze parti",
        "el": "Άδειες τρίτων", "ar": "تراخيص الأطراف الثالثة",
        "gl": "Licenzas de terceiros", "ca": "Llicències de tercers",
        "eu": "Hirugarrenen lizentziak",
    },
    "acerca_privacidad": {
        "en": "Privacy policy", "es": "Política de privacidad",
        "fr": "Politique de confidentialité", "de": "Datenschutzerklärung",
        "zh": "隐私政策", "ja": "プライバシーポリシー",
        "ru": "Политика конфиденциальности", "it": "Informativa sulla privacy",
        "el": "Πολιτική απορρήτου", "ar": "سياسة الخصوصية",
        "gl": "Política de privacidade", "ca": "Política de privadesa",
        "eu": "Pribatutasun-politika",
    },
    "acerca_codigo_fuente": {
        "en": "Source code", "es": "Código fuente", "fr": "Code source",
        "de": "Quellcode", "zh": "源代码", "ja": "ソースコード",
        "ru": "Исходный код", "it": "Codice sorgente", "el": "Πηγαίος κώδικας",
        "ar": "الشيفرة المصدرية", "gl": "Código fonte", "ca": "Codi font",
        "eu": "Iturburu-kodea",
    },
    "acerca_contacto": {
        "en": "Contact", "es": "Contacto", "fr": "Contact", "de": "Kontakt",
        "zh": "联系", "ja": "連絡先", "ru": "Контакт", "it": "Contatto",
        "el": "Επικοινωνία", "ar": "التواصل", "gl": "Contacto",
        "ca": "Contacte", "eu": "Harremana",
    },
    "acerca_gratis": {
        "en": "Free, with no ads and no tracking.",
        "es": "Gratis, sin anuncios y sin seguimiento.",
        "fr": "Gratuit, sans publicité ni pistage.",
        "de": "Kostenlos, ohne Werbung und ohne Tracking.",
        "zh": "免费，无广告，不做任何追踪。",
        "ja": "無料、広告なし、追跡なし。",
        "ru": "Бесплатно, без рекламы и слежки.",
        "it": "Gratis, senza pubblicità e senza tracciamento.",
        "el": "Δωρεάν, χωρίς διαφημίσεις και χωρίς παρακολούθηση.",
        "ar": "مجاني، بلا إعلانات وبلا تتبّع.",
        "gl": "De balde, sen anuncios e sen seguimento.",
        "ca": "Gratuït, sense anuncis i sense seguiment.",
        "eu": "Doakoa, iragarkirik gabe eta jarraipenik gabe.",
    },

    # --- Donacion ------------------------------------------------------------
    "donar_titulo": {
        "en": "Buy me a coffee", "es": "Invítame a un café",
        "fr": "Offrez-moi un café", "de": "Spendier mir einen Kaffee",
        "zh": "请我喝杯咖啡", "ja": "コーヒーをごちそうする",
        "ru": "Угостите меня кофе", "it": "Offrimi un caffè",
        "el": "Κεράστε με έναν καφέ", "ar": "ادعُني إلى قهوة",
        "gl": "Convídame a un café", "ca": "Convida’m a un cafè",
        "eu": "Kafe bat gonbidatu",
    },
    "donar_texto": {
        "en": "This app is free, has no ads and does not collect your data. If you find it useful, you can buy me a coffee.",
        "es": "Esta app es gratuita, sin anuncios y no recoge tus datos. Si te resulta útil, puedes invitarme a un café.",
        "fr": "Cette appli est gratuite, sans publicité et ne collecte pas vos données. Si elle vous est utile, vous pouvez m’offrir un café.",
        "de": "Diese App ist kostenlos, werbefrei und sammelt keine Daten. Wenn sie dir nützt, kannst du mir einen Kaffee spendieren.",
        "zh": "这个应用免费、没有广告，也不收集你的数据。如果觉得有用，可以请我喝杯咖啡。",
        "ja": "このアプリは無料で、広告もなく、データも集めません。役に立ったら、コーヒーをごちそうしてください。",
        "ru": "Это приложение бесплатное, без рекламы и не собирает ваши данные. Если оно вам полезно, можете угостить меня кофе.",
        "it": "Questa app è gratuita, senza pubblicità e non raccoglie i tuoi dati. Se ti è utile, puoi offrirmi un caffè.",
        "el": "Αυτή η εφαρμογή είναι δωρεάν, χωρίς διαφημίσεις και δεν συλλέγει τα δεδομένα σας. Αν σας φανεί χρήσιμη, μπορείτε να με κεράσετε έναν καφέ.",
        "ar": "هذا التطبيق مجاني وبلا إعلانات ولا يجمع بياناتك. إن وجدته مفيدًا، يمكنك أن تدعوني إلى قهوة.",
        "gl": "Esta app é gratuíta, sen anuncios e non recolle os teus datos. Se che resulta útil, podes convidarme a un café.",
        "ca": "Aquesta aplicació és gratuïta, sense anuncis i no recull les teves dades. Si et resulta útil, em pots convidar a un cafè.",
        "eu": "Aplikazio hau doakoa da, iragarkirik gabe, eta ez ditu zure datuak biltzen. Erabilgarria bazaizu, kafe bat gonbida diezadakezu.",
    },
    "donar_boton": {
        "en": "Buy me a coffee · %1$s", "es": "Invítame a un café · %1$s",
        "fr": "Offrez-moi un café · %1$s", "de": "Kaffee spendieren · %1$s",
        "zh": "请我喝杯咖啡 · %1$s", "ja": "コーヒーをごちそうする · %1$s",
        "ru": "Угостить кофе · %1$s", "it": "Offrimi un caffè · %1$s",
        "el": "Κεράστε μου έναν καφέ · %1$s", "ar": "ادعُني إلى قهوة · %1$s",
        "gl": "Convídame a un café · %1$s", "ca": "Convida’m a un cafè · %1$s",
        "eu": "Kafe bat gonbidatu · %1$s",
    },
    "donar_ahora_no": {
        "en": "Not now", "es": "Ahora no", "fr": "Pas maintenant",
        "de": "Jetzt nicht", "zh": "暂时不用", "ja": "今はやめておく",
        "ru": "Не сейчас", "it": "Non ora", "el": "Όχι τώρα", "ar": "ليس الآن",
        "gl": "Agora non", "ca": "Ara no", "eu": "Orain ez",
    },
    "donar_no_mostrar": {
        "en": "Do not show again", "es": "No volver a mostrar",
        "fr": "Ne plus afficher", "de": "Nicht mehr anzeigen",
        "zh": "不再显示", "ja": "今後表示しない", "ru": "Больше не показывать",
        "it": "Non mostrare più", "el": "Να μην εμφανιστεί ξανά",
        "ar": "عدم الإظهار مجددًا", "gl": "Non volver amosar",
        "ca": "No ho tornis a mostrar", "eu": "Ez erakutsi berriro",
    },
    "donar_otro_dispositivo": {
        "en": "Pay from another device", "es": "Pagar desde otro dispositivo",
        "fr": "Payer depuis un autre appareil",
        "de": "Von einem anderen Gerät bezahlen", "zh": "用其他设备支付",
        "ja": "別の端末から支払う", "ru": "Оплатить с другого устройства",
        "it": "Paga da un altro dispositivo",
        "el": "Πληρωμή από άλλη συσκευή", "ar": "الدفع من جهاز آخر",
        "gl": "Pagar desde outro dispositivo",
        "ca": "Paga des d’un altre dispositiu", "eu": "Ordaindu beste gailu batetik",
    },
    "donar_copiar_enlace": {
        "en": "Copy link", "es": "Copiar enlace", "fr": "Copier le lien",
        "de": "Link kopieren", "zh": "复制链接", "ja": "リンクをコピー",
        "ru": "Копировать ссылку", "it": "Copia link",
        "el": "Αντιγραφή συνδέσμου", "ar": "نسخ الرابط",
        "gl": "Copiar ligazón", "ca": "Copia l’enllaç", "eu": "Kopiatu esteka",
    },
    "donar_enlace_copiado": {
        "en": "Link copied", "es": "Enlace copiado", "fr": "Lien copié",
        "de": "Link kopiert", "zh": "链接已复制", "ja": "リンクをコピーしました",
        "ru": "Ссылка скопирована", "it": "Link copiato",
        "el": "Ο σύνδεσμος αντιγράφηκε", "ar": "تم نسخ الرابط",
        "gl": "Ligazón copiada", "ca": "Enllaç copiat", "eu": "Esteka kopiatuta",
    },
    "donar_gracias": {
        "en": "Thanks for stopping by", "es": "Gracias por pasarte por ahí",
        "fr": "Merci d’être passé", "de": "Danke fürs Vorbeischauen",
        "zh": "谢谢你过去看看", "ja": "のぞいてくれてありがとう",
        "ru": "Спасибо, что заглянули", "it": "Grazie per essere passato",
        "el": "Ευχαριστώ που περάσατε", "ar": "شكرًا لمرورك",
        "gl": "Grazas por pasarte por alí", "ca": "Gràcies per passar-hi",
        "eu": "Eskerrik asko bertaratzeagatik",
    },
    "donar_qr_desc": {
        "en": "QR code with the link to buy a coffee",
        "es": "Código QR con el enlace para invitar a un café",
        "fr": "Code QR contenant le lien pour offrir un café",
        "de": "QR-Code mit dem Link, um einen Kaffee zu spendieren",
        "zh": "含有请喝咖啡链接的二维码",
        "ja": "コーヒーをごちそうするリンクの QR コード",
        "ru": "QR-код со ссылкой, чтобы угостить кофе",
        "it": "Codice QR con il link per offrire un caffè",
        "el": "Κωδικός QR με τον σύνδεσμο για να κεράσετε καφέ",
        "ar": "رمز QR يحتوي رابط دعوة القهوة",
        "gl": "Código QR coa ligazón para convidar a un café",
        "ca": "Codi QR amb l’enllaç per convidar a un cafè",
        "eu": "Kafe bat gonbidatzeko estekaren QR kodea",
    },
    "donar_taza_desc": {
        "en": "Drawing of a steaming cup of coffee",
        "es": "Dibujo de una taza de café humeante",
        "fr": "Dessin d’une tasse de café fumante",
        "de": "Zeichnung einer dampfenden Kaffeetasse",
        "zh": "一杯冒着热气的咖啡的插画",
        "ja": "湯気の立つコーヒーカップのイラスト",
        "ru": "Рисунок дымящейся чашки кофе",
        "it": "Disegno di una tazza di caffè fumante",
        "el": "Σχέδιο ενός φλιτζανιού καφέ που αχνίζει",
        "ar": "رسم لفنجان قهوة يتصاعد منه البخار",
        "gl": "Debuxo dunha cunca de café fumegante",
        "ca": "Dibuix d’una tassa de cafè fumejant",
        "eu": "Lurruna darion kafe-katilu baten marrazkia",
    },

    # --- Accesibilidad -------------------------------------------------------
    "cd_volver": {
        "en": "Go back", "es": "Volver", "fr": "Revenir", "de": "Zurück",
        "zh": "返回", "ja": "戻る", "ru": "Назад", "it": "Torna indietro",
        "el": "Επιστροφή", "ar": "رجوع", "gl": "Volver", "ca": "Torna",
        "eu": "Itzuli",
    },
    "cd_ajustes": {
        "en": "Open settings", "es": "Abrir ajustes",
        "fr": "Ouvrir les réglages", "de": "Einstellungen öffnen",
        "zh": "打开设置", "ja": "設定を開く", "ru": "Открыть настройки",
        "it": "Apri le impostazioni", "el": "Άνοιγμα ρυθμίσεων",
        "ar": "فتح الإعدادات", "gl": "Abrir axustes",
        "ca": "Obre la configuració", "eu": "Ireki ezarpenak",
    },
    "cd_pagina_numero": {
        "en": "Page %1$d", "es": "Página %1$d", "fr": "Page %1$d",
        "de": "Seite %1$d", "zh": "第 %1$d 页", "ja": "%1$d ページ目",
        "ru": "Страница %1$d", "it": "Pagina %1$d", "el": "Σελίδα %1$d",
        "ar": "الصفحة %1$d", "gl": "Páxina %1$d", "ca": "Pàgina %1$d",
        "eu": "%1$d. orria",
    },
    "cd_bandera": {
        "en": "Flag for %1$s", "es": "Bandera de %1$s",
        "fr": "Drapeau pour %1$s", "de": "Flagge für %1$s",
        "zh": "%1$s 的旗帜", "ja": "%1$s の旗", "ru": "Флаг для %1$s",
        "it": "Bandiera di %1$s", "el": "Σημαία για %1$s",
        "ar": "علم %1$s", "gl": "Bandeira de %1$s", "ca": "Bandera de %1$s",
        "eu": "%1$s hizkuntzaren bandera",
    },
}

# Plurales. Cada idioma solo declara las categorias que su gramatica usa; el
# generador escribe las que haya. El chino, el japones y el euskera no
# distinguen numero en estos casos y solo declaran `other`.
PLURALES = {
    "plural_paginas": {
        "en": {"one": "%1$d page", "other": "%1$d pages"},
        "es": {"one": "%1$d página", "other": "%1$d páginas"},
        "fr": {"one": "%1$d page", "other": "%1$d pages"},
        "de": {"one": "%1$d Seite", "other": "%1$d Seiten"},
        "zh": {"other": "%1$d 页"},
        "ja": {"other": "%1$d ページ"},
        "ru": {"one": "%1$d страница", "few": "%1$d страницы", "many": "%1$d страниц",
               "other": "%1$d страницы"},
        "it": {"one": "%1$d pagina", "other": "%1$d pagine"},
        "el": {"one": "%1$d σελίδα", "other": "%1$d σελίδες"},
        "ar": {"zero": "لا صفحات", "one": "صفحة واحدة", "two": "صفحتان",
               "few": "%1$d صفحات", "many": "%1$d صفحة", "other": "%1$d صفحة"},
        "gl": {"one": "%1$d páxina", "other": "%1$d páxinas"},
        "ca": {"one": "%1$d pàgina", "other": "%1$d pàgines"},
        "eu": {"one": "orri %1$d", "other": "%1$d orri"},
    },
    "plural_seleccionadas": {
        "en": {"one": "%1$d selected", "other": "%1$d selected"},
        "es": {"one": "%1$d seleccionada", "other": "%1$d seleccionadas"},
        "fr": {"one": "%1$d sélectionnée", "other": "%1$d sélectionnées"},
        "de": {"one": "%1$d ausgewählt", "other": "%1$d ausgewählt"},
        "zh": {"other": "已选 %1$d 项"},
        "ja": {"other": "%1$d 件選択中"},
        "ru": {"one": "выбрана %1$d", "few": "выбрано %1$d", "many": "выбрано %1$d",
               "other": "выбрано %1$d"},
        "it": {"one": "%1$d selezionata", "other": "%1$d selezionate"},
        "el": {"one": "%1$d επιλεγμένη", "other": "%1$d επιλεγμένες"},
        "ar": {"zero": "لا شيء محدد", "one": "واحدة محددة", "two": "اثنتان محددتان",
               "few": "%1$d محددة", "many": "%1$d محددة", "other": "%1$d محددة"},
        "gl": {"one": "%1$d seleccionada", "other": "%1$d seleccionadas"},
        "ca": {"one": "%1$d seleccionada", "other": "%1$d seleccionades"},
        "eu": {"one": "%1$d hautatuta", "other": "%1$d hautatuta"},
    },
    "plural_documentos": {
        "en": {"one": "%1$d document", "other": "%1$d documents"},
        "es": {"one": "%1$d documento", "other": "%1$d documentos"},
        "fr": {"one": "%1$d document", "other": "%1$d documents"},
        "de": {"one": "%1$d Dokument", "other": "%1$d Dokumente"},
        "zh": {"other": "%1$d 个文档"},
        "ja": {"other": "%1$d 個の文書"},
        "ru": {"one": "%1$d документ", "few": "%1$d документа", "many": "%1$d документов",
               "other": "%1$d документа"},
        "it": {"one": "%1$d documento", "other": "%1$d documenti"},
        "el": {"one": "%1$d έγγραφο", "other": "%1$d έγγραφα"},
        "ar": {"zero": "لا مستندات", "one": "مستند واحد", "two": "مستندان",
               "few": "%1$d مستندات", "many": "%1$d مستندًا", "other": "%1$d مستند"},
        "gl": {"one": "%1$d documento", "other": "%1$d documentos"},
        "ca": {"one": "%1$d document", "other": "%1$d documents"},
        "eu": {"one": "dokumentu %1$d", "other": "%1$d dokumentu"},
    },
    "plural_imagenes": {
        "en": {"one": "%1$d image", "other": "%1$d images"},
        "es": {"one": "%1$d imagen", "other": "%1$d imágenes"},
        "fr": {"one": "%1$d image", "other": "%1$d images"},
        "de": {"one": "%1$d Bild", "other": "%1$d Bilder"},
        "zh": {"other": "%1$d 张图片"},
        "ja": {"other": "%1$d 枚の画像"},
        "ru": {"one": "%1$d изображение", "few": "%1$d изображения",
               "many": "%1$d изображений", "other": "%1$d изображения"},
        "it": {"one": "%1$d immagine", "other": "%1$d immagini"},
        "el": {"one": "%1$d εικόνα", "other": "%1$d εικόνες"},
        "ar": {"zero": "لا صور", "one": "صورة واحدة", "two": "صورتان",
               "few": "%1$d صور", "many": "%1$d صورة", "other": "%1$d صورة"},
        "gl": {"one": "%1$d imaxe", "other": "%1$d imaxes"},
        "ca": {"one": "%1$d imatge", "other": "%1$d imatges"},
        "eu": {"one": "irudi %1$d", "other": "%1$d irudi"},
    },
}
