#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Textos de proteger un PDF con contraseña, en los trece idiomas.

Va aparte del catálogo base por el mismo motivo que ajustes o el editor: son
los textos de una pantalla concreta y así se lee de un vistazo lo que dice esa
pantalla entera en los trece idiomas.

Una nota sobre el tono: la pantalla no promete lo que el formato no cumple. Las
casillas de permisos son indicaciones que el lector obedece si quiere, y eso se
dice con esas palabras; lo que de verdad cierra el documento es la contraseña.
"""

TEXTOS = {
    # --- Baldosa del inicio --------------------------------------------------
    "herr_cifrar_titulo": {
        "en": "Protect PDF",
        "es": "Proteger PDF",
        "fr": "Protéger un PDF",
        "de": "PDF schützen",
        "zh": "加密 PDF",
        "ja": "PDF を保護",
        "ru": "Защитить PDF",
        "it": "Proteggi PDF",
        "el": "Προστασία PDF",
        "ar": "حماية PDF",
        "gl": "Protexer PDF",
        "ca": "Protegir PDF",
        "eu": "Babestu PDFa",
    },
    "herr_cifrar_desc": {
        "en": "With a password",
        "es": "Con contraseña",
        "fr": "Par mot de passe",
        "de": "Mit Passwort",
        "zh": "设置打开密码",
        "ja": "パスワードで",
        "ru": "Паролем",
        "it": "Con password",
        "el": "Με κωδικό",
        "ar": "بكلمة مرور",
        "gl": "Con contrasinal",
        "ca": "Amb contrasenya",
        "eu": "Pasahitzarekin",
    },

    # --- Cabecera y estado ---------------------------------------------------
    "cifrar_titulo": {
        "en": "Protect with a password",
        "es": "Proteger con contraseña",
        "fr": "Protéger par mot de passe",
        "de": "Mit Passwort schützen",
        "zh": "用密码保护",
        "ja": "パスワードで保護",
        "ru": "Защита паролем",
        "it": "Proteggi con password",
        "el": "Προστασία με κωδικό",
        "ar": "الحماية بكلمة مرور",
        "gl": "Protexer con contrasinal",
        "ca": "Protegir amb contrasenya",
        "eu": "Babestu pasahitzarekin",
    },
    "cifrar_estado_libre": {
        "en": "Opens without a password",
        "es": "Se abre sin contraseña",
        "fr": "S’ouvre sans mot de passe",
        "de": "Öffnet ohne Passwort",
        "zh": "当前无需密码即可打开",
        "ja": "パスワードなしで開きます",
        "ru": "Открывается без пароля",
        "it": "Si apre senza password",
        "el": "Ανοίγει χωρίς κωδικό",
        "ar": "يُفتح بدون كلمة مرور",
        "gl": "Ábrese sen contrasinal",
        "ca": "S’obre sense contrasenya",
        "eu": "Pasahitzik gabe irekitzen da",
    },
    "cifrar_estado_protegido": {
        "en": "Already asks for a password",
        "es": "Ya pide contraseña",
        "fr": "Demande déjà un mot de passe",
        "de": "Fragt bereits nach einem Passwort",
        "zh": "已经设置了打开密码",
        "ja": "すでにパスワードが必要です",
        "ru": "Уже запрашивает пароль",
        "it": "Chiede già una password",
        "el": "Ζητά ήδη κωδικό",
        "ar": "يطلب كلمة مرور بالفعل",
        "gl": "Xa pide contrasinal",
        "ca": "Ja demana contrasenya",
        "eu": "Dagoeneko pasahitza eskatzen du",
    },

    # --- Modos ---------------------------------------------------------------
    "cifrar_modo_poner": {
        "en": "Set password",
        "es": "Poner contraseña",
        "fr": "Ajouter un mot de passe",
        "de": "Passwort setzen",
        "zh": "设置密码",
        "ja": "パスワードを設定",
        "ru": "Поставить пароль",
        "it": "Metti password",
        "el": "Ορισμός κωδικού",
        "ar": "تعيين كلمة مرور",
        "gl": "Poñer contrasinal",
        "ca": "Posar contrasenya",
        "eu": "Jarri pasahitza",
    },
    "cifrar_modo_quitar": {
        "en": "Remove password",
        "es": "Quitar contraseña",
        "fr": "Retirer le mot de passe",
        "de": "Passwort entfernen",
        "zh": "移除密码",
        "ja": "パスワードを解除",
        "ru": "Снять пароль",
        "it": "Togli password",
        "el": "Αφαίρεση κωδικού",
        "ar": "إزالة كلمة المرور",
        "gl": "Quitar contrasinal",
        "ca": "Treure la contrasenya",
        "eu": "Kendu pasahitza",
    },

    # --- Campos --------------------------------------------------------------
    "cifrar_contrasena": {
        "en": "Password",
        "es": "Contraseña",
        "fr": "Mot de passe",
        "de": "Passwort",
        "zh": "密码",
        "ja": "パスワード",
        "ru": "Пароль",
        "it": "Password",
        "el": "Κωδικός",
        "ar": "كلمة المرور",
        "gl": "Contrasinal",
        "ca": "Contrasenya",
        "eu": "Pasahitza",
    },
    "cifrar_repetir": {
        "en": "Repeat the password",
        "es": "Repite la contraseña",
        "fr": "Répétez le mot de passe",
        "de": "Passwort wiederholen",
        "zh": "再输入一次",
        "ja": "パスワードを再入力",
        "ru": "Повторите пароль",
        "it": "Ripeti la password",
        "el": "Επανάληψη κωδικού",
        "ar": "أعد كتابة كلمة المرور",
        "gl": "Repite o contrasinal",
        "ca": "Repeteix la contrasenya",
        "eu": "Errepikatu pasahitza",
    },
    "cifrar_actual": {
        "en": "Current password",
        "es": "Contraseña actual",
        "fr": "Mot de passe actuel",
        "de": "Aktuelles Passwort",
        "zh": "当前密码",
        "ja": "現在のパスワード",
        "ru": "Текущий пароль",
        "it": "Password attuale",
        "el": "Τρέχων κωδικός",
        "ar": "كلمة المرور الحالية",
        "gl": "Contrasinal actual",
        "ca": "Contrasenya actual",
        "eu": "Uneko pasahitza",
    },
    "cifrar_no_coincide": {
        "en": "The two passwords are different",
        "es": "Las dos contraseñas no son iguales",
        "fr": "Les deux mots de passe sont différents",
        "de": "Die beiden Passwörter sind verschieden",
        "zh": "两次输入的密码不一致",
        "ja": "2 つのパスワードが一致しません",
        "ru": "Пароли не совпадают",
        "it": "Le due password non coincidono",
        "el": "Οι δύο κωδικοί δεν είναι ίδιοι",
        "ar": "كلمتا المرور غير متطابقتين",
        "gl": "Os dous contrasinais non son iguais",
        "ca": "Les dues contrasenyes no són iguals",
        "eu": "Bi pasahitzak ez dira berdinak",
    },
    "cifrar_corta": {
        "en": "Use at least 4 characters",
        "es": "Usa al menos 4 caracteres",
        "fr": "Utilisez au moins 4 caractères",
        "de": "Mindestens 4 Zeichen",
        "zh": "至少 4 个字符",
        "ja": "4 文字以上にしてください",
        "ru": "Не меньше 4 символов",
        "it": "Usa almeno 4 caratteri",
        "el": "Χρησιμοποιήστε τουλάχιστον 4 χαρακτήρες",
        "ar": "استخدم 4 أحرف على الأقل",
        "gl": "Usa polo menos 4 caracteres",
        "ca": "Fes servir com a mínim 4 caràcters",
        "eu": "Erabili gutxienez 4 karaktere",
    },
    "cifrar_ver": {
        "en": "Show password",
        "es": "Ver la contraseña",
        "fr": "Afficher le mot de passe",
        "de": "Passwort anzeigen",
        "zh": "显示密码",
        "ja": "パスワードを表示",
        "ru": "Показать пароль",
        "it": "Mostra la password",
        "el": "Εμφάνιση κωδικού",
        "ar": "إظهار كلمة المرور",
        "gl": "Ver o contrasinal",
        "ca": "Mostra la contrasenya",
        "eu": "Erakutsi pasahitza",
    },
    "cifrar_ocultar": {
        "en": "Hide password",
        "es": "Ocultar la contraseña",
        "fr": "Masquer le mot de passe",
        "de": "Passwort verbergen",
        "zh": "隐藏密码",
        "ja": "パスワードを隠す",
        "ru": "Скрыть пароль",
        "it": "Nascondi la password",
        "el": "Απόκρυψη κωδικού",
        "ar": "إخفاء كلمة المرور",
        "gl": "Agochar o contrasinal",
        "ca": "Amaga la contrasenya",
        "eu": "Ezkutatu pasahitza",
    },

    # --- Fuerza de la contraseña ---------------------------------------------
    "cifrar_fuerza_debil": {
        "en": "Weak password",
        "es": "Contraseña débil",
        "fr": "Mot de passe faible",
        "de": "Schwaches Passwort",
        "zh": "密码强度弱",
        "ja": "弱いパスワード",
        "ru": "Слабый пароль",
        "it": "Password debole",
        "el": "Αδύναμος κωδικός",
        "ar": "كلمة مرور ضعيفة",
        "gl": "Contrasinal débil",
        "ca": "Contrasenya feble",
        "eu": "Pasahitz ahula",
    },
    "cifrar_fuerza_media": {
        "en": "Decent password",
        "es": "Contraseña aceptable",
        "fr": "Mot de passe correct",
        "de": "Brauchbares Passwort",
        "zh": "密码强度中等",
        "ja": "まずまずのパスワード",
        "ru": "Средний пароль",
        "it": "Password accettabile",
        "el": "Αποδεκτός κωδικός",
        "ar": "كلمة مرور مقبولة",
        "gl": "Contrasinal aceptable",
        "ca": "Contrasenya acceptable",
        "eu": "Pasahitz onargarria",
    },
    "cifrar_fuerza_fuerte": {
        "en": "Strong password",
        "es": "Contraseña fuerte",
        "fr": "Mot de passe robuste",
        "de": "Starkes Passwort",
        "zh": "密码强度高",
        "ja": "強いパスワード",
        "ru": "Надёжный пароль",
        "it": "Password robusta",
        "el": "Ισχυρός κωδικός",
        "ar": "كلمة مرور قوية",
        "gl": "Contrasinal forte",
        "ca": "Contrasenya forta",
        "eu": "Pasahitz sendoa",
    },
    "cifrar_aviso_perdida": {
        "en": "If you forget it, the document cannot be opened again. NexaPDF does not keep a copy of the password anywhere.",
        "es": "Si la olvidas, el documento no se puede volver a abrir. NexaPDF no guarda una copia de la contraseña en ningún sitio.",
        "fr": "Si vous l’oubliez, le document ne pourra plus être ouvert. NexaPDF n’en garde aucune copie.",
        "de": "Wenn Sie es vergessen, lässt sich das Dokument nicht mehr öffnen. NexaPDF speichert das Passwort nirgends.",
        "zh": "一旦忘记，文档就再也打不开了。NexaPDF 不会在任何地方保存这个密码。",
        "ja": "忘れると文書は二度と開けません。NexaPDF はパスワードをどこにも保存しません。",
        "ru": "Если забудете — документ уже не открыть. NexaPDF нигде не хранит пароль.",
        "it": "Se la dimentichi, il documento non si potrà più aprire. NexaPDF non ne conserva copia da nessuna parte.",
        "el": "Αν τον ξεχάσετε, το έγγραφο δεν ανοίγει ξανά. Το NexaPDF δεν κρατά αντίγραφο του κωδικού πουθενά.",
        "ar": "إذا نسيتها فلن يمكن فتح المستند مرة أخرى. لا يحتفظ NexaPDF بنسخة منها في أي مكان.",
        "gl": "Se a esqueces, o documento non se pode volver abrir. NexaPDF non garda copia do contrasinal en ningún sitio.",
        "ca": "Si l’oblides, el document ja no es podrà obrir. NexaPDF no en guarda cap còpia enlloc.",
        "eu": "Ahazten baduzu, dokumentua ezin izango da berriro ireki. NexaPDFek ez du pasahitzaren kopiarik inon gordetzen.",
    },

    # --- Permisos ------------------------------------------------------------
    "cifrar_permisos_titulo": {
        "en": "What the document allows",
        "es": "Qué permite el documento",
        "fr": "Ce que le document autorise",
        "de": "Was das Dokument erlaubt",
        "zh": "文档允许的操作",
        "ja": "文書で許可する操作",
        "ru": "Что разрешено с документом",
        "it": "Che cosa permette il documento",
        "el": "Τι επιτρέπει το έγγραφο",
        "ar": "ما يسمح به المستند",
        "gl": "Que permite o documento",
        "ca": "Què permet el document",
        "eu": "Dokumentuak zer onartzen duen",
    },
    "cifrar_permisos_aviso": {
        "en": "These are requests, not locks: a reader obeys them if it wants to. What really closes the document is the password.",
        "es": "Son peticiones, no candados: el lector las respeta si quiere. Lo que de verdad cierra el documento es la contraseña.",
        "fr": "Ce sont des demandes, pas des verrous : un lecteur les respecte s’il le veut. Ce qui ferme vraiment le document, c’est le mot de passe.",
        "de": "Das sind Bitten, keine Schlösser: ein Betrachter hält sich daran, wenn er will. Wirklich verschlossen wird das Dokument nur durch das Passwort.",
        "zh": "这些是约定而非锁：阅读器愿意遵守才遵守。真正锁住文档的是密码。",
        "ja": "これは施錠ではなく申し合わせです。従うかどうかは閲覧アプリ次第で、文書を本当に閉じるのはパスワードです。",
        "ru": "Это просьбы, а не замки: программа соблюдает их, если захочет. По-настоящему закрывает документ только пароль.",
        "it": "Sono richieste, non lucchetti: un lettore le rispetta se vuole. Quello che chiude davvero il documento è la password.",
        "el": "Είναι παρακλήσεις, όχι κλειδαριές: ένα πρόγραμμα τις τηρεί αν θέλει. Αυτό που κλείνει πραγματικά το έγγραφο είναι ο κωδικός.",
        "ar": "هذه طلبات لا أقفال: يحترمها البرنامج إن شاء. ما يغلق المستند فعلًا هو كلمة المرور.",
        "gl": "Son peticións, non cadeados: o lector respéctaas se quere. O que de verdade pecha o documento é o contrasinal.",
        "ca": "Són peticions, no panys: un lector les respecta si vol. El que tanca de debò el document és la contrasenya.",
        "eu": "Eskaerak dira, ez sarrailak: irakurgailuak nahi badu betetzen ditu. Dokumentua benetan ixten duena pasahitza da.",
    },
    "cifrar_perm_imprimir": {
        "en": "Printing",
        "es": "Imprimir",
        "fr": "Imprimer",
        "de": "Drucken",
        "zh": "打印",
        "ja": "印刷",
        "ru": "Печать",
        "it": "Stampare",
        "el": "Εκτύπωση",
        "ar": "الطباعة",
        "gl": "Imprimir",
        "ca": "Imprimir",
        "eu": "Inprimatzea",
    },
    "cifrar_perm_copiar": {
        "en": "Copying text",
        "es": "Copiar el texto",
        "fr": "Copier le texte",
        "de": "Text kopieren",
        "zh": "复制文字",
        "ja": "テキストのコピー",
        "ru": "Копирование текста",
        "it": "Copiare il testo",
        "el": "Αντιγραφή κειμένου",
        "ar": "نسخ النص",
        "gl": "Copiar o texto",
        "ca": "Copiar el text",
        "eu": "Testua kopiatzea",
    },
    "cifrar_perm_modificar": {
        "en": "Changing the content",
        "es": "Cambiar el contenido",
        "fr": "Modifier le contenu",
        "de": "Inhalt ändern",
        "zh": "修改内容",
        "ja": "内容の変更",
        "ru": "Изменение содержимого",
        "it": "Modificare il contenuto",
        "el": "Αλλαγή περιεχομένου",
        "ar": "تغيير المحتوى",
        "gl": "Cambiar o contido",
        "ca": "Canviar el contingut",
        "eu": "Edukia aldatzea",
    },
    "cifrar_perm_anotar": {
        "en": "Annotating and filling in forms",
        "es": "Anotar y rellenar formularios",
        "fr": "Annoter et remplir des formulaires",
        "de": "Kommentieren und Formulare ausfüllen",
        "zh": "批注与填写表单",
        "ja": "注釈とフォームの入力",
        "ru": "Пометки и заполнение форм",
        "it": "Annotare e compilare moduli",
        "el": "Σχολιασμός και συμπλήρωση φορμών",
        "ar": "التعليق وملء النماذج",
        "gl": "Anotar e encher formularios",
        "ca": "Anotar i emplenar formularis",
        "eu": "Oharrak eta inprimakiak betetzea",
    },

    # --- Acciones y resultado ------------------------------------------------
    "cifrar_accion_proteger": {
        "en": "Protect document",
        "es": "Proteger el documento",
        "fr": "Protéger le document",
        "de": "Dokument schützen",
        "zh": "保护文档",
        "ja": "文書を保護",
        "ru": "Защитить документ",
        "it": "Proteggi il documento",
        "el": "Προστασία εγγράφου",
        "ar": "حماية المستند",
        "gl": "Protexer o documento",
        "ca": "Protegeix el document",
        "eu": "Babestu dokumentua",
    },
    "cifrar_accion_quitar": {
        "en": "Remove protection",
        "es": "Quitar la protección",
        "fr": "Retirer la protection",
        "de": "Schutz entfernen",
        "zh": "移除保护",
        "ja": "保護を解除",
        "ru": "Снять защиту",
        "it": "Togli la protezione",
        "el": "Αφαίρεση προστασίας",
        "ar": "إزالة الحماية",
        "gl": "Quitar a protección",
        "ca": "Treu la protecció",
        "eu": "Kendu babesa",
    },
    "cifrar_trabajando": {
        "en": "Protecting the document…",
        "es": "Protegiendo el documento…",
        "fr": "Protection du document…",
        "de": "Dokument wird geschützt …",
        "zh": "正在保护文档…",
        "ja": "文書を保護しています…",
        "ru": "Защищаем документ…",
        "it": "Protezione del documento…",
        "el": "Γίνεται προστασία του εγγράφου…",
        "ar": "جارٍ حماية المستند…",
        "gl": "Protexendo o documento…",
        "ca": "S’està protegint el document…",
        "eu": "Dokumentua babesten…",
    },
    "cifrar_hecho": {
        "en": "Protected document created",
        "es": "Documento protegido creado",
        "fr": "Document protégé créé",
        "de": "Geschütztes Dokument erstellt",
        "zh": "已生成加密文档",
        "ja": "保護された文書を作成しました",
        "ru": "Защищённый документ создан",
        "it": "Documento protetto creato",
        "el": "Δημιουργήθηκε προστατευμένο έγγραφο",
        "ar": "أُنشئ مستند محمي",
        "gl": "Documento protexido creado",
        "ca": "Document protegit creat",
        "eu": "Babestutako dokumentua sortu da",
    },
    "cifrar_quitado": {
        "en": "Password removed",
        "es": "Contraseña quitada",
        "fr": "Mot de passe retiré",
        "de": "Passwort entfernt",
        "zh": "密码已移除",
        "ja": "パスワードを解除しました",
        "ru": "Пароль снят",
        "it": "Password rimossa",
        "el": "Ο κωδικός αφαιρέθηκε",
        "ar": "أُزيلت كلمة المرور",
        "gl": "Contrasinal quitado",
        "ca": "Contrasenya treta",
        "eu": "Pasahitza kendu da",
    },
    "cifrar_sufijo": {
        "en": "protected",
        "es": "protegido",
        "fr": "protege",
        "de": "geschuetzt",
        "zh": "protected",
        "ja": "protected",
        "ru": "protected",
        "it": "protetto",
        "el": "protected",
        "ar": "protected",
        "gl": "protexido",
        "ca": "protegit",
        "eu": "babestua",
    },
    "cifrar_sufijo_sin": {
        "en": "unlocked",
        "es": "sin contrasena",
        "fr": "sans mot de passe",
        "de": "ohne Passwort",
        "zh": "unlocked",
        "ja": "unlocked",
        "ru": "unlocked",
        "it": "senza password",
        "el": "unlocked",
        "ar": "unlocked",
        "gl": "sen contrasinal",
        "ca": "sense contrasenya",
        "eu": "pasahitzik gabe",
    },

    # --- Ajustes -------------------------------------------------------------
    "aj_tarea_cifrar": {
        "en": "After protecting",
        "es": "Al proteger",
        "fr": "Après avoir protégé",
        "de": "Nach dem Schützen",
        "zh": "加密之后",
        "ja": "保護したあと",
        "ru": "После защиты",
        "it": "Dopo aver protetto",
        "el": "Μετά την προστασία",
        "ar": "بعد الحماية",
        "gl": "Ao protexer",
        "ca": "En protegir",
        "eu": "Babestu ondoren",
    },

    # --- Tour ----------------------------------------------------------------
    "tour_z_proteger_t": {
        "en": "Put a password on it",
        "es": "Ponle una contraseña",
        "fr": "Mettez-y un mot de passe",
        "de": "Mit einem Passwort versehen",
        "zh": "给文档加把锁",
        "ja": "パスワードをかける",
        "ru": "Поставьте пароль",
        "it": "Mettici una password",
        "el": "Βάλτε του έναν κωδικό",
        "ar": "ضع له كلمة مرور",
        "gl": "Ponlle un contrasinal",
        "ca": "Posa-hi una contrasenya",
        "eu": "Jarri pasahitz bat",
    },
    "tour_z_proteger_c": {
        "en": "Before sending a payslip or a contract, close it with a password. It is done on the phone, and the same screen takes the password off again.",
        "es": "Antes de mandar una nómina o un contrato, ciérralo con contraseña. Se hace en el teléfono, y la misma pantalla se la quita después.",
        "fr": "Avant d’envoyer une fiche de paie ou un contrat, fermez-le par mot de passe. Tout se fait sur le téléphone, et le même écran le retire ensuite.",
        "de": "Bevor Sie eine Gehaltsabrechnung oder einen Vertrag verschicken, schließen Sie ihn mit einem Passwort. Alles auf dem Telefon, und derselbe Bildschirm nimmt es wieder weg.",
        "zh": "在发送工资单或合同之前，先加上打开密码。全程在手机上完成，同一个界面也能再把密码去掉。",
        "ja": "給与明細や契約書を送る前に、パスワードで閉じておきましょう。処理は端末内で完結し、同じ画面で解除もできます。",
        "ru": "Перед отправкой расчётного листка или договора закройте его паролем. Всё делается на телефоне, и тот же экран потом пароль снимет.",
        "it": "Prima di mandare una busta paga o un contratto, chiudilo con una password. Si fa sul telefono, e la stessa schermata te la toglie dopo.",
        "el": "Πριν στείλετε μια μισθοδοσία ή ένα συμβόλαιο, κλειδώστε το με κωδικό. Γίνεται στο τηλέφωνο, και η ίδια οθόνη τον αφαιρεί μετά.",
        "ar": "قبل إرسال كشف راتب أو عقد، أغلقه بكلمة مرور. يتم كل شيء على الهاتف، والشاشة نفسها تزيلها لاحقًا.",
        "gl": "Antes de mandar unha nómina ou un contrato, péchao con contrasinal. Faise no teléfono, e a mesma pantalla quítallo despois.",
        "ca": "Abans d’enviar una nòmina o un contracte, tanca’l amb contrasenya. Es fa al telèfon, i la mateixa pantalla te la treu després.",
        "eu": "Nomina edo kontratu bat bidali aurretik, itxi pasahitzarekin. Telefonoan bertan egiten da, eta pantaila berak kentzen du gero.",
    },
}
