#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Textos del detalle de una firma electrónica, en los trece idiomas.

Son las etiquetas de la ficha que se abre al tocar una firma en el visor. Van
aparte porque describen una cosa muy concreta y así se lee de un vistazo qué
dice esa ficha entera en todos los idiomas.
"""

TEXTOS = {
    "firma_ver_detalle": {
        "en": "Show signature details",
        "es": "Ver los detalles de la firma",
        "fr": "Afficher les détails de la signature",
        "de": "Details der Signatur anzeigen",
        "zh": "查看签名详情",
        "ja": "署名の詳細を表示",
        "ru": "Показать сведения о подписи",
        "it": "Mostra i dettagli della firma",
        "el": "Εμφάνιση λεπτομερειών υπογραφής",
        "ar": "عرض تفاصيل التوقيع",
        "gl": "Ver os detalles da sinatura",
        "ca": "Mostra els detalls de la signatura",
        "eu": "Erakutsi sinaduraren xehetasunak",
    },
    "firma_det_firmante": {
        "en": "Signer",
        "es": "Firmante",
        "fr": "Signataire",
        "de": "Unterzeichner",
        "zh": "签名者",
        "ja": "署名者",
        "ru": "Подписант",
        "it": "Firmatario",
        "el": "Υπογράφων",
        "ar": "الموقِّع",
        "gl": "Asinante",
        "ca": "Signant",
        "eu": "Sinatzailea",
    },
    "firma_det_emisor": {
        "en": "Issued by",
        "es": "Emitido por",
        "fr": "Émis par",
        "de": "Ausgestellt von",
        "zh": "颁发者",
        "ja": "発行者",
        "ru": "Кем выдан",
        "it": "Rilasciato da",
        "el": "Εκδόθηκε από",
        "ar": "جهة الإصدار",
        "gl": "Emitido por",
        "ca": "Emès per",
        "eu": "Nork emana",
    },
    "firma_det_serie": {
        "en": "Serial number",
        "es": "Número de serie",
        "fr": "Numéro de série",
        "de": "Seriennummer",
        "zh": "序列号",
        "ja": "シリアル番号",
        "ru": "Серийный номер",
        "it": "Numero di serie",
        "el": "Σειριακός αριθμός",
        "ar": "الرقم التسلسلي",
        "gl": "Número de serie",
        "ca": "Número de sèrie",
        "eu": "Serie-zenbakia",
    },
    "firma_det_validez": {
        "en": "Certificate valid",
        "es": "Certificado válido",
        "fr": "Certificat valide",
        "de": "Zertifikat gültig",
        "zh": "证书有效期",
        "ja": "証明書の有効期間",
        "ru": "Сертификат действителен",
        "it": "Certificato valido",
        "el": "Ισχύς πιστοποιητικού",
        "ar": "صلاحية الشهادة",
        "gl": "Certificado válido",
        "ca": "Certificat vàlid",
        "eu": "Ziurtagiria baliozkoa",
    },
    "firma_det_rango": {
        "en": "%1$s to %2$s",
        "es": "del %1$s al %2$s",
        "fr": "du %1$s au %2$s",
        "de": "%1$s bis %2$s",
        "zh": "%1$s 至 %2$s",
        "ja": "%1$s 〜 %2$s",
        "ru": "с %1$s по %2$s",
        "it": "dal %1$s al %2$s",
        "el": "από %1$s έως %2$s",
        "ar": "من %1$s إلى %2$s",
        "gl": "do %1$s ao %2$s",
        "ca": "del %1$s al %2$s",
        "eu": "%1$s – %2$s",
    },
    "firma_det_fecha": {
        "en": "Signed on",
        "es": "Fecha de la firma",
        "fr": "Date de la signature",
        "de": "Signiert am",
        "zh": "签名时间",
        "ja": "署名日時",
        "ru": "Дата подписи",
        "it": "Data della firma",
        "el": "Ημερομηνία υπογραφής",
        "ar": "تاريخ التوقيع",
        "gl": "Data da sinatura",
        "ca": "Data de la signatura",
        "eu": "Sinaduraren data",
    },
    "firma_det_algoritmo": {
        "en": "Algorithm",
        "es": "Algoritmo",
        "fr": "Algorithme",
        "de": "Algorithmus",
        "zh": "算法",
        "ja": "アルゴリズム",
        "ru": "Алгоритм",
        "it": "Algoritmo",
        "el": "Αλγόριθμος",
        "ar": "الخوارزمية",
        "gl": "Algoritmo",
        "ca": "Algorisme",
        "eu": "Algoritmoa",
    },
    "firma_det_formato": {
        "en": "Format",
        "es": "Formato",
        "fr": "Format",
        "de": "Format",
        "zh": "格式",
        "ja": "形式",
        "ru": "Формат",
        "it": "Formato",
        "el": "Μορφή",
        "ar": "الصيغة",
        "gl": "Formato",
        "ca": "Format",
        "eu": "Formatua",
    },
    "firma_det_sello": {
        "en": "Timestamp",
        "es": "Sello de tiempo",
        "fr": "Horodatage",
        "de": "Zeitstempel",
        "zh": "时间戳",
        "ja": "タイムスタンプ",
        "ru": "Метка времени",
        "it": "Marca temporale",
        "el": "Χρονοσήμανση",
        "ar": "الختم الزمني",
        "gl": "Selo de tempo",
        "ca": "Segell de temps",
        "eu": "Denbora-zigilua",
    },
    "firma_det_con_sello": {
        "en": "Yes, from a timestamping authority",
        "es": "Sí, de una autoridad de sellado",
        "fr": "Oui, d’une autorité d’horodatage",
        "de": "Ja, von einer Zeitstempelstelle",
        "zh": "有，来自时间戳颁发机构",
        "ja": "あり（タイムスタンプ局によるもの）",
        "ru": "Есть, от службы меток времени",
        "it": "Sì, di un’autorità di marcatura temporale",
        "el": "Ναι, από αρχή χρονοσήμανσης",
        "ar": "نعم، من هيئة ختم زمني",
        "gl": "Si, dunha autoridade de selado",
        "ca": "Sí, d’una autoritat de segellat",
        "eu": "Bai, zigilatze-agintaritza batena",
    },
    "firma_det_sin_sello": {
        "en": "None. The date is the one on the device that signed.",
        "es": "No tiene. La fecha es la del dispositivo que firmó.",
        "fr": "Aucun. La date est celle de l’appareil signataire.",
        "de": "Keiner. Das Datum stammt vom signierenden Gerät.",
        "zh": "无。此日期来自签名所用的设备。",
        "ja": "なし。日時は署名した端末のものです。",
        "ru": "Нет. Дата — с устройства, которое подписало.",
        "it": "Nessuna. La data è quella del dispositivo che ha firmato.",
        "el": "Καμία. Η ημερομηνία είναι της συσκευής που υπέγραψε.",
        "ar": "لا يوجد. التاريخ هو تاريخ الجهاز الذي وقّع.",
        "gl": "Non ten. A data é a do dispositivo que asinou.",
        "ca": "No en té. La data és la del dispositiu que va signar.",
        "eu": "Ez du. Data sinatu duen gailuarena da.",
    },
    "firma_det_alcance": {
        "en": "Scope",
        "es": "Alcance",
        "fr": "Portée",
        "de": "Umfang",
        "zh": "覆盖范围",
        "ja": "対象範囲",
        "ru": "Охват",
        "it": "Ambito",
        "el": "Εμβέλεια",
        "ar": "النطاق",
        "gl": "Alcance",
        "ca": "Abast",
        "eu": "Irismena",
    },
    "firma_det_revision": {
        "en": "An earlier revision. More was added to the document afterwards.",
        "es": "Una revisión anterior. Después se añadió más al documento.",
        "fr": "Une révision antérieure. Du contenu a été ajouté ensuite.",
        "de": "Eine frühere Fassung. Danach wurde dem Dokument mehr hinzugefügt.",
        "zh": "较早的版本。之后文档还有新增内容。",
        "ja": "以前のリビジョン。そのあとに文書へ追記されています。",
        "ru": "Более ранняя редакция. Позже в документ добавили ещё.",
        "it": "Una revisione precedente. Dopo è stato aggiunto altro al documento.",
        "el": "Προηγούμενη αναθεώρηση. Μετά προστέθηκαν κι άλλα στο έγγραφο.",
        "ar": "مراجعة سابقة. أُضيف إلى المستند بعدها المزيد.",
        "gl": "Unha revisión anterior. Despois engadiuse máis ao documento.",
        "ca": "Una revisió anterior. Després s’hi va afegir més contingut.",
        "eu": "Aurreko berrikuspen bat. Ondoren gehiago erantsi zaio dokumentuari.",
    },
    "firma_det_no_consta": {
        "en": "Not stated",
        "es": "No consta",
        "fr": "Non renseigné",
        "de": "Nicht angegeben",
        "zh": "未提供",
        "ja": "記載なし",
        "ru": "Не указано",
        "it": "Non indicato",
        "el": "Δεν αναφέρεται",
        "ar": "غير مذكور",
        "gl": "Non consta",
        "ca": "No hi consta",
        "eu": "Ez dago jasota",
    },
}
