#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Textos del menú de herramientas del visor, en los trece idiomas.

El visor era un callejón sin salida: un PDF abierto desde otra aplicación solo
se podía leer, y para firmarlo había que salir, entrar en NexaPDF y volver a
buscarlo. Estos son los textos del menú que lo resuelve.
"""

TEXTOS = {
    "vis_eliminar_pagina": {
        "en": "Delete this page",
        "es": "Eliminar esta página",
        "fr": "Supprimer cette page",
        "de": "Diese Seite löschen",
        "zh": "删除当前页",
        "ja": "このページを削除",
        "ru": "Удалить эту страницу",
        "it": "Elimina questa pagina",
        "el": "Διαγραφή αυτής της σελίδας",
        "ar": "حذف هذه الصفحة",
        "gl": "Eliminar esta páxina",
        "ca": "Elimina aquesta pàgina",
        "eu": "Ezabatu orri hau",
    },
    "vis_eliminar_unica": {
        "en": "A document cannot be left with no pages",
        "es": "Un documento no puede quedarse sin páginas",
        "fr": "Un document ne peut pas rester sans pages",
        "de": "Ein Dokument kann nicht ohne Seiten bleiben",
        "zh": "文档不能一页都不剩",
        "ja": "ページが 1 枚もない書類にはできません",
        "ru": "Документ не может остаться без страниц",
        "it": "Un documento non può restare senza pagine",
        "el": "Ένα έγγραφο δεν μπορεί να μείνει χωρίς σελίδες",
        "ar": "لا يمكن أن يبقى المستند بلا صفحات",
        "gl": "Un documento non pode quedar sen páxinas",
        "ca": "Un document no pot quedar-se sense pàgines",
        "eu": "Dokumentu batek ezin du orririk gabe geratu",
    },
    "vis_confirmar_eliminar_pagina": {
        "en": "Delete page %1$d?",
        "es": "¿Eliminar la página %1$d?",
        "fr": "Supprimer la page %1$d ?",
        "de": "Seite %1$d löschen?",
        "zh": "要删除第 %1$d 页吗？",
        "ja": "%1$d ページ目を削除しますか？",
        "ru": "Удалить страницу %1$d?",
        "it": "Eliminare la pagina %1$d?",
        "el": "Διαγραφή της σελίδας %1$d;",
        "ar": "هل تحذف الصفحة %1$d؟",
        "gl": "Eliminar a páxina %1$d?",
        "ca": "Voleu eliminar la pàgina %1$d?",
        "eu": "%1$d. orria ezabatu?",
    },
    "vis_mas_acciones": {
        "en": "What to do with this document",
        "es": "Qué hacer con este documento",
        "fr": "Que faire de ce document",
        "de": "Was mit diesem Dokument tun",
        "zh": "对此文档可以做什么",
        "ja": "この文書にできること",
        "ru": "Что сделать с документом",
        "it": "Cosa fare con questo documento",
        "el": "Τι να κάνετε με αυτό το έγγραφο",
        "ar": "ما يمكن فعله بهذا المستند",
        "gl": "Que facer con este documento",
        "ca": "Què fer amb aquest document",
        "eu": "Zer egin dokumentu honekin",
    },
    "vis_paginas_y_mas": {
        "en": "Pages, split and export",
        "es": "Páginas, separar y exportar",
        "fr": "Pages, diviser et exporter",
        "de": "Seiten, teilen und exportieren",
        "zh": "页面、拆分与导出",
        "ja": "ページ、分割、書き出し",
        "ru": "Страницы, разделение и экспорт",
        "it": "Pagine, dividere ed esportare",
        "el": "Σελίδες, διαχωρισμός και εξαγωγή",
        "ar": "الصفحات والتقسيم والتصدير",
        "gl": "Páxinas, separar e exportar",
        "ca": "Pàgines, dividir i exportar",
        "eu": "Orriak, zatitu eta esportatu",
    },
}
