#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Textos del escáner de documentos, en los trece idiomas.

Va aparte como el resto de pantallas grandes. Dos notas sobre el tono:

  - Se dice **«texto buscable»** y no «OCR». Las siglas no significan nada para
    quien abre la aplicación por primera vez, y lo que la persona quiere saber
    es qué gana: poder buscar dentro de lo que acaba de fotografiar.
  - El permiso de cámara se explica **antes** de pedirlo y se dice hasta dónde
    llega: sólo el escáner, y las fotos no salen del teléfono. Un permiso que
    salta sin explicación se deniega, y con razón.
"""

TEXTOS = {
    # --- Baldosa del inicio --------------------------------------------------
    "herr_escanear_titulo": {
        "en": "Scan",
        "es": "Escanear",
        "fr": "Numériser",
        "de": "Scannen",
        "zh": "扫描",
        "ja": "スキャン",
        "ru": "Сканировать",
        "it": "Scansiona",
        "el": "Σάρωση",
        "ar": "مسح ضوئي",
        "gl": "Dixitalizar",
        "ca": "Escanejar",
        "eu": "Eskaneatu",
    },
    "herr_escanear_desc": {
        "en": "Photos to searchable PDF",
        "es": "Fotos a PDF con texto buscable",
        "fr": "Photos en PDF avec texte recherchable",
        "de": "Fotos zu durchsuchbarem PDF",
        "zh": "照片转为可搜索的 PDF",
        "ja": "写真を検索できる PDF に",
        "ru": "Фото в PDF с поиском по тексту",
        "it": "Foto in PDF con testo ricercabile",
        "el": "Φωτογραφίες σε PDF με αναζητήσιμο κείμενο",
        "ar": "صور إلى PDF نصه قابل للبحث",
        "gl": "Fotos a PDF con texto buscable",
        "ca": "Fotos a PDF amb text cercable",
        "eu": "Argazkiak bilagarria den testua duen PDF bihurtu",
    },

    # --- Permiso de cámara ---------------------------------------------------
    "esc_permiso_titulo": {
        "en": "The scanner needs the camera",
        "es": "El escáner necesita la cámara",
        "fr": "Le scanner a besoin de l’appareil photo",
        "de": "Der Scanner braucht die Kamera",
        "zh": "扫描需要使用相机",
        "ja": "スキャンにはカメラが必要です",
        "ru": "Сканеру нужна камера",
        "it": "Lo scanner ha bisogno della fotocamera",
        "el": "Ο σαρωτής χρειάζεται την κάμερα",
        "ar": "الماسح الضوئي يحتاج إلى الكاميرا",
        "gl": "O dixitalizador precisa a cámara",
        "ca": "L’escàner necessita la càmera",
        "eu": "Eskanerrak kamera behar du",
    },
    "esc_permiso_detalle": {
        "en": "It is used only here, to find the edges of the paper while you aim. "
              "The photos stay on your phone: the app has no internet permission.",
        "es": "Se usa sólo aquí, para encontrar los bordes del papel mientras apuntas. "
              "Las fotos se quedan en el teléfono: la aplicación no tiene permiso de internet.",
        "fr": "Il ne sert qu’ici, pour trouver les bords de la feuille pendant que vous visez. "
              "Les photos restent sur le téléphone : l’application n’a pas la permission internet.",
        "de": "Sie wird nur hier verwendet, um die Ränder des Blattes beim Zielen zu finden. "
              "Die Fotos bleiben auf dem Telefon: Die App hat keine Internetberechtigung.",
        "zh": "只在这里使用，用于在取景时找到纸张边缘。照片留在手机上："
              "本应用没有联网权限。",
        "ja": "ここでのみ使用し、紙の端を見つけるために使います。写真は端末に残ります。"
              "このアプリにはインターネット権限がありません。",
        "ru": "Используется только здесь, чтобы находить края листа при наведении. "
              "Фотографии остаются в телефоне: у приложения нет разрешения на интернет.",
        "it": "Si usa solo qui, per trovare i bordi del foglio mentre inquadri. "
              "Le foto restano sul telefono: l’app non ha il permesso di internet.",
        "el": "Χρησιμοποιείται μόνο εδώ, για να βρίσκει τις άκρες του χαρτιού καθώς στοχεύετε. "
              "Οι φωτογραφίες μένουν στο τηλέφωνο: η εφαρμογή δεν έχει άδεια internet.",
        "ar": "تُستخدم هنا فقط، للعثور على حواف الورقة أثناء التصويب. "
              "تبقى الصور في هاتفك: التطبيق لا يملك إذن الإنترنت.",
        "gl": "Úsase só aquí, para atopar os bordos do papel mentres apuntas. "
              "As fotos quedan no teléfono: a aplicación non ten permiso de internet.",
        "ca": "Només s’usa aquí, per trobar les vores del paper mentre apuntes. "
              "Les fotos es queden al telèfon: l’aplicació no té permís d’internet.",
        "eu": "Hemen bakarrik erabiltzen da, paperaren ertzak aurkitzeko apuntatzen duzun bitartean. "
              "Argazkiak telefonoan geratzen dira: aplikazioak ez du interneterako baimenik.",
    },
    "esc_permiso_conceder": {
        "en": "Allow the camera",
        "es": "Permitir la cámara",
        "fr": "Autoriser l’appareil photo",
        "de": "Kamera erlauben",
        "zh": "允许使用相机",
        "ja": "カメラを許可",
        "ru": "Разрешить камеру",
        "it": "Consenti la fotocamera",
        "el": "Να επιτραπεί η κάμερα",
        "ar": "السماح بالكاميرا",
        "gl": "Permitir a cámara",
        "ca": "Permet la càmera",
        "eu": "Baimendu kamera",
    },
    "esc_permiso_denegado": {
        "en": "Without the camera you can still scan photos from the gallery.",
        "es": "Sin la cámara puedes escanear igualmente fotos de la galería.",
        "fr": "Sans l’appareil photo, vous pouvez quand même numériser des photos de la galerie.",
        "de": "Ohne Kamera können Sie trotzdem Fotos aus der Galerie scannen.",
        "zh": "不使用相机，仍然可以从相册选择照片来扫描。",
        "ja": "カメラを使わなくても、ギャラリーの写真をスキャンできます。",
        "ru": "Без камеры можно сканировать фотографии из галереи.",
        "it": "Senza fotocamera puoi comunque scansionare foto dalla galleria.",
        "el": "Χωρίς κάμερα μπορείτε να σαρώσετε φωτογραφίες από τη συλλογή.",
        "ar": "بدون الكاميرا يمكنك مسح صور من المعرض.",
        "gl": "Sen a cámara podes dixitalizar igualmente fotos da galería.",
        "ca": "Sense la càmera pots escanejar igualment fotos de la galeria.",
        "eu": "Kamerarik gabe ere galeriako argazkiak eskaneatu ditzakezu.",
    },
    "esc_sin_camara": {
        "en": "This device has no usable camera",
        "es": "Este dispositivo no tiene una cámara utilizable",
        "fr": "Cet appareil n’a pas d’appareil photo utilisable",
        "de": "Dieses Gerät hat keine nutzbare Kamera",
        "zh": "此设备没有可用的相机",
        "ja": "この端末には使えるカメラがありません",
        "ru": "На этом устройстве нет пригодной камеры",
        "it": "Questo dispositivo non ha una fotocamera utilizzabile",
        "el": "Αυτή η συσκευή δεν έχει αξιοποιήσιμη κάμερα",
        "ar": "لا توجد كاميرا صالحة في هذا الجهاز",
        "gl": "Este dispositivo non ten unha cámara utilizable",
        "ca": "Aquest dispositiu no té una càmera utilitzable",
        "eu": "Gailu honek ez du kamera erabilgarririk",
    },

    # --- Visor ---------------------------------------------------------------
    "esc_titulo": {
        "en": "Scan document",
        "es": "Escanear documento",
        "fr": "Numériser un document",
        "de": "Dokument scannen",
        "zh": "扫描文档",
        "ja": "書類をスキャン",
        "ru": "Сканировать документ",
        "it": "Scansiona documento",
        "el": "Σάρωση εγγράφου",
        "ar": "مسح مستند",
        "gl": "Dixitalizar documento",
        "ca": "Escaneja un document",
        "eu": "Eskaneatu dokumentua",
    },
    "esc_buscando": {
        "en": "Looking for the document",
        "es": "Buscando el documento",
        "fr": "Recherche du document",
        "de": "Dokument wird gesucht",
        "zh": "正在寻找文档",
        "ja": "書類を探しています",
        "ru": "Ищем документ",
        "it": "Ricerca del documento",
        "el": "Αναζήτηση του εγγράφου",
        "ar": "البحث عن المستند",
        "gl": "Buscando o documento",
        "ca": "S’està buscant el document",
        "eu": "Dokumentua bilatzen",
    },
    "esc_encuadrando": {
        "en": "Hold steady",
        "es": "Mantén el pulso",
        "fr": "Ne bougez plus",
        "de": "Ruhig halten",
        "zh": "请保持稳定",
        "ja": "そのまま静止してください",
        "ru": "Держите ровно",
        "it": "Tieni fermo",
        "el": "Κρατήστε σταθερά",
        "ar": "حافظ على ثبات اليد",
        "gl": "Mantén o pulso",
        "ca": "Aguanta el pols",
        "eu": "Eutsi geldi",
    },
    "esc_listo": {
        "en": "Ready",
        "es": "Listo",
        "fr": "Prêt",
        "de": "Bereit",
        "zh": "就绪",
        "ja": "準備完了",
        "ru": "Готово",
        "it": "Pronto",
        "el": "Έτοιμο",
        "ar": "جاهز",
        "gl": "Listo",
        "ca": "A punt",
        "eu": "Prest",
    },
    # Un solo % y no %%: el formateador de Compose Resources sustituye los
    # marcadores indexados pero no colapsa el doble porcentaje de Android, asi
    # que escribirlo duplicado salia duplicado en pantalla.
    "esc_porcentaje": {
        "en": "%1$d%",
        "es": "%1$d %",
        "fr": "%1$d %",
        "de": "%1$d %",
        "zh": "%1$d%",
        "ja": "%1$d%",
        "ru": "%1$d %",
        "it": "%1$d%",
        "el": "%1$d%",
        "ar": "%1$d%",
        "gl": "%1$d %",
        "ca": "%1$d %",
        "eu": "% %1$d",
    },
    "esc_deteccion": {
        "en": "Edge detection",
        "es": "Detección del borde",
        "fr": "Détection du bord",
        "de": "Kantenerkennung",
        "zh": "边缘识别度",
        "ja": "輪郭の検出度",
        "ru": "Распознавание края",
        "it": "Rilevamento del bordo",
        "el": "Ανίχνευση περιγράμματος",
        "ar": "اكتشاف الحواف",
        "gl": "Detección do bordo",
        "ca": "Detecció de la vora",
        "eu": "Ertzaren detekzioa",
    },
    "esc_consejo": {
        "en": "Put the paper on a surface of a different colour",
        "es": "Pon el papel sobre una superficie de otro color",
        "fr": "Posez la feuille sur une surface d’une autre couleur",
        "de": "Legen Sie das Blatt auf eine andersfarbige Fläche",
        "zh": "把纸放在颜色不同的平面上",
        "ja": "紙は色の違う面の上に置いてください",
        "ru": "Положите лист на поверхность другого цвета",
        "it": "Metti il foglio su una superficie di un altro colore",
        "el": "Βάλτε το χαρτί σε επιφάνεια άλλου χρώματος",
        "ar": "ضع الورقة على سطح بلون مختلف",
        "gl": "Pon o papel sobre unha superficie doutra cor",
        "ca": "Posa el paper sobre una superfície d’un altre color",
        "eu": "Jarri papera beste kolore bateko gainazal batean",
    },
    "esc_capturar": {
        "en": "Take the photo",
        "es": "Hacer la foto",
        "fr": "Prendre la photo",
        "de": "Foto aufnehmen",
        "zh": "拍照",
        "ja": "撮影する",
        "ru": "Сделать снимок",
        "it": "Scatta la foto",
        "el": "Λήψη φωτογραφίας",
        "ar": "التقاط الصورة",
        "gl": "Facer a foto",
        "ca": "Fes la foto",
        "eu": "Atera argazkia",
    },
    "esc_linterna": {
        "en": "Flash",
        "es": "Linterna",
        "fr": "Lampe",
        "de": "Licht",
        "zh": "补光灯",
        "ja": "ライト",
        "ru": "Подсветка",
        "it": "Torcia",
        "el": "Φακός",
        "ar": "الإضاءة",
        "gl": "Lanterna",
        "ca": "Llanterna",
        "eu": "Linterna",
    },
    "esc_automatica": {
        "en": "Auto capture",
        "es": "Captura automática",
        "fr": "Capture auto",
        "de": "Autoaufnahme",
        "zh": "自动拍摄",
        "ja": "自動撮影",
        "ru": "Автосъёмка",
        "it": "Scatto automatico",
        "el": "Αυτόματη λήψη",
        "ar": "التقاط تلقائي",
        "gl": "Captura automática",
        "ca": "Captura automàtica",
        "eu": "Kaptura automatikoa",
    },
    "esc_modo_auto": {
        "en": "Auto",
        "es": "Auto",
        "fr": "Auto",
        "de": "Auto",
        "zh": "自动",
        "ja": "自動",
        "ru": "Авто",
        "it": "Auto",
        "el": "Αυτόματο",
        "ar": "تلقائي",
        "gl": "Auto",
        "ca": "Auto",
        "eu": "Auto",
    },
    "esc_modo_manual": {
        "en": "Manual",
        "es": "Manual",
        "fr": "Manuel",
        "de": "Manuell",
        "zh": "手动",
        "ja": "手動",
        "ru": "Вручную",
        "it": "Manuale",
        "el": "Χειροκίνητο",
        "ar": "يدوي",
        "gl": "Manual",
        "ca": "Manual",
        "eu": "Eskuz",
    },
    "esc_siguiente_hoja": {
        "en": "Next sheet, please",
        "es": "Pon la hoja siguiente",
        "fr": "Passez à la feuille suivante",
        "de": "Nächstes Blatt",
        "zh": "请换下一页",
        "ja": "次の紙をどうぞ",
        "ru": "Положите следующий лист",
        "it": "Metti il foglio successivo",
        "el": "Βάλτε το επόμενο φύλλο",
        "ar": "ضع الورقة التالية",
        "gl": "Pon a folla seguinte",
        "ca": "Posa el full següent",
        "eu": "Jarri hurrengo orria",
    },
    "esc_galeria": {
        "en": "Gallery",
        "es": "Galería",
        "fr": "Galerie",
        "de": "Galerie",
        "zh": "相册",
        "ja": "ギャラリー",
        "ru": "Галерея",
        "it": "Galleria",
        "el": "Συλλογή",
        "ar": "المعرض",
        "gl": "Galería",
        "ca": "Galeria",
        "eu": "Galeria",
    },
    "esc_continuar": {
        "en": "Continue",
        "es": "Continuar",
        "fr": "Continuer",
        "de": "Weiter",
        "zh": "继续",
        "ja": "次へ",
        "ru": "Далее",
        "it": "Continua",
        "el": "Συνέχεια",
        "ar": "متابعة",
        "gl": "Continuar",
        "ca": "Continua",
        "eu": "Jarraitu",
    },
    "esc_capturada": {
        "en": "Page %1$d captured",
        "es": "Página %1$d capturada",
        "fr": "Page %1$d capturée",
        "de": "Seite %1$d aufgenommen",
        "zh": "已拍摄第 %1$d 页",
        "ja": "%1$d ページ目を撮影しました",
        "ru": "Страница %1$d снята",
        "it": "Pagina %1$d acquisita",
        "el": "Η σελίδα %1$d καταγράφηκε",
        "ar": "تم التقاط الصفحة %1$d",
        "gl": "Páxina %1$d capturada",
        "ca": "Pàgina %1$d capturada",
        "eu": "%1$d. orria hartuta",
    },

    # --- Revisión ------------------------------------------------------------
    "esc_salir_titulo": {
        "en": "Leave without creating the PDF?",
        "es": "¿Salir sin crear el PDF?",
        "fr": "Quitter sans créer le PDF ?",
        "de": "Ohne PDF zu erstellen verlassen?",
        "zh": "还没生成 PDF，要退出吗？",
        "ja": "PDF を作らずに出ますか？",
        "ru": "Выйти, не создав PDF?",
        "it": "Uscire senza creare il PDF?",
        "el": "Έξοδος χωρίς να δημιουργηθεί το PDF;",
        "ar": "الخروج دون إنشاء PDF؟",
        "gl": "Saír sen crear o PDF?",
        "ca": "Vols sortir sense crear el PDF?",
        "eu": "Irten PDFa sortu gabe?",
    },
    "esc_salir_detalle": {
        "en": "The pages you have scanned will be discarded.",
        "es": "Las páginas que has escaneado se descartan.",
        "fr": "Les pages numérisées seront écartées.",
        "de": "Die gescannten Seiten werden verworfen.",
        "zh": "已经扫描的页面会被丢弃。",
        "ja": "スキャン済みのページは破棄されます。",
        "ru": "Отсканированные страницы будут отброшены.",
        "it": "Le pagine scansionate verranno scartate.",
        "el": "Οι σελίδες που σαρώσατε θα απορριφθούν.",
        "ar": "سيتم تجاهل الصفحات التي مسحتها.",
        "gl": "As páxinas que dixitalizaches descártanse.",
        "ca": "Les pàgines que has escanejat es descarten.",
        "eu": "Eskaneatu dituzun orriak baztertu egingo dira.",
    },
    "esc_salir_confirmar": {
        "en": "Discard",
        "es": "Descartar",
        "fr": "Écarter",
        "de": "Verwerfen",
        "zh": "丢弃",
        "ja": "破棄",
        "ru": "Отбросить",
        "it": "Scarta",
        "el": "Απόρριψη",
        "ar": "تجاهل",
        "gl": "Descartar",
        "ca": "Descarta",
        "eu": "Baztertu",
    },
    "esc_rev_titulo": {
        "en": "Review the scan",
        "es": "Revisar el escaneo",
        "fr": "Vérifier la numérisation",
        "de": "Scan prüfen",
        "zh": "检查扫描结果",
        "ja": "スキャンを確認",
        "ru": "Проверить скан",
        "it": "Rivedi la scansione",
        "el": "Έλεγχος της σάρωσης",
        "ar": "مراجعة المسح",
        "gl": "Revisar a dixitalización",
        "ca": "Revisa l’escaneig",
        "eu": "Berrikusi eskaneatua",
    },
    "esc_rev_pagina": {
        "en": "Page %1$d of %2$d",
        "es": "Página %1$d de %2$d",
        "fr": "Page %1$d sur %2$d",
        "de": "Seite %1$d von %2$d",
        "zh": "第 %1$d 页，共 %2$d 页",
        "ja": "%2$d ページ中 %1$d ページ目",
        "ru": "Страница %1$d из %2$d",
        "it": "Pagina %1$d di %2$d",
        "el": "Σελίδα %1$d από %2$d",
        "ar": "الصفحة %1$d من %2$d",
        "gl": "Páxina %1$d de %2$d",
        "ca": "Pàgina %1$d de %2$d",
        "eu": "%2$d orritik %1$d.",
    },
    "esc_rev_ajustar": {
        "en": "Adjust edges",
        "es": "Ajustar bordes",
        "fr": "Ajuster les bords",
        "de": "Ränder anpassen",
        "zh": "调整边缘",
        "ja": "枠を調整",
        "ru": "Поправить края",
        "it": "Regola i bordi",
        "el": "Προσαρμογή άκρων",
        "ar": "ضبط الحواف",
        "gl": "Axustar bordos",
        "ca": "Ajusta les vores",
        "eu": "Doitu ertzak",
    },
    "esc_rev_hecho": {
        "en": "Done",
        "es": "Hecho",
        "fr": "Terminé",
        "de": "Fertig",
        "zh": "完成",
        "ja": "完了",
        "ru": "Готово",
        "it": "Fatto",
        "el": "Έτοιμο",
        "ar": "تم",
        "gl": "Feito",
        "ca": "Fet",
        "eu": "Eginda",
    },
    "esc_rev_todo": {
        "en": "Whole photo",
        "es": "Foto entera",
        "fr": "Photo entière",
        "de": "Ganzes Foto",
        "zh": "整张照片",
        "ja": "写真全体",
        "ru": "Всё фото",
        "it": "Foto intera",
        "el": "Όλη η φωτογραφία",
        "ar": "الصورة كاملة",
        "gl": "Foto enteira",
        "ca": "Foto sencera",
        "eu": "Argazki osoa",
    },
    "esc_rev_detectar": {
        "en": "Detect again",
        "es": "Detectar otra vez",
        "fr": "Détecter à nouveau",
        "de": "Erneut erkennen",
        "zh": "重新识别",
        "ja": "もう一度検出",
        "ru": "Определить заново",
        "it": "Rileva di nuovo",
        "el": "Ανίχνευση ξανά",
        "ar": "إعادة الاكتشاف",
        "gl": "Detectar outra vez",
        "ca": "Detecta un altre cop",
        "eu": "Detektatu berriro",
    },
    "esc_rev_girar": {
        "en": "Rotate",
        "es": "Girar",
        "fr": "Pivoter",
        "de": "Drehen",
        "zh": "旋转",
        "ja": "回転",
        "ru": "Повернуть",
        "it": "Ruota",
        "el": "Περιστροφή",
        "ar": "تدوير",
        "gl": "Xirar",
        "ca": "Gira",
        "eu": "Biratu",
    },
    "esc_rev_eliminar": {
        "en": "Delete page",
        "es": "Eliminar página",
        "fr": "Supprimer la page",
        "de": "Seite löschen",
        "zh": "删除此页",
        "ja": "ページを削除",
        "ru": "Удалить страницу",
        "it": "Elimina pagina",
        "el": "Διαγραφή σελίδας",
        "ar": "حذف الصفحة",
        "gl": "Eliminar páxina",
        "ca": "Elimina la pàgina",
        "eu": "Ezabatu orria",
    },
    "esc_rev_anadir": {
        "en": "Add page",
        "es": "Añadir página",
        "fr": "Ajouter une page",
        "de": "Seite hinzufügen",
        "zh": "添加页面",
        "ja": "ページを追加",
        "ru": "Добавить страницу",
        "it": "Aggiungi pagina",
        "el": "Προσθήκη σελίδας",
        "ar": "إضافة صفحة",
        "gl": "Engadir páxina",
        "ca": "Afegeix una pàgina",
        "eu": "Gehitu orria",
    },
    "esc_rev_mejora": {
        "en": "Enhancement",
        "es": "Mejora",
        "fr": "Amélioration",
        "de": "Verbesserung",
        "zh": "画面增强",
        "ja": "補正",
        "ru": "Улучшение",
        "it": "Miglioramento",
        "el": "Βελτίωση",
        "ar": "التحسين",
        "gl": "Mellora",
        "ca": "Millora",
        "eu": "Hobekuntza",
    },
    "esc_rev_intensidad": {
        "en": "Strength",
        "es": "Intensidad",
        "fr": "Intensité",
        "de": "Stärke",
        "zh": "强度",
        "ja": "強さ",
        "ru": "Сила",
        "it": "Intensità",
        "el": "Ένταση",
        "ar": "الشدة",
        "gl": "Intensidade",
        "ca": "Intensitat",
        "eu": "Intentsitatea",
    },
    "esc_rev_crear": {
        "en": "Create PDF",
        "es": "Crear PDF",
        "fr": "Créer le PDF",
        "de": "PDF erstellen",
        "zh": "生成 PDF",
        "ja": "PDF を作成",
        "ru": "Создать PDF",
        "it": "Crea PDF",
        "el": "Δημιουργία PDF",
        "ar": "إنشاء PDF",
        "gl": "Crear PDF",
        "ca": "Crea el PDF",
        "eu": "Sortu PDFa",
    },
    "esc_rev_borrar_titulo": {
        "en": "Delete this page?",
        "es": "¿Eliminar esta página?",
        "fr": "Supprimer cette page ?",
        "de": "Diese Seite löschen?",
        "zh": "要删除这一页吗？",
        "ja": "このページを削除しますか？",
        "ru": "Удалить эту страницу?",
        "it": "Eliminare questa pagina?",
        "el": "Διαγραφή αυτής της σελίδας;",
        "ar": "هل تحذف هذه الصفحة؟",
        "gl": "Eliminar esta páxina?",
        "ca": "Voleu eliminar aquesta pàgina?",
        "eu": "Orri hau ezabatu?",
    },
    "esc_rev_borrar_detalle": {
        "en": "The photo is discarded. The rest of the scan is untouched.",
        "es": "La foto se descarta. El resto del escaneo no cambia.",
        "fr": "La photo est écartée. Le reste de la numérisation ne change pas.",
        "de": "Das Foto wird verworfen. Der Rest des Scans bleibt unverändert.",
        "zh": "这张照片会被丢弃，扫描的其余部分不受影响。",
        "ja": "この写真は破棄されます。ほかのページはそのままです。",
        "ru": "Фотография будет отброшена. Остальные страницы не изменятся.",
        "it": "La foto viene scartata. Il resto della scansione non cambia.",
        "el": "Η φωτογραφία απορρίπτεται. Η υπόλοιπη σάρωση δεν αλλάζει.",
        "ar": "سيتم تجاهل الصورة. بقية المسح لا تتغير.",
        "gl": "A foto descártase. O resto da dixitalización non cambia.",
        "ca": "La foto es descarta. La resta de l’escaneig no canvia.",
        "eu": "Argazkia baztertu egingo da. Eskaneatuaren gainerakoa ez da aldatzen.",
    },
    "esc_rev_aviso_borde": {
        "en": "The edge was not found clearly. Check it before creating the PDF.",
        "es": "El borde no se ha detectado bien. Compruébalo antes de crear el PDF.",
        "fr": "Le bord n’a pas été bien détecté. Vérifiez-le avant de créer le PDF.",
        "de": "Der Rand wurde nicht sicher erkannt. Prüfen Sie ihn vor dem Erstellen.",
        "zh": "边缘识别得不够可靠，生成 PDF 前请先确认。",
        "ja": "輪郭をうまく検出できませんでした。PDF を作る前に確認してください。",
        "ru": "Край распознан неуверенно. Проверьте его перед созданием PDF.",
        "it": "Il bordo non è stato rilevato bene. Controllalo prima di creare il PDF.",
        "el": "Το περίγραμμα δεν εντοπίστηκε καθαρά. Ελέγξτε το πριν τη δημιουργία.",
        "ar": "لم يُكتشف الحد بوضوح. تحقق منه قبل إنشاء PDF.",
        "gl": "O bordo non se detectou ben. Compróbao antes de crear o PDF.",
        "ca": "La vora no s’ha detectat bé. Comprova-la abans de crear el PDF.",
        "eu": "Ertza ez da ondo detektatu. Egiaztatu PDFa sortu aurretik.",
    },
    "esc_rev_vacio": {
        "en": "No pages left",
        "es": "No queda ninguna página",
        "fr": "Il ne reste aucune page",
        "de": "Keine Seiten mehr",
        "zh": "已经没有页面了",
        "ja": "ページが残っていません",
        "ru": "Не осталось ни одной страницы",
        "it": "Non è rimasta nessuna pagina",
        "el": "Δεν έμεινε καμία σελίδα",
        "ar": "لم تبقَ أي صفحة",
        "gl": "Non queda ningunha páxina",
        "ca": "No queda cap pàgina",
        "eu": "Ez da orririk geratzen",
    },

    # --- Guardar -------------------------------------------------------------
    "esc_nombre_titulo": {
        "en": "Save as",
        "es": "Guardar como",
        "fr": "Enregistrer sous",
        "de": "Speichern unter",
        "zh": "另存为",
        "ja": "名前を付けて保存",
        "ru": "Сохранить как",
        "it": "Salva con nome",
        "el": "Αποθήκευση ως",
        "ar": "حفظ باسم",
        "gl": "Gardar como",
        "ca": "Desa com a",
        "eu": "Gorde honela",
    },
    "esc_nombre_etiqueta": {
        "en": "Document name",
        "es": "Nombre del documento",
        "fr": "Nom du document",
        "de": "Name des Dokuments",
        "zh": "文档名称",
        "ja": "書類の名前",
        "ru": "Название документа",
        "it": "Nome del documento",
        "el": "Όνομα εγγράφου",
        "ar": "اسم المستند",
        "gl": "Nome do documento",
        "ca": "Nom del document",
        "eu": "Dokumentuaren izena",
    },
    "esc_nombre_vacio": {
        "en": "Type a name",
        "es": "Escribe un nombre",
        "fr": "Saisissez un nom",
        "de": "Geben Sie einen Namen ein",
        "zh": "请输入名称",
        "ja": "名前を入力してください",
        "ru": "Введите название",
        "it": "Scrivi un nome",
        "el": "Γράψτε ένα όνομα",
        "ar": "اكتب اسمًا",
        "gl": "Escribe un nome",
        "ca": "Escriu un nom",
        "eu": "Idatzi izen bat",
    },
    "esc_ocr_titulo": {
        "en": "Searchable text",
        "es": "Texto buscable",
        "fr": "Texte recherchable",
        "de": "Durchsuchbarer Text",
        "zh": "可搜索的文字",
        "ja": "検索できる文字",
        "ru": "Текст с поиском",
        "it": "Testo ricercabile",
        "el": "Αναζητήσιμο κείμενο",
        "ar": "نص قابل للبحث",
        "gl": "Texto buscable",
        "ca": "Text cercable",
        "eu": "Testu bilagarria",
    },
    "esc_ocr_detalle": {
        "en": "Reads the words so you can search and copy them. Done on the phone, "
              "and it adds a few seconds per page.",
        "es": "Lee las palabras para poder buscarlas y copiarlas. Se hace en el teléfono, "
              "y añade unos segundos por página.",
        "fr": "Lit les mots pour pouvoir les rechercher et les copier. Fait sur le téléphone, "
              "cela ajoute quelques secondes par page.",
        "de": "Liest die Wörter, damit Sie sie suchen und kopieren können. Geschieht auf dem "
              "Gerät und dauert ein paar Sekunden pro Seite.",
        "zh": "识别文字，让你可以搜索和复制。在手机上完成，每页多花几秒钟。",
        "ja": "文字を読み取って検索やコピーができるようにします。端末内で処理し、"
              "1 ページにつき数秒かかります。",
        "ru": "Распознаёт слова, чтобы их можно было искать и копировать. Всё в телефоне, "
              "занимает несколько секунд на страницу.",
        "it": "Legge le parole per poterle cercare e copiare. Avviene sul telefono e "
              "aggiunge qualche secondo per pagina.",
        "el": "Διαβάζει τις λέξεις ώστε να μπορείτε να τις αναζητήσετε και να τις αντιγράψετε. "
              "Γίνεται στο τηλέφωνο και προσθέτει λίγα δευτερόλεπτα ανά σελίδα.",
        "ar": "يقرأ الكلمات لتتمكن من البحث فيها ونسخها. يتم على الهاتف ويضيف بضع ثوانٍ لكل صفحة.",
        "gl": "Le as palabras para poder buscalas e copialas. Faise no teléfono e engade "
              "uns segundos por páxina.",
        "ca": "Llegeix les paraules per poder cercar-les i copiar-les. Es fa al telèfon i "
              "afegeix uns segons per pàgina.",
        "eu": "Hitzak irakurtzen ditu bilatu eta kopiatu ahal izateko. Telefonoan egiten da "
              "eta segundo batzuk gehitzen ditu orriko.",
    },
    "esc_ocr_no_disponible": {
        "en": "This device cannot recognise text",
        "es": "Este dispositivo no sabe reconocer texto",
        "fr": "Cet appareil ne sait pas reconnaître le texte",
        "de": "Dieses Gerät kann keinen Text erkennen",
        "zh": "此设备无法识别文字",
        "ja": "この端末では文字を認識できません",
        "ru": "Это устройство не умеет распознавать текст",
        "it": "Questo dispositivo non sa riconoscere il testo",
        "el": "Αυτή η συσκευή δεν μπορεί να αναγνωρίσει κείμενο",
        "ar": "هذا الجهاز لا يستطيع التعرف على النص",
        "gl": "Este dispositivo non sabe recoñecer texto",
        "ca": "Aquest dispositiu no sap reconèixer text",
        "eu": "Gailu honek ezin du testua ezagutu",
    },
    "esc_tamano": {
        "en": "Page size",
        "es": "Tamaño de página",
        "fr": "Format de page",
        "de": "Seitenformat",
        "zh": "页面尺寸",
        "ja": "ページの大きさ",
        "ru": "Размер страницы",
        "it": "Formato pagina",
        "el": "Μέγεθος σελίδας",
        "ar": "حجم الصفحة",
        "gl": "Tamaño de páxina",
        "ca": "Mida de pàgina",
        "eu": "Orriaren tamaina",
    },
    "esc_tamano_escaneo": {
        "en": "Like the paper",
        "es": "Como el papel",
        "fr": "Comme la feuille",
        "de": "Wie das Blatt",
        "zh": "与纸张一致",
        "ja": "紙と同じ",
        "ru": "Как у листа",
        "it": "Come il foglio",
        "el": "Όπως το χαρτί",
        "ar": "مثل الورقة",
        "gl": "Como o papel",
        "ca": "Com el paper",
        "eu": "Paperaren berdina",
    },

    # --- Trabajo en curso ----------------------------------------------------
    "esc_preparando": {
        "en": "Straightening the pages…",
        "es": "Enderezando las páginas…",
        "fr": "Redressement des pages…",
        "de": "Seiten werden begradigt…",
        "zh": "正在校正页面…",
        "ja": "ページを補正しています…",
        "ru": "Выравниваем страницы…",
        "it": "Raddrizzamento delle pagine…",
        "el": "Ισιώνονται οι σελίδες…",
        "ar": "جارٍ تعديل الصفحات…",
        "gl": "Endereitando as páxinas…",
        "ca": "S’estan redreçant les pàgines…",
        "eu": "Orriak zuzentzen…",
    },
    "esc_leyendo": {
        "en": "Reading the text…",
        "es": "Leyendo el texto…",
        "fr": "Lecture du texte…",
        "de": "Text wird gelesen…",
        "zh": "正在识别文字…",
        "ja": "文字を読み取っています…",
        "ru": "Распознаём текст…",
        "it": "Lettura del testo…",
        "el": "Ανάγνωση του κειμένου…",
        "ar": "جارٍ قراءة النص…",
        "gl": "Lendo o texto…",
        "ca": "S’està llegint el text…",
        "eu": "Testua irakurtzen…",
    },
    "esc_montando": {
        "en": "Building the document…",
        "es": "Montando el documento…",
        "fr": "Assemblage du document…",
        "de": "Dokument wird erstellt…",
        "zh": "正在生成文档…",
        "ja": "書類を作成しています…",
        "ru": "Собираем документ…",
        "it": "Composizione del documento…",
        "el": "Δημιουργία του εγγράφου…",
        "ar": "جارٍ تجميع المستند…",
        "gl": "Montando o documento…",
        "ca": "S’està muntant el document…",
        "eu": "Dokumentua osatzen…",
    },
    "esc_sin_texto": {
        "en": "No text was recognised. The PDF keeps the images.",
        "es": "No se ha reconocido ningún texto. El PDF conserva las imágenes.",
        "fr": "Aucun texte reconnu. Le PDF conserve les images.",
        "de": "Es wurde kein Text erkannt. Das PDF behält die Bilder.",
        "zh": "没有识别到文字，PDF 仍然保留图像。",
        "ja": "文字を認識できませんでした。PDF には画像がそのまま残ります。",
        "ru": "Текст не распознан. PDF сохраняет изображения.",
        "it": "Non è stato riconosciuto alcun testo. Il PDF conserva le immagini.",
        "el": "Δεν αναγνωρίστηκε κείμενο. Το PDF διατηρεί τις εικόνες.",
        "ar": "لم يُتعرف على أي نص. يحتفظ ملف PDF بالصور.",
        "gl": "Non se recoñeceu ningún texto. O PDF conserva as imaxes.",
        "ca": "No s’ha reconegut cap text. El PDF conserva les imatges.",
        "eu": "Ez da testurik ezagutu. PDFak irudiak gordetzen ditu.",
    },

    # --- Ajustes -------------------------------------------------------------
    "aj_seccion_escaner": {
        "en": "Scanner",
        "es": "Escáner",
        "fr": "Scanner",
        "de": "Scanner",
        "zh": "扫描",
        "ja": "スキャナー",
        "ru": "Сканер",
        "it": "Scanner",
        "el": "Σαρωτής",
        "ar": "الماسح الضوئي",
        "gl": "Dixitalizador",
        "ca": "Escàner",
        "eu": "Eskanerra",
    },
    "aj_escaner_ocr": {
        "en": "Searchable text by default",
        "es": "Texto buscable por defecto",
        "fr": "Texte recherchable par défaut",
        "de": "Standardmäßig durchsuchbarer Text",
        "zh": "默认生成可搜索的文字",
        "ja": "既定で検索できる文字にする",
        "ru": "Текст с поиском по умолчанию",
        "it": "Testo ricercabile per impostazione predefinita",
        "el": "Αναζητήσιμο κείμενο από προεπιλογή",
        "ar": "نص قابل للبحث افتراضيًا",
        "gl": "Texto buscable por defecto",
        "ca": "Text cercable per defecte",
        "eu": "Testu bilagarria lehenetsita",
    },
    "aj_escaner_ocr_desc": {
        "en": "Recognise the words of every scan. A few seconds per page.",
        "es": "Reconocer las palabras de cada escaneo. Unos segundos por página.",
        "fr": "Reconnaître les mots de chaque numérisation. Quelques secondes par page.",
        "de": "Die Wörter jedes Scans erkennen. Einige Sekunden pro Seite.",
        "zh": "识别每次扫描中的文字，每页多花几秒钟。",
        "ja": "スキャンごとに文字を読み取ります。1 ページにつき数秒。",
        "ru": "Распознавать слова в каждом скане. Несколько секунд на страницу.",
        "it": "Riconoscere le parole di ogni scansione. Qualche secondo per pagina.",
        "el": "Αναγνώριση των λέξεων κάθε σάρωσης. Λίγα δευτερόλεπτα ανά σελίδα.",
        "ar": "التعرف على كلمات كل عملية مسح. بضع ثوانٍ لكل صفحة.",
        "gl": "Recoñecer as palabras de cada dixitalización. Uns segundos por páxina.",
        "ca": "Reconèixer les paraules de cada escaneig. Uns segons per pàgina.",
        "eu": "Eskaneatze bakoitzeko hitzak ezagutu. Segundo batzuk orriko.",
    },
    "aj_escaner_auto": {
        "en": "Auto capture",
        "es": "Captura automática",
        "fr": "Capture automatique",
        "de": "Automatische Aufnahme",
        "zh": "自动拍摄",
        "ja": "自動撮影",
        "ru": "Автоматическая съёмка",
        "it": "Scatto automatico",
        "el": "Αυτόματη λήψη",
        "ar": "التقاط تلقائي",
        "gl": "Captura automática",
        "ca": "Captura automàtica",
        "eu": "Kaptura automatikoa",
    },
    "aj_escaner_auto_desc": {
        "en": "Shoot on its own when the paper is well framed.",
        "es": "Disparar solo cuando el papel esté bien encuadrado.",
        "fr": "Déclencher tout seul quand la feuille est bien cadrée.",
        "de": "Von selbst auslösen, wenn das Blatt gut im Bild ist.",
        "zh": "当纸张取景良好时自动按下快门。",
        "ja": "紙がきれいに収まったら自動でシャッターを切ります。",
        "ru": "Снимать самостоятельно, когда лист хорошо в кадре.",
        "it": "Scattare da solo quando il foglio è ben inquadrato.",
        "el": "Να τραβά μόνο του όταν το χαρτί είναι καλά καδραρισμένο.",
        "ar": "يلتقط تلقائيًا عندما تكون الورقة مؤطرة جيدًا.",
        "gl": "Disparar só cando o papel estea ben encadrado.",
        "ca": "Disparar sol quan el paper estigui ben enquadrat.",
        "eu": "Bakarrik atera papera ondo enkoadratuta dagoenean.",
    },
    "aj_escaner_filtro": {
        "en": "Default enhancement",
        "es": "Mejora por defecto",
        "fr": "Amélioration par défaut",
        "de": "Standardverbesserung",
        "zh": "默认增强方式",
        "ja": "既定の補正",
        "ru": "Улучшение по умолчанию",
        "it": "Miglioramento predefinito",
        "el": "Προεπιλεγμένη βελτίωση",
        "ar": "التحسين الافتراضي",
        "gl": "Mellora por defecto",
        "ca": "Millora per defecte",
        "eu": "Hobekuntza lehenetsia",
    },
    "aj_escaner_filtro_desc": {
        "en": "Applied to each page as soon as it is captured.",
        "es": "Se aplica a cada página nada más capturarla.",
        "fr": "Appliquée à chaque page dès sa capture.",
        "de": "Wird auf jede Seite direkt nach der Aufnahme angewendet.",
        "zh": "拍摄后立即应用到每一页。",
        "ja": "撮影した直後に各ページへ適用します。",
        "ru": "Применяется к каждой странице сразу после съёмки.",
        "it": "Si applica a ogni pagina appena acquisita.",
        "el": "Εφαρμόζεται σε κάθε σελίδα μόλις καταγραφεί.",
        "ar": "يُطبَّق على كل صفحة فور التقاطها.",
        "gl": "Aplícase a cada páxina nada máis capturala.",
        "ca": "S’aplica a cada pàgina just després de capturar-la.",
        "eu": "Orri bakoitzari hartu bezain laster aplikatzen zaio.",
    },
    "aj_tarea_escanear": {
        "en": "Scan",
        "es": "Escanear",
        "fr": "Numériser",
        "de": "Scannen",
        "zh": "扫描",
        "ja": "スキャン",
        "ru": "Сканирование",
        "it": "Scansione",
        "el": "Σάρωση",
        "ar": "المسح الضوئي",
        "gl": "Dixitalizar",
        "ca": "Escanejar",
        "eu": "Eskaneatu",
    },

    # --- Tour ----------------------------------------------------------------
    "tour_z_escanear_t": {
        "en": "A scanner in your pocket",
        "es": "Un escáner en el bolsillo",
        "fr": "Un scanner dans la poche",
        "de": "Ein Scanner in der Tasche",
        "zh": "口袋里的扫描仪",
        "ja": "ポケットの中のスキャナー",
        "ru": "Сканер в кармане",
        "it": "Uno scanner in tasca",
        "el": "Ένας σαρωτής στην τσέπη",
        "ar": "ماسح ضوئي في جيبك",
        "gl": "Un dixitalizador no peto",
        "ca": "Un escàner a la butxaca",
        "eu": "Eskaner bat poltsikoan",
    },
    "tour_z_escanear_c": {
        "en": "Point at a paper: it finds the edges, straightens it and reads the text "
              "so you can search it later.",
        "es": "Apunta a un papel: encuentra los bordes, lo endereza y lee el texto para "
              "que luego puedas buscarlo.",
        "fr": "Visez une feuille : il trouve les bords, la redresse et lit le texte pour "
              "que vous puissiez le rechercher ensuite.",
        "de": "Auf ein Blatt richten: Es findet die Ränder, begradigt es und liest den Text, "
              "damit Sie ihn später suchen können.",
        "zh": "对准一张纸：它会找到边缘、校正透视，并识别文字，方便以后搜索。",
        "ja": "紙に向けるだけ。輪郭を見つけて歪みを直し、文字を読み取るので後から検索できます。",
        "ru": "Наведите на лист: приложение найдёт края, выровняет его и прочитает текст, "
              "чтобы потом можно было искать.",
        "it": "Inquadra un foglio: trova i bordi, lo raddrizza e legge il testo perché tu "
              "possa cercarlo dopo.",
        "el": "Στοχεύστε ένα χαρτί: βρίσκει τις άκρες, το ισιώνει και διαβάζει το κείμενο "
              "ώστε να μπορείτε να το αναζητήσετε αργότερα.",
        "ar": "وجّه الكاميرا نحو ورقة: يجد الحواف، ويصحح الميل، ويقرأ النص لتتمكن من البحث فيه لاحقًا.",
        "gl": "Apunta a un papel: atopa os bordos, endereítao e le o texto para que despois "
              "poidas buscalo.",
        "ca": "Apunta a un paper: troba les vores, el redreça i llegeix el text perquè "
              "després el puguis cercar.",
        "eu": "Apuntatu paper bati: ertzak aurkitzen ditu, zuzendu egiten du eta testua "
              "irakurtzen du gero bilatu ahal izateko.",
    },

    # --- Modo tarjeta --------------------------------------------------------
    # Se habla de "tamaño real" y no de "ISO 7810": lo que la persona necesita
    # saber es que al imprimirlo saldrá del tamaño del carné, no el número de la
    # norma que lo garantiza.
    "esc_tarjeta_titulo": {
        "en": "Card mode",
        "es": "Modo tarjeta",
        "fr": "Mode carte",
        "de": "Kartenmodus",
        "zh": "证卡模式",
        "ja": "カードモード",
        "ru": "Режим карточки",
        "it": "Modalità tessera",
        "el": "Λειτουργία κάρτας",
        "ar": "وضع البطاقة",
        "gl": "Modo tarxeta",
        "ca": "Mode targeta",
        "eu": "Txartel modua",
    },
    "esc_tarjeta_detalle": {
        "en": "Both sides on one sheet, at actual size for printing",
        "es": "Las dos caras en una hoja, a tamaño real para imprimir",
        "fr": "Les deux faces sur une feuille, à taille réelle pour l’impression",
        "de": "Beide Seiten auf einem Blatt, in Originalgröße zum Ausdrucken",
        "zh": "正反面同页，按实际尺寸打印",
        "ja": "表裏を 1 枚に、印刷しても実物大",
        "ru": "Обе стороны на одном листе, в натуральную величину для печати",
        "it": "Fronte e retro in un foglio, a grandezza reale per la stampa",
        "el": "Και οι δύο όψεις σε ένα φύλλο, σε φυσικό μέγεθος για εκτύπωση",
        "ar": "الوجهان في ورقة واحدة، بالحجم الحقيقي للطباعة",
        "gl": "As dúas caras nunha folla, a tamaño real para imprimir",
        "ca": "Les dues cares en un full, a mida real per imprimir",
        "eu": "Bi aldeak orri bakarrean, tamaina errealean inprimatzeko",
    },
    "esc_tarjeta_documento": {
        "en": "Document",
        "es": "Documento",
        "fr": "Document",
        "de": "Dokument",
        "zh": "文档",
        "ja": "書類",
        "ru": "Документ",
        "it": "Documento",
        "el": "Έγγραφο",
        "ar": "مستند",
        "gl": "Documento",
        "ca": "Document",
        "eu": "Dokumentua",
    },
    "esc_tarjeta_auto": {
        "en": "Automatic",
        "es": "Automático",
        "fr": "Automatique",
        "de": "Automatisch",
        "zh": "自动",
        "ja": "自動",
        "ru": "Автоматически",
        "it": "Automatico",
        "el": "Αυτόματα",
        "ar": "تلقائي",
        "gl": "Automático",
        "ca": "Automàtic",
        "eu": "Automatikoa",
    },
    "esc_tarjeta_id1": {
        "en": "ID / bank card",
        "es": "DNI o tarjeta",
        "fr": "Carte d’identité ou bancaire",
        "de": "Ausweis oder Bankkarte",
        "zh": "身份证 / 银行卡",
        "ja": "身分証・カード",
        "ru": "Удостоверение или банковская карта",
        "it": "Carta d’identità o bancaria",
        "el": "Ταυτότητα ή κάρτα",
        "ar": "بطاقة هوية أو مصرفية",
        "gl": "DNI ou tarxeta",
        "ca": "DNI o targeta",
        "eu": "NAN edo txartela",
    },
    "esc_tarjeta_id2": {
        "en": "Medium document",
        "es": "Documento mediano",
        "fr": "Document moyen",
        "de": "Mittelgroßes Dokument",
        "zh": "中型证件",
        "ja": "中サイズの証明書",
        "ru": "Средний документ",
        "it": "Documento medio",
        "el": "Μεσαίο έγγραφο",
        "ar": "مستند متوسط",
        "gl": "Documento mediano",
        "ca": "Document mitjà",
        "eu": "Tamaina ertaineko agiria",
    },
    "esc_tarjeta_id3": {
        "en": "Passport",
        "es": "Pasaporte",
        "fr": "Passeport",
        "de": "Reisepass",
        "zh": "护照",
        "ja": "パスポート",
        "ru": "Паспорт",
        "it": "Passaporto",
        "el": "Διαβατήριο",
        "ar": "جواز سفر",
        "gl": "Pasaporte",
        "ca": "Passaport",
        "eu": "Pasaportea",
    },
    "esc_tarjeta_aviso_caras": {
        "en": "Photograph both sides: they go on the same sheet",
        "es": "Fotografía las dos caras: van en la misma hoja",
        "fr": "Photographiez les deux faces : elles vont sur la même feuille",
        "de": "Fotografiere beide Seiten: sie kommen auf dasselbe Blatt",
        "zh": "正反面都要拍：它们会放在同一页",
        "ja": "表と裏の両方を撮ってください。同じ用紙に並びます",
        "ru": "Сфотографируйте обе стороны: они лягут на один лист",
        "it": "Fotografa entrambe le facce: vanno nello stesso foglio",
        "el": "Φωτογραφίστε και τις δύο όψεις: μπαίνουν στο ίδιο φύλλο",
        "ar": "صوّر الوجهين: سيظهران في الورقة نفسها",
        "gl": "Fotografa as dúas caras: van na mesma folla",
        "ca": "Fotografia les dues cares: van al mateix full",
        "eu": "Atera bi aldeen argazkia: orri berean joango dira",
    },

    # --- Ajuste de rafaga ----------------------------------------------------
    # Se habla de "varias fotos" y no de "apilado multifotograma". Lo que la
    # persona necesita decidir es si prefiere calidad o rapidez.
    "aj_escaner_rafaga": {
        "en": "Several shots per page",
        "es": "Varias fotos por página",
        "fr": "Plusieurs photos par page",
        "de": "Mehrere Aufnahmen pro Seite",
        "zh": "每页拍摄多张",
        "ja": "1 ページにつき複数枚",
        "ru": "Несколько снимков на страницу",
        "it": "Più scatti per pagina",
        "el": "Πολλές λήψεις ανά σελίδα",
        "ar": "عدة لقطات لكل صفحة",
        "gl": "Varias fotos por páxina",
        "ca": "Diverses fotos per pàgina",
        "eu": "Orriko argazki bat baino gehiago",
    },
    "aj_escaner_rafaga_desc": {
        "en": "Cleaner, sharper pages. Each one takes a few seconds longer.",
        "es": "Páginas más limpias y nítidas. Cada una tarda unos segundos más.",
        "fr": "Des pages plus propres et plus nettes. Chacune prend quelques secondes de plus.",
        "de": "Sauberere, schärfere Seiten. Jede dauert ein paar Sekunden länger.",
        "zh": "页面更干净、更清晰，每页会多花几秒。",
        "ja": "ページがより清潔で鮮明に。1 枚あたり数秒長くかかります。",
        "ru": "Страницы чище и чётче. Каждая занимает на несколько секунд больше.",
        "it": "Pagine più pulite e nitide. Ognuna richiede qualche secondo in più.",
        "el": "Πιο καθαρές και ευκρινείς σελίδες. Κάθε μία αργεί λίγα δευτερόλεπτα παραπάνω.",
        "ar": "صفحات أنظف وأوضح. كل صفحة تستغرق ثوانٍ إضافية.",
        "gl": "Páxinas máis limpas e nítidas. Cada unha tarda uns segundos máis.",
        "ca": "Pàgines més netes i nítides. Cadascuna triga uns segons més.",
        "eu": "Orri garbiagoak eta zorrotzagoak. Bakoitzak segundo batzuk gehiago behar ditu.",
    },
}

PLURALES = {
    "plural_esc_paginas": {
        "en": {"one": "%1$d page scanned", "other": "%1$d pages scanned"},
        "es": {"one": "%1$d página escaneada", "other": "%1$d páginas escaneadas"},
        "fr": {"one": "%1$d page numérisée", "other": "%1$d pages numérisées"},
        "de": {"one": "%1$d Seite gescannt", "other": "%1$d Seiten gescannt"},
        "zh": {"other": "已扫描 %1$d 页"},
        "ja": {"other": "%1$d ページをスキャン済み"},
        "ru": {"one": "отсканирована %1$d страница", "few": "отсканировано %1$d страницы",
               "many": "отсканировано %1$d страниц", "other": "отсканировано %1$d страницы"},
        "it": {"one": "%1$d pagina scansionata", "other": "%1$d pagine scansionate"},
        "el": {"one": "%1$d σελίδα σαρώθηκε", "other": "%1$d σελίδες σαρώθηκαν"},
        "ar": {"zero": "لم تُمسح صفحات", "one": "صفحة واحدة ممسوحة", "two": "صفحتان ممسوحتان",
               "few": "%1$d صفحات ممسوحة", "many": "%1$d صفحة ممسوحة", "other": "%1$d صفحة ممسوحة"},
        "gl": {"one": "%1$d páxina dixitalizada", "other": "%1$d páxinas dixitalizadas"},
        "ca": {"one": "%1$d pàgina escanejada", "other": "%1$d pàgines escanejades"},
        "eu": {"one": "orri %1$d eskaneatuta", "other": "%1$d orri eskaneatuta"},
    },
}
